### ISSUE TITLE
confirmed accidental, complete loss of folder contents!

### ISSUE THREAD

**Issue by xraymike** [bitwarden/clients#10009]
### Steps To Reproduce

// set the stage for the problem
1. create a new folder
2. create contents (logins, secure notes, etc) in above folder

hey, that's great.

here's my user story:

1. I had the above circumstance
2. I was looking for a search for something that couldn't be found
3. I selected a folder
4. (hey, the folder is empty!)   // it was not empty...it looked empty because none of the contents matched the filter
5. delete the (apparently empty) folder
6. **all the contents are deleted and do not appear in the trash**

### Expected Result

the deleted folder's contents should go to trash **OR**, it should refuse to delete a folder that contains something.

### Actual Result

the folder contents appear to be lost forever

### Operating System

Windows

### Operating System Version

win 10/64 pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi there,

Items added to a folder will still appear in your vault when All vaults is selected from the filter menu, and deleting a folder will not delete the items in that folder.
https://bitwarden.com/help/folders/

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by xraymike** [comment]
thank you; just found them myself & was coming back to delete this issue!
