### ISSUE TITLE
iOS app sync is very slowly, then return result sync failed

### ISSUE THREAD

**Issue by zhiweizh0ng** [bitwarden/clients#10003]
### Steps To Reproduce

1. Go to 'iOS app'
2. Pull down to start syncing
3. After a few minutes, the result is returned that the synchronization failed

### Expected Result

sync successful

### Actual Result

sync failed

### Operating System

macOS

### Operating System Version

iOS 17.5.1

### Installation method

Mac App Store

### Build Version

2024.6.0 (7846)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
