### ISSUE TITLE
Bitwarden covering select field that is not a password, preventing proper input

### ISSUE THREAD

**Issue by chriswaterside** [bitwarden/clients#10178]
### Steps To Reproduce

I cannot provide an working example. But the issue was with Bitwarden displaying a list of login info for a web site when I was editing an HTML select element that has nothing to do with passwords.
The login info was covering up the options I was trying to select from., see screenshots.

### Expected Result

I would what either to be able to turn off the Bitwarden display of login data,

or the best option would be that it does not try and provide info for now password fields on a form.

### Actual Result

The issue was with Bitwarden displaying a list of login info for a web site when I was editing an HTML select element that has nothing to do with passwords.
The login info was covering up the options I was trying to select from., see screenshots.
One screenshot shows the form with a couple of select fields
The other shows Bitwarden trying to provide input for these fields.

### Screenshots or Videos

![bitwarden covering](https://github.com/user-attachments/assets/0ef6ede3-23dd-4be4-844c-bd8de9040179)
![bitwarden - combo](https://github.com/user-attachments/assets/2f37c463-d448-44c6-8cc1-f3562465e6d3)

### Operating System

Windows

### Operating System Version

windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed.

**Comment by chriswaterside** [comment]
Hi
I'm just a user and cannot see why you closed this issue. As the field is a select statement surely bitwarden should not be providing and possible input.
I don't understand your comments/closure.
Please explain.
Chris
