### ISSUE TITLE
Random password generators never shows the digits zero or one (0, 1)

### ISSUE THREAD

**Issue by sandoche** [bitwarden/clients#10199]
### Steps To Reproduce

1. Go to 'Generator' tab
2. Disable all except '0-9'
3. Increase lenght (easier to test)
4. Click on 'Regenerate'

### Expected Result

You expect to have at some point some passwords that contains digits from 0 to 9

### Actual Result

Passwords only contains digits from 2 to 9 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/e097d6f2-9f0f-406d-8db0-01149f2edcd7)

![image](https://github.com/user-attachments/assets/2cc1cd7f-ae7b-4f1c-af9b-ca529afb4eee)

![image](https://github.com/user-attachments/assets/3b327cb3-0200-4e2c-a1c7-206840af0a40)

### Additional Context

This issue also occurs here: https://bitwarden.com/password-generator/
And on the desktop app.

This also happen if you select letters and special characters.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rchomat** [comment]
Have you tried without "Avoid ambiguous characters" checked? 1 and 0 are considered as ambiguous as they look like lowercase L and uppercase O

**Comment by SergeantConfused** [comment]
Hello @sandoche,

Thank you for reporting this. This is happening because the (Avoid ambiguous characters) option is activated in the Bitwarden application clients that you're using; The same applies to the online generator. In the application clients, you can turn it off in order to generate a password that includes zeros and ones.

If you have any further questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) and please include a link to this GitHub report if you do so.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
