### ISSUE TITLE
Biometric authentication for the extension has stopped working for more than a week

### ISSUE THREAD

**Issue by maximedrouhin** [bitwarden/clients#10195]
### Steps To Reproduce

1. Start up your computer. At this point, if you have set up the biometric authentication for the extension, the desktop app should start up automatically after a few seconds/dozens of seconds.
2. Open Chrome. At this point, your vault should be locked.
3. Try to unlock your vault with biometrics.

### Expected Result

 Your vault should unlock without any problem.

### Actual Result

I get this error:

> User locked or logged out.
> Please unlock this user in the desktop application and try again.

This doesn't make any sense, because the reason I was trying to unlock my vault in the first place is that it was locked... (please note that in the desktop application, my vault is locked but I'm not logged out)

Things were working fine until a bit more than a week ago, I wonder if maybe an update (of either the extension or the desktop app) broke biometric authentication.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/c3520d58-885f-4999-9167-2149cf667fcd)

### Additional Context

Both the extension and the desktop app are up-to-date at the time of writing this.

### Operating System

Windows

### Operating System Version

Microsoft Windows 11 Pro - 10.0.22631 Build 22631

### Web Browser

Chrome

### Browser Version

Version 126.0.6478.182 (Official Build) (64-bit)

### Build Version (extension)

Version: 2024.6.1
Server version: 2024.6.2

### Build Version (desktop app)

Version 2024.6.4
Shell 29.4.2
Renderer 122.0.6261.156
Node 20.9.0
Architecture x64

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. It's important to note that the Bitwarden desktop app must be logged in and running in order to use unlock with biometrics for a browser extension. I recommend uninstalling the browser extension, restarting the device, and then reinstalling the browser extension. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
