### ISSUE TITLE
Biometrics not supported alert

### ISSUE THREAD

**Issue by mendimr** [bitwarden/clients#10198]
### Steps To Reproduce

1. Simply close the lid of your device, in this case a macbook with a touch id
2. Open the Bitwarden Chrome extension (configured to unlock via biometrics when available)
3. The alert is presented, removing focus from the master password field

### Expected Result

Display a toast or any other kind of a message that doesn't remove focus from the master password instead of the alert for "biometrics are not supported"

### Actual Result

An alert is displayed that tells you that the biometrics are not supported.

### Screenshots or Videos

![bitwardenextension](https://github.com/user-attachments/assets/7d06465e-5a77-405c-a82c-415e79004bb8)

### Additional Context

I get it that you want to notify the user that the biometrics are not supported but it should be a toast, something that doesn't remove focus from the master password. Often times you open the Bitwarden extension and right away start typing your password just to realize that you typed your longest password for nothing.

### Operating System

macOS

### Operating System Version

15.0

### Web Browser

Chrome

### Browser Version

126.0.6478.127 

### Build Version

0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Dot-Dash** [comment]
As a work-around, you can go into the settings for the browser plug-in and uncheck _Unlock with Biometrics_. (Under Account Security).

**Comment by SergeantConfused** [comment]
Hi @mendimr,

Thank you for this report. I recommend considering submitting this as an improvement suggestion/feature request in the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/5/none), because this appears to be more of a request to change a certain behaviour within the Bitwarden browser extension, rather than a report about a particular malfunction. In the meantime, please consider pressing on the Return/Enter key to click on the (Ok) button and dismiss that alert, and to then enter the Bitwarden master password to unlock the Bitwarden browser extension.

If you decide to submit this in the Bitwarden Community, please remember to use the search function to see if this topic has already been brought up, before creating a new thread.

If you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) and please include a link to this GitHub report if you do.

I will now close this GitHub report.

Thank you again,
