### ISSUE TITLE
Firefox extension shows verification code without reentering credentials

### ISSUE THREAD

**Issue by MarcelVersteeg** [bitwarden/clients#10200]
### Steps To Reproduce

When you have a login item configured with the "Master password reprompt" option enabled, that also has a verification code configured, then:

1. Open the website that requires the authentication
2. Click on the Bitwarden icon and the login entry to fill in the credentials. The extension will ask for the master password and after that fill the user name and password fields on the website. The website continues to the page where the verification code is requested.
3. Click on the bitwarden logo again.
4. Click the "clock"-icon of the login entry
5. The prompt for the master password is shown
6. Press Ctrl-V to paste "something" into the master password field.
7. Click the "eye"-icon to show what has been pasted. The verification code has been pasted into this field, without entering the master password.

### Expected Result

The verification code is not placed on the clipboard before the master password has been entered.

### Actual Result

The verification code is put on the clipboard before the master password has been entered.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

128.0

### Build Version

64-bit

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @MarcelVersteeg,

Thank you for this report. You may want to consider turning off the [Copy TOTP automatically](https://bitwarden.com/help/integrated-authenticator/#use-generated-codes) function in the browser extension, if you'd rather not have the 6-digit TOTP code be copied to the clipboard automatically as part of the autofill flow. What you are describing is the expected behaviour; If you'd like to need to enter the master password twice when autofilling items that have Master Password Re-prompt active and also have a TOTP code, without affecting vault items that have a TOTP code without Master Password Re-prompt, you can consider submitting that as a feature request in the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/5/none); Please remember to look this up to see if there's an existing thread about this before creating a new one.

If you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) and please include a link to this GitHub report if you do so.

I will now close this GitHub report.

Thank you again,
