### ISSUE TITLE
Desktop app open deafult web browser causing SSO auth failure.

### ISSUE THREAD

**Issue by david-levin-riverbed** [bitwarden/clients#10217]
### Steps To Reproduce

1. Go to Windows BitWarden app.
2. Enter email address and Click on Continue
3. Click on Enterprise single sign-on
4. This launches the default web-brower which is already SSO authenticated desktop user.
5. This is not the Bitwarden user, and generates this error. 

### Expected Result

Not sure about product design, but not opening a browser for an apps authentication.  Doing the SSO in the app with the account/email that was specified.

### Actual Result

Error
There was an unexpected error during single sign-on.

To accept your invite to Riverbed Technology, you must first log in using your master password. Once your invite has been accepted, you will be able to log in using SSO.

Request ID: 00-ba25f8417347f6f0d8f6acec20cf4119-3d52b739e38e16e3-00

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/1a2d1bc0-c1ec-482f-a086-0e579eb54797)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.  If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by david-levin-riverbed** [comment]
Issue is still on going.  Noting that we use Azure SSO for end user authentication.
