### ISSUE TITLE
MacOS app requires you to open it twice upon initial startup

### ISSUE THREAD

**Issue by imwithsam** [bitwarden/clients#10250]
### Steps To Reproduce

1. Start or restart your MacOS laptop/desktop.
2. Open the BitWarden app for MacOS.

### Expected Result

The BitWarden app opens and displays the login screen (or vault if you're already logged in).

### Actual Result

The BitWarden app starts but does not display anything. You have to open the app again to get the login screen to display.

### Additional Context

This has been a bug for as long as I've had the BitWarden app installed on my 2021 MacBook Pro (M1 Max). After you open the app a couple of times, then quit the app and open it again, it appears to load correctly without having to open it twice again. But if you restart the operating system, you have to open the app twice again to get it to function properly.

### Operating System

macOS

### Operating System Version

14.5

### Installation method

Mac App Store

### Build Version

Version 2024.6.4 Shell 29.4.2 Renderer 122.0.6261.156 Node 20.9.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you make sure the option "Start automatically on login" is selected in the Bitwarden settings? You may also need to add it to the "login items" in your Mac's Settings app. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
