### ISSUE TITLE
Bitwarden hijacks hardware keys in webauthn

### ISSUE THREAD

**Issue by auroraanna** [bitwarden/clients#10253]
### Steps To Reproduce

1. Get prompted for tapping hardware key/autheticating via webauthn

### Expected Result

Plug in hardware key and tap on it to authenticate (or however you might use webauthn)

### Actual Result

A window from the Bitwarden browser extension pops up asking what to do with seemingly no way to disable it.

### Operating System

Linux

### Operating System Version

at least NixOS 24.11.20240719.1d9c2c9 

### Web Browser

Firefox

### Browser Version

at least 128.0

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

You can dismiss this or click on "Use browser" in order to launch other WebAuthn options. If you do not want Bitwarden to offer itself during enrollment for that URL, you can add that URL to the (Excluded domains) list in the Bitwarden browser extension.  If you do not wish to use Bitwarden for passkeys at all, you may turn off these notifications by opening the Bitwarden browser extension and navigating to Settings > Notifications > Ask to save and use passkeys.

If you have any questions, please write to us using the "Contact Support" option in the Help Center: https://bitwarden.com/help/

This ticket will now be closed.
