### ISSUE TITLE
Raycast extension doesn't accept correct password

### ISSUE THREAD

**Issue by rightsaidfred99** [bitwarden/clients#10276]
### Steps To Reproduce

Raycast Extension is broken, can't unloack the vault with the correct password.
I copy paste the password into the Desktop App or Vault online it opens, the same password I get an error of wrong password in the raycast extension.

### Expected Result

SHould unlock

### Actual Result

Doesn't unlock

### Operating System

macOS

### Operating System Version

14

### Shell

Bash

### Build Version

2004.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

The Raycast extension is a community maintained extension, and is not maintained by Bitwarden.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by rightsaidfred99** [comment]
It's the cli part that's broken....

**Comment by rightsaidfred99** [comment]
Same as bug https://github.com/bitwarden/clients/issues/9919
