### ISSUE TITLE
Are google chrome browser extension no longer updated?

### ISSUE THREAD

**Issue by qwerttvv** [bitwarden/clients#10309]
### Steps To Reproduce

official website
https://bitwarden.com/download/#downloads-web-browser

Official website pointing to google link
https://chromewebstore.google.com/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?browser=chrome

btw, edge seems to still be updating
https://microsoftedge.microsoft.com/addons/detail/jbkfoedolllekgbhcbcoahefnbanhhlh

### Expected Result

update

### Actual Result

No more updates

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.7.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. Extension updates are subject to review by browser's web store teams, and will then be updated in a staged rollout.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
