### ISSUE TITLE
Autofill does not work at chase.com 

### ISSUE THREAD

**Issue by davidgblezard** [bitwarden/clients#10306]
### Steps To Reproduce

1. Go to chase.com
2. Click on 'Sign In'
3. Try to auto fill id and password

### Expected Result

Expect id and password to be populated

### Actual Result

does not fill the id or password.  I have to open Bitwarden and copy and paste id and password.

### Additional Context

 Firefox on a windows 11 laptop

MS Edge works as expected.

### Operating System

Windows

### Operating System Version

Win 11 Pro   10.0.22631 Build 22631

### Web Browser

Firefox

### Browser Version

128.0.3  (64 bit)

### Build Version

24.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
