### ISSUE TITLE
"Default Password Manager" setting also overrides credit cards and addresses 

### ISSUE THREAD

**Issue by jamesshannon** [bitwarden/clients#10339]
### Steps To Reproduce

1. Allow browser (e.g., chrome) to save credit card info
2. Make Bitwarden your default password manager (Settings > Autofill > Make BW default password manager)
3. Go to a page that accepts credit cards

### Expected Result

Chrome should offer to auto-fill credit card info

### Actual Result

Nothing

### Additional Context

BW is a good password manager, but I like Chrome to be my credit card manager.

From what I can tell, earlier this year #7592 introduced a function to [update the browser autofill settings](https://github.com/bitwarden/clients/blame/27fa7625cf749c4993f687f75fe5bc0aed22d9bd/apps/browser/src/platform/browser/browser-api.ts#L578). However, it updates the address and credit card autofill settings, not just the password settings.

### Operating System

macOS

### Operating System Version

14.3.1

### Web Browser

Chrome

### Browser Version

126.0.6478.185 (Official Build)

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request. Chrome uses auto-fill for your saved cards - enabling **Make Bitwarden your default password manager** will disable Chrome's auto-fill per the message below the setting.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
