### ISSUE TITLE
Version: 2024.7.1 performance issues in browser extension

### ISSUE THREAD

**Issue by coolnetworks** [bitwarden/clients#10336]
### Steps To Reproduce

1. open a web page, any web page.
2. click on bitwarden to load the list of passwords
3. wait. like a really long time - up to a minute for the list to appear
4. cry tears of joy when it finally comes up

### Expected Result

it should just pop up quickly - I understand that there is encryption to deal with but it was never this bad until 2024.7.1

### Actual Result

the panel shows up but is all black until it finally decides to display sites

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/f4e8f115-cbd1-4792-a941-356f2478f248)

### Additional Context

in fact any click in the extension is just awful wait times

took 30 seconds to get the version Version: 2024.7.1 string

### Operating System

Windows

### Operating System Version

windows 10 and 11

### Web Browser

Chrome, Microsoft Edge

### Browser Version

latest for each windows version

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by coolnetworks** [comment]
Closing because we found out. it was dns. it is always dns

**Comment by notnamed** [comment]
Hi @coolnetworks - good to hear you were able to find a root cause for the issue! I am curious if you have more details (feel free to contact our support team directly as well: https://bitwarden.com/contact/ ) on the DNS issue you saw. The expectation if there is connectivity issues to the server - such as a DNS malfunction, or the server being down - is that the client will operate in a read-only offline mode. I did a quick test breaking my DNS to a self-hosted instance deliberately, and was unable to replicate the behavior you described; the Chrome extension opened normally, even after a lock and unlock when the server was inaccessible. Just want to make sure you haven't discovered a bug in the offline access!

**Comment by wesinator** [comment]
yea @notnamed this has not worked as expected in the Firefox browser extension for the last few months. If there is no connection the vault hangs on the blank screen when you enter the unlock password.
It happens if the client internet connection is unstable/high packet loss, or if the connection disconnects. The vault isn't generally accessible offline like it is in the other apps.
I'm almost certain the caching of the vault used to work in the browser extensions also.

Do I need to file a new issue?

[NO_TRAIN]::

**Comment by notnamed** [comment]
@wesinator thank you for the correlation assistance! Based on some recent comments in that thread:

1) Replication is difficult, which is why I was unable to replicate this in my testing (self-hosted; Chrome)
2) There are reports in #9561 for the Cloud environments as well as self-hosted
3) There is a specifically synchronous call that is blocking the rest of the application

I've located some internal notes on this behavior and am updating with additional details from this and the other thread so that we can continue to investigate.
