### ISSUE TITLE
Safari extension is gone after update to 2024.7.0 and then back to 2024.6.4

### ISSUE THREAD

**Issue by igorfraa** [bitwarden/clients#10343]
### Steps To Reproduce

Do not now is it reproducable. 
I've updated to 2024.7.0 from AppStore. Then the update was revoked and I've reinstalled 2024.6.4. 

"Enable browser extension" is selected in settings, but no Bitwarden in Safari menu.

### Expected Result

Bitwarden icon near address bar

### Actual Result

No Bitwarden extension

### Screenshots or Videos

<img width="472" alt="Screenshot 2024-07-31 at 15 05 11" src="https://github.com/user-attachments/assets/a1c1f12c-7bf9-48db-a58d-63e21a807fa3">

### Operating System

macOS

### Web Browser

Safari

### Build Version

Version 2024.6.4 Shell 29.4.2 Renderer 122.0.6261.156 Node 20.9.0 Architecture arm64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in not allowing the update to finish.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
