### ISSUE TITLE
Unable to unlock vault in safari browser on macOS with biometry

### ISSUE THREAD

**Issue by curiousbarbarian** [bitwarden/clients#10371]
### Steps To Reproduce

1. In vault settings enable unlocking with biometry (fingerprint in my case).
2. Lock your vault.
3. Click on Bitwarden icon near address bar.
4. See Bitwarden asks for biometry to unlock vault.
5. Put your finger on fingerprint scanner.
6. See success (native macOS windows disappears without issues)
7. See Bitwarden is still locked.

### Expected Result

Unlocked vault

### Actual Result

Locked vault

### Screenshots or Videos

https://github.com/user-attachments/assets/9500c6d1-5a21-456a-948b-f48d6e353438

### Additional Context

After obviously unsuccessful unlocking with biometry if I click unlock button Bitwarden gives me a error and asks to enter master password like I didn't use biometry at all and it sill waits for MP

### Operating System

macOS

### Operating System Version

Sonoma 14.5

### Web Browser

Safari

### Browser Version

17.5 (19618.2.12.11.6)

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 

Thanks for getting in touch - this should be resolved by ensuring your desktop application is updated to 2024.71. There should be an update available in the App Store - please ensure this is installed. You may need to restart Safari once to ensure TouchID unlock is working as expected.

macOS Store Link: https://itunes.apple.com/app/bitwarden/id1352778147

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
