### ISSUE TITLE
password is not cleared from clipboard in firefox extension

### ISSUE THREAD

**Issue by HOHLAND-CblP** [bitwarden/clients#10372]
### Steps To Reproduce

1. Activate clipboard in Windows settings 
2. Set the clipboard clearing time in bitwarden settings 
3. Go to vault
4. Click on any password copy button
5. Wait for the time you set for the password to be erased
6. If you press win+v you see this:
![изображение](https://github.com/user-attachments/assets/eca8696d-f9a7-4447-be34-1bb2b0971515)

### Expected Result

I expect to see the password cleared from clipboard

### Actual Result

the password is not cleared from the clipboard, an empty line is added to the clipboard

### Additional Context

I think the extension thinks that I have the clipboard disabled in Windows

### Operating System

Windows

### Operating System Version

23H2

### Web Browser

Firefox

### Browser Version

128.0.3 (64 bit)

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software on the Firefox. If you don't want items to be saved to your clipboard I would suggest deactivating the clipboard settings on windows.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
