### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by rightsaidfred99** [bitwarden/clients#10389]
### Steps To Reproduce

A popup happens, click on "New Item" and a blank window appears

### Expected Result

It should work

### Actual Result

Blank window

### Screenshots or Videos

![Screenshot](https://github.com/user-attachments/assets/ce0d28f3-a198-43ac-8ddd-0d413add6e11)

### Operating System

macOS

### Operating System Version

14.6

### Web Browser

Safari

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @rightsaidfred99,

Thank you for reporting this. I recommend that you proceed with a fresh new installation of Bitwarden on that macOS machine; Uninstall your Bitwarden macOS desktop client, remove all [its leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot your machine, install Bitwarden anew from the Mac App Store, and test that again. [This guide](https://bitwarden.com/help/install-safari-app-extension/) explains how to activate the Safari browser extension. I say this because I was unable to reproduce this; Clicking on the (New item) button within the [Inline autofill prompt](https://bitwarden.com/help/auto-fill-browser/#inline-autofill-menu) opened the Bitwarden browser extension within its own window as expected.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in the Bitwarden [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
