### ISSUE TITLE
Error messages should not be transient

### ISSUE THREAD

**Issue by mcalmus** [bitwarden/clients#10386]
### Steps To Reproduce

This applies to both browser and app/plugins. When there is an error message, a popup is shown in the upper right corner of the browser window. The popup flashes briefly then disappears. This is bad from an accessibility perspective because a user with low vision is likely not even to see it. Even for other uers, though, if the user has happened to look away or not be looking at the corner of the page they wouldn't see it. Also, a slow reader might not even be able to read the message before it disappears.

### Expected Result

Error messages should persist at least until the user takes another action. The corner of the screen is not the best place to display them, but if they were persistent, that would be less of an issue.

### Actual Result

Error messages are displayed briefly and then disappear.

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

2024.7.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @mcalmus,

Thank you for this report. I understand what you mean and this topic is already on our radar internally; Generally speaking, this would be considered an improvement suggestion/feature request and should ideally be raised in the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/5/none), and due to this I will now proceed and close this GitHub report.

If you have any questions or concerns, please feel free to get in touch with us and please include a link to this GitHub report if you do.

Thank you again,
