### ISSUE TITLE
"Timeout on system lock" not working in Chrome extension

### ISSUE THREAD

**Issue by robert97520** [bitwarden/clients#10391]
### Steps To Reproduce

1. Go to Chrome extension > Settings > Account security > Session Timeout > Vault timeout
2. Click on "On system lock"

### Expected Result

Expect browser extension to lock when the system locks (or is locked).

### Actual Result

Browser extension locks before system locks. (Browser window has NOT been closed in the meantime.)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

Version 127.0.6533.89 (Official Build) (64-bit)

### Build Version

Version 127.0.6533.89 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Take into account that there are unique scenarios to consider: https://bitwarden.com/help/vault-timeout/#web-and-browser-extension-timeouts

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I am re-opening this issue today, as I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by trmartin4** [comment]
@robert97520 unfortunately, this is a limitation of the APIs that Chrome exposes to the extensions for determining system lock.  Namely, the `chrome.idle` API that we use, as documented [here](https://developer.chrome.com/docs/extensions/reference/api/idle#event):

> Fired when the system changes to an active, idle or locked state. The event fires with "locked" if the screen is locked or the screensaver activates, "idle" if the system is unlocked and the user has not generated any input for a specified number of seconds, and "active" when the user generates input on an idle system.

What this means is that we detect system lock when "the screen is locked **or** the screensaver activates", regardless of whether the login screen option is chosen.

We will look to add some clarification to our documentation to make this clearer.
