### ISSUE TITLE
Chrome Extension doesn't save new entry

### ISSUE THREAD

**Issue by GodMonkey** [bitwarden/clients#10390]
### Steps To Reproduce

1. Open Chrome Extension
2. Create new entry
3. Save the entry

### Expected Result

The entry gets saved and eventually synchronized.

### Actual Result

After clicking on "save" nothing happend, no new entry is saved.

### Operating System

Linux

### Operating System Version

Arch Linux 6.10.2

### Web Browser

Chrome

### Browser Version

129.0.6614.3

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @GodMonkey,

Thank you for reporting this. I recommend that you check if a fresh new installation assist; Please uninstall the Bitwarden browser extension, reboot the machine, install the extension anew, and give that another try. I say this because I was unable to reproduce this behaviour.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket; Also, please clarify how you installed Chrome, which desktop environment you're using, and what exactly happens after clicking on (Save). Testing this in another browser on the same machine may assist in narrowing down the potential cause.

Alternatively, you can seek assistance from other Bitwarden users in the Bitwarden [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by giejay** [comment]
I have the exact same issue, @GodMonkey were you able to fix this?
