### ISSUE TITLE
Error when adding to a collection in the desktop app

### ISSUE THREAD

**Issue by FreshFoxyHD** [bitwarden/clients#10428]
### Steps To Reproduce

1. go to an existing entry
2. click on Collections
3. select a collection
4. click on Save

### Expected Result

That the entry moves as in the web view or appears in the collection provided for this purpose.

### Actual Result

I go to an existing entry that is in an organization and click on Collections to move the entry

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/cd965c75-da59-4466-9451-c8ea52f448b8)

### Operating System

Windows

### Operating System Version

WIN 11 PRO

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.7.1 Shell 31.2.0 Renderer 126.0.6478.127 Node 20.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue but was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
