### ISSUE TITLE
URL Sorting

### ISSUE THREAD

**Issue by bzmshang** [bitwarden/clients#10476]
### Steps To Reproduce

Normal sorting change and custom icon selection.

### Expected Result

1. "I am unable to change the URL sorting using the web version, desktop version, mobile version, or browser plugin, but the icon recognition only identifies the first URL, making it very cumbersome to change the sorting. I hope this can be improved."

2. "Additionally, the way icons are obtained may not match the desired icons, and there is no way to customize the icons."

### Actual Result

Cannot change the URL sorting, cannot customize icons.

### Operating System

Windows

### Operating System Version

windows，edge，android

### Installation method

Other

### Build Version

As of August 11, 2024, the latest version released on GitHub.

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @bzmshang,

Thank you for this report. This seems to be closer to an improvement suggestion or a feature request, than a report about a certain function not operating as expected; With that in mind, please feel free to submit your ideas in the [Feature Requests](https://community.bitwarden.com/c/feature-requests/5/none) section of the Bitwarden Community Forums.

You can sign up on the Bitwarden Community Forums and search for this idea, just in case a similar request already exists. If you find one, you can vote for it and contribute to any discussions about it; If not, you can submit this idea as a new request there so that it can be properly tracked.

Because we used GitHub to track bugs and other development related issues, this report will now be closed. Please note that the “Closed as not planned” status is for internal tracking purposes only; Please do not hesitate to submit your suggestion to in the Community Forums.

Thank you again,
