### ISSUE TITLE
Ubuntu Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by thewraithofharambe** [bitwarden/clients#10495]
### Steps To Reproduce

1. Go to Bitwarden on Linux system 76 galago pro
2. Click on login credentials move to next PW entry.
enter PW and it works on my mobile, iMac, etc, and it says its incorrect on this machine.
No PW reset option for obvious reasons.

### Expected Result

Bitwarden to open up.

### Actual Result

Repeated attempts to login lead to failure.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.7.1 Shell 31.2.0 Renderer 126.0.6478.127 Node 20.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of keyboard layout or similar.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
