### ISSUE TITLE
Bitwarden Inline Autofill Dropdown not Showing on Latest Firefox Nightly

### ISSUE THREAD

**Issue by M1ch431** [bitwarden/clients#10494]
### Steps To Reproduce

1. Go to any website with a login form.
2. Click on login fields.
3. Bitwarden icon doesn't do anything (but shows), and when enabled the inline autofill dropdown doesn't show.

### Expected Result

The inline autofill to show available logins as intended.

### Actual Result

Doesn't work regardless of settings/how many logins are present for a website. The context menu works fine to autofill.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

131.0a1 (2024-08-12) (64-bit)

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a conflict with another extension or browser flag/setting.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
