### ISSUE TITLE
Crash when put a first email character in Ubuntu snap

### ISSUE THREAD

**Issue by alexandresoliveira** [bitwarden/clients#10555]
### Steps To Reproduce

1.  Install snap (sudo snap install bitwarden)
2. Open app
3. Put email

### Expected Result

It was expected to put all email and password for login

### Actual Result

Put the first character and app close

### Operating System

Linux

### Operating System Version

Ubuntu 24.04 LTS

### Installation method

Snap

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by sevenstars770** [comment]
Same problem wit Ubuntu 25.04
