### ISSUE TITLE
Can't login to Bitwarden through OS app

### ISSUE THREAD

**Issue by hml808** [bitwarden/clients#10637]
### Steps To Reproduce

1. Open iphone app
2. attempt to login with exact same credentials as for desktop app and browser extension 

### Expected Result

I expected to get in

### Actual Result

 it gives me an error message even though I'm using the same EXACT master password as desktop

### Screenshots or Videos

I have a feeling you know about this issue; It's a red error message 

### Operating System

iOS

### Operating System Version

iOs 17.6

### Web Browser

Chrome

### Build Version

N.A.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
