### ISSUE TITLE
Safari extension triggers high CPU authentication service in Safari Technology Preview 201 (Safari 18.0)

### ISSUE THREAD

**Issue by quimic** [bitwarden/clients#10651]
### Steps To Reproduce

1. Make sure the Bitwarden extension is NOT enabled in Safari 
2. Install Safari Technology Preview 201 (latest version as of this writing)
3. Enable the extension

### Expected Result

The extension should not generate high CPU

### Actual Result

com.apple.AuthenticationServicesCore.AuthenticationServicesAgent-STP process is started and uses high CPU (120% or more).
Once started, the service in question never stops until forced to quit

### Screenshots or Videos

![PixelSnap 2024-08-21 at 11 22 39](https://github.com/user-attachments/assets/70f3b788-bfdd-4103-a087-2dc88a957ef4)

### Additional Context

After force quitting the com.apple.AuthenticationServicesCore.AuthenticationServicesAgent-STP process, any new call to the extension (like visiting a website that requires authentication) will restart it.
Uninstalling the extension does not stop the process either (you still need to force quit it).

This issue is specific to Safari Technology Preview, so it is probably not strictly a Bitwarden bug. But no other extension I used is Safari Technology Preview triggered this issue.

### Operating System

macOS

### Operating System Version

14.6.1

### Web Browser

Safari

### Browser Version

201 (Safari 18.0)

### Build Version

2024.7.1 (server version 2024.7.4)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @quimic 

We are only able to test or use Bitwarden in the current version of MacOS Sonoma with Safari version 17.6.

We use GitHub issues as a place to track bugs and other development related issues, especially with the corresponding stable operating systems. 

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
