### ISSUE TITLE
Email Verification Broken on Firefox

### ISSUE THREAD

**Issue by Pretentiousness** [bitwarden/clients#10694]
### Steps To Reproduce

1. Go to 'your personal email'
2. Click on 'verify email.'
3. Email Verification Fails

### Expected Result

To verify email

### Actual Result

Unable to verify email

### Additional Context

This only happens in firefox (both desktop and mobile). after many failed attempts i was able to verify using microsoft edge instead (chromium)

### Operating System

Windows

### Operating System Version

23H2 22631.4037

### Web Browser

Firefox

### Browser Version

129.0.2 (64-bit)

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try clearing your browser's cache and cookies before logging back in and sending the verification email.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
