### ISSUE TITLE
Autofill forms

### ISSUE THREAD

**Issue by icegood** [bitwarden/clients#10710]
### Steps To Reproduce

Pre-conditions:
1) User has 100% filled up the identity form

Use case: 
1) Goto site 
https://en.pylontech.com.cn/service/support/
and try to fill up values from identity

### Expected Result

appropriate values from identity profile would be filled up

### Actual Result

failed phone number, email, city, address, Country

### Operating System

Linux

### Operating System Version

Ubuntu 24.04 LTS

### Web Browser

Chrome

### Browser Version

Version 127.0.6533.119 (Official Build) (64-bit)

### Build Version

Version: 2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
