### ISSUE TITLE
Uptodate.com autofill broken

### ISSUE THREAD

**Issue by Anvil5465** [bitwarden/clients#10739]
### Steps To Reproduce

1. Go to 'uptodate.com'
2. Click on 'sign in'
3. Autofill the username so that the password field emerges
4. Autofill again now that the username and password fields are both visible

### Expected Result

Both the username and password fields will be autofilled

### Actual Result

The password field disappears when I attempt to autofill, presumably because the website detects that the username is being modified by Bitwarden

### Operating System

Linux

### Operating System Version

Fedora 40

### Web Browser

Brave

### Browser Version

1.69.153

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
