### ISSUE TITLE
Desktop login issue

### ISSUE THREAD

**Issue by dfm2422** [bitwarden/clients#10804]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Often, when desktop app opens, the login dialog does not seem to appear.

### Actual Result

Often, when desktop app opens, the login dialog is hidden behind the app.
This occurs when the  app runs on startup.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.8.1 Shell 31.3.1 Renderer 126.0.6478.185 Node 20.15.1 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. You could try reinstalling the desktop app once more to see if this helps your issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
