### ISSUE TITLE
Password with passkey could not display properly and causes crashes on chrome extension and macos app

### ISSUE THREAD

**Issue by jchen8tw** [bitwarden/clients#10811]
### Steps To Reproduce

1. Go to any password stored with passkey
2. Click on the password

### Expected Result

The password should show properly just like how it does on IOS app.

### Actual Result

The password did not show properly. It become uneditable and occasionally causes the app to hang or crash if I click other password afterwards.

### Screenshots or Videos

<img width="418" alt="截圖 2024-08-30 上午9 47 06" src="https://github.com/user-attachments/assets/10b0974d-6ca1-4276-9226-6a6bc724f120">

### Operating System

macOS

### Operating System Version

14.6.1（23G93）

### Installation method

Mac App Store

### Build Version

版本 2024.7.1 Shell 31.2.0 Renderer 126.0.6478.127 Node 20.15.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of some sort on your machine.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jchen8tw** [comment]
@daniellbw 
Hi, thank you for your prompt response. 
I have figured out that the problem is resolved when I change my language from zh-TW(Traditional Chinese) to english and reappear when I change my language back to zh-TW.
It might be the reason why this problem is not reproducible on your device.

**Comment by idzbg** [comment]
Same here. 

The problem only appears in "zh-TW - 中文（台灣）", 
but not in "zh-CN - 中文（中国大陆）".

Hope this help finding the problem.
