### ISSUE TITLE
Unable to enable Windows Hello

### ISSUE THREAD

**Issue by EJB15** [bitwarden/clients#10829]
### Steps To Reproduce

1. Go to 'settings'
2. Click on 'Unlock with Windows Hello'
3. Scan fingerprint or face

### Expected Result

After you scan your fingerprint or face then the "Unlock with Windows Hello" box  should remain checked. It should work when you open Bitwarden next time.

### Actual Result

After you scan your fingerprint or face, the box is unchecked and it won't work to unlock.

### Screenshots or Videos

https://github.com/user-attachments/assets/0b647c7f-8579-4d5d-a729-7d3cc13c4f05

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @EJB15,

Thank you for reporting this. I am able to unlock the Bitwarden desktop client (.exe) on Windows 11 Pro (23H2) via Windows Hello (Facial Recognition). I recommend that you proceed and test this with a fresh new installation; Please uninstall the Bitwarden desktop client, clear its [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the machine, install it a new and test that again; If you encounter the same behaviour, please deactivate Windows Hello so that your Windows User Account is protected with only a password (not a PIN), and then set Windows Hello up anew and check if that assists.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by ValueXu** [comment]
Same bug here, it's my first time to use Bitwarden client from MS Store. After uninstalling and using installer version, problem still exists. It‘s absolutely a bug.
