### ISSUE TITLE
On Cardmarket.com , impossible to auto-fill and no login drop-down list for login/password fields 

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#10898]
### Steps To Reproduce

1. Go to https://www.cardmarket.com/fr/
2. Try to login using Bitwarden (add an entry for this website in Bitwarden if you do not have one, anything will do as you don't actually need a really login/password)

### Expected Result

Having your login/password being automatically filled-out in the corresponding fields

### Actual Result

You get the error message: "Unable to auto-fill the selected item
on this page. Copy and paste the
information instead."

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/4d45262d-dac3-4f30-8afd-5f45920a4140)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

v128.0

### Build Version

v128.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration in your **Settings** > **Enable Autofill on Page Load**

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
