### ISSUE TITLE
Your email today said to update the extension.  There is no way to do that.

### ISSUE THREAD

**Issue by Celerity2** [bitwarden/clients#10916]
### Steps To Reproduce

1. Go to 'the Firefox extension.'
2. Click on 'Settings....'
3. Scroll down to 'About.or Options...'
4. Click on 'About or Options..'

### Expected Result

Your email today was titled: Bitwarden Release Notes | 2024.8.0 - 2024.8.2
Your email today said to update the browser extension.: 
Here is the quote: "Please note: Applications and browser extensions need to be updated to the latest version for new features. "
If updating is not automatic, how do I update the browser extension?

### Actual Result

I don't see a way to update the browser extension.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 22H2

### Web Browser

Firefox

### Browser Version

130.0

### Build Version

Bitwarden extension 2024.4.1, server 2024.8.1, desktop app 2024.8.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

The Bitwarden browser extension typically should update automatically. If this is not happening, please uninstall the extension, and then re-install the extension: [https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/?browser=firefox](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/?browser=firefox )

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
