### ISSUE TITLE
Support generating email aliases in Email fields if it's configured

### ISSUE THREAD

**Issue by tunnckoCore** [bitwarden/clients#10940]
### Steps To Reproduce

Hey there.

I configured a DDG email alias forwarding with api key, but it seems the extension does not detect email fields. I mean, it doesn't suggest to generate email like the DDG extension does.

I have problem connecting what email alias is for what, and usually i use AnonAddy for aliasing, but recently started using more DuckDuckGo's. The only thing i miss there is to name/describe each alias for what it is - plus that it doesn't keep track of all used/generated ones but that's another story.

### Expected Result

Something like the default behavior of DuckDuckGo's extension - email field dropdown/popover to generate email alias.

### Actual Result

none

### Operating System

Linux

### Web Browser

Firefox

### Build Version

Server 2024.8.1 / Version 2024.1.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
