### ISSUE TITLE
App starts with blank screen

### ISSUE THREAD

**Issue by tgelser** [bitwarden/clients#10987]
### Steps To Reproduce

1. Start the App
2. Empty screen
3. Restart the App
4. Everything normal afte second start

### Expected Result

App should show GUI on first start

### Actual Result

App not showing GUI on first start. Only after closing the App and starting again everything works as expected (GUI shows)

### Operating System

Windows

### Operating System Version

10 22H2 and 11 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
