### ISSUE TITLE
Chrome extension wont autofill or use passkey

### ISSUE THREAD

**Issue by matthewjrallen** [bitwarden/clients#11032]
### Steps To Reproduce

Autofill doesnt show on login form
1. click bitwarden extension
2. click login
3. error shows: "Unable to auto-fill the selected item on this page. Copy and paste the information instead"

### Expected Result

The username and password should be automatically entered into the login form

### Actual Result

Error shows: "Unable to auto-fill the selected item on this page. Copy and paste the information instead"

### Screenshots or Videos

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/7d1b0584-f301-4405-a4a7-ea07979c0af2)

### Operating System

macOS

### Operating System Version

13.6.9

### Web Browser

Chrome

### Browser Version

128.0.6613.120

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you verify that the item contains the correct URI for the website you're trying to autofill? 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by JABirchall** [comment]
This is a duplicate of #10814 and #10815
