### ISSUE TITLE
TOTP not providing correct MFA codes

### ISSUE THREAD

**Issue by debugdeem** [bitwarden/clients#11086]
### Steps To Reproduce

1. set up MFA for an account
2. view QR code to scan or manual code
3. open bitwarden app or desktop app
4. scan QR code with app or enter manual code into desktop app
5. verify code

### Expected Result

After verifying, the result should show the correct MFA code. But it does not.

### Actual Result

Incorrect MFA code is being generated after verifying the code initially.

### Additional Context

I was trying to log into a website. The 2FA code generated from Bitwarden Desktop App did not work. I clicked edit on the entry in Bitwarden, copied the TOTP Authenticator Key (the long code), I sent that to myself in an email, and added this entry into Microsoft Authenticator app on my phone. After manually entering the code and adding this to the Microsoft Authenticator, the MFA code generated worked successfully.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.8.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. TOTP generated codes are based on the system clock of a device. If there is a mismatch between the device clock and the server clock, then the codes generated may not work as expected.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
