### ISSUE TITLE
Save and edit icons are missing

### ISSUE THREAD

**Issue by KeGitHub25** [bitwarden/clients#11107]
### Steps To Reproduce

1. Go to 'folders/Item Right click edit'
2. update password '....'
3. No button or icon to save '....'
4. Click on '...'

### Expected Result

Unable to save password after updating the password

### Actual Result

earlier there was a save button next to edit

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Windows 11 Home

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so:

![save](https://github.com/user-attachments/assets/375db658-638e-46a4-aa26-e285f4d41298)

I suggest you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing. Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
