### ISSUE TITLE
LinkedIn compatibility issue - role="combobox"

### ISSUE THREAD

**Issue by luxalpa** [bitwarden/clients#11101]
### Steps To Reproduce

In the LinkedIn window for "Tell us what kind of work you’re open to", the "Job Title" field is incorrectly mistaken for a login field and whenever trying to enter any text there, the auto-fill dropdown appears and covers the actual drop-down from linkedIn

### Expected Result

Bitwarden dropdown should not appear for input elements with `role="combobox"`

### Actual Result

Bitwarden Drop-down covers the actual drop-down, making it unusable.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/1ecc9ed2-d500-4abf-927c-50b23aba3077)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Firefox

### Browser Version

130.0

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

You can change the settings in Bitwarden to prevent the auto-fill dropdown from appearing automatically. Navigate to Settings > Autofill in your Bitwarden browser extension, and change the option selected for 'Show autofill menu on form fields' from 'When field is selected (on focus)' to 'When autofill icon is selected'. This should prevent the inline autofill menus from popping up automatically in fields that have focus.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by cagonzalezcs** [comment]
@luxalpa 

Thank you for providing this report. We have an extension release coming soon that incorporates the changes from https://github.com/bitwarden/clients/pull/10865.

That should fix the problem experienced on LinkedIn's form by tightening up the logic for where we place the autofill inline menu.

Beyond that, I spoke with the team and we are in agreement with you regarding blocking presentation of the inline menu when a form indicates that it contains a `combox` implementation in some manner. We'll be working to incorporate a fix for that in the near future.
