### ISSUE TITLE
Unable to download note attachments

### ISSUE THREAD

**Issue by max06** [bitwarden/clients#11104]
### Steps To Reproduce

1. Have a note with an attached file
2. Open Note
3. Click attachment or the download button next to it

### Expected Result

"Save as"-dialog should open up.

### Actual Result

Nothing happens. (I can see the file being requested in the browser debug tools)

### Additional Context

I was able to get the attachments using your desktop app. Otherwise I would have been very screwed.

### Operating System

Linux

### Operating System Version

NixOS unstable/KDE

### Web Browser

Vivaldi

### Browser Version

6.9.3447.41

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by max06** [comment]
Is it reproducible if that note requires the master password?
