### ISSUE TITLE
Password generator not working correctly

### ISSUE THREAD

**Issue by spinlud** [bitwarden/clients#11146]
### Steps To Reproduce

Password generator doesn't seem to follow the specified settings:

![image](https://github.com/user-attachments/assets/26938c12-4a5e-4619-b5b3-e94a9b02f57d)

### Expected Result

Password generator should follow the specified settings.

### Actual Result

![image](https://github.com/user-attachments/assets/26938c12-4a5e-4619-b5b3-e94a9b02f57d)

### Operating System

macOS

### Operating System Version

14.7

### Web Browser

Chrome

### Browser Version

128.0.6613.138

### Build Version

2024.9.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
