### ISSUE TITLE
chromium bug 129

### ISSUE THREAD

**Issue by DarklinuxFr** [bitwarden/clients#11170]
### Steps To Reproduce

I go to the bitwarden site
2. I click on connect
3. I enter my email address
4. I enter my password

### Expected Result

access to my account

### Actual Result

nothing

### Operating System

Linux

### Operating System Version

debian 12.7

### Web Browser

Chrome

### Browser Version

129

### Build Version

Version 129.0.6668.58 (Build officiel) built on Debian GNU/Linux 12 (bookworm) (64 bits)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
