### ISSUE TITLE
Browser extension accepts master-password, that is wrong for web and anroid client

### ISSUE THREAD

**Issue by andschir** [bitwarden/clients#11189]
### Steps To Reproduce

I am logging in browser extension with my master password. 
Using the same password in web version or android client fails with "Incorrect login or password", with login and password being basically same.

### Expected Result

Logging behaviour is same an all platforms for one account

### Actual Result

Browser extension lets me to login with master password, while web and android clients fails with "Incorrect login or password"

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so - it would be best to contact the support team to troubleshoot this issue, as it doesn't seem to be a client bug.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
