### ISSUE TITLE
Vault items blank in Windows Bitwarden App.  The matching item will appear in search and work fine, but the initial list does not populate anything but the icons.

### ISSUE THREAD

**Issue by SallyMstar** [bitwarden/clients#11192]
### Steps To Reproduce

1. Go to 'Window Bitwarden app and login as usual'
2. Click on 'All Items or any of the list options'
3. The item list is blank, but the icons are visible.
4. If you click on the item, the data is missing 
5. If you search for an item, it does show up and is fully functional

### Expected Result

'List of All Items entries should be displayed after I log in.  Will only return proper results when search is executed for the desired line item.'

### Actual Result

'No entries are shown, only can see the icons.  Data is missing when I click on the icon, but it does then show the date updated, date created, and password history.'

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/14148e59-0c72-4c85-8d49-fd19ea8b7594)

![image](https://github.com/user-attachments/assets/565e897f-87c7-4473-a5bc-fd38148f4b35)

![image](https://github.com/user-attachments/assets/2db58c58-0845-4724-8e54-98f3f436a883)

### Additional Context

'I also tried light, dark, and Nord themes in case it was a text color issue.  There was no change to the visibility of the items.'

### Operating System

Windows

### Operating System Version

'Windows 11 Home Edition; Version 10.0.22631 Build 22631'

### Web Browser

Chrome

### Browser Version

'app only - browser works fine'

### Build Version

'Version: 2023.5.1 '

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the desktop app being out of date - this version was released in May 2023. Please try updating, or re-downloading from the page below.

Bitwarden Downloads: https://bitwarden.com/download

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
