### ISSUE TITLE
MacOS client master password not synced

### ISSUE THREAD

**Issue by kanish671** [bitwarden/clients#11190]
### Steps To Reproduce

1. Change the master password using web
2. Open MacOS desktop client
3. Enter new master password
4. Client says invalid master password. (Can login with TouchID though)
5. Logout using the options menu
6. Login again
7. This time the new master password works

### Expected Result

The new master password is synced as soon as it is changed on web. Client doesn't allow login with touchID when master password has been changed on web.

### Actual Result

The new master password is not synced to the desktop client. Client allows login with touchID (hence bypassing the new master password).

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software - the client has a cached session with the previous master password, and these unlock options are offered even when a client is offline. Once the client syncs, it will update with the latest master password.

If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
