### ISSUE TITLE
TouchID not detected using Firefox extension on Sonoma and M2 MacBook Air

### ISSUE THREAD

**Issue by golemB** [bitwarden/clients#11213]
### Steps To Reproduce

1. Go to AWS Console login page for an account with a login that uses WebAuthn as a second factor.
2. Enter the Account ID or account alias, IAM user name, and Password, then click "Sign In".
3. A fingerprint icon appears in the left side of browser nav bar, with text saying "Touch your security key to continue with <URL>."
4. Touching the fingerprint sensor causes no discernible effect, despite multiple attempts.

[](url)

### Expected Result

I would expect the login to work when I touch the fingerprint sensor on my M2 MacBook Air.  (It works fine for me in Chrome, though both browsers have the BitWarden extension installed.  In Chrome, it causes a system dialog to pop up prompting me to touch the fingerprint sensor, rather than the browser-based message in Firefox.)

### Actual Result

Touching the fingerprint sensor causes no discernible effect, despite multiple attempts.

### Additional Context

Potentially complicating factors:
1. Initially, when I tried to log in, the BitWarden extension showed a prompt allowing either its WebAuthn to run, or to use the system/hardware WebAuthn.  I think I told it to always use the system/hardware WebAuthn.
2. This AWS login was set up with both a BitWarden WebAuthn passkey, and a system/hardware passkey (via the fingerprint sensor).  I tried deleting the BitWarden WebAuthn passkey (by logging in with Chrome then deleting that passkey from IAM), and then logged out and tried logging in with Firefox, but the same problem occurs.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Firefox

### Browser Version

130.0 (64-bit)

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of Firefox settings, or the Ask to save and use passkeys option in the extension.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
