### ISSUE TITLE
Endless loading Spinner desktop Bitwarden Linux Mint 21.3

### ISSUE THREAD

**Issue by felix2380** [bitwarden/clients#11276]
### Steps To Reproduce

4. Click on '...'
I'm going to open Bitwarden desktop
I click on the application
I get endless loading

### Expected Result

My expectations are to be able to enter the password and open the Bitwarden vault

### Actual Result

Endless loading

### Screenshots or Videos

![Screenshot from 2024-09-27 07-40-22](https://github.com/user-attachments/assets/6e17dba3-fbe3-4875-a59d-6fda9bdb286d)

### Additional Context

This problem with endless loading is recent for about 2 days

### Operating System

Linux

### Operating System Version

21.3

### Installation method

Other

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by felix2380** [comment]
I know that this problem has existed before, but I have been experiencing this problem for 2 days.

**Comment by felix2380** [comment]
The application is installed from Flatpak (Flathub)

**Comment by BBGhub** [comment]
Hi There,

I'm glad to assist you with resolving the issue you're experiencing with the Bitwarden desktop app. Please follow these instructions:

Can you close the desktop app, and remove the folder for your OS: https://bitwarden.com/help/data-storage/#on-your-local-machine

Please relaunch Bitwarden and attempt to sign in again.

Please note that our team is actively investigating this issue, which appears to be related to the GPU hardware acceleration settings on the Bitwarden app. You can track the progress of this issue here: https://github.com/bitwarden/clients/issues/6691 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).
