### ISSUE TITLE
BitWarden AutoFill hides form elements

### ISSUE THREAD

**Issue by JP95Git** [bitwarden/clients#11282]
### Steps To Reproduce

- Install Firefox and Bitwarden extension.
- Connect the extension to a self hosted BitWarden
- Open a website, which has no credentials stored in BitWarden

### Expected Result

All form fields are visible. It should be enough to just show the little blue icon in the input fields and show the big popup only when clicked on the icon.

### Actual Result

The autofill-popup shows the text "Kein Eintrag zum Anzeigen" but hides most parts of the input form.

### Screenshots or Videos

![bitwarden-hide-form-fields](https://github.com/user-attachments/assets/a8be31cf-1e78-4191-a147-8272cc4e9df0)

Left: BitWarden hides my form.
Right: Press ESC shows the form again.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

130

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

Your issue appears to be describing the intended default behavior of the software. You can change the behavior of the Bitwarden browser extension to match your expected result by:

1. Open the Bitwarden browser exentsion
2. Click **Settings**
3. Click **Autofill**
4. Under the option **Show autofill menu on form fields** change it to **When autofill icon is selected**

If you want this default behavior to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by JP95Git** [comment]
@daniellbw 
The settings are not used, as seen on the linked issue and as seen in my current settings:
![grafik](https://github.com/user-attachments/assets/3d388d5c-ac82-48b5-845f-0adedc3c6036)

Furthermore I think this is a bug and no feature.
Are you telling me that it is a feature that the extension makes input forms unusable by hiding parts of them.
