### ISSUE TITLE
Holding ”option”, ”command” and then pressing ”space” to switch to Finder and bring up a search window there keeps Bitwarden on top when vaults are locked

### ISSUE THREAD

**Issue by star-affinity** [bitwarden/clients#11308]
### Steps To Reproduce

1. Have Bitwarden open, as the frontmost application and all vaults locked.
3. Hold down down ”option”, ”command” and then press ”space”.  
4. This should switch to the Finder and bring up a search there, but for some reason Bitwarden stays as the frontmost application. This does not happen if the vault in Bitwarden is unlocked – then the switch to the Finder as the active application also happens. 
5. Of all the applications I use Bitwarden is the only one that behaves this way.

### Expected Result

I expect the switch to Finder as the front most app to happen no matter if Bitwarden's vault  is locked or not.

### Actual Result

Bitwarden stays at the front even if it shouldn't.

### Operating System

macOS

### Operating System Version

Sonoma 14.7

### Installation method

Mac App Store

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin as a random device specific error and not a bug, a restart of the system or update of the OS may resolve the issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
