### ISSUE TITLE
Unable to use self-hosted login via https

### ISSUE THREAD

**Issue by kotorimiku** [bitwarden/clients#11329]
### Steps To Reproduce

Using https URLs in self-hosted

### Expected Result

Can log in successfully

### Actual Result

Unable to log in successfully. After clicking login, it says "failed to fetch"

### Screenshots or Videos

![1](https://github.com/user-attachments/assets/7804ea07-acdd-468d-9be2-668776e0014b)

### Additional Context

You can log in using an http URL. By capturing packets, it is found that no matter whether you use an http URL or an https URL, the request sent by the client is http. This problem also exists in the Android client, but not in the Chrome extension.

### Operating System

Windows

### Operating System Version

win11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.9.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
