### ISSUE TITLE
Autofill doesn't autofill

### ISSUE THREAD

**Issue by t1b00** [bitwarden/clients#11343]
### Steps To Reproduce

1. Go to any website with a saved login
2. Try to auto-fill with Command+Shift+L

### Expected Result

Bitwarden should autofill

### Actual Result

Nothing happens until I click on the extension icon. It then gets filled.

### Screenshots or Videos

https://github.com/user-attachments/assets/88d4c471-22fe-47f3-ae22-53492bfb4f48

### Additional Context

I also contacted Bitwarden support, they recommended that I enable Automatic autofill but this doesn't change anything.
When the login menu pops up and click on a login item, nothing happens until I click on the extension icon.
I have been using Bitwarden for multiple years and it has only started doing this roughly two months ago.

On the screen recording, I have automatic autofill enabled and as you can see nothing happens. If I press Command+Shift+L, nothing happens either, it is only once I click on the icon the something happens.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Safari

### Browser Version

17.6

### Build Version

19618.3.11.11.5

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content. Please keep working with our support to troubleshoot this issue. 

The issue here will be closed.

Thanks!
