### ISSUE TITLE
Passkey use does not copy TOTP

### ISSUE THREAD

**Issue by puenka** [bitwarden/clients#11360]
### Steps To Reproduce

0. Have the TOTP clipboard setting enabled
1. Go to a passkey supported login page (e.g. Amazon)
2. Use the passkey authentication method

### Expected Result

The TOTP should be in the clipboard.

### Actual Result

The TOTP is not in the clipboard when using the passkey, but only when using password login methods.

### Operating System

Windows

### Web Browser

Brave

### Build Version

1.70.119

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development-related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
