### ISSUE TITLE
Browser extension possible incompatibility with Portalguard

### ISSUE THREAD

**Issue by polymo1** [bitwarden/clients#11371]
### Steps To Reproduce

Prereq: Have a portalguard instance accessible, mine is provided through my college, as that is what the college uses for an SSO portal.

Enable 2FA on the portal guard account
Put account information + 2fa code into Bitwarden and enable the autofill menu, but not autofill on page load
Click the account and click login.

### Expected Result

Bitwarden autofills username, password, and 2fa code into portalguard and the authentication is wholly successful.

### Actual Result

Bitwarden autofills username into portalguard, and either while the password is being printed, while the login button is being printed, or while the 2fa code is being printed, an error appears many many times. 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/36a68f37-4149-4459-81c8-97dc3814985b)

### Additional Context

I use Vaultwarden, but this feels like an issue with either portalguard or the extension

### Operating System

Windows, Linux

### Operating System Version

All to what I've seen

### Web Browser

Chrome, Microsoft Edge, Firefox

### Browser Version

All to what I've seen. I'm running Firefox 130.0.1 on Windows 10 right now

### Build Version

Version: 2024.9.1  Server version (Third-party): 2024.2.0 

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the specific login portal.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by polymo1** [comment]
Alright, thanks for looking into it.
