### ISSUE TITLE
uptodate.com doesn't work with autofill

### ISSUE THREAD

**Issue by thibaultmol** [bitwarden/clients#11393]
### Steps To Reproduce

1. Go to https://www.uptodate.com/login
2. Try to login by clicking the login in the bitwarden extension
3. It'll autofill both fields but reset so it gets stuck 

### Expected Result

It doesn't login

### Actual Result

You have manually copy the password and paste it instead

### Screenshots or Videos

i think the js on this website is resetting the username field each time you try to autofill, making the password field dissapear

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
