### ISSUE TITLE
I cannot drag and drop files into the attachment window while editing a login/secure note

### ISSUE THREAD

**Issue by Majestic7979** [bitwarden/clients#11427]
### Steps To Reproduce

Create a login or secure note.
Open the attachments menu.
It's not possible to drag and drop multiple files, or even just a single file, into the attachments upload window. I have to select 1, upload, select the 2nd, upload, select the 3rd file, upload, etc. This is honestly stupid and cumbersome, for managing software licences with multiple documents that I need to save as attachments for future reference/auditing purposes it's a nightmare! Imagine having to complete this process for 100+ documents.
It's 2024, drag and drop is a thing, I humbly and politely request you to please implement drag and drop/multiple file upload on the Attachments menu, thanks in advance.

### Expected Result

Able to easily upload a single, or multiple files by dragging from an email client or file explorer and dropping into the attachments upload window on Bitwarden.

### Actual Result

The mouse cursor changes showing the + sign next to the arrow, but when I release the mouse the files do not upload as expected.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
