### ISSUE TITLE
Firefox extension: bitwarden does not offer to update stored credentials or to create new

### ISSUE THREAD

**Issue by endlessterror** [bitwarden/clients#11499]
EDIT: This is a browser issue, not a desktop one. Please modify the label if possible.

### Steps To Reproduce

During the first days I can recall that the bitwarden extension (currently 2024.9.1) presented a toolbar to ask me whether I'd like to save changes to credentials stored, on my Firefox (131.0.2 atm).

The extension was installed from the firefox store.

Steps to reproduce:
1. Visit a site for which credentials are stored and offered by bitwarden
2. Elect to change the password

### Expected Result

Bitwarden should ask whether I'd like to update the stored credentials. If I recall correctly, a toolbar appeared a couple of times, but that was it.

### Actual Result

BW does not do anything at all. Stored credentials still contain the old password.

### Operating System

Windows

### Operating System Version

10 22H2

### Installation method

Other

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by endlessterror** [comment]
Let me add that even adding new credentials to the vault goes undetected by the extension. Looking around I thought that my case was an exception, but I've stumbled a 3-year old (!!!) thread that describes the exact same issue, https://github.com/bitwarden/clients/issues/1620

Although I was really excited initially, it now feels that bitwarden lacks a decade compared to the Firefox sync password handling and syncing, which has been operating flawlessly all the time. No point in gaining a number of security gimmicks, if I don't have some basic functionality on both my browsers and my Android phone.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so on multiple platforms. I think your error could have its origin in a potential cached data issue with browser extension.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
