### ISSUE TITLE
Switching accounts not working; loads forever

### ISSUE THREAD

**Issue by jonaskohl** [bitwarden/clients#11500]
### Steps To Reproduce

1. Have two or more accounts signed into Bitwarden
2. Have all vaults be locked
3. Open the extension popup/sidebar
4. Click on the profile selector on the top right
5. Switch to a different vault

### Expected Result

Bitwarden should now prompt me for the master password of the other vault

### Actual Result

A loading spinner appears for about 30 seconds, then disappears without changing anything.

Inspecting the extension popup page I see the following message:

> ⚠️ message 'switchAccount' never responded. [console-log.service.ts:47:16]

### Operating System

Windows

### Operating System Version

11 23H2

### Web Browser

Firefox

### Browser Version

131.0.2

### Build Version

2024.9.1 (Server version 2024.9.2)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
