### ISSUE TITLE
DuckDuckGo browser - Bitwarden is not responding

### ISSUE THREAD

**Issue by markj-s** [bitwarden/clients#11524]
### Steps To Reproduce

Ventura 13.7 on MacBook 2017 12 inch
DuckDuckGo Browser Version 1.108.0 (276) - not the App Store version
Bitwarden Version 2024.9.0 (30042)

### Expected Result

I am having a problem getting the DuckDuckGo (DDG) browser to work with Bitwarden. Despite having selected the option to allow the DDG browser integration, the browser keeps showing me a message saying “Bitwarden is not responding. Please restart it to initiate the communication again.”. Having done this though, DDG still shows me the same message which I can only get rid of by clicking on cancel. If I then visit a page where I need to login, DDG shows that Bitwarden is locked even though I have unlocked it.

I use both DDG and Bitwarden on a Mac Mini M2 and they work fine. Recently though the integration of the 2 applications will not work on my older Intel MacBook. I have tried reinstalling both of them but the issue continues.

### Actual Result

The DDG browser is failing to communicate with Bitwarden.

### Screenshots or Videos

<img width="336" alt="SCR-20241012-sbxc-2" src="https://github.com/user-attachments/assets/e55ed3db-012c-4a16-aee5-b3d05ba8ef57">

### Operating System

macOS

### Operating System Version

13.7

### Web Browser

Safari

### Browser Version

DuckDuckGo 

### Build Version

1.108.0 (276)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please ensure that Bitwarden is successfully integrated with DuckDuckGo. You can confirm this by checking for a green checkmark next to Bitwarden in the passwords and autofill settings of the browser. Also ensure that you've granted full disc access to DuckDuckGo. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
