### ISSUE TITLE
Unable to enable unlock with Biometrics in Firefox on MacOS

### ISSUE THREAD

**Issue by qwikatb** [bitwarden/clients#11600]
### Steps To Reproduce

1. Start Firefox
2. Click on Bitwarden extension icon
3. click on settings
4. click on account security 
5. click on unlock with biometrics

I receive a message stating that the desktop app needs to be started before unlock with biometrics can be used.  I am attaching a screenshot that clearly shows both the message and that the desktop app is running and open  

MAC OS 18.1 Firefox 131.0.3 (aarch6)

![CS 2024-10-17 42 2](https://github.com/user-attachments/assets/2b42deb7-2fde-41a2-a56f-7db6b1941c00)

### Expected Result

Able to unlock the Firefox extension with bio-metrics rather than having to enter the master password every time I start Firefox. 

### Actual Result

Error message is received 

### Screenshots or Videos

Attached 

### Operating System

macOS

### Operating System Version

18.1

### Web Browser

Firefox

### Build Version

131.0.3 (aarch6)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, could you try uninstalling and reinstalling the extension and ensure that you are logging into the same Bitwarden account both on Desktop and on the extension.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
