### ISSUE TITLE
Can update password with out master password re-prompt.

### ISSUE THREAD

**Issue by dhon-rh** [bitwarden/clients#11622]
### Steps To Reproduce

1. Go to any site with an existing stored credential in Bitwarden with the Master password re-prompt option enabled.
2. Login as with a new password manually, ignore the Bitwarden auto-fill.
3. Bitwarden will show UPDATE password prompt near tool bar.
4. Click the UPDATE button to update the stored credentials without a re-prompt for master password.

### Expected Result

Bitwarden should re-prompt for master password before allowing the UPDATE password process to complete.

### Actual Result

Bitwarden updates the stored credentials without re-prompting for master password.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

131.0.3 (64-bit)

### Build Version

Version: 2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development-related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
