### ISSUE TITLE
Overprotected Pasteboard type

### ISSUE THREAD

**Issue by leonvogt** [bitwarden/clients#11631]
### Steps To Reproduce

1. Go to a vault entry
2. Click on the copy button on a cleartext field like Username
3. The copied text will not be visible in a clipboard manager, since it was copied with the `nspasteboard.ConcealedType` flag

### Expected Result

I would expect that cleartext values like Username would be copied without `nspasteboard.ConcealedType` so clipboard managers could store the copy.    
I would expect that only passwords and hidden fields are being copied with `nspasteboard.ConcealedType`.

### Actual Result

It seems that everything in Bitwarden now is beeing copied with `nspasteboard.ConcealedType`.    
Nothing that I copy with "copy button" in Bitwarden is beeing stored in the clipboard manager.  
Not even things like the send link from "send items"

### Operating System

macOS

### Operating System Version

15.0.1 (24A348)

### Installation method

Mac App Store

### Build Version

2024.10.0 (31484)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
Hello!  Thank you for your report.

As a security product, our current position is that we should err on the side of over-protecting copied data, regardless of the field from which it has been copied.

We may revisit this in the future if there is a desire to make this configurable or otherwise allow field-by-field behavior definition, but for now we will remain with the current implementation.

Thank you for your report and your use of Bitwarden.  We truly do appreciate this feedback and will keep it in consideration for future enhancements.
