### ISSUE TITLE
Bitwarden's autofill menu blocks site's autofill

### ISSUE THREAD

**Issue by dawnandrew100** [bitwarden/clients#11632]
### Steps To Reproduce

1. Go to checkout of a site
2. Click on the address field
3. Start typing out an address

### Expected Result

A close button for the autofill dropdown to vanish so that I can select an address from the site's drop-down menu

### Actual Result

Bitwarden's dropdown menu persists which blocks the address I wish to select from the site's dropdown menu

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/03af8dac-2582-4229-be82-b4a21a056f5f)

### Additional Context

As can be seen in the screenshot, the first two choices of the site's dropdown menu are obscured by Bitwarden's dropdown menu. This is specifically an issue when a site expects a specific format for an address which can only really be accomplished by clicking an option from the site's autofill options.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed.
