### ISSUE TITLE
Beta Extension: Password Generator Options do not Work as Expected

### ISSUE THREAD

**Issue by windmueller** [bitwarden/clients#11644]
### Steps To Reproduce

1. Open the password generator
2. Observer the defaults: 14 characters, no special characters
3. Enable "special characters"

### Expected Result

A new password is generated containing special characters

### Actual Result

A new password without special characters is generated. After disabling the option again, a new password with(!) special characters is generated.

### Additional Context

Additionally, when clearing the password length field and entering "16" manually, a password with 5 characters is generated.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Brave

### Browser Version

1.71.114

### Build Version

2024.10.999

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hello,

Bitwarden is collecting feedback directly via the following form. We encourage sharing all feedback there, where our Product and Engineering teams will receive it directly.

Browser Client Beta Feedback Form: https://forms.bitwarden.com/to/HsQ8IHOJ 

Please keep in mind that the extension refresh is in beta. If there are behaviors which block regular use of Bitwarden, we recommend sticking with the production version of the browser client while parity is achieved. 

Below is a list of items still being worked on:

Unauthenticated pages (before login)

Legacy UI still in use

Generator: 

Parameters are lost after closing extension

Options not always reflected in auto-generated passwords

Forwarded usernames not available

Vault: 

New buttons are inaccessible via keyboard

Passwords in view login page do not have custom styling

Login item password history uses old UI

Page transitions:

Page transition animations do not slide in from right / slide out to left

We use GitHub issues as a place to track bugs and other development related issues

The issue here will be closed.

Thanks!
