### ISSUE TITLE
Not possible to use 2 accounts on different self-hosted instances?

### ISSUE THREAD

**Issue by MatthiasGrandl** [bitwarden/clients#11706]
### Steps To Reproduce

1. Login to your first self-hosted account
2. Go to `Switch Accounts`
3. Click `Add Account`
4. Have no option to specify another selfhosted endpoint for the second account

### Expected Result

be able to log into 2 different self-hosted accounts

### Actual Result

only able to use 1 self-hosted account

### Screenshots or Videos

<img width="375" alt="image" src="https://github.com/user-attachments/assets/958fdb05-a5b0-46e4-8726-bdc8dc0b74e7">

### Operating System

macOS

### Web Browser

Firefox

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I see that you're running version 2024.6.3. Can you please try updating to the latest version of the browser extension?

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by MatthiasGrandl** [comment]
confirmed it works. I just didn't think of actually trying to click on self-hosted again and changing the endpoint 🤦
