### ISSUE TITLE
Password Generator settings do not persist in Firefox or Chrome after closing the browser and reopening

### ISSUE THREAD

**Issue by auberonlogic** [bitwarden/clients#11726]
### Steps To Reproduce

1. Go to 'https://vault.bitwarden.com/#/login'
2. Login to vault
3. Select 'Tools'
4. Select Password Generator
5. Change the settings password length to 32, minimum numbers to 5, and minimum special to 5
6. Completely close the browser
7. Open the browser
8. repeat steps 1-4

### Expected Result

I expect the length, minimum numbers, and minimum special to remain set at
- length=32
- minimum numbers=5
- and minimum special=5

### Actual Result

Instead, these are the settings:
- length=14
- minimum numbers=1
- minimum special=0

### Additional Context

I have this problem on Firefox on my laptop, and on Firefox and Chrome on my android phone. My phone's bitwarden client successfully persists the password generator settings though.

### Operating System

Linux, Android

### Operating System Version

laptop: 6.11.5-arch1-1 ----- android: 14

### Web Browser

Chrome, Firefox

### Browser Version

laptop: firefox 131.0.3-1 ----- android: firefox 131.0.3    chrome 130.0.6723.73

### Build Version

2024.10.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @auberonlogic,

Thank you for this report. That is the expected behaviour of the Bitwarden Web App at this time; Further improving this is on the radar. As a side note, this [feature request](https://community.bitwarden.com/t/generators-options-history-synced-across-apps-or-default-settings/66758) might be relevant to you.

If you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) with us, and please include a link to this GitHub report if you do.

Because we used GitHub to track bugs and other development related issues, this report will now be closed.

Thank you again,
