### ISSUE TITLE
Bitwarden doesn't lock extension on Windows lock in Firefox

### ISSUE THREAD

**Issue by narbhar** [bitwarden/clients#11722]
### Steps To Reproduce

1. In the Firefox Bitwarden extension, Go to 'Settings'
2. Click on 'Account Security'
3. Under unlock options check 'Unlock with PIN' and set your desired PIN
4. 'Lock with master password on browser restart' is enabled here
5. Restart the browser and unlock extension with master password
6. Lock Windows using Win + L 
7. Unlock Windows and go to Firefox
8. The browser is still unlocked and all the vault items are accessible

### Expected Result

When Unlock with PIN is enabled and 'Lock with master password on browser restart' is checked, the extension is supposed to be locked under PIN on window lock and unlock with the browser running in the background

### Actual Result

When Unlock with PIN is enabled and 'Lock with master password on browser restart' is checked, the extension is supposed to be locked under PIN on window lock and unlock with the browser running in the background, however the extension stays unlocked with all vault items accessible. 

### Additional Context

This behavior doesn't occur on Microsoft Edge Dev Version 131.0.2903.5 running build version 2024.10.1 of the bitwarden extension

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

132.0

### Build Version

2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by narbhar** [comment]
Additional context: I manually updated the browser extension on Firefox to 2024.10.1 and it still persists. The main cause of the issue seems to be the vault timeout under session timeout settings. The Edge extension has Windows Lock on it whereas the Firefox extension doesn't have that option 
![Firefox](https://github.com/user-attachments/assets/21194bfd-7f0c-4a7a-b9fa-f1f01a774251)
![Edge](https://github.com/user-attachments/assets/88d6e1e3-dde4-4a4e-91c4-3b5c9d2b8e22)

**Comment by SergeantConfused** [comment]
Hello @narbhar,

Thank you for this report. More about this topic and why (On system lock) is not a Vault Timeout option in Firefox can be found in the [Bitwarden Community](https://community.bitwarden.com/t/on-system-idle-lock-option/33). In this case, the Firefox extension remains unlocked due to how the browser behaves and due to the fact that (On system lock) is unavailable in the Firefox extension; It's unrelated to the (Unlock with PIN) function. If you have anything you'd like to add to this, please feel free to post that in the Bitwarden Community.

I hope you find this clear and helpful; If you have any questions or concerns, please feel free to get in touch with us via a [support ticket](https://bitwarden.com/help/), and include a link to this GitHub report if you do so. I will now close this GitHub report.

Thank you again,
