### ISSUE TITLE
"Allow screen sharing" option breaks remote access.

### ISSUE THREAD

**Issue by Onred** [bitwarden/clients#11766]
### Steps To Reproduce

1. Run Bitwarden on a client machine
2. Access the machine with RDP or looking-glass-client
3. Make sure "Allow screen sharing" in settings is unchecked (default)

### Expected Result

"Allow screen sharing" should block things like discord, chrome, OBS, etc, but not remote access. If this is technically impossible, turn this into a feature request to either:

1) allow certain services to bypass the hiding behavior. or
2) leave this option checked by default, perhaps with a notification when any screensharing is detected so that we can turn it off if desired, or
3) the same as 2 but opposite: keep it unchecked by default, but give us somewhere to enable it when it's active so that Bitwarden is not completely invisible/unusable on a headless machine.

### Actual Result

Bitwarden in invisible through remote access when the option is checked.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
