### ISSUE TITLE
Fonts and buttons aren't showing on the extension client

### ISSUE THREAD

**Issue by TheSecurityDev** [bitwarden/clients#11810]
### Steps To Reproduce

All you have to do is open the browser extension and try navigate or log into a site

### Expected Result

It should work like before, where the text is visible

### Actual Result

I can't see anything because the text isn't visible

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/c7c0161d-7342-4f4f-8fc8-1d66b3c4f3e2)
![image](https://github.com/user-attachments/assets/26ccb24d-41ba-4c07-a710-dca3412838c2)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

130.0.6723.70

### Build Version

I don't know because I can't see the menu options :(

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. One step you may want to try is uninstalling and reinstalling the extension.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by TheSecurityDev** [comment]
Updating and restarting the browser seems to have worked.
