### ISSUE TITLE
Login Issue in Microsoft Edge Browser Extension: Incorrect Password Error althought Valid Credentials

### ISSUE THREAD

**Issue by KaiZenSpace** [bitwarden/clients#11820]
### Steps To Reproduce

Open Microsoft Edge and go to the browser extension for login.
Enter a valid email address in the login field.
Note: The "Next" button may appear grayed out but is still clickable.
Click on Next and then enter the correct password.
Attempt to sign in.
Expected Result
The extension should allow login with the correct email and password.

### Expected Result

The **"Next" button** should look more clickable to avoid confusion, and the extension should accept the correct password when logging in.

### Actual Result

When trying to log in to the browser extension in Microsoft Edge, I encountered an issue where I couldn’t sign in even though I’m sure my email and password are correct.

First, I enter my email:  
![Email Entry Issue](https://github.com/user-attachments/assets/eeee75b3-84aa-4436-88f0-c82b2feeaaa8)

Next, I enter the password, but the extension says the password is incorrect:  
![Incorrect Password Error](https://github.com/user-attachments/assets/dc7a8f82-adfc-4911-8551-ff498f5f7c47)

I can log into my account dashboard with the same email and password, so I’m confident the credentials are correct.

### Additional Context

The **"Next" button** appears very gray, which makes it look unclickable, although it does actually work. The button itself doesn’t seem to be the issue.

### Operating System

Windows

### Web Browser

Microsoft Edge

### Browser Version

Version 130.0.2849.56

### Build Version

(Offizielles Build) (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

Could you please try reinstalling the Bitwarden app by following the below steps:

 -  Uninstall the Bitwarden client
 -  Restart the device (perform a full power cycle, shutting the device down completely and then restarting it)
 -  Reinstall Bitwarden from the download link below

 Bitwarden Downloads: https://bitwarden.com/download

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
