### ISSUE TITLE
Login Issue in Microsoft Edge Browser Extension: Incorrect Password Error Despite Valid Credentials

### ISSUE THREAD

**Issue by KaiZenSpace** [bitwarden/clients#11821]
### Steps To Reproduce

Open Microsoft Edge and go to the browser extension for login.
Enter a valid email address in the login field.
Note: The "Next" button may appear grayed out but is still clickable.
Click on Next and then enter the correct password.
Attempt to sign in.

### Expected Result

The extension should allow login with the correct email and password.

### Actual Result

The extension shows an "incorrect password" error, even though the credentials are verified and work on the account dashboard. I defenetly using correct credentials!!!

### Screenshots or Videos

First I enter my Email
![image](https://github.com/user-attachments/assets/eeee75b3-84aa-4436-88f0-c82b2feeaaa8)

Next the password, the extension says the password is incorrect:
![image](https://github.com/user-attachments/assets/dc7a8f82-adfc-4911-8551-ff498f5f7c47)

### Additional Context

The login button appears too gray, in my opinion, making it seem unclickable.

I also double-checked the password by comparing what I used to access the dashboard with what I entered in the extension, and they match exactly!

### Operating System

Windows

### Web Browser

Microsoft Edge

### Browser Version

130.0.2849.56 

### Build Version

(Offizielles Build) (64-Bit)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by KaiZenSpace** [comment]
My previous bug report was closed, and I’d prefer not to use the contact form on your website. I believe the login issue still needs attention. Thank you for your understanding.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration. I would encourage that you contact our support team to further look into this.


We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!
