### ISSUE TITLE
Google Chrome - pressing enter / return key after master password does nothing

### ISSUE THREAD

**Issue by plittlefield** [bitwarden/clients#11823]
### Steps To Reproduce

Click on the Bitwarden extension icon or keyboard combination (SHIFT+CTRL+U) to bring up the master password text input box and after typing your password press enter on your keyboard.

### Expected Result

After typing in the vault master password and pressing enter on the keyboard, I should see the vault load in the usual pop-up window.

### Actual Result

The enter key does nothing in Google Chrome but works in the Mozilla Firefox browser extension.

To get around it, you press the 'Unlock' button shown on the pop-up.

### Operating System

Linux

### Operating System Version

Linux Mint 21.3

### Web Browser

Chrome

### Browser Version

130

### Build Version

130.0.6723.91 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
