### ISSUE TITLE
Firefox extension won't remember email every time

### ISSUE THREAD

**Issue by IamBennJ** [bitwarden/clients#11834]
### Steps To Reproduce

1. Go to the firefox extension.
2. Click on "Remember email".
3. Connect.
4. Disconnect.
5. Click on the extension again.
6. See if the email is autofilled and the "Remember email" is checked.
7. If not, try again from step 1.

### Expected Result

When the "Remember email" button is checked on the very first page of the Firefox extension, the email is supposed to be autofilled the next time we try to connect.

I never touched the button so the email should be autofilled every times.

### Actual Result

Sometimes, the email won't be autofilled and the "Remember email" will be unchecked.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/e7681fd7-36e1-470c-a416-d6352c65554a)

When everything is fine, the email is autofilled and the button is checked.

![image](https://github.com/user-attachments/assets/772fc9e4-dd8f-40ad-ba06-7c81b2a4044e)

When the bug appear, the button is unchecked and the email field is empty.

### Additional Context

Sometimes, the email will be autofilled but the "Remember email" button will be unchecked, it means that this button uncheck itself randomly.

### Operating System

Windows

### Operating System Version

22H2 ( build 19045.5073 )

### Web Browser

Firefox

### Browser Version

132.0 (64 bits) 

### Build Version

Bitwarden 2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
