### ISSUE TITLE
DWService username field not filled

### ISSUE THREAD

**Issue by edmundlaugasson** [bitwarden/clients#11921]
### Steps To Reproduce

1. Go to https://www.dwservice.net/
2. Click on Login button
3. Try to fill username field with Bitwarden
4. Unable to fill username field

### Expected Result

username field is filled as usually

### Actual Result

unable to fill username field

### Screenshots or Videos

N/A

### Additional Context

password field can be filled
issue persists already long time, looks like still not fixed, finally reported

### Operating System

Linux

### Operating System Version

EndeavourOS, rolling release

### Web Browser

Brave

### Browser Version

1.71.123

### Build Version

Chromium: 130.0.6723.116, 64-bit

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by jelabarre59** [comment]
I'm presuming this is one of those cases where I'd have to define the custom field name in the saved Bitwarden entry (even though the field says "User" it's probably using some non-standard field name/identifier).  Where is this being tracked?

**Comment by vazquezrodjoel** [comment]
I want to find out what was the solution to this one.  Thanks.
