### ISSUE TITLE
Inline Autofill is not working properly with custom field.

### ISSUE THREAD

**Issue by xcell-jbantel** [bitwarden/clients#11956]
### Steps To Reproduce

1. create an item (username: user, password: test, custom field: loginClient -> bitwarden) ![item](https://github.com/user-attachments/assets/b81f52b6-0886-445b-8831-72a72f8292ce)
2. go to: https://schubertfull.academymaker.de/academymaker/
3. click into password field and select your item ![1](https://github.com/user-attachments/assets/aa75b135-d2d7-45f3-8719-7372781970d2)

### Expected Result

All 3 field should be filled correctly. This is the case if you go via the extension menu:

1. go to: https://schubertfull.academymaker.de/academymaker/
2. select your item via the extension ![3](https://github.com/user-attachments/assets/48b8678b-e1b4-4332-be25-16026a5c7329)
3. everything is filled correctly ![4](https://github.com/user-attachments/assets/0ac6d084-80d8-4984-9450-e7f4c119cbe0)

### Actual Result

Username is not filled correctly
![2](https://github.com/user-attachments/assets/2e0e91c3-c7c1-429f-a76f-594d2dc073f6)

### Additional Context

we are using an additional input field. Please also note, that filling the credential via the extension menu is working fine.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Version 130.0.6723.117 (Official Build) (64-bit)

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
