### ISSUE TITLE
logged out

### ISSUE THREAD

**Issue by woutervanwijk** [bitwarden/clients#11966]
### Steps To Reproduce

Once every one or two months, I'm suddenly logged out. Maybe after an update, or whatever. It happens on Desktop (Macos) and the browser plugins. It's extremely annoying and I'm on the lookout for another password manager that is more reliable.

### Expected Result

stay logged in

### Actual Result

sometimes logged out

### Additional Context

Don't know why it happens. It didn't use to happen before

### Operating System

macOS

### Operating System Version

15.1 now, but 14 before. Same thing

### Installation method

Direct Download (from bitwarden.com)

### Build Version

32149

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please check your Vault timeout and see if it is set to logout or Lock. https://bitwarden.com/help/vault-timeout/#vault-timeout-action

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by woutervanwijk** [comment]
What? You attempted to reproduce the issue in 15 minutes? It's not possible to reproduce due to the nature of it. I wrote "Once every one or two months". You lost a client with this kind of 'service'. I will not pay for Bitwarden anymore.

**Comment by dgrinin** [comment]
I have the same problem.
It is ridiculous how they keep closing issues without even trying to understand them.

**Comment by SergeantConfused** [comment]
Hello @woutervanwijk,

Thank you for following up on this.
1. You mentioned that this happens to the desktop client and the browser extensions on macOS; do you have any Bitwarden clients on that same machine which do not exhibit this behaviour?
2. Do all the Bitwarden clients on that machine log out together at the same time?
3. Do you shut your computer down, or put it to sleep? Do you think that you typically encounter this after waking the machine up from sleep?
4. To what is the (Vault Timeout Action) function set in each client?

Thank you in advance,
