### ISSUE TITLE
Disabling Autofill doesn't get saved in Safari

### ISSUE THREAD

**Issue by vordenken** [bitwarden/clients#12006]
### Steps To Reproduce

1. Go to the browser extension in safari
2. Click on settings -> autofill
4. Select "Disabled"

### Expected Result

autofill should stay disabled even after reboot/restarting safari etc.

### Actual Result

autofill keeps reactivating itself for weeks. It didn't happen one or two times but a dozen times by now. I think I saw that behaviour in firefox too but I mainly use safari so idk.

### Operating System

macOS

### Operating System Version

15.1

### Web Browser

Safari

### Browser Version

18.1

### Build Version

Version: 2024.10.1  Server-Version: 2024.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by vordenken** [comment]
Hello, after bitwarden updated itself the setting got reset to default again. Could you maybe try and replicate it that way?
