### ISSUE TITLE
Can't select less than 6 words for Passphrase in Edge Extension

### ISSUE THREAD

**Issue by DrBazUK** [bitwarden/clients#12015]
### Steps To Reproduce

1. Go to Bitwarden Extension in Edge Browser
2. Click on + to create new password
3. Enter username
4. Click on generate password
5. Choose passphrase as password type
6. Attempt to use less than 6 words - dialog overrides user input to have minimum 6 words

### Expected Result

The user should be able to choose fewer than 6 words as some dialogs prevent excessively long passwords/passphrases

### Actual Result

User is required to choose 6 words minimum and then delete extraneous words before saving passphrase to comply with some websites/applications password length requirements.

### Operating System

Windows

### Operating System Version

11 23H2

### Web Browser

Microsoft Edge

### Browser Version

130.0.2849.80

### Build Version

2024.11.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 

Your issue appears to be describing the **New** intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by dholling1** [comment]
I can see that it's "intended" by reading the documentation, but this is a bad decision.  @darksidemilk is correct in that it makes it fail most password length checks.  Even at 3 I sometimes have to truncate due to antiquated systems.  Please consider reverting this back to 3 and maybe add a warning if this was added due to an excess of security zeal.

**Comment by wperry1** [comment]
I know this is closed but want to throw in my two cents. Most online systems have a maximum password length that 3 to 4 words regularly exceeds. This makes the generator almost useless for generating passphrases.

**Comment by jpligthart** [comment]
Well, it mighht be intended. But when I try 2 it says it should be three at least. And if i make it three it just changes to 6 automatically. Like stated above: I think it is not user friendly, and looks like a bug as it behaves.

**Comment by vultux** [comment]
Please let the user choose what they consider safe.
As others have said here, 6 words is unfeasible for several services.

**Comment by cu-ri-os-i-ty** [comment]
I have the same issue here: only six words to change it. I have the same extension issue. I've tried the website, the same problem, the iPhone app, and the same problem. Please fix

**Comment by Magneticdud** [comment]
When i generate a password now i get "Colossal-Heaviness-Camper-Murky3-Mummified-Upbeat"

That's 54 letters. I don't know any website that allows a password with this length.

Please allow the user to decide if 3 words are enough or not. I don't need another mommy to decide for me which password is appropriate and I definitely don't need a 54 letters password to login in low importance website.

What's the difference between allowing the user to choose a "simple" 22 letters password vs "forcing" a 54 letter password and then the user truncate it later?

**Comment by broodslawns** [comment]
This is pretty absurd for intended behavior. That should be left to the user, especially those paying for the service. It also doesn't make sense as the desktop applicaiton allows for 3 word generations while the CLI and extensions require 6. I use this function pretty heavily and slows my workflow down heavily. Please revert this change.

**Comment by Magneticdud** [comment]
We all need to upvote this feature request to revert this new "security theater" feature

Link is here: https://community.bitwarden.com/t/avoid-arbitrary-length-restrictions-in-generator/75764

Reason explained in the comments: user doesn't like a 60 chars password so he now generates passwords with an **online** password generator. Security completely defeated ☠️☠️☠️☠️

**Comment by ginat** [comment]
Hi all - @audreyality has merged a PR [here](url) that will be reverting the 6-word minimum back to the 3-word minimum. 

This came in via a Hacker1 report, the bug bounty program used by Bitwarden. The wordlist currently being [used](https://github.com/bitwarden/clients/blob/main/libs/common/src/platform/misc/wordlist.ts) by the passphrase generator is sourced from EFF's Long Wordlist and is on the shorter side of 7776 words. EFF's guidance is to use a six-word passphrase with this source list, adding that ideal use-cases for passphrases are when directly used to encrypt information. 

In the Hacker1 report, a 3-word passphrase generated can seem secure due to overall password length but has low entropy, given the smaller source reference word list and the number of combinations possible accordingly. 

We moved forward with a short-term solution, increasing the minimum words in the generator, rather than holding for the longer-term solution of updating the reference word list. This made it more challenging for the much broader number of scenarios where users don't need a long passphrase (if they aren't encrypting items) or websites that have maximum character limits. This is also a limited risk, given the attacker must know that the user prefers Bitwarden passphrases in the applications being accessed. 

In addition to reverting back to a three-word minimum, there is also helper-text included to outline that 6-word minimum is considered the most secure for the passphrase generator as well as similar helper-text in the password generator for a minimum of 14 characters. 

This PR has been completed, merged to production, and pending approvals from the browser extension stores.

**Comment by crankyoldbugger** [comment]
I'm having the same problem with BW in Firefox.  Six words is way too long for my applications.

**Comment by lightmaster** [comment]
If you're on Firefox and don't want to wait however long it takes for the extension to actually be updated in the browsers webstores, you can remove the current version and install 2024.10.1 to get the password generator working again. https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/

I assume Chrome and Edge have previous versions available for download too, but I don't use them so don't know myself.

**Comment by cori** [comment]
> EFF's guidance is to use a six-word passphrase with this source list, adding that ideal use-cases for passphrases are when directly used to encrypt information.

Possibly-notable that this guidance is from ... 2016 - almost a decade ago. One might think that 8 years later they'd suggest even _longer_ passphrases, but NIST's authentication guidance has become _much_ more user-friendly in that time-frame,, especially recently - I'd love to see the EFF update _this_ guidance for the modern web.

**Comment by vinceblake** [comment]
The difference between a 3 word passphrase (with numbers and symbols interspersed) and a 6 word passphrase is next to nothing. The former is not getting brute-forced either. Nothing is achieved by forcing the 6 word minimum from a security perspective. However, the tool is now less usable than it was, because of all the reasons listed above already -- there are legacy systems which will reject passwords of this length and they are ubiquitous. I am now forced to jump through several additional hoops to benefit from the generator. 

This change is bad and should be reverted. If you want to warn me on the screen that I am "not as secure as I could be," I will still be annoyed, but less so. 

I love you Bitwarden, but please revert this.

**Comment by crankyoldbugger** [comment]
I'm getting around this problem by running a six-word password, copying it to a text file, trimming it down to three words, then using the shortened version.  Not a great hack; but it's getting me through this problem for now.

**Comment by Stricken1670** [comment]
workaround for linux users: alias genpasswd='bw generate -pc --includeNumber'

**Comment by ginat** [comment]
An update on rollout: this change has been reverted in versions 2024.11.2 and on. This version is approved in Chrome, Firefox, and Edge and is pending approvals in Opera.
