### ISSUE TITLE
The autofill erroneously suggests logins from other domains (somewhat dangerous)

### ISSUE THREAD

**Issue by trodiz** [bitwarden/clients#12018]
### Steps To Reproduce

Go to Pinterest. Try logging in via OAuth (google). You don't have to finish the login process - simply switch back to the login page on Pinterest and look at the autofill suggestions - your google credentials will be there.

### Expected Result

Autofill should only suggest login credentials from the same domain.

### Actual Result

Google credentials shows up alongside Pinterest ones.

### Screenshots or Videos

![pinterest_bitwarden_extension](https://github.com/user-attachments/assets/8c5959ca-6691-4712-a6c2-746bed96caf4)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Microsoft Edge

### Browser Version

130

### Build Version

2024.11.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Bitwarden allows users to configure domains as global equivalents, which means that credentials saved for one domain can appear as options for other related domains. This feature is intended to streamline the login process for services that share authentication across multiple domains, such as Google services. If Pinterest and Google are somehow linked in your domain rules or if there is a misconfiguration, this could cause Google credentials to appear when logging into Pinterest.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, we'd be happy to look into your domain configurations with you, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
