### ISSUE TITLE
I cannot log in to the Bitwarden app from the App Store

### ISSUE THREAD

**Issue by xuemio73** [bitwarden/clients#12028]
### Steps To Reproduce

After installing the app, when I enter my email address and password and press the login button, it keeps loading and I cannot log in.

### Expected Result

I cannot update macOS from Big Sur, so I cannot install the latest version from the App Store

### Actual Result

I can log in if I install the DMG from GitHub, but I cannot use the Safari extension feature. This is by design

### Operating System

macOS

### Operating System Version

BigSur11.5.2

### Installation method

Mac App Store

### Build Version

31511

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin Currently, our desktop app which includes the Safari Browser extension has support for macOS 12+ (Monterey) and Safari 15+. Apple setting the End-of-life (EOL) for Big Sur in 2023, and even longer ago for older versions of macOS, so we are no longer able to maintain reverse compatibility.

You can refer to the following article from Apple on what computers support what version of macOS: https://support.apple.com/en-us/HT211683

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
