### ISSUE TITLE
(Feature request) advanced full-text searches for android app/clients?

### ISSUE THREAD

**Issue by valtoree** [bitwarden/clients#12026]
Hi as per above title.
Currently I have to login via web browser on my phone if I want to search the notes section of all my entries, which is a huge pain in the arse to login that way.
Is there any chance this feature could be implemented?
Well done on an amazing app and keep up all the great work dev/s! ❤️

**Comment by NovaSilentium** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
