### ISSUE TITLE
Firefox extension stopped working with Mac's biometrics: endless `“Bitwarden” would like to access data from other apps`

### ISSUE THREAD

**Issue by pmalek** [bitwarden/clients#12063]
### Steps To Reproduce

1. Click on Firefox Bitwarden extension
2. Click on "Settings" -> "Account Security" -> "Unlock with biometrics"
3. See `“Bitwarden” would like to access data from other apps.`
4. Click on "Allow"
5. Nothing happens

### Expected Result

Biometrics unlocking is enabled.

### Actual Result

Nothing happens.

### Operating System

macOS

### Operating System Version

15.0.1 (24A348)

### Web Browser

Firefox

### Browser Version

133.0 (aarch64)

### Build Version

Firefox extension 2024.10.1, Mac os desktop app 2024.11.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please ensure that you have enabled unlock with biometrics in desktop before proceeding. https://bitwarden.com/help/biometrics/#tab-browser-extension-2vCWb5iFg4OqKS0B2xXpqW
We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by pmalek** [comment]
I didn't have the Touch ID enabled in desktop app but even after enabling it

<img width="446" alt="image" src="https://github.com/user-attachments/assets/1fe29249-c0e3-41f3-99a3-a8d538aefd8b">


the issue persists. I have to note that Touch ID on the desktop app works without any problems.
