### ISSUE TITLE
Biometric Login Not Working in Chrome Extension only

### ISSUE THREAD

**Issue by FoldZero** [bitwarden/clients#12064]
### Steps To Reproduce

1. open Chrome Browser
2. Click bitwarden icon
3. Click "unlock with Biometrics"

### Expected Result

Allows fingerprint\hello login

### Actual Result
![image](https://github.com/user-attachments/assets/be31e978-b3af-4137-b010-bfb8d2c02be9)

unable to login through chrome with fingerprint (Windows Hello)

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/be31e978-b3af-4137-b010-bfb8d2c02be9)

BW Version
![image](https://github.com/user-attachments/assets/10049a2b-5cb5-4074-91ee-89a6e3d02cdb)

### Additional Context

This process will work, but only if I open Bitwarden Desktop and login through any means. 
Just means to avoid using master password i have to sign in 2x, desktop then chrome extension

### Operating System

Windows

### Operating System Version

Win 10 

### Web Browser

Chrome

### Browser Version

131.0.6778.71

### Build Version

2024.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. You will need to enable unlock with biometrics in desktop before proceeding and the Bitwarden desktop app must be logged in and running in order to use unlock with biometrics for a browser extension. https://bitwarden.com/help/biometrics/#tab-browser-extension-2vCWb5iFg4OqKS0B2xXpqW

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
