### ISSUE TITLE
Generator passphrase number of words stuck

### ISSUE THREAD

**Issue by buddentist** [bitwarden/clients#12096]
### Steps To Reproduce

1. Go to 'Generator'
2. Select 'Password' radio button
3. Click on 'Options'
4. Select 'Passphrase' radio button
5. Try to decrease the number of words, either by typing or by clicking increment button

### Expected Result

Number of words should decrease from 6 

### Actual Result

Number of words doesn't decrease, stays on 6. Increasing the number works, though.

### Operating System

macOS

### Operating System Version

Sonoma 14.7.1 

### Installation method

Mac App Store

### Build Version

2024.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please consider signing up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked. I have found a discussion regarding this here(https://community.bitwarden.com/t/has-bitwarden-lost-all-in-house-expertise-on-entropy-password-strength/75719/18)

This issue will now be closed. 

Thanks!

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/12015
