### ISSUE TITLE
BitWarden badge does not appear for Email field on personalcapital.com

### ISSUE THREAD

**Issue by daniel-dara** [bitwarden/clients#12103]
### Steps To Reproduce

1. Save a username and password with the URI `home.personalcapital.com`.
2. Navigate to https://home.personalcapital.com/page/login/goHome
3. Click on the input field with the label "Email" (html name of "username") to give it the focus.

### Expected Result

Bug 1:
The input should show the BitWarden icon so credentials can be selected.

Bug 2:
The input should populate when selecting the credentials manually through the BitWarden icon in the browser's menu bar. 

Bug 3:
After manually entering an email address and clicking "Next", the BitWarden icon will appear when giving the "Password" field focus. The BitWarden list contains the entry created in step 1.

### Actual Result

Bug 1:
The input does not show the BitWarden icon when focused.

Bug 2:
The input does not populate when selecting credentials manually through the BitWarden icon, nor through the right-click context menu.

Bug 3:
The BitWarden list shows "No items to show".

### Additional Context

Bug 2 can be worked around by creating a linked field for "Username" to "username", which seems like it shouldn't be necessary based on the names being nearly the same.

Bug 3 can be worked around by manually selecting the credentials in the extension from the menu bar. The list is appropriately filtered by the domain.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Firefox

### Browser Version

132.0.2

### Build Version

2024.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by daniel-dara** [comment]
@cbbit Bumping this just to ask a quick question. Is there a way to search existing autofill issues in order to track their progress and avoid submitting duplicates?
