### ISSUE TITLE
Unlock box appears without password fields in focus

### ISSUE THREAD

**Issue by nofishonfriday** [bitwarden/clients#12102]
### Steps To Reproduce

1. Go to https://forum.cockos.com/index.php
2. Scroll around (without being locked in)

### Expected Result

Nothing. :)

### Actual Result

The unlock box appears from time to time.

### Screenshots or Videos

![Unlock](https://github.com/user-attachments/assets/1b4083ab-2f98-4080-86f4-2b2e932560b6)

### Operating System

Windows

### Operating System Version

10 Pro

### Web Browser

Firefox

### Browser Version

Waterfox 6.5.1

### Build Version

2024.110

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello,

Thank you for bringing this matter to our attention. 

Due to the specific requirements of addressing autofill issues, we manage them through distinct tracking forms based on the application:
For browser extension reports, please use: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

Completing the relevant form will greatly assist us in resolving the problem efficiently.

**Comment by nofishonfriday** [comment]
Thanks for the reply.
I looked at the form you linked but I'm not sure it fits my case  as auto-fill *does* work on that side.
It's not an auto-fill issue I have (maybe re-read my report above again in case) so I'm not sure how I should fill that form.
For example, question: 
> Which Bitwarden auto-fill method did you use? 

Answer (related to the issue here) would be 'none' but that's not a possible answer.
Please advise how I should proceed.
