### ISSUE TITLE
[Vivaldi, Autofill] Extension icon shows available credentials but inline says "nothing to show"

### ISSUE THREAD

**Issue by rapus95** [bitwarden/clients#12193]
### Steps To Reproduce

1) Open any page, in my case it was patreon (but the same issue occured on other pages)
2) focus a password or username field
3) inline pop up appears, says "nothing to show" but at the same time the extension icon shows available data.

### Expected Result

The inline autofill shows the same data as the extension icon

### Actual Result

The inline autofill claims no available credentials

### Screenshots or Videos

In top right corner the extension shows a 1 for an available login dataset.
![image](https://github.com/user-attachments/assets/ba08205d-19d7-45c3-a660-d8ade007aaa2)

### Additional Context

Might be related to https://github.com/bitwarden/clients/issues/9369 ? But since that was marked as fixed and closed I decided to create a new issue.

### Operating System

Windows

### Operating System Version

Windows 11 Version 24H2 (Build 26100.2454)

### Web Browser

Vivaldi

### Browser Version

7.0.3495.6 (Stable channel) (64-bit) 

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JSS3M3** [comment]
Confirming that I’m seeing the same behavior in Chrome on Windows.

**Comment by pamperer562580892423** [comment]
I guess I'm seeing the same thing as @rapus95 describes (and which seems similar to https://github.com/bitwarden/clients/issues/12194).

Example: the Bitwarden Community Forum.
If I open the site first (Brave, Version 1.73.91)- and then unlock the Bitwarden browser extension (2024.11.2), I see the "1" in the extension icon immediately, but the inline menu doesn't show the logins. - If I refresh the page, then the inline menu could show the logins. (I wrote "could" because rarely one refresh of the page is enough, sometimes it seems I have to refresh, navigate on the page a bit, and refresh again, until the inline menu logins appear on the login page.

(this is on Windows 11, 24H2, everything up-to-date; and Bitwarden "cloud-default")

**Comment by pamperer562580892423** [comment]
I just recorded it. At first, you can see the extension is locked. The longer loading time after PIN unlock is due to my Argon2-KDF. (PS: I shortened the clip here a bit afterwards)

After the unlocking of the extension, I tried to click in the fields a few times, but the inline menu doesn't show up.

Then I refreshed the page once. And as you can see, the inline menu appears now.

At the end, I didn't login to the Community Forum, but that part is no problem - when the logins are there in the inline menu, the login works then.


https://github.com/user-attachments/assets/a46f52ef-69c2-4ee9-9bb6-8bd9f4558120

EDIT: In retrospect, my video indeed shows a different issue than this one here as it doesn't show the "No items to show" message (but a complete absence of the inline autofill menu).

**Comment by PegHorse** [comment]
https://github.com/bitwarden/clients/issues/12194#issue-2707761944

**Comment by rapus95** [comment]
For me, it was exactly the same as for @PegHorse (continuously showing the little 1 on the icon, but not showing any credentials to select on the inline menu) but different than for @pamperer562580892423 (which showed a different bug IMO). But today I couldn't reproduce it myself. So I guess it might be a weird interaction between program states. I'll still keep it open as others are facing the same problem, hoping, we'll find the reason.

**Comment by pszalanski** [comment]
Same here: I can fill using the extension icon, without any issues. But the autofill menu in login forms shows "no entry".

**Comment by idanoo** [comment]
I'm also seeing this on Bitwarden extension 2025.3.2 - Firefox 137.0.2 - Mac 15.4.1.
![Image](https://github.com/user-attachments/assets/b88d6f41-f237-4c3e-aed1-a98900d37554)


I have my vault set to not lock, so I force locked the vault and unlocked it with the master password now it seems to work.. Not sure if that helps anyone else.

**Comment by marc-cwm** [comment]
I've been dealing with this issue since around early December as well.

I use Vivaldi, and for me, autofill will usually populate items for a short period of time after the browser is restarted and if I make sure to fully close out the browser (it can take more than closing the window) and restart it, this seems to also temporarily restore functionality.  This may just be chance, sometimes it seems to just work even if the browser has been sitting open for days.

As with the others, filling with the extension icon continues to work fine and the extension icon still seems to recognize when it has items to fill (the '1' shows up on the icon).  Mine presents similarly to peghorse where I do get the bitwarden popup but it always says 'No Items to Show'.

**Comment by idkjustgoogleit** [comment]
+1

Dealing with same issue on android and win11 with vivaldi browser.

**Comment by seaartic** [comment]
+1
The same behavior is happening here with Vivaldi. I'm hoping for a quick fix.

**Comment by jaykyll** [comment]
+1
same issue (vivaldi browser too).
When disable extension and re-enable, works again

**Comment by cfree789** [comment]
+1

MacOS 15.5
Firefox Developer Edition 141.0b4 (aarch64)
Bitwarden Desktop Version 2025.5.1 (43022)
Bitwarden Firefox Extension 2025.5.0

Disabled and re-enabling the extension does allow autofill (via CMD+SHIFT+L) to work temporarily.  After that, manually have to open the extension window and click "Fill" under "Autofill suggestions".



7/7/25 UPDATE:

Bitwarden Firefox Extension 2025.6.1 seems to have corrected this?
My Desktop client has also updated to 2025.6.1.

**Comment by seaartic** [comment]
Still the same Problem. Even with the new Version.

Vivaldi: 7.5.3735.41
Bitwarden: 2025.6.1
Windows 10 x64

**Comment by zR-JB** [comment]
Same Problem on Linux:

Fedora: 42
cosmic-comp:  7a52eff
Bitwarden Version: 2025.5.0
Firefox: 140.0.2

**Comment by cfree789** [comment]
> Same Problem on Linux:
> 
> Fedora: 42 cosmic-comp: 7a52eff Bitwarden Version: 2025.5.0 Firefox: 140.0.2

See if updating to 2025.6.1 is fixing this for you as well.

**Comment by zR-JB** [comment]
>  See if updating to 2025.6.1 is fixing this for you as well.

have not noticed it since, might have fixed it!

**Comment by seaartic** [comment]
Vivaldi: 7.5.3735.47
Bitwarden: 2025.6.1

It continues to appear.

**Comment by idkjustgoogleit** [comment]
Same here, very random. The plugin recognized the site, but no autofill most of the times...

-------- Original Message --------

**Comment by jwmann** [comment]
Exactly the same issue for me as well.

```
Bitwarden Extension Version: 2025.6.1
Vivaldi: 7.5.3735.54 (Stable channel) (arm64)
OS: macOS Sequoia 15.5 (24F74)
```

#### -- UPDATE --

My Bitwarden is set to lock on browser restart, so I quit Vivaldi and unlocked/re-logged into my Bitwarden and the suggestions show up from the input field now.

Might help for someone else 👍

**Comment by seaartic** [comment]
Still the same behavior with 2025.7.0
Vivaldi: 7.5.3735.56
Windows 10 x64

**Comment by justauserid** [comment]
It's the same in Firefox. It has been this way for too long. 

OS: Mac Sequoia: 15.6 (24G84)
Firefox: 142.0 (aarch64)
Bitwarden ext: 2025.7.1
BitWarden desktop: 2025.8.0 (46219)

Sharing these details here anyway (as if someone is looking at it!). It feels like a feature now!

**Comment by yype** [comment]
This happened to my Chrome extension as well. Uninstalling and reinstalling the extension fixed the issue. However, it only worked for a couple of hours before the issue came back.

Chrome Version 139.0.7258.155. Extension version 2025.8.2.

**Comment by alankchan** [comment]
Same on Arc browser (Chrome-based).

OS: macOS Sequoia 15.7
Browser: Arc browser 1.114.1 (Chromium 140.0.7339.214)
Bitwarden extension: 2025.9.0
Bitwarden desktop: 2025.9.0

<img width="896" height="666" alt="Image" src="https://github.com/user-attachments/assets/94e70ff6-e127-4af8-9723-b58062c35a75" />

**Comment by njbyler1** [comment]
We are nearing a year since this problem was originally reported. On my part, I've been dealing with it for at least that long. Generally it happens at least once a day and sometimes multiple times per day. Restarting the browser, disabling/enabling the extension, and forcing the service worker to restart all have the effect of _temporarily_ fixing it.

@SergeantConfused Would you be so kind as to give this issue a bump? I realize you might have trouble reproducing it yourself, but I would be happy to provide console logs, service worker details, and any other documentation or logging info you ask for. I represent a company with 20+ members on a paid subscription. We depend on Bitwarden heavily. Thanks in advance!

Linux Mint 22.2
Vivaldi 7.6.3797.63
Bitwarden extension 2025.10.0

**Comment by husjon** [comment]
I'm also seeing this, however I did not see this until I just recently enabled suspend / hibernation on my workstation, before this I had no issues with it.
It does not seem to happen instantly after wake-up but rather some times after (~1-2 hours). Logging out, disabling/re-enabling the plugin, restarting the browser all works as temporary fixes.

I do not see from the issues listed above if users are on laptop (where suspend is more common) or not.
I should also note that I do however see it on my laptop too every now and then, I just haven't used it a lot lately.


NixOS 25.11 (Xantusia)
Vivaldi 7.6.3797.63 (Stable channel) stable (64-bit) 
Bitwarden Version: 2025.10.0

**Comment by jacobgkau** [comment]
@husjon I don't think enabling suspend on your system has anything to do with this. It's happening on my desktop that I never suspend.

**Comment by marc-cwm** [comment]
My experience matches njbyler1, I don't typically utilize suspend on my system.  This issue just seems to be generally time sensitive.  It will work for while after a restart, but then will just stop working mysteriously.

**Comment by spiral6** [comment]
Still happening on my end. 
Vivaldi 7.6.3797.63 (Stable channel) (64-bit) 
Extension Bitwarden 2025.10.0

**Comment by Perkolator** [comment]
First time seeing this. Don't know if related but started right after I updated to 2025.11.1. Vivaldi 7.7.3851.52 (linux).

Also, don't know if related, but using some login page fields started to show a separate "Update existing login" popup from Bitwarden. For example using my Synology NAS device (local network) login/pw fields (the update popup shows a scrollable list of ALL my login items for my NAS device for some reason). The local network address to the NAS is still the same as it has been for years, so it can't be that. Autofill match detection is the same as it has been: Default (base domain).

Closing the update popup, not updating the items, might have something to do with this problem?

**Comment by pamperer562580892423** [comment]
> Also, don't know if related, but using some login page fields started to show a separate "Update existing login" popup from Bitwarden. For example using my Synology NAS device (local network) login/pw fields (the update popup shows a scrollable list of ALL my login items for my NAS device for some reason). The local network address to the NAS is still the same as it has been for years, so it can't be that.

Those "Update existing login" and also "Save (new) login" popups are a recent issue that probably started with extension version 2025.11.0 - here the corresponding GitHub issue to it: https://github.com/bitwarden/clients/issues/17405

Maybe those issues are also somehow connected - but this "nothing to show" issue is much older than the current "update popups" issue...

**Comment by dwiprawira** [comment]
This has also happened to me using the Orion Browser. I use Firefox extensions as recommended by the Orion browser. Has also tried the Chrome version and is facing the same issue.

Using Bitwarden Version: 2025.6.1
SDK: main (1fa0f7a)
Server version: 2025.12.1

<img width="1553" height="933" alt="Image" src="https://github.com/user-attachments/assets/931676b5-c739-49e6-aadc-9f5aee3f933a" />

**Comment by pamperer562580892423** [comment]
@dwiprawira:

> Using Bitwarden Version: 2025.6.1

Though it probably doesn't help with this issue here, but you should consider enabling automatic updates for the browser extension... (current extension version is 2025.12.0)

**Comment by EnricoBara** [comment]
+1 of this issue. I'm also unable to save login credentials for new accounts

**Comment by pamperer562580892423** [comment]
@EnricoBara:

> I'm also unable to save login credentials for new accounts

This is a completely different and separate issue, that should be investigated on it's own.

**Comment by vitobotta** [comment]
This problem still persists. Has anyone found a solution?

**Comment by teknolai** [comment]
+1 to this issue

I also encounter this issue daily, in both my browsers, Vivaldi and Arc.

**Comment by timovos** [comment]
+1

On MacOS, with Vivaldi 7.8.3925.62 and Bitwarden extension 2026.1.0. Dropdown stays empty, while clicking on the icon shows a login entry. Using "Fill in" there, that works.

**Comment by karaktaka** [comment]
+1

Can confirm that this happens on MacOS with Vivaldi. If I restart the browser the Dropdown works for a while but eventually will stay empty.

**Comment by davidhund** [comment]
+1 issue persists with Extension version `2025.12.1` on Vivaldi

```
Version: 7.8.3925.62 (Official Build) (arm64)
Chromium Version: 144.0.7559.167
Channel: Official Build
Platform / OS: macOS Version 15.7.3 (Build 24G419)
Executable Path: /Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Command Line:  /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=CanvasTextNg|WebAssemblyCustomDescriptors --disable-smooth-scrolling
```

**Comment by Wikunia** [comment]
Have the same issue. Command + Shift + L works 
Is there any progress on this as this exists for over a year?

**Comment by PixelyIon** [comment]
+1 on `Zen 1.19.8b (Firefox 149.0.2) (Windows aarch64)`. I have an x64 Windows desktop running Zen where this issue doesn't exist, so it's really odd.

**Comment by AndreKelling** [comment]
same here since yesterday

MacOS 15.7.7
Chrome Version 148.0.7778.179 (Official Build) (arm64)

**BitWarden Extension**
Version: 2026.4.1
SDK: 'main (aaccd8d)'
Server version: 2026.6.0

**edit**: now gine that issue.
changed has the extension version

**BitWarden Extension**
Version: 2026.5.1
SDK: 'main (e13c4fc)'
Server version: 2026.6.0

**Comment by Ironheart777** [comment]
I've been dealing with this issue non-stop for the last few months on vivaldi on windows and on my iphone. Selfhosted Vaultwarden backend with Bitwarden pointed at it on both devices. The bitwarden plugin will show 1 and when I click on it, it'll recognize the site (lets say dominos.com) and ctrl+shift+L will autofill it correctly but clicking the inline autofill button says no credentials found. I installed the plugin on MS Edge and it worked without issue. If there's anything I can do to help this along please let me know.

**Comment by Nordlicht-13** [comment]
Same here, Bitwarden has Auto-Fill-Suggestions in the extention, but in the fields on the page it shows the entry to save a new entry.
Problem under Windows 11 64 bit, using Vivaldi 8.0.4033.57 (Chomium 148.0.7778.289)

**Comment by HottYGithub** [comment]
Same issue with me. 

Version: 8.1.4087.58 (Official Build) (arm64)
Chromium Version: 150.0.7871.208
Channel: Official Build
Platform / OS: macOS Version 26.5.1 (Build 25F80)

**Comment by seaartic** [comment]
Since the last two versions of the Bitwarden browser extension, it has been appearing more and more frequently again.
The same thing happens with 2FA codes as well.

Sometimes, nothing appears at all. I click somewhere on the page to make the inline menu disappear, and then click in the login field—at which point the saved login appears in the inline menu.

It might be great if Bitwarden’s entire autofill feature were redesigned.

Vivaldi 8.1 Build 4087.61 (Chromium 150.0.7871.214)
Browser v2026.7.0
Windows 11 x64

**Comment by njbyler1** [comment]
I'll echo the comment from @seaartic. For me this problem had almost completely vanished for several months earlier this year, then it suddenly returned a few weeks ago (I don't have an exact timeline). 

Based on the progress [here](https://github.com/bitwarden/clients/pull/18681), I think the developers will eventually get the issue resolved, though I do wonder at times why it takes this long. We're coming up on two years since the issue was reported (Nov. 2024). 

**Vivaldi Info**
Version: 8.1.4087.68 (Official Build) (64-bit)
Chromium Version: 150.0.7871.252
Channel: Official Build
Platform / OS: Linux - linuxmint 22.3

**Bitwarden Info**
Version: 2026.7.0
SDK: 'main (3e060f8)'
Server version: 2026.8.0

**Comment by pamperer562580892423** [comment]
I'm not exactly sure if this was mentioned before, but this other issue seems related: https://github.com/bitwarden/clients/issues/15001 (and maybe some cases of "No items to show" that were reported here might be connected to that other issue?!)

**Comment by alankchan** [comment]
> I'll echo the comment from [@seaartic](https://github.com/seaartic). For me this problem had almost completely vanished for several months earlier this year, then it suddenly returned a few weeks ago (I don't have an exact timeline).
> 
> Based on the progress [here](https://github.com/bitwarden/clients/pull/18681), I think the developers will eventually get the issue resolved, though I do wonder at times why it takes this long. We're coming up on two years since the issue was reported (Nov. 2024).
> 
> **Vivaldi Info** Version: 8.1.4087.68 (Official Build) (64-bit) Chromium Version: 150.0.7871.252 Channel: Official Build Platform / OS: Linux - linuxmint 22.3
> 
> **Bitwarden Info** Version: 2026.7.0 SDK: 'main (3e060f8)' Server version: 2026.8.0

@ njbyler1 To answer your pondering, part of it may be that no one has been assigned to this bug or the related pull request that has write access. Thus, it's a staffing issue:

> ## 1. It is a Niche Platform Issue (Low Priority)
> The bug is specifically isolated to the Vivaldi web browser. While Vivaldi is a great power-user browser, its market share is exceptionally small compared to Google Chrome, Apple Safari, or Microsoft Edge.
> 
> * The Staffing Reality: Bitwarden's engineers must prioritize bugs affecting millions of Chrome and Edge users before dedicating engineering hours to browser-specific edge cases like Vivaldi.
> 
> ## 2. A Core Workaround Already Exists
> The issue description notes that while the inline (on-page) autofill menu says "nothing to show," the extension icon in the toolbar still correctly identifies and shows the credential.
> 
> * The Staffing Reality: Because a user can still easily log in by simply clicking the extension icon in their toolbar, this bug does not completely "break" the app. In triage terms, it is labeled a minor UI inconvenience rather than a critical failure.
> 
> ## 3. Chromium Layer Complexity
> Vivaldi is built on top of Chromium (the same underlying engine as Chrome), but it heavily modifies the user interface and how web panels interact.
> 
> * The Staffing Reality: The Bitwarden extension icon code is working perfectly (it shows the "1" for an available login). The failure happens when Bitwarden tries to inject the inline menu directly into Vivaldi's custom-rendered page layers. Fixing this requires an engineer who deeply understands Chromium compatibility layers, making it a complex task for a general developer to solve quickly.
> 
> ## 4. "Regression" and Tracking Hurdles
> The user who filed the bug mentions it might be related to a previous bug (#9369) that Bitwarden engineers already fixed and closed once before. When a bug returns (called a regression), engineers cannot just rush a patch. They have to carefully study why their previous fix broke, ensuring that a new fix won't accidentally break autofill for Chrome or Brave users.
> Furthermore, as the issue explicitly notes, "Bitwarden tracks work outside of GitHub". Just because no one is "assigned" to it on GitHub doesn't mean a paid developer isn't looking at it in their private internal database.
> To help deal with this in the meantime, would you like to know the keyboard shortcuts to bypass the inline menu, or should we look at how to adjust Vivaldi's internal settings to see if it fixes the conflict?

**Comment by TheJulianJES** [comment]
My issue was (IMO incorrectly) closed as a duplicate of this one:
- https://github.com/bitwarden/clients/issues/22420

That issue is about "No items to show" and "Fill generated password" randomly popping up on **non-Vivaldi** browsers. It was likely closed because these issue's comments here are a mix of both that one and the (original) Vivaldi-specific one.
But they are two separate issues and should really be tracked separately IMO.

For anyone curious, there are relatively consistent reproduction steps in the issue description there (as well as a video).
The non-Vivaldi-specific issue is a race condition that happens most often when an email/username or password field is already focused when loading the page, which can be perfectly reproduced by refreshing https://vault.bitwarden.com/#/login a bunch, as that focuses the username/password field by default when reloading the page.

With some help of an LLM, I've had that issue **fully fixed (confirmed working)**: https://github.com/bitwarden/clients/compare/main...TheJulianJES:clients:tjj/fix-inline-menu-cipher-race. More information about that can be found [in this comment](https://github.com/bitwarden/clients/issues/22420#issuecomment-5288640281).

---

I've also thrown it at the Vivaldi-specific issue (about which the original report here is about) but as I don't use that browser, I haven't tested that. There's more information about that Vivaldi issue (and a possible branch to try) in the [last comment of that issue](https://github.com/bitwarden/clients/issues/22420#issuecomment-5289068860) I linked above. If anyone wants to test that possible (untested) Vivaldi fix, feedback is appreciated.

I'm open to creating a PR for the first (confirmed working fix) for non-Vivaldi browsers and possibly also for the Vivaldi bug when that patch is confirmed working (or when I get around to reproducing that bug and trying the possible fix myself), but if a Bitwarden engineer wants to drop in and say if the fix(es) is/are at least going in an acceptable direction, that would be appreciated.

**Comment by lukaaas176** [comment]
I can confirm that this is still happening on Firefox with Bitwarden 2026.8.0.

The inline menu says `No items to show`, while the extension popup correctly shows the matching login. `Ctrl+Shift+L` also fills the credentials correctly, so URI matching and autofill itself are still working.

I tried to isolate the broken state:

1. Reloading the affected login page does not restore the inline suggestions.
2. No error appears in the Bitwarden background console while reproducing it.
3. Locking and unlocking the Bitwarden vault, followed by reloading the page, restores the inline suggestions.

I have not yet found what initially triggers the broken state. Since reloading the page does not help, but locking and unlocking the vault does, this seems like something goes stale.

Environment:

- macOS 26.6.2 (25G83), arm64
- Firefox 155.0
- Bitwarden extension 2026.8.0
- Firefox password saving and login autofill disabled

So this is not limited to Vivaldi and is still reproducible with a current Firefox and Bitwarden version. Please let me know if there is any other state or debug information I can collect.

**Comment by francescocam** [comment]
I can reproduce this on macOS 26.6.2 (25G83), Vivaldi 8.2.4133.47, Bitwarden extension 2026.7.0.
Inline suggestions work initially, then stop during normal use. The inline menu displays “No items to show,” while the extension popup and context menu still identify matching logins.
Toggling inline suggestions, opening a fresh window, and switching away and refocusing the field did not resolve it. Disabling/re-enabling the extension and unlocking restores suggestions temporarily, but the failure returns.
While the failure was present, the extension’s service-worker console contained:
Uncaught Error: No tab with id: 915829626.
Source: rxjs/.../reportUnhandledError.js:10.
I cannot yet establish whether this error causes the failure. The same problem does not occur on my Kubuntu workstation using Vivaldi.
What additional diagnostics would help identify the cause?
