### ISSUE TITLE
Password is shown on autofill

### ISSUE THREAD

**Issue by ocean211** [bitwarden/clients#12191]
### Steps To Reproduce

1. Go to https://contorendimax.bancaifis.it/home-banking-ng/public/login/?abi=03205&codiceProdotto=default&lang=it&codiceservizio=null&scadenza=null&task=null
2. Create a login (user numeric and pwd casual)
3. autofill

### Expected Result

Pwd not shown

### Actual Result

The pwd is shown

### Operating System

Windows

### Operating System Version

11 Pro 23H2

### Web Browser

Firefox

### Browser Version

133.0

### Build Version

2024.11.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. 

When filling in the password field for the site you provided, it will temporarily show the character that has been input into the field. In the case of the Bitwarden browser extension, the entire value of the password is submitted at once and not one character at a time. For this to change, the site form field will need to process the values entered differently.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
