### ISSUE TITLE
Windows Security not focused/on top

### ISSUE THREAD

**Issue by bilogic** [bitwarden/clients#12214]
### Steps To Reproduce

1. I use biometric to unlock BW
2. When trying to unlock using the keyboard shortcut `ctrl + shift + L`, the windows security often does not get focused or surface to the top

### Expected Result

The Windows Security window should always be top most

### Actual Result

The Windows Security window is often not focused/on top

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Build Version

Version: 2024.11.2  Server version (Third-party): 2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in needing the setting "Ask for biometrics on launch" to be enabled. With this setting enabled the Windows Security window was always in focus during the tests on my own system.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by bilogic** [comment]
I have `Ask for biometrics on launch` enabled.

**Comment by bilogic** [comment]
@rmcdowell-bitwarden can you fully terminate your chrome before testing it again? It is not focused on first launch.
