### ISSUE TITLE
Password not autofilling correctly on instagram.com in browser and in android app 

### ISSUE THREAD

**Issue by helium9171** [bitwarden/clients#12280]
### Steps To Reproduce

In firefox (linux):
1. Go to instagram.com
2. Let bitwarden autofill login information
3. Attempt to sign in

In android app:
1. Open app
2. Let bitwarden autofill login information
3. Attempt to sign in

### Expected Result

The password that I have saved works.

### Actual Result

The password is for some reason not correctly being input from bitwarden into the password field in both the app and on the website (firefox). It inputs a password that looks like mine, but it is wrong.

### Additional Context

I can bypass the issues by copying the password in the bitwarden app, and then pasting it into the password box, successfully signing in. So the wrong password hasn't been saved, it just won't autofill into the password field properly.

### Operating System

Linux, Android

### Web Browser

Firefox

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
