### ISSUE TITLE
Suddenly can't unlock/login bitwarden extension

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [bitwarden/clients#12290]
### Steps To Reproduce

1. Go to 'locked/logged out bitwarden extension'
2. Click on 'bitwarden icon' to unlock/login
3. enter correct password

### Expected Result

Bitwarden unlock (if in locked state)
Bitwarden pop up for 2fa authentication(if in logged out state)

### Actual Result

Bitwarden small window closes and stay in locked state/logged out state(grey icon)
If inputting incorrect password, bitwarden reports "credential incorrect" information.

### Additional Context

On a new brave browser profile bitwarden extension works fine.
Firefox addon on the same machine also works fine.
The problem occurred suddenly when the bitwarden extension was in locked state (logged in but locked).

### Operating System

Linux

### Operating System Version

Debian 12

### Web Browser

Brave

### Build Version

Version 1.73.97 Chromium: 131.0.6778.108 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
