### ISSUE TITLE
Accessing selector only contains one "self hosed" url

### ISSUE THREAD

**Issue by johanvandyck** [bitwarden/clients#12316]
### Steps To Reproduce

1) open desktop app.
2) login account1
2a) type email address1
2b) choose self hosted and verify url1 or type url1, save
3) login.
4) on the upper right corner, choose "add account"
5a) type email address2
5b) choose self hosted. you will notice only url1 is saved from the previous login. Your need to type url2. I'm not able to add a "self hosted url2 line". Save.
6) login second account.

### Expected Result

In the desktop (or browser extension) you can login with up to 5 logins. However, it is not possible to save more than one selfhosed url. the dropdown box only contains "bitwarden.com, bitwarden.eu and selfhosted". It is not possible to add a self hosted bis link.

### Actual Result

Only the last used url in self hosted drop down box is kept.

### Screenshots or Videos

![afbeelding](https://github.com/user-attachments/assets/f8a9d83b-b005-4878-8b2d-e9b1b27e57ce)

### Additional Context

I posted the issue on the community: [https://community.bitwarden.com/t/can-i-have-2-self-hosted-url-in-the-desktop-gui/76451]
A senior member suggested to create a bug report.

Why I need 2 self hosted logins? I use bitwarden at home. However my work is picking it up. -> 2 self hosted environments.

### Operating System

Windows

### Operating System Version

win11 24H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. In the Bitwarden desktop app, you can log in to multiple accounts, including up to five accounts simultaneously. However, there is a limitation when it comes to saving multiple self-hosted URLs. The dropdown menu for server selection only includes 'bitwarden.com', 'bitwarden.eu', and a single 'self-hosted' option. This means that while you can switch between multiple accounts, you cannot save more than one self-hosted URL at a time. Each time you switch accounts, you need to manually enter the URL for the self-hosted server if it differs from the one previously used**. If you want this to be changed, it would be a feature request.** 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
