### ISSUE TITLE
Missing delete button on any item in the shared vault

### ISSUE THREAD

**Issue by JasmeowTheCat** [bitwarden/clients#12415]
### Steps To Reproduce

1. Open any item inside a collection with rights to edit.
2. Missing delete buttons, only allowing edits, save and cancel.

### Expected Result

Allow deletion of items into trash. This works on the browser version of BitWarden vault.

### Actual Result

No button is visible or exists for deletion.

### Screenshots or Videos

![qHhVeE 1](https://github.com/user-attachments/assets/10a396c0-3059-475e-8b38-431b6d783491)
![image](https://github.com/user-attachments/assets/917e4a93-2474-4003-91a2-0b0c4ae95e35)

### Operating System

Windows

### Operating System Version

Version 22H2 (OS Build 19045.5011)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version: 2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

As @bwbug mentioned, your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
