### ISSUE TITLE
[Linux] ARM64 Builds

### ISSUE THREAD

**Issue by denysvitali** [bitwarden/clients#12420]
### Steps To Reproduce

N/A

### Expected Result

N/A

### Actual Result

N/A

### Additional Context

It looks like there aren't ARM64 builds available for Linux.  
As more and more ARM64 linux devices are popping up, it would be very appreciated to have ARM64 builds (AppImage / deb)

### Operating System

Linux

### Web Browser

N/A

### Build Version

N/A

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/t/arm-support/8306

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by denysvitali** [comment]
Why was this closed?

**Comment by denysvitali** [comment]
GitHub now supports ARM64 builders:
https://github.com/orgs/community/discussions/148648

Is there any blocker preventing this from happening?
