### ISSUE TITLE
Inline-autofill menu causes iframe to disappear

### ISSUE THREAD

**Issue by jasdevbhogal** [bitwarden/clients#12441]
### Steps To Reproduce

1. Make sure die inline-autofill menu is enabled
2. Go to https://salenti.de/c/fef9354ae3f8bf91e4acc3a3a19540ec/demo
3. Click on any Product
4. Scroll down a bit and wait for the autofill menu to appear

### Expected Result

The autofill menu shows up

### Actual Result

The iframe looses its state and dissapears

### Screenshots or Videos

https://github.com/user-attachments/assets/bf437e41-6cf1-45d2-9fa9-3ea6b65bd3ab

### Additional Context

The issue only occurs when the inline-autofill feature is enabled and the page containing the form is inside an iframe, like in the example above. Opening the page containing the form outside of the iframe context seems to work fine.

### Operating System

Windows, Linux

### Operating System Version

Windows 11 22H2, Ubuntu 24.04

### Web Browser

Chrome, Firefox

### Build Version

2024.12.2 (and a few older ones)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
