### ISSUE TITLE
[App store installation] Can't enable browser integration (Chrome)

### ISSUE THREAD

**Issue by mattegoghero** [bitwarden/clients#12457]
### Steps To Reproduce

1. Install Bitwarden from App Store
2. Login into bitwarden app and enabled biometrics
3. Got to preferences and try to enable browser integration

### Expected Result

The app should be able to activate the browser integration

### Actual Result

The app fails to activate the browser integration

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/ee830bc1-58b1-461a-943d-d1c9d248e0a3)

### Additional Context

I've tried uninstalling and reinstalling the app multiple times, even the browser extension, but nothing seems to help.

### Operating System

macOS

### Operating System Version

15.1

### Installation method

Mac App Store

### Build Version

2024.12.1 (34750)

**Comment by opswiz** [comment]
Same issue here, happens always since sequoia I guess. It just stopped working. Firefox/chrome/everything. As stated in the issue, it simply can't be enabled in the first place to get the extensions work.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. We use GitHub issues as a place to track bugs and other development related issues. Please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
