### ISSUE TITLE
[New-Extension] Having 1 copy button for both username & password is a huge UX downgrade

### ISSUE THREAD

**Issue by shinebayar-g** [bitwarden/clients#12486]
### Steps To Reproduce

1. Open a browser
2. Click on Bitwarden Extension
3. Click on Copy button
4. Click on Copy username
5. Click on Copy button
6. Click on Copy password

### Expected Result

1. Open a browser
2. Click on Bitwarden Extension
3. Click on Copy username button
4. Click on Copy password button

### Actual Result

How is it even possible to adding more useless step is considered an "improvement"? I can bear the ugliest design ever created, but I cannot handle this external clicks just to get my username & password copied.

Extension has one job. Copy & Paste. Not clicking more buttons and navigations.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/8a6b175e-7a8d-4275-baf9-54f6d512a7dd)

### Operating System

Linux

### Web Browser

Chrome

### Build Version

Version 131.0.6778.204 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there, 

You can toggle the quick copy buttons by navigating to the extension's Settings tab > Appearance > Show quick copy actions on Vault. 

We use GitHub issues as a place to track bugs and other development-related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by shinebayar-g** [comment]
Hiding it behind a toggle? Great feature! Thanks. :clap:
