### ISSUE TITLE
Biometric unlock in Edge broken on both Windows and Mac

### ISSUE THREAD

**Issue by chromadesign** [bitwarden/clients#12497]
### Steps To Reproduce

1. Enabled "Allow browser extension" in Desktop App
2. Activated "Unlock with biometrics" in Edge and allowed file URLs.
3. Edge asked for permission which I granted. Vault immediately locks.
4. Unlocked vault again and tried activating biometrics again. Error message saying "Browser integration is not set up" pops up.

### Expected Result

Being able to enable "Unlock with biometrics" in Edge browser extension.

### Actual Result

Error message "Browser integration is not set up"

### Screenshots or Videos

![app](https://github.com/user-attachments/assets/93b64829-a475-46ff-9d56-9e5fbd8d2e75)
![extension](https://github.com/user-attachments/assets/f601eed1-9095-4d42-9873-9e2936fd1ced)

### Additional Context

Several reboots, deinstallations etc. already done. Same behavior on four different devices and on both Windows and Mac. Chrome, Brave and Firefox work fine.

### Operating System

Windows, macOS

### Operating System Version

Windows 11, macOS 15.2

### Web Browser

Microsoft Edge

### Browser Version

131.0.2903.99

### Build Version

2024.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
