### ISSUE TITLE
Autofill not autofilling password only username

### ISSUE THREAD

**Issue by luanfernandes** [bitwarden/clients#12506]
### Steps To Reproduce

When both selecting "fill" in the extension or using the shortcut, my autofill is only working with the username. I don't remember exactly which sites I tested it with but 100% sure it's not working in wordpress.

I use firefox with bitwarden as well, version 2024.11.2 and it works fine there.

### Expected Result

Both password and username autofill

### Actual Result

Only username autofilling

### Operating System

Windows

### Web Browser

Chrome, Opera

### Build Version

2024.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
