### ISSUE TITLE
Unlocking with biometrics should not require multiple clicks around the screen

### ISSUE THREAD

**Issue by mwisnicki** [bitwarden/clients#12523]
### Steps To Reproduce

1. Lock vault and go to website where you have saved password
2. Click password input
3. Click "Unlock account" in the dropdown
4. Move your mouse halfway across the screen to bitwarden extension popup
5. Click "Unlock with biometrics"
6. See yet another prompt and finally use touch fingerprint reader

### Expected Result

Steps 4-5 should at least be optional. Bitwarden should jump straight to fingerprint unlock.

Also step 3 could be eliminated if bitwarden injected overlay icon into password prompt that jumps straight to unlock on click.

Even better would be autounlock/autofill for selected websites but that's a separate issue.

### Actual Result

Too many clicks required.
This is especially annoying if your workplace enforces pretty short vault timeout.

### Operating System

Windows, macOS

### Web Browser

Chrome

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. When "Ask for biometrics on launch" is enabled in the Bitwarden extension, clicking on the password field redirects to the unlock screen, where the biometric prompt automatically appears for a fingerprint scan.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Yundin** [comment]
I thought “Ask for biometrics on launch” meant that I have to unlock Bitwarden on browser launch. Maybe there is something you can do about the wording.
