### ISSUE TITLE
Unsaved changes - no warning message

### ISSUE THREAD

**Issue by pamperer562580892423** [bitwarden/clients#12556]
### Steps To Reproduce

1. Go to e.g. "view card" (any given "card")
2. Click on edit.
3. Make any change in the item.
4. Click on "back".

### Expected Result

There should be a warning message about unsaved changes ("save" v. "discard" or something like that).

### Actual Result

I can go back and all changes made are gone without any warning message and therefore a possibility, to save the changes.

### Screenshots or Videos

https://github.com/user-attachments/assets/17b56e29-a68b-4603-b939-0d157634edc9

### Additional Context

Additional comment from me: I guess I'm not the first person remarking that. Maybe it is more seen as a specific "feature request"?! But I would see that more as a "bug" that needs no "feature request", as to get a warning for unsaved changes is totally ubiquitous and common design. Especially with the new UI/UX changes, this should be part of a good User Experience, to be warned about unsaved changes instead of just disregarding them without any notice.

### Operating System

Windows

### Operating System Version

11 (24H2)

### Web Browser

Brave

### Browser Version

Version 1.73.104 Chromium: 131.0.6778.204 (Offizieller Build) (64-Bit)

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
