### ISSUE TITLE
Folder of Item should be shown in Search results

### ISSUE THREAD

**Issue by vorburger** [bitwarden/clients#12560]
### Steps To Reproduce

1. Create 2 items with the same name (e.g. **Test Item**), but keep one in _No Folder_ and another in a Folder named **Test**
1. Type the _Name_ of that _Item_ into the _Search_ box
1. The Search results show 2 **Test Item** entries - but you cannot tell which of them is in what Folder... 😿 

### Expected Result

The Search results should e.g. show:

* **Test Item**
* **Test / Test Item**

### Actual Result

The Search results shows:

* **Test Item**
* **Test Item**

### Operating System

Linux

### Web Browser

Brave

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: 
https://community.bitwarden.com/t/extend-search-to-folders-and-collections-and-vaults/46535

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
