### ISSUE TITLE
Browser extension code is minimized

### ISSUE THREAD

**Issue by benmccann** [bitwarden/clients#12574]
### Steps To Reproduce

Right-click and "Inspect popup"

### Expected Result

Don't minimize the source code. It is much easier to debug when not minimized. The source code is open source anyway, so nothing is being hidden. It also makes the download smaller as it would make source maps easier to distribute

https://webpack.js.org/configuration/optimization/#optimizationminimize

### Actual Result

The source code is minimized

### Operating System

Linux

### Web Browser

Chrome

### Build Version

2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
