### ISSUE TITLE
Need a warning whenimpossible to save (because Bitwarden is locked)

### ISSUE THREAD

**Issue by avikla** [bitwarden/clients#12581]
### Steps To Reproduce

When the message: do you want to save appears in the browser, if Bitwarden is locked by PIN or Master password - there is no message to the user, but it is impossible to save the new login. Please make a warning to appear and clarify the need to unlock before saving.

### Expected Result

Warning to appear and clarify the need to unlock before saving.

### Actual Result

No reaction

### Operating System

Windows

### Web Browser

Brave

### Browser Version

Latest

### Build Version

2024.11.9991

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @avikla,

Thank you for reporting this. The extension would show a window asking for the master password in order to be unlocked in that case, and it'd save the credentials after it's unlocked; I tested this with extension 2024.12.3 in Brave and this worked as expected. Going by the version number of the extension you're using, I suspect you're still using the preview release; please remove it and install the Bitwarden browser extension from the Chrome Web Store, as that may assist.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track potential bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
