### ISSUE TITLE
Firefox Plugin Windows Biometric Authentication Failing

### ISSUE THREAD

**Issue by knightsqr** [bitwarden/clients#12591]
### Steps To Reproduce

1. Log in to Windows
2. Make sure the Windows App is running and logged in.
3. Open Firefox
4. Click on Bitwarden Extension icon.
5. When Biometric log-in prompt opens, use the fingerprint sensor to log in
6. Click Bitwarden Icon again only to see log-in failed.
7. Repeat Steps 5-6 only to get same result

### Expected Result

Vault unlocks.

### Actual Result

Vault failed to unlock

### Operating System

Windows

### Operating System Version

Windows 11 Pro

### Web Browser

Firefox

### Browser Version

133.0.3 (64-bit)

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Tipoff4317** [comment]
@knightsqr 

Are you running 24H2?  

There seem to be also non-FF specific biometric/keyboard problems reported, maybe related to 24H2.
* https://github.com/bitwarden/clients/issues/12171
* https://github.com/bitwarden/clients/issues/12177

**Comment by knightsqr** [comment]
Yes, the Preview Release Build (Windows 11 Build 26100.2448 to the Release Preview Channel), but I am not having any issues with other applications. Works to log in to Windows. Works for Bitwarden under the latest Chrome. I thought many of those issues were Intel chipset-specific, as I am running an AMD machine.

**Comment by daniellbw** [comment]
Hi @knightsqr ,

I attempted to reproduce your issue and was unable to do so. 

Could you make sure that you unlock your laptop using Windows hello( https://bitwarden.com/help/biometrics/#tab-browser-extension-2vCWb5iFg4OqKS0B2xXpqW)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
