### ISSUE TITLE
website logos are different sizes

### ISSUE THREAD

**Issue by hugo9655** [bitwarden/clients#12601]
### Steps To Reproduce

1. Open Bitwarden browser extension
2. Notice that icon sizes are inconsistent.

### Expected Result

All logos should be the same size.

### Actual Result

They are differing sizes.

### Additional Context

This happened after the new UI update. Before the update, they were all the same size. Only happens to some vault items, and ones with a placeholder icon.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration. I am able to see all my login logos and they are all of the same size.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by pamperer562580892423** [comment]
@daniellbw Sorry, isn't it rather a duplicate of https://github.com/bitwarden/clients/issues/12511 ?

**Comment by pamperer562580892423** [comment]
@hugo9655 I have no say here - and only saw that by chance - but as your "issue" seems to be a "duplicate" and would have been closed anyway, the best for you would be, to add your info to https://github.com/bitwarden/clients/issues/12511

**Comment by daniellbw** [comment]
Hi @pamperer562580892423  and @hugo9655 ,

My apologies, as I was misled by the initial title and did not have varying sizes for logos and there were no subsequent screenshots.

I will mark this as a duplicate of https://github.com/bitwarden/clients/issues/12511 and close this.

Thank you for the follow up!
