### ISSUE TITLE
Back button when pop up mode is open in a item view doesn't work in the new UI

### ISSUE THREAD

**Issue by aleochoam** [bitwarden/clients#12618]
### Steps To Reproduce

1. Open the bitwarden extention
2. Click on any vault item
3. Click on the "pop up in a new window"
4. In the new window, click on the back button
5. Nothing happens

### Expected Result

When I click on the back button on the popped up window, it should go to the "all items" view

### Actual Result

When I click on the back button on the popped up window, nothing happens

### Operating System

Windows

### Operating System Version

Microsoft Windows 10 Enterprise, Version 10.0.19045 Build 19045

### Web Browser

Firefox

### Browser Version

133.0.3 (64-bit)

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please reinstall the extension, removing any leftover [data](https://bitwarden.com/help/data-storage/) and try again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

The issue here will be closed.
