### ISSUE TITLE
disallow screenshot like on android/ios

### ISSUE THREAD

**Issue by finch71** [bitwarden/clients#12612]
### Steps To Reproduce

disallow screenshot like on android/ios

### Expected Result

disallow screenshot like on android/ios

### Actual Result

on windows bitwarden can be screen-shoted

### Additional Context

https://github.com/pedrolcl/rust-forbidden-screenshot

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.12.1 

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @finch71,

Thank you for this report. This seems to be closer to an improvement suggestion or a feature request, than a report about a certain function not operating as expected; with that in mind, please feel free to submit this idea in the [Feature Requests](https://community.bitwarden.com/c/feature-requests/5/none) section of the Bitwarden Community Forums.

You can sign up on the Bitwarden Community Forums and search for this idea, just in case a similar request already exists. If you find one, you can vote for it and contribute to any discussions about it; if not, you can submit this idea as a new request there so that it can be properly tracked.

Because we used GitHub to track bugs and other development related issues, this report will now be closed. Please note that the “Closed as not planned” status is for internal tracking purposes only; please do not hesitate to submit your suggestion to in the Community Forums.

Thank you again,
