### ISSUE TITLE
Firefox on Ubuntu 22.04 do not respect Vault Timeout

### ISSUE THREAD

**Issue by ildella** [bitwarden/clients#2525]
### Steps To Reproduce

In settings, select Vault Timeout "never" and accept. 

### Expected Result

The vault never ask for the password again. 

### Actual Result

Vault ask for password for password at browser restart

### Additional Context

Ubuntu 22.04 by default installs Firefox as a snap and not as apt as it always has. 

This probably has more restrictive permissions to access computer resources like the file system. This has been creating problems for other extensions in my experience so maybe we have a similar situation here. 

### Operating System

Linux

### Operating System Version

22.04

### Web Browser

Firefox

### Browser Version

99

### Build Version

1.58.0

**Comment by ifernandezdiaz** [comment]
Hi @ildella, we couldn't replicate this issue on our latest version. Could you please confirm if the issue you reported is stills being replicable on your side? Thanks in advance!

**Comment by aj-bw** [comment]
Hi @ildella !

Following up on @ifernandezdiaz's note above, I also did some additional testing across multiple versions and could not reproduce this in the snap or apt installs of Firefox.

If you need further assistance, we ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content, the issue here will be closed.
