### ISSUE TITLE
"Always on top" can be defaulted to off anymore

### ISSUE THREAD

**Issue by petevieira** [bitwarden/clients#2559]
### Steps To Reproduce

1. Click the **Window** menu and click **Always on Top** to turn it off.
2. Quit Bitwarden
3. Reopen Bitwarden
4. Click the **Window** menu and **Always on Top** should now be back on

### Expected Result

If **Always on Top** is unchecked, and I quit and reopen Bitwarden, it should still be unchecked.
Or there should be an option in Preferences where isn't default setting on application startup can be selected.

### Actual Result

**Always on Top** is rechecked upon reopening the app.

### Operating System

macOS

### Operating System Version

Monterey 12.3.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0 (2645)

**Comment by aj-bw** [comment]
Hi @petevieira!

Thank you for getting in touch and bringing this to our attention! So far, I am unable to reproduce this on MacOS 12.3.1 and version 1.33.0 of the desktop app. However, we would like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
