### ISSUE TITLE
New version category loading to much time.

### ISSUE THREAD

**Issue by jzh20042003** [bitwarden/clients#2560]
### Steps To Reproduce

1. Open bitwarden
2. 2min pass,but the category is still "loading"
3. This should be a bug
4. 4 minutes pass,the caregory finish loading.
5. I am using win7 e3 1230v3

### Expected Result

1.When I open bitwarden and finish,all thing should be finish loading as soon as possible.Like previous version.
2.category should not loading for 3+ minutes.
3.When I searching ,if there are no result,bitwarden should say "no result" But not "loading" "searching" for a long time.

### Actual Result

1.category loading for 3+ minutes in the newest version.
2.before 3+ minutes loading finish,when I searching and no result,it tell me "loading"/"searching"(I forget which notice word)

### Additional Context

I am using win7 e3 1230v3
Old versions don't have this problem.But bitwarden always auto upgrade it self.
版本 1.33.0
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

### Operating System

Windows

### Operating System Version

win7

### Installation method

Direct Download (from bitwarden.com)

### Build Version

版本 1.33.0 Shell 16.1.0 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by aj-bw** [comment]
hi @jzh20042003!
Thank you for getting in touch and bringing this to our attention! I did some testing and so far cannot reproduce the issue you are describing. However, we would like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
