### ISSUE TITLE
An encrypted copy of the vault remains on the disk after the app gets closed.

### ISSUE THREAD

**Issue by thericle** [bitwarden/clients#2568]
### Steps To Reproduce

1. Close the app from the 'x' button.

### Expected Result

The "data.json" file that keeps all the encrypted data should shrink and all the data of the vault should be deleted.

### Actual Result

The "data.json" file remains on the disk unchanged.

### Additional Context

My vault timeout settings are "log out on system lock". When I lock my windows account, all the vault data are removed from the "data.json" file. The same thing happens when I log out from within the app. But when I just close the app, the "data.json" file stays as it is.

I doubt this is how it's supposed to work because when I re-open the app, it asks me to authenticate again as if I have logged out. What's the point of authentication if I already have the vault on my PC?

If it's not a bug, I think it's a design mistake. The vault should not remain on the PC when the app gets closed if the vault timeout setting is "log out".

### Operating System

Windows

### Operating System Version

Windows 10 Home 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.32.1

**Comment by addisonbeck** [comment]
Thanks for the report!

This is expected behavior for the system lock timeout. To achieve the effect you are looking for, I would recommend using the "Logout On Restart" timeout behavior and automating Bitwarden to close on lock using your operating system. This will log you out whenever you application instance is closed, clear vault data from `data.json`, and do so when you lock you system.

I'm going to close this, but please reach out of you have any questions 😁
