### ISSUE TITLE
Search doesn't works

### ISSUE THREAD

**Issue by aitorserra** [bitwarden/clients#2580]
### Steps To Reproduce

1. Open the app in Windows 10
2. Search any text

### Expected Result

Show the text

### Actual Result

It doesn't do anything. 

### Additional Context

It was working correctly in previous verions.

### Operating System

Windows

### Operating System Version

10, all updated yesterday

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.31.3 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1 Architecture x64

**Comment by mrlinuxfish** [comment]
I'm having similar issues with the Firefox extension. I can search one time and it gives irrelevant results and then when I search again I get no results

I've had to resort to opening the web vault or navigating to a webpage with uri detection to find passwords for desktop applications

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. This issue may have been fixed in a previous update. If your issue still persists at this time, please first log in to https://vault.bitwarden.com to make sure you know your login credentials, and if you are able to successfully log in, then please try uninstalling/reinstalling the application that is having the issue to see if that helps.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
