### ISSUE TITLE
Help Menu Search disappeared with recent update

### ISSUE THREAD

**Issue by mcint** [bitwarden/clients#2582]
### Steps To Reproduce

1. With application open and focus, open the Help menu from the system menu bar.
Search is no longer present

### Expected Result

I used cmd-? (cmd-shift-/) to leverage the Help menu Search function to do in-app tasks, but as of the most recent update that is no longer possible.

### Actual Result

System menus cannot be searched

### Screenshots or Videos

Previously present search box (example from another application from Apple's docs), 
![](https://user-images.githubusercontent.com/601708/153972168-352b03d4-71f2-4dd9-98c1-6d54aff2b303.png)

In latest version, 
![](https://user-images.githubusercontent.com/601708/154390828-2eaf14d8-1a04-4280-abf2-69b4c03cc729.png)

### Operating System

macOS

### Installation method

Homebrew

### Build Version

Version 1.31.2 (2303)

**Comment by MarsCandyBars** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software at this time. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
