### ISSUE TITLE
Feature request: disable GPU render accelerate please.

### ISSUE THREAD

**Issue by ghost** [bitwarden/clients#2615]
For my pc/laptop, the GPU not well drived. so i have problem with bitwarden desktop client.
There need be an option to disable GPU render accelerated.

By the way , If enable GPU render accelerate. the Client will take more memory consumed.

**Comment by evelez7** [comment]
I will be looking into this.

**Comment by cnmade** [comment]
glad to know

**Comment by njmulsqb** [comment]
Is this issue about disabling hardware acceleration or providing a feature to enable/disable hardware acceleration?
I can see some commits on this issue, how much work is done and whats left now?

**Comment by evelez7** [comment]
> Is this issue about disabling hardware acceleration or providing a feature to enable/disable hardware acceleration?
> 
> I can see some commits on this issue, how much work is done and whats left now?

I have an open PR #2896 that I'm waiting on being processed/reviewed. It adds a checkbox in the settings to make hardware acceleration optional.

**Comment by dbosompem** [comment]
Hi @evelez7 , thank you for opening a PR for this issue. This will be reviewed internally(will follow up), and we will get back to you soon.

**Comment by prithvi2k2** [comment]
Seems like this issue has become stale... Can I try working on this issue? or kindly let me know if this issue has been resolved already. I'm a beginner and never contributed anything meaningful to open-source, also the fact that this issue has been labelled "good first issue" attracts me - I'd love to contribute to Bitwarden as a regular user of it.

**Comment by djsmith85** [comment]
@prithvi2k2 Thank you for your interest in contributing. The issue is still open as far as I can see. 

Best place to start is going through [Bitwarden's contribution guidelines](https://contributing.bitwarden.com/). It will provide guidance but also instructions on how to set up your development environment.

Once you have that set up, you'll probably want to check out the [previous work](https://github.com/bitwarden/clients/pull/2896) by @evelez7 and review comments by @Hinton to see how this is best implemented.

Kind regards,
Daniel

**Comment by prithvi2k2** [comment]
Thanks @djsmith85 for providing clarity. 
I'm on it!

**Comment by prithvi2k2** [comment]
Opened a PR #5968 which adds a toggle for hardware acceleration on the Desktop client
