### ISSUE TITLE
While the extension is locked, generated a new password using shortcuts in the Bitwarden Google Chrome extension causes the new password to not be logged to history

### ISSUE THREAD

**Issue by Jayto1** [bitwarden/clients#2640]
### Steps To Reproduce

1. Open a new chrome tab
2. Press Ctrl + Shift + 9 while the Bitwarden extension is locked
3. Unlock and open your Bitwarden Google Chrome extension
4. Click on "Generator"
5. Scroll down and click on "Password History"

### Expected Result

The new password that is copied to your clipboard will not appear in "Password History"

### Actual Result

The password that is copied to my clipboard while the extension is locked does not appear in "Password History"

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

101.0.4951.54 

### Build Version

1.58.0

**Comment by jlf0dev** [comment]
Hi @Jayto1, thanks for the report! This is actually expected behavior with our browser extension, we can't access the vault to alter the password generator history while it is locked. One way around this would be to make sure the extension is unlocked before generating your password.

I'm going to close for now, but feel free to let me know if you have any other questions.
