### ISSUE TITLE
If you click away from the browser popup for any reason before saving a regenerated password it discards it

### ISSUE THREAD

**Issue by Gooberpatrol66** [bitwarden/clients#2686]
### Steps To Reproduce

1. regenerate password for account
2. click outside the popup
3. open the popup again
4. the edit menu is gone and the new password is gone

### Expected Result

The popup is where I left off in the edit menu

### Actual Result

The edit menu and password are gone

### Additional Context

I am locked out of an account now because bitwarden threw away my new password.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

99.0.1

**Comment by aj-bw** [comment]
Hi @Gooberpatrol66!

Thank you for reaching out. Currently, it is expected behavior for the extension to close when clicking outside of the popup. There is a "pop out" icon in the top left of the extension that pops it out into a small tab that persists when focus is moved to other tabs, applications, etc.

If you need any additional assistance, please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
