### ISSUE TITLE
Can't clone org items on the browser extension

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#2704]
### Steps To Reproduce

1. Go to the vault
2. Open a shared item
3. Clone menu is missing. 

### Expected Result

Able to clone org items

### Actual Result

There is no method to clone org items using the browser extension

### Operating System

Windows

### Web Browser

Chrome

### Build Version

1.58.0

**Comment by aj-bw** [comment]
Hi @sso-bitwarden,

after checking internally and reviewing our documentation, this is expected behavior for now. https://bitwarden.com/help/managing-items/#clone

The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
