### ISSUE TITLE
password generator history will log password that not press copy button

### ISSUE THREAD

**Issue by imtipi** [bitwarden/clients#2715]
### Steps To Reproduce

1. Go to 'password generator'
2. change some parameters like length,alphebets...
3. Scroll down to 'password history'
4. Click on it and enter

### Expected Result

only show the password that clicked copy button in previous version

### Actual Result

it start logging password that not click copy button.makes the history tabs a piece of mess

### Operating System

Windows

### Operating System Version

windows10

### Web Browser

Chrome

### Browser Version

101.0.4951.67

### Build Version

1.58.0

**Comment by vphan916** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
