### ISSUE TITLE
Brave Browser Extension Fails to Present Captcha

### ISSUE THREAD

**Issue by matthewelmer** [bitwarden/clients#2716]
### Steps To Reproduce

1. Add the extension
2. Click on the extension
3. Click "Log In"
4. Enter valid e-mail and password
5. ta-da! The extension adds a captcha-sized box, but does not populate it with a captcha. It does not seem to matter whether I have shields on or off, or javascript execution on or off.

### Expected Result

I expected to see a captcha, complete the captcha, and be logged into bitwarden through the extension.

### Actual Result

No captcha was presented.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/26128847/169747903-44c4f1ae-c6dc-4e7d-b630-1928d5547498.png)

![image](https://user-images.githubusercontent.com/26128847/169748007-cd47e2b5-ef00-435f-a768-4f4bac29c1f6.png)

### Operating System

Windows

### Operating System Version

10 build 19044.1645

### Web Browser

Brave

### Browser Version

1.38.117

### Build Version

won't let me cause I can't log in.

**Comment by matthewelmer** [comment]
Update: turning this setting off, on, off, signing into the extension, and back on again served as a workaround:
![image](https://user-images.githubusercontent.com/26128847/169752675-3d592652-fdf4-41df-9a45-70d40b0d57f6.png)

**Comment by djsmith85** [comment]
@matthewelmer This is expected behavior if scripts are blocked. The captcha only appears on new logins and the disabling of the setting let the captcha load once, you validated yourself and then the captcha is not shown again, as you are logged in. 

Bitwarden has received similar reports where users used other extensions like uBlock origin and not whitelisted hcaptcha.

Closing this now.
