### ISSUE TITLE
Bitwarden CLI potentially reveals vulnerability in sudo

### ISSUE THREAD

**Issue by kzhang2** [bitwarden/clients#2727]
## Describe the Bug

If I pipe the results of `echo $(bw get ...)` into `sudo ...` then for some reason `sudo` is unable to hide the keystrokes in the terminal

## Steps To Reproduce

Run `echo "$(bw get password asdf)" | sudo su` and mash the keyboard for a bit. 

## Expected Result
When the keyboard is mashed, the resulting characters do not show in the terminal. 

## Actual Result
When the keyboard is mashed, the resulting characters are shown in the terminal. 

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/12497065/164571323-b4d51fb3-0c0b-4603-a979-8dfcf0f1258f.png)

## Environment

- Operating system: Artix linux, kernel version 5.17.3
- Shell: zsh 5.8.1 (I've also verified that this issue occurs on bash)
- Build Version (run `bw --version`): 1.22.0

## Additional Context

I'm not sure this is the best place to submit the issue, but after a cursory skim of the Bitwarden source I was unsure of what code is actually triggering the vulnerability. Perhaps when we figure out what's going on here we can open this issue in the right place (like maybe the sudo bugzilla?).

**Comment by joshtrichards** [comment]
I dug into this a bit.

I'm not clear on the issue here. The password *isn't* revealed (unless you're typing it manually when you happen to see the prompt show up - which makes no sense to me since you're literally trying to pipe the password non-interactively from bw).

Unless you're saying that the `3298...` is your password *and* that you didn't type it manually? That would be unexpected.

I was a little perplexed when you said @jgelens suggestion (https://github.com/bitwarden/clients/issues/2727#issuecomment-1137336449) didn't fix the issue. Until I realized you maybe tried his suggestion then found you could mash the keyboard and still see output?

Sure. But so what? You're not going to *really* type your password there at that prompt are you? After all, if your pipe is working correctly then your password is also being provided automatically. 

Besides... the prompt (for your password) itself is a cosmetic side effect of not redirecting your stderr (more on that below - including how to get rid of it). It's not a real prompt for your password since you're providing it via stdin via bw/the pipe.

sudo will **not** accept the password from stdin by default. That's what the `-S` parameter is for. Without it, if you try to pipe your password to it you're going to get weird behavior that is almost certainly not what you want.

It looks like you:

1. Ran `sudo` without the `-S` parameter
2. Tried to pipe your sudo password from bw to sudo
3. `sudo` properly ignored your password provided via the pipe because it wasn't told to pull it from stdin
4. You tried to type when you saw the prompt and, yeah, your characters showed up

The same thing happens if you echo anything to sudo without running it the right way:

```
echo blah | sudo id
[sudo] password for jrichard:
sfljfkjslf
sdlkfjsf
Sorry, try again.
[sudo] password for jrichard:
```

The "blah" (or, in your case, the stdout from running `bw` to pull in your password) never shows up in the output - just whatever you happen to type after.

Same if using `bw` to get the password:

```
echo "$(bw get password XXXX)" | sudo su
[sudo] password for jrichard: sfsf

sdf
```

bw isn't doing anything unusual here.

If you run sudo with the correct parameter you'll get something closer to the behavior you're probably expecting:

```
echo "$(bw get password XXXX)" | sudo -k -S id
[sudo] password for jrichard: uid=0(root) gid=0(root) groups=0(root)
```

And if you don't want to see the prompt for the password (which gets sent to stderr when using `-S`):

```
echo "$(bw get password XXXX)" | sudo -k -S id 2> /dev/null
uid=0(root) gid=0(root) groups=0(root)
```

If you truly think it's an issue with sudo, bring it up on the `sudo-users` email list or report it:
https://github.com/sudo-project/sudo/issues/

I appreciate the sensitivity and concern - since sudo is an important security tool - but this seems more a self-created issue than an actual bug in sudo. The solution is simple and entirely in your control: Don't do that. :-)

Disclaimer: I am *not* affiliated with BW in any way - just a happy user (and long-time *nix sysadmin).

**Comment by kzhang2** [comment]
My intention was not to get the sudo password from bitwarden, rather to pipe the password from bitwarden into the command that is being run with sudo.

**Comment by quexten** [comment]
Hi, thank you for the question and everyone who participated in helping answer this.
This is not a bug in the CLI, the CLI correctly just outputs over stdout and anything past that is not under the CLI's control. I also do not think this is a vulnerability in sudo.

If you want to pass a password stored in the cli into a privileged program, you could do:
`bw get password MYPASSWORD | sudo su`. In this case su would receive the password over stdin and try to run whatever is stored as the password as a command. On the fedora implementation of sudo, this does not reveal the sudo password, if you have to type it in. If it does on your system, this might be a bug in the sudo implementation you have installed.

Since both programs, sudo, and bitwarden cli need the stdin in this case for password unlock (if the cli is not already unlocked), you might want to used pkexec instead of sudo so the prompt is handled by your DE's polkit agent.
