### ISSUE TITLE
Can't Download PDF Attachment From Firefox Extention

### ISSUE THREAD

**Issue by harrismcc** [bitwarden/clients#2750]
### Steps To Reproduce

1. Click on 'Secure Notes'
2. Click on a note with a pdf attachment
3. Click the download icon next to the attachment

### Expected Result

PDF Downloads, and appears in the download tab/folder.

### Actual Result

Extension window closes, but download never starts and file never appears

### Screenshots or Videos

![bitwarden-bug](https://user-images.githubusercontent.com/740503/170540104-4aee8f03-b491-465c-aa30-d38bb010228e.gif)

### Additional Context

- Does not seem to affect non pdf file types. Other files I have download fine.
- I have downloaded this file in the past, probably in previous versions of either the browser or extension
- I am able to download the file via the web vault, so it's not corrupted. 

### Operating System

macOS

### Operating System Version

12.2.1

### Web Browser

Firefox

### Browser Version

100.0.2

### Build Version

1.58.0

**Comment by aj-bw** [comment]
Hi @harrismcc,

Thanks for reaching out and providing clear steps on how you saw the issue! So far, I am unable to reproduce this issue on MacOS in Firefox. I was able to download PDF attachments form the browser extension from all applicable item types.

We'd like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
