### ISSUE TITLE
Autofill issue on www.ebay-kleinanzeigen.de

### ISSUE THREAD

**Issue by 030-030** [bitwarden/clients#2755]
### Steps To Reproduce

2. Click on '...'
4. Click on '...'

https://www.ebay-kleinanzeigen.de/m-einloggen.html?targetUrl=/anzeigen/s-suchen.html

### Expected Result

Bitwarden have problem to fill in

### Actual Result

bitwarden do not work

### Operating System

macOS

### Web Browser

Brave

### Browser Version

newest

### Build Version

1.58.0

**Comment by djsmith85** [comment]
Hi @030-030 and thank you for your report. 

I'm unable to test this on a Mac, but using Brave on Windows I am unable to reproduce this. 

Could you please provide more information on the re-production steps and what issue you are seeing? 

Does Autofill on Page load not work?
Auto fill via the shortcut (Cmd+Shift+L)
Auto fill via the context menu?
Does the extension show a match for the url (number 1 on the extension icon)?

**Comment by aj-bw** [comment]
Thank you for getting in touch and bringing this to our attention! As @djsmith85 mentioned, I also cannot reproduce this issue on MacOS as well.

We'd like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
