### ISSUE TITLE
Attempting to log in using incorrect credentials returns an error message with "Captcha is invalid. Please refresh and try again'.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#2789]
### Steps To Reproduce

1. Navigate to the Web Vault (https://vault.bitwarden.com/#/).
2. Type the email address and/or the master password incorrectly.
3. Click on Log In.
4. Complete the Captcha, and click on Verify.
5. Click on Log In again.

### Expected Result

The error message should show "Username or password is incorrect. Try again."

### Actual Result

The error message shows "Capthca is invalid. Please refresh and try again."

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/73389600/156887996-38869bec-4d9d-4e7f-af47-939691cdef87.png)

### Additional Context

If you maintain the same valid Capthca token and only update the credentials to the correct ones, you'd be able to log in successfully.

### Operating System

Windows

### Operating System Version

11 Pro 21H2.

### Web Browser

Firefox

### Browser Version

97.0.1.

### Build Version

2.26.2.

**Comment by atjbramley** [comment]
Hi @SergeantConfused ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a temporary issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
