### ISSUE TITLE
Brave: bitwarden immediately crashing

### ISSUE THREAD

**Issue by androidacy-user** [bitwarden/clients#2834]
### Steps To Reproduce

1. Install bitwarden on brave
2. See notification "bitwarden has crashed"
3. Click on notification but it just keeps crashing

### Expected Result

Not to crash? 

### Actual Result

Crashing

### Additional Context

Tried reinstalling both brave and bitwarden to no avail

### Operating System

Windows

### Operating System Version

11

### Web Browser

Brave

### Browser Version

1.39.111

### Build Version

I literally can't look at that

**Comment by aj-bw** [comment]
Hi @androidacy-user,

Thanks for reaching out! I did some testing on existing installs as well as fresh installs with the steps and versions provided and could not recreate the issue. I was able to install the browser extension in Brave without issue in all scenarios.

We'd like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
