### ISSUE TITLE
Import of encrypted vault backup fails - "Data is not formatted correctly"

### ISSUE THREAD

**Issue by cholzer79** [bitwarden/clients#2872]
### Steps To Reproduce

1. with the CLI create an encrypted_json vault backup using the --password flag to set an encryption password 
2. import that backup on vault.bitwarden.com

### Expected Result

1. prompt asking for the encryption password
2. backup gets imported

### Actual Result

**Import Error**
Data is not formatted correctly.

### Screenshots or Videos

https://i.imgur.com/aOtw3hR.jpeg

### Operating System

Windows, Linux

### Web Browser

Chrome, Vivaldi

### Build Version

Server 2022.05.0 Web 2022.5.2

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue on multiple OSs and was unable to do so. You are running _bw export --format encrypted_json --password examplepassword_ correct? Does updating your Bitwarden client help resolve the issue?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
