### ISSUE TITLE
Custom fields not working

### ISSUE THREAD

**Issue by Godehardt2003** [bitwarden/clients#2914]
### Steps To Reproduce

1. Go to 'https://www.aerosoft.com/en/account'
2. Create login data
3. Try to fill it (this should result in filled inputs on the right side "I'm a new customer")
4. Create custom fields in Bitwarden (input ids are "email" & "passwort")
5. Try it again

### Expected Result

That it fills the left side under "I'm already a customer."

### Actual Result

It fills the right side.

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/78535292/173889443-a00fd96f-6b89-41f6-a754-bd43e0a697ca.png)
Nutzername => Username
Passwort => Password
![grafik](https://user-images.githubusercontent.com/78535292/173889668-8b7a8173-8328-46e4-9a7f-d6346ebd73b5.png)
![grafik](https://user-images.githubusercontent.com/78535292/173889993-b4388804-9cd1-4575-b7b6-714d82b463bf.png)
(Inputs wich should be filled)
![grafik](https://user-images.githubusercontent.com/78535292/173890068-0ed5c8f3-a424-494c-b5cc-3d9b1be7fefd.png)
(Inputs wich are filled)

### Additional Context

I posted it already in https://github.com/bitwarden/clients/issues/1621 but I think this should be a bug because I filled the custom fields and the input ids are unique...
And yeah, the autofill itself is also not working, only if I click on the specific entry. On other sides this is working perfectly.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2022.5.0

**Comment by TroyBW** [comment]
Hi there!

We appreciate you letting us know of this issue, and I can confirm that I am able to reproduce this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, it seems you have already submitted a report using one of these forms (thank you!).

In the future, if you encounter any other page or app that doesn't autofill as expected, we ask that you submit the information using the corresponding form.

This issue will now be closed. 

Thanks!
