### ISSUE TITLE
Badge counter disappears and autofill fails after a period of time in Safari even if there are matched items

### ISSUE THREAD

**Issue by snachx** [bitwarden/clients#2924]
### Steps To Reproduce

1. Launch Safari and use it casually for a while
2. Go to any website which has matched items in bitwarden

### Expected Result

the Bitwarden icon should overlay a badge counter reporting the number of items found for that web page
![CleanShot 2022-06-17 at 10 19 50@2x](https://user-images.githubusercontent.com/2197143/174212104-f29a6d2f-4655-4d73-9e83-fc37aff7dcdc.png)

### Actual Result

No badge counter and autofill not working
![CleanShot 2022-06-17 at 10 16 57@2x](https://user-images.githubusercontent.com/2197143/174212168-a737b30c-a7de-41e6-8256-ba53cd271551.png)

### Additional Context

If I toggle the option which controls the badge counter off and on, it works again but for just a while.

### Operating System

macOS

### Operating System Version

12.4

### Web Browser

Safari

### Browser Version

15.5 (17613.2.7.1.8)

### Build Version

2022.5.0

**Comment by dbosompem** [comment]
Hi @snachx , thanks for creating this issue. Your issue has been reproduced and the team will make time to take a look, hopefully we can get things sorted and working for you. Very appreciated!

**Comment by atjbramley** [comment]
Hi @snachx, 

I attempted to reproduce your issue and was unable to do so.  I used the following setup:

- Bitwarden version 2023.9.2
- Safari 17.0
- macOS 14.0

I think your error could have been fixed in the versions between your original reporting and the latest release. The issue here will therefore be closed.

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Thanks!
