### ISSUE TITLE
On Chrome need to cancel WebAuthn prompt to check "Remember me" checkbox

### ISSUE THREAD

**Issue by jikamens** [bitwarden/clients#2933]
### Steps To Reproduce

1. Configure a security key for 2FA on your Bitwarden account.
2. Make sure you are logged out of the browser extension in Chrome.
3. Enter your username and password to log into the browser extension in Chrome.
4. Note how the WebAuthn prompt pops up on top of the "Remember me" checkbox.
5. To check that checkbox, you need to cancel the WebAuthn prompt, check the checkbox, and click the "Authenticate WebAuthn" button to re-initiate the WebAuthn authentication.

### Expected Result

I shouldn't have to click two extra times (cancel the WebAuthn prompt, re-initiate the WebAuthn prompt) to be able to check "Remember me". Maybe make the user click the button to bring up the WebAuthn prompt (like, e.g., Github does when you log in)?

### Actual Result

I have to click two extra times to click the "Remember me" checkbox.

### Additional Context

The WebAuthn flow in Firefox is different and doesn't have this problem. It's just Chrome that has this annoying behavior.

### Operating System

macOS

### Operating System Version

12.4

### Web Browser

Chrome

### Build Version

2922.5.0

**Comment by yashwalter12** [comment]
Hello @jikamens This is working at expected right now. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
