### ISSUE TITLE
Generator password length reverts after being set with slider

### ISSUE THREAD

**Issue by jikamens** [bitwarden/clients#2935]
### Steps To Reproduce

1. Open the password generator in the Chrome extension pop-up.
2. Make sure you've selected Password and Password.
3. Change the password length with the slider.
4. Close the pop-up.
5. Open the pop-up and go back to the generator.
6. Observe that the password length has reverted to whatever it was before you set it with the slider.
7. Now repeat steps 1-5 but this time change the length with the up and down arrows instead of the slider.
8. Observe that the password length you set sticks when you set it with the arrows.

### Expected Result

Password length sticks when set with slider.

### Actual Result

Password length doesn't stick when set with slider.

### Operating System

macOS

### Operating System Version

Monterey 12.4

### Web Browser

Chrome

### Build Version

2022.5.0

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. If you update to the latest version of the browser extension, does that resolve the issue?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
