### ISSUE TITLE
Start automatically at login does not work in Desktop AppImage installation on Linux

### ISSUE THREAD

**Issue by evelez7** [bitwarden/clients#2938]
### Steps To Reproduce

1. Download Bitwarden AppImage 
2. Launch AppImage
3. Go to File/Settings
4. Check "Start automatically on login"
5. Close settings
6. Restart

### Expected Result

Upon reboot and login, the Bitwarden app should launch automatically.

### Actual Result

The Bitwarden app does not launch automatically upon login.

### Screenshots or Videos

![bitwarden_autostart_appimage_terminal](https://user-images.githubusercontent.com/20407271/174684857-01984236-825b-4dd1-a3a5-be2448421a48.png)

### Additional Context

The screenshot shows that the executable being targeted is located inside a temporary directory that is only loaded when the AppImage is launched. So the `.desktop` file is targeting a non-existent location. The `.rpm` installation targets an executable located inside of `/opt`.

[Essentially a copy of this issue from the original desktop repo.](https://github.com/bitwarden/desktop/issues/701) It seems that it did not survive the transition and was not addressed.

### Operating System

Linux

### Operating System Version

5.18.5-200.fc36.x86_64 (Fedora 36)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by aj-bw** [comment]
Hi @evelez7! Thanks for reaching out.

We were able to reproduce the issue you described, I will raise it to be reviewed / prioritized accordingly. A workaround in the meantime would be to edit the Exec path in the screenshot you provided to `Exec=/path/to/your/AppImage`

**Comment by danielrosehill** [comment]
Experiencing the same issue (Ubuntu 22.04 LTS + LXDE)

**Steps To Reproduce**
Download the appimage from the Bitwarden site.
Launch the application / GUI.
Enable "start automatically on login"
autostart

**Expected Result**
Bitwarden should automatically start after login (or start minimised to the tray icon depending on settings).

**Actual Result**
Bitwarden does not start.

**Screenshots or Videos**

![autostart](https://github.com/bitwarden/clients/assets/40233203/6416ba98-7b1f-49fd-828b-630cc7edb9d6)


**Additional Context**
I'm using LXDE as my DE which is a little old and buggy so perhaps this issue is DE-related.

**Operating System**
Linux

**Operating System Version**
22.04 LTS

**Installation method**
Direct Download (from bitwarden.com), Other

**Build Version**
Version 2024.3.0 Shell 28.2.4 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

**Comment by artemdanielov** [comment]
Same issue on Ubuntu 22.04 with Gnome.
This odes not work:
![image](https://github.com/bitwarden/clients/assets/59414351/0eb328b6-6253-449c-add0-2f8a71d4af73)

**Comment by trmartin4** [comment]
Hello,

We have consolidated and adjusted our supported Linux [download](https://bitwarden.com/download/#downloads-desktop) options to reflect the fact that the AppImage distributable does not full desktop integration. We recommend that users install the Flatpak or Snap package, which will ensure updates are managed correctly and you remain on the latest version.

If you do wish to continue with AppImage, there are some third-party tools listed on the download page that could be used in concert with the Bitwarden application, but these tools are not maintained or audited by Bitwarden.

![image](https://github.com/user-attachments/assets/86ba3cba-ec26-4f1f-961b-a9414b8c55f5)

Our recommendation is that you install the Bitwarden desktop through Flatpak or Snap to ensure that you have the best experience, all functionality is available, and the application receives updates automatically.
