### ISSUE TITLE
CLI client on Linux does not support FIDO2 2FA "No providers available for this client"

### ISSUE THREAD

**Issue by guerby** [bitwarden/clients#3026]
### Steps To Reproduce

1. Set up FIDO2/webauthn for your account on the web interface
2. On a Linux install the CLI client 
3. bw login
4. Enter Email et Master password

### Expected Result

Asking to touch the FIDO2 key button and successful login

### Actual Result

The CLI client prints "No providers available for this client." and then hangs

### Operating System

Linux

### Operating System Version

Debian 10

### Shell

Bash

### Build Version

1.22.1

**Comment by Larry-Sussman** [comment]
Hi @guerby, from the [Two-step Login via FIDO2 WebAuthn](https://bitwarden.com/help/setup-two-step-login-fido/) Help Center article:
> FIDO2 WebAuthn cannot be used on all Bitwarden applications. Enable another two-step login method in order to access your vault on unsupported applications. Supported applications include:
> - Web vault on a device with a [FIDO2-supported browser](https://fidoalliance.org/fido2/fido2-web-authentication-webauthn/).
> - Browser extensions for a [FIDO2-supported browser](https://fidoalliance.org/fido2/fido2-web-authentication-webauthn/).
> - Desktop apps on Windows 10 and above.
> - Mobile apps for Android and iOS 13.3+ with a [FIDO2-supported browser](https://fidoalliance.org/fido2/fido2-web-authentication-webauthn/).

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.
We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one.
Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked. This issue will now be closed. Thanks! 😄
