### ISSUE TITLE
Not Asking for Yubico Security Key

### ISSUE THREAD

**Issue by YngDbz** [bitwarden/clients#3046]
### Steps To Reproduce

1. Configure Yubikey Security Key as 2FA
2. Log out of web client and login. Web client will always ask to scan NFC fingerprint on Yubikey
3. Log into Bitwarden Application on Windows 10. Initial login gets prompted for Yubikey NFC fingerprint scan
4. Close the Bitwarden Application
5. The next login asks for a password but skips the NFC 2FA challange effectively rendering 2FA useless

### Expected Result

Every new login on any platform (web, or desktop app etc) should always request **both** authentication methods.

### Actual Result

Any subsequent logins after the initial login on the desktop application will only ask for the master password and skips the request for Yubico 2FA NFC fingerprint challenge.

The same behavior doesn't happen on the web console as it requests both factors every time.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.6.0

**Comment by dbosompem** [comment]
Hi @YngDbz , apologies for facing this issue. We will reproduce this internally, and upon a successful one take a look at it. Thank you for your patience!

**Comment by djsmith85** [comment]
@YngDbz Did you have a look at our [help site article for using Yubico keys](https://bitwarden.com/help/setup-two-step-login-yubikey/#use-yubikey)?

- Did you possibly click on the "Remember me" option?
  > Check the Remember Me box to remember your device for 30 days. Remembering your device will mean you won't be required to complete your two-step login step.
- The web-vault is usually logging in to a new session instead of an unlock
- On the desktop client, please check if you only locking instead of logging out of your vault. 
  > You will not be required to complete your secondary two-step login step to Unlock your vault once logged in. For help configuring Log Out vs. Lock behavior, see [Vault Timeout Options](https://bitwarden.com/help/vault-timeout/).

**Comment by aj-bw** [comment]
Hi @YngDbz,

I see a few responses above, I did attempt to recreate the issue as described but could not recreate it. Similar to what @djsmith85 explained, if your Vault Timeout Action in the desktop app is set to `Lock`, then you are experiencing expected behavior. Yubikey or any other 2FA methods are only required for Login, not Unlock ( more can be read on Unlock vs. Login that here: https://bitwarden.com/help/biometrics/#understanding-unlock-vs-log-in ).

If you wish for your 2FA method to be required each time you access your vault in the desktop app, you can set your Vault Timeout Action to `Logout` and Vault Timeout Timer to whichever is fitting for your preference - this will result in having to log in with your Password _and_ 2FA method.

If you need further assistance configuring these options, please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content.
