### ISSUE TITLE
New added Organization folder exist in both sides

### ISSUE THREAD

**Issue by jjrosado** [bitwarden/clients#3163]
### Steps To Reproduce

1. Create and select new organization, then create a new folder into that organization.
2. Click on My Vault.
3. Scroll down to folders and you will see the folder in both sides, My Vault and into the created organization.

### Expected Result

Every folder should be exist in every section, separated.

### Actual Result

You will see the folders in both sides.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.6.2

**Comment by njmulsqb** [comment]
@jjrosado By folder, do you mean collections? As I can only see collections feature in Bitwarden, and yes collections of an organization are being displayed in the vault as well

Can someone confirm me if its a bug or an intended functionality?

**Comment by djsmith85** [comment]
@jjrosado and @njmulsqb This is intended behaviour. Folders are structures used to organize your individual vault, which can also include items shared with you via a an organization. Collections are used within an organization.

The vault-filter set to `My vault` indicates you are viewing your individual vault, hence it is showing the folders.

Further information can be found on our help pages for [Folders](https://bitwarden.com/help/folders/) and [Collections](https://bitwarden.com/help/about-collections/)

**Comment by Tyree** [comment]
This makes no sense. I want to be able to have folders in an organization that is not in another organization or my personal vault. As it is, I create a folder in an organization, put items in it, and the folder shows up in my personal vault and other organizations but empty since I don't need that folder in the other vaults. For example, if I create an Entertainment folder to store a Netflix login, I don't need that folder in my work organization. It just sits there empty and pointless. Why would that be intended behavior?
