### ISSUE TITLE
I can't autofill credentials from search.

### ISSUE THREAD

**Issue by Leopere** [bitwarden/clients#3183]
### Steps To Reproduce

1. Navigate to a login page.
2. Use any of the browser extensions to search for a credential
3. No option to auto-fill.

### Expected Result

3. should allow for auto-fill credentials for the website. 

### Actual Result

3. doesn't allow for auto-fill credentials for the website. 

### Operating System

Windows, macOS

### Web Browser

Chrome, Safari, Firefox, Brave

### Build Version

Version: 2022.6.1

**Comment by tanveermahendra** [comment]
Currently, the browser extension shows these inline options when the Tab or Vault option is selected:
<img width="171" alt="Screenshot 2022-08-01 at 18 18 49" src="https://user-images.githubusercontent.com/1792863/182196186-864b4581-4c4d-42ba-989a-f2a37735e0a2.png">
<img width="192" alt="Screenshot 2022-08-01 at 18 18 37" src="https://user-images.githubusercontent.com/1792863/182196197-340e3284-0157-4858-b586-9221979eff1f.png">

However, the right-most icon doesn't bring value to me as a user. Additionally, the auto-fill option under the 'Tab' view is hidden behind the 'View' option.

**Proposed solution:**
Remove the right-most clock icon which remains mostly disabled and replace it with an 'Auto-Fill' icon for the user.
An alternate solution would be to open a List popover by clicking the 'Key icon' and provide the user with an option to copy or fill.

I am willing to contribute by providing a mockup of the same if someone can share UX contribution guidelines.

**Comment by Leopere** [comment]
> However, the right-most icon doesn't bring value to me as a user. Additionally, the auto-fill option under the 'Tab' view is hidden behind the 'View' option.
> 
> **Proposed solution:** Remove the right-most clock icon which remains mostly disabled and replace it with an 'Auto-Fill' icon for the user. An alternate solution would be to open a List popover by clicking the 'Key icon' and provide the user with an option to copy or fill.
> 
> I am willing to contribute by working with the internal UX team and working on mockups for the same (if someone can share UX contribution guidelines).

@tanveermahendra, I think you might be on point to some degree with this suggestion however, since I, for one frequently use the Clock Button [Two Factor Authentication], I would like to suggest an augmentation to your recommendation.  Wherein instead of suggesting the all-out removal of the TFA[Clock] button to only show it when it's available. 

My main gripe is that BitWarden's extension is simply just not giving me the ability to choose to auto-fill a specific website via the search function.  Even if the pattern matches the URL.

**Comment by aj-bw** [comment]
Hi @Leopere and @tanveermahendra! Thanks for reaching out.

Currently, if you search for for a vault item in the browser extension, click on the desired search result, there is an "Auto-Fill" or "Auto-Fill and Save" option you can select to fill that data into the webpage you are on. I will attach a screenshot at the bottom of this response.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like the changes mentioned above.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

![search auto-fill 2 of 2](https://user-images.githubusercontent.com/81774843/185928514-89452e0b-e7bb-4f76-a215-be737a61a0ec.jpg)

**Comment by Leopere** [comment]
Thanks for adding this feature it definitely is a great improvement!  Keep up the excellent work!
