### ISSUE TITLE
Username generator saves wrong website to description on AnonAddy

### ISSUE THREAD

**Issue by Twiglet1022** [bitwarden/clients#3199]
### Steps To Reproduce

1. Open the Bitwarden sidepanel in Firefox while on the website that you want to generate a username for
2. Click on "Generator" along the bottom
3. Create a forwarded email alias with AnonAddy for your custom domain (API access token already applied) by clicking on the "Regenerate Username" icon in the top right
4. Login to your account on AnonAddy and check the description for the newly created alias

### Expected Result

If I am on github.com when generating a username, I expect that the description would read "Website: github.com. Generated by Bitwarden." when I check the alias on AnonAddy

### Actual Result

Instead the description reads "Website: some.website.I.visited.a.month.ago.com. Generated by Bitwarden." it is always the same website.

### Additional Context

If I generate a username from the "Tab" menu along the bottom (and have remembered to click refresh in the top-left) then create a new login using the plus icon in the top-right and use the username generator from within that menu, the description is saved correctly. It is only the standalone generator that is giving the wrong description.

I tried creating a new login with a generated username to see if this updated the website that appears in the description for the standalone generator, but it still saves with the same website that I last visited over a month ago.

The reason I'm not going through the normal login creation route is because sometimes I want to generate a username for newsletter signups this way.

### Operating System

Windows

### Operating System Version

Windows 11 (22621.436)

### Web Browser

Firefox

### Browser Version

103

### Build Version

2022.6.1

**Comment by vphan916** [comment]
Hi @Twiglet1022!  Hope all is well and thanks for reaching out.  I do apologize but we are unable to reproduce this.  Do you mind updating to the latest version of the Browser extension and let us know if the problem persists? Thank you!

**Comment by Twiglet1022** [comment]
Hi @vphan916 thanks for your reply. I still had this issue on the latest build (2022.8.0) so I just tried deleting the browser extension and reinstalling. For now, when I generate usernames this way the description just reads "Generated by Bitwarden." without a website.

So at least it's not giving me the wrong website. But I was expectingt it to populate the description with the URL of the website I'm currently on when using the username generator.

**Comment by uladz-zubrycki** [comment]
Similarly for me wrong website is used. It's always the same website I once generated a email alias for. 

AnonAddy as an email provider.
Windows 10.0.22000 Build 22000
Firefox 107.0 (64-bit)
Extension 2022.10.1

**Comment by kev153** [comment]
Same issue here with AnonAddy. Always the same website in the description I once generated an alias for some time ago.

Windows 10.0.22621 Build 22621
Firefox 114.0.1 (64-bit)
Extension 2023.5.0

**Comment by xsc27** [comment]
Same issue w/ SimpleLogin

Fedora 37
Firefox 114.0 (64-bit)
Extention 2023.5.0

**Comment by sam-hatley** [comment]
Same issue with AnonAddy, still.

Windows 10.0.22621 Build 22621
Firefox 116.0.3 (64-bit)
Extension 2023.7.1

**Comment by smuun** [comment]
Same issue, except that it has persisted after reinstall.  Fedora 38, Firefox 118.0.1 (64-bit), Bitwarden extension 2023.9.2.

**Comment by atjbramley** [comment]
Hi @Twiglet1022,

I attempted to reproduce your issue and was unable to do so. In particular, I:

- created a new addy.io API key
- added this to my Bitwarden extension in Firefox on macOS 
- created a new alias for Github
- noted that this appeared as Website: github.com in the addy.io control panel

I suspect that you may be running into a conflict in your browser environment, and would suggest a clean reinstall and a refresh of the firefox profile as a first step.  

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.  We will happily re-open this issue and direct it to the attention of the team if reproduction steps can be discovered.

Thanks!

**Comment by lynara** [comment]
I have exactly the same issue as well, but for me this happens witch Brave and Edge browser.

**Comment by fchagas97** [comment]
Any progress on this? The problem still exists

**Comment by Twiglet1022** [comment]
The issue seems to be stuck because the developers can't replicate it, but I'm not sure what else to say. The reproduction tsteps that I provided work for me with a fresh install of both the extension and browser.

I suppose it's not not entirely clear from @atjbramley's reply if their test specifically used the "Generator" here because it is here that the problem is being experienced.

![image](https://github.com/bitwarden/clients/assets/29353990/6f3b37f2-ae11-428d-a03e-a66644009245)

Creating a new entry by clicking on the "+" icon from within "Tab" works fine and correctly associates the new entry with the URL of the current page that is open in the browser.

**Comment by lynara** [comment]
@Twiglet1022 this might be a very good point!

thing is also that this issue got closed.
@atjbramley could you please reopen this?

**Comment by smlloyd** [comment]
I subscribed to this issue a while ago because I too somehow ended up with the same website entry for all my addy aliases. Though I don't remember how I generated the aliases ("+" button or generator button), I didn't run into this anymore after creating and using a new api key.

Since using the new api key, creating aliases via the "+" butten gives me:

> Website: www.example.org. Generated by Bitwarden.

Using the generator button directly gives me:

> Generated by Bitwarden.

Presumably this is the expected behaviour.

However, given that (a) the BW window closes when switching browser tab, and (b) the URI field is autopopulated when creating a new item via the "+" button, one might say that the active BW window itself is tied to that tab (as long as it's not popped out)? In way then, the website *not* being included when going via the generator button directly is a bit unexpected?

An important thing to consider is that managing addy aliases *without* knowing which website they correspond to may become a bit tricky, so I'd rather deal with some unnecessarily included "website" entries than accidentally missing some.
