### ISSUE TITLE
Delay on opening the extension in chromium

### ISSUE THREAD

**Issue by MartinX3** [bitwarden/clients#3266]
### Steps To Reproduce

1. Click on the extension icon
2. Wait
3. It popups

### Expected Result

Instant opening like in firefox.

### Actual Result

Chromium has a 1-3 seconds delay, while it instant opens in firefox.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Chrome

### Browser Version

104.0.5112.79

### Build Version

2022.8.0

**Comment by vphan916** [comment]
Hey @MartinX3!  We are unable to reproduce this. Are you using a VM by chance?  Can you update to the latest version and let us know if this problem persist?

**Comment by MartinX3** [comment]
Hey @vphan916 
I'm using archinux on bare metal with the newest version.

After clicking on the icon in chromium I need to wait 1-2 seconds until it opens the context menu of the botwarden extension.

In Firefox there is no delay. Just instand opening.

**Comment by kis87988** [comment]
I have the same issue with normal Chrome

**Comment by motir** [comment]
Same here, on two different machines, one is Windows 11 and the other is a Mac.

**Comment by mindrunner** [comment]
Can confirm this partly. The delay seems to be rather max 1 second for me. But definitely not as instant as in firefox

**Comment by mindrunner** [comment]
feels more snappy now for me

**Comment by motir** [comment]
same here, works great. @djsmith85 thank you!

**Comment by MartinX3** [comment]
I still have this delay.

**Comment by djsmith85** [comment]
> I still have this delay. Enough to make a screenshot after I clicked the button. ![image](https://private-user-images.githubusercontent.com/4518092/309219668-5ee64e55-05ea-4777-b06c-57eaf9e502f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODg1NDUsIm5iZiI6MTcwOTI4ODI0NSwicGF0aCI6Ii80NTE4MDkyLzMwOTIxOTY2OC01ZWU2NGU1NS0wNWVhLTQ3NzctYjA2Yy01N2VhZjllNTAyZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTAxNzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIxMTdmNjdmNGJmOTI1ZDJlYjcwNjlkY2IwOGI5Zjg1MTI1MDNjMDE0N2MxNWEwZDI0MDk3MzJiYTFmMGEwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K5AxpSKotB-G2UE0e8wmL2eF6pQfdI-qu0nc5lJ6a_c)

@MartinX3 Could please provide more details about your setup.
The used versions will likely have changed since your first report:
OS version, browser version (normal vs incognito session), extension version, etc.

Please check if you can update any of them and see if the issue persists.

I also see quite a few extensions installed, does the disabling all of them besides Bitwarden make a difference?

Kind regards,
Daniel

**Comment by MartinX3** [comment]
@djsmith85 
Thank you for your response!

OS: Arch Linux  (Rolling Release always up to date)
Browser: Chromium 122.0.6261.94  
Extension version: 2024.2.0  

The incognito Session which has only the bitwarden extension allowed has the same delay.

**Comment by Greenderella** [comment]
Hello,

I attempted to replicate the issue on my Arch machine (current release: 2024.08.01) with Chromium Version 128.0.6613.36 and Bitwarden 2024.7.1, but I was unable to reproduce it. The extension appears to be working correctly without any noticeable delays. I recommend uninstalling the extension, clearing any remaining data, restarting your device, and then reinstalling the extension to see if the issue continues.

You can find guidance on clearing leftover data here: https://bitwarden.com/help/data-storage/#on-your-local-machine.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/), so our support team can help you troubleshoot this issue.

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
