### ISSUE TITLE
I am unable to manipulate the custom field headers via some methods.

### ISSUE THREAD

**Issue by rokejulianlockhart** [bitwarden/clients#3302]
### Steps To Reproduce

1. Create a custom field.
2. Attempt to:
3. 1. Move the cursor to any of it via mouse-clicks.
4. 2. Select any of it.

### Expected Result

I should be able to manipulate it as I do to most other text.

### Actual Result

Nothing occurs.

### Operating System

Linux

### Operating System Version

"uname -a" produces "Linux BEEDELLROKEJULIANLOCKHART.1660221716 5.18.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 3 15:44:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux".

### Web Browser

Firefox

### Browser Version

103.0.1

### Build Version

2022.8.0

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Does updating to the latest version of the add-on resolve the issue?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
