### ISSUE TITLE
Implement Offline mode

### ISSUE THREAD

**Issue by marcbull** [bitwarden/clients#3335]
### Steps To Reproduce

* Disable the Internet connection, either on purpose or forced by your Internet provider.
* Open the Bitwarden desktop app. - As a side effect of not having an internet connection, I was logged out.
* Enter the master password.

### Expected Result

The expected result is that I'm still able to access my logins without an Internet connection. In the best case scenario, I'm also not forced to enter my master password and can still use biometrics to open the vault.

### Actual Result

As a result of the above login attempt, I get the error message "failed to fetch" or something similar.

### Additional Context

I'm using a MacBook Air (M1, 2020) with 8 GB of memory.

### Operating System

macOS

### Operating System Version

12.5.1 (21G83)

### Installation method

Mac App Store

### Build Version

2022.5.1 (3283)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Additionally, I am unable to save modifications via the Android application when my connection to the internet ceases.

**Comment by aj-bw** [comment]
Hi @marcbull and @BEEDELLROKEJULIANLOCKHART!

What you are describing is currently expected behavior for our applications. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a Feature Requests section for submitting, voting for, and discussing requests like this one as well as our [Bitwarden Roadmap](https://community.bitwarden.com/t/bitwarden-roadmap/12865). Offline Editing is on our Future Initiatives section of the Roadmap.

Feel free to sign up for the Community Forums to participate or track any of these efforts! This issue will now be closed. Thanks!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@marcbull, vote at "http://community.bitwarden.com/t/107".
