### ISSUE TITLE
bw get item failing to find exact match

### ISSUE THREAD

**Issue by JWBWork** [bitwarden/clients#3366]
### Steps To Reproduce

1. Create two credential items where one name is the substring of the other. Such as `Cred Item` and `Cred Item Second`
2. request the item which has a name that's a substring of the other
```
bw get item "Cred Item"
```

### Expected Result

Expect the credential set `Cred Item` to be returned as a json string in the console

### Actual Result

```
STDERR: More than one result was found. Try getting a specific object by `id` instead. The following objects were found:
1234abc-credential-set-1-id-1234abc-1234abc
1234abc-credential-set-2-id-1234abc-1234abc
```

### Operating System

macOS

### Shell

Zsh

### Build Version

2022.6.2

**Comment by Larry-Sussman** [comment]
Hi @JWBWork, thanks for the report!

Your issue appears to be describing the expected behavior of the software. In this scenario, we would recommend getting the item by ID to avoid the multiple results. If you want this to be changed, it would be a feature request, not a bug report. 

We can absolutely consider an enhancement request to modify or enhance the search functionality used here in the CLI, and if that would be desired, please consider searching through and/or posting to the [Bitwarden Community Forums](https://community.bitwarden.com/) which has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.

Thanks!

**Comment by istarkov** [comment]
Following function alias at (.zshrc) can be used 

```zsh
# Usage:
# bwget <item-name>
# to get any org password
# bwget <item-name> null
# to get self password
bwget() {
  local pwd
  local count
  # by default search inside any organisation
  local organisation=${2:-notnull}

  count=$(bw list items --pretty --organizationid ${organisation} | jq -r '[.[] | select(.name=="'$1'")] | length')

  if [[ "$count" -gt 1 ]]; then
    echo "Multiple items found"
    return 1
  fi

  if [[ "$count" -lt 1 ]]; then
    echo "No items found"
    return 1
  fi

  pwd=$(bw list items --pretty --organizationid ${organisation} | jq -r '.[] | select(.name=="'$1'") | .login.password')
  if [[ -z "$pwd" ]]; then
    echo "Password not found"
    return 1
  fi

  echo "$pwd"
}
```
