### ISSUE TITLE
Ghost security keys in WebAuthn config

### ISSUE THREAD

**Issue by mimi89999** [bitwarden/clients#3404]
### Steps To Reproduce

1. Open two factor settings
2. Manage WebAuthn FIDO2 security provider
3. Notice a list of 5 security keys named `Clé WebAuthn 1` to `Clé WebAuthn 5`
4. Add a FIDO2 key
5. Notice your key in the list and 4 other security keys named `Clé WebAuthn 4` to `Clé WebAuthn 5`

### Expected Result

The list should only contain FIDO2 keys that I added. If there is a limit on the number of keys that can be added, present it in another form like `x/5 allowed keys`.

### Actual Result

The list shows security keys that I didn't add.

### Screenshots or Videos

![Screenshot 2022-08-28 at 22-36-17 Identification en deux étapes Coffre web Bitwarden](https://user-images.githubusercontent.com/8530546/187093503-e335c9cc-2260-42cd-9708-6e460b923222.png)

### Operating System

Linux

### Operating System Version

Debian testing

### Web Browser

Firefox

### Browser Version

104.0

### Build Version

2022.8.1

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. The Bitwarden Password supports registering multiple security keys (and it's great to have multiple in case you ever lose a key). The other spots are empty spaces to register additional keys. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
