### ISSUE TITLE
Search is not wildcard, by default

### ISSUE THREAD

**Issue by DeflateAwning** [bitwarden/clients#3413]
### Steps To Reproduce

1. Create a password entry with a title, username, password, etc. Make the description Notes section something like "hello word, it's me, margret". Make sure the title, UN, PW doesn't include "margret".
2. Save entry.
3. Search for "argret" with the main search (without the letter 'm')
4. See no results.

### Expected Result

In Step 4, I would expect to see the search result created in step 1.

### Actual Result

In Step 4, I do not see the search result created in step 1.

### Additional Context

Related to #3348 (closed). 

Per the [full text search article](https://bitwarden.com/help/searching-vault/#full-text-search), it appears that the repro above is actually a bug and is not a "feature" (at least as documented currently; maybe the docs just need an update).

Here's the specific part I'm talking about: https://user-images.githubusercontent.com/11021263/186948817-5e018abf-6946-444c-b80a-4532997275fd.png

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Vivaldi

### Browser Version

Latest

### Build Version

2022.8.0

**Comment by Krychaz** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request. Please have a look here - https://bitwarden.com/help/searching-vault/#wildcards-and-advanced-search-parameters

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
