### ISSUE TITLE
 Repeated “verify browser connection” renders Windows Hello unusable 

### ISSUE THREAD

**Issue by rodalpho** [bitwarden/clients#3428]
### Steps To Reproduce

I'm running:
- Windows 11 latest GA release
- Firefox 104.0.1
- Bitwarden Firefox addon 2022.8.0
- Bitwarden Windows Version 2022.8.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

Every time I restart my browser, the BW app, or my computer (which Windows does quite often) when I try to authenticate via fingerprint the Bitwarden application (not extension) pops up and I need to click “OK” to “verify browser connection”. Then I need to go back to the browser and reauthenticate yet again. This is extremely annoying and led to me not using windows hello for Bitwarden at all. The feature is effectively broken for me.

This is very different from how it works on MacOS, which is perfect. You click the BW addon button in the browser, the app pops up, you authenticate with your fingerprint, and the BW vault immediately unlocks. Windows should work this way too.

### Expected Result

When my vault times out, I expect the Bitwarden browser addon to pop-up a request to biometrically authenticate via Windows Hello, connecting to the desktop application running in the background. Then I touch the Windows Hello fingerprint and the vault should immediately unlock.

The "verify browser connection" thing should only happen once per browser, ever.

### Actual Result

See repro steps

### Screenshots or Videos

n/a

### Additional Context

n/a

### Operating System

Windows

### Operating System Version

21H2 22000.918

### Web Browser

Firefox

### Browser Version

104.0.1

### Build Version

2022.8.0

**Comment by rodalpho** [comment]
Honestly, my feeling is Windows Hello integration was never usability tested as I can't imagine how anyone would believe it's functional. It absolutely isn't. I just turned it off entirely.

**Comment by Krychaz** [comment]
Hello there, 

Could I ask if this issue is still present for you?

**Comment by rodalpho** [comment]
Nope, still have it turned off. Why, is it supposed to be fixed?

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
