### ISSUE TITLE
Attachment filename overflows

### ISSUE THREAD

**Issue by nvlang** [bitwarden/clients#3445]
### Steps To Reproduce

1. Create a file with a long name, e.g. `Long filename example to demonstrate overflow - Lorem ipsum dolor sit amet, consectetur adipiscing elit, etc.txt`
2. Add this file as new attachment to a new (or existing) Bitwarden login item, save changes

### Expected Result

Filename was expected to be displayed wrapped or truncated somehow.

### Actual Result

Filename overflows from attachments field.

### Screenshots or Videos

![bitwarden filename overflow](https://user-images.githubusercontent.com/60381640/188442075-0f637127-db89-488f-8875-d69f1040b725.png)

### Operating System

macOS

### Operating System Version

12.5.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.8.1 (4085)

**Comment by mphelp** [comment]
@nvlang 
I wasn't able to reproduce the text overflow. See below.

<img width="485" alt="Screen Shot 2022-09-09 at 4 47 13 PM" src="https://user-images.githubusercontent.com/25730130/189450712-ea68e7c5-b1df-4493-8fd0-987991d42df1.png">
<img width="609" alt="Screen Shot 2022-09-09 at 4 47 32 PM" src="https://user-images.githubusercontent.com/25730130/189450728-4f723d06-5c15-4a23-bfb5-b2b7498c657f.png">

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try updating your Bitwarden client to see if that helps resolve the issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
