### ISSUE TITLE
Persist Form Fill State When Clicking Outside Extension

### ISSUE THREAD

**Issue by djpecot** [bitwarden/clients#3455]
### Steps To Reproduce

1. Open the Chrome Extension (I'm using Brave)
2. Open the "+" to manually enter the new login information
3. Start adding some extra information
4. Click out on something else to close the extension
5. My login + password information has now vanished! 

[Loom here](https://www.loom.com/share/2be90140bd3f499e9854248aaf88d6c5)

### Expected Result

Ideally, I would like there to be an auto-save on click out or at least a way to recover a working "draft" of the login form I've started.

### Actual Result

Lose all the data :(

### Screenshots or Videos

[Here ya go](https://www.loom.com/share/2be90140bd3f499e9854248aaf88d6c5)

### Operating System

Windows

### Operating System Version

Win 10

### Web Browser

Brave

### Browser Version

1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit) 

### Build Version

2022.8.0

**Comment by rootwork** [comment]
This is also true when editing a record, which can be even more frustrating -- for instance I was copying security question information into the "notes" field, accidentally clicked outside the window, and then had to go back and tediously enter it all in again.

I am using the extension build 2022.8.0, with Firefox 104.0.2, on Linux Mint 20.3.

**Comment by vphan916** [comment]
Hi @djpecot!  The actual behavior described by the ticket is the intended and correct behavior of the software.  One work around is when you are on the browser ext, you can click on the top left square icon to open the browser ext in a pop up window.  This way, you won't lose any information you entered when clicking outside the browser ext. 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

<img width="379" alt="browser extension" src="https://user-images.githubusercontent.com/95309255/190707287-8286be5c-3ca7-45a1-89e4-04ee7e04c67c.png">

**Comment by rootwork** [comment]
For others who land on this issue, the feature request is here:

https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470

It has been open for 4+ years and has hundreds of votes...
