### ISSUE TITLE
Missing Credentials

### ISSUE THREAD

**Issue by AlexanderDignan** [bitwarden/clients#3521]
### Steps To Reproduce

Logging into second bitwarden account all saved logins, cards and identities are missing, under All Items, Login, Cards, everywhere in the desktop app.

### Expected Result

Upon logging in with other accounts, a list of items (credentials) should appear.

### Actual Result

No items are listed, but icons still exist and search still filters for the expected credentials.

### Screenshots or Videos

https://i.imgur.com/EdgUkiw.png
https://i.imgur.com/9wR90bb.png
https://i.imgur.com/JWQbwq4.png

### Additional Context

Running latest version of Bitwarden (2022.9.0), but has been happening for a few weeks now. Have restarted the App and the Computer. Account works fine on Mobile app, all credentials are accessible. Other accounts work fine on affected PC. Have resynced vault successfully (many times) with no changes.

### Operating System

Windows

### Operating System Version

Version 21H2 (OS Build 22000.856)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.0

**Comment by vphan916** [comment]
Hi @AlexanderDignan. Thank you for getting in touch and bringing this to our attention!  We are unable to reproduce this.  We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
