### ISSUE TITLE
Chrome extension is unable to sync/save the username generation API keys (i.e. simplelogin)

### ISSUE THREAD

**Issue by bharatbots** [bitwarden/clients#3530]
### Steps To Reproduce

I just used a simplelogin API to generate email aliases through my chrome extension and it worked fine until i switched the device and tried doing the same. I got an error saying "Invalid API"

I'm wondering if it's a bug or feature. Afterall, what's the point of having such email integrations if you can't even retain the API keys? I was unable to generate usernames through simplelogin email-forwarding service on my 2nd device(also chrome ext). I'm thinking it's either a syncing issue or just a general application bug.

### Expected Result

It should retain the API key for simplelogin.

### Actual Result

When switching to another device, it asks for the API key again.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

104+

### Build Version

2022.9.0

**Comment by Larry-Sussman** [comment]
Hi @bharatbots, thanks for the report! We don't sync API keys across clients/devices. You can generate a new API key for your second device on this page: https://app.simplelogin.io/dashboard/api_key

![Screen Shot 2022-10-26 at 2 17 04 PM](https://user-images.githubusercontent.com/17710965/198140880-790ee2c2-74ac-48d2-b12d-a9a4041fd1d2.png)

I believe SimpleLogin intends for an API key to be unique to a device/application. On our side, the majority of other settings are client specific and stored locally. Since most of our other architecture doesn't store any of those client-side settings on the server, I believe this also true of the API keys used for our Username Generator.

I hope this helps, thanks!
