### ISSUE TITLE
Bitwarden CLI Throws TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by Daemonslayer2048** [bitwarden/clients#3564]
### Steps To Reproduce

This issue may be somewhat unique in the sense that the steps to reproduce are just to call the binary. Literally any call to the binary regardless of the flag passed in (including --version). 

I am assuming something is wrong with perhaps my stored user credentials but I have no idea where that file may be or what its nae may be so I am not sure how to investigate that part. 

### Expected Result

When running:  
``` zsh
❯ bw --version
```
I should get the version number

### Actual Result

```zsh
❯ bw --version
/snapshot/clients/apps/cli/build/bw.js:27266
            yield Promise.all(authenticatedUserIds.map((userId) => stateMigration_service_awaiter(this, void 0, void 0, function* () {
                                                   ^

TypeError: Cannot read properties of null (reading 'map')
    at StateMigrationService.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:27266:52)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/clients/apps/cli/build/bw.js:26888:58)


```

### Additional Context

I do not know what the previous version was that I downloaded so I made sure to download the newest version and the results are the same, I get the same error listed above.

### Operating System

Linux

### Operating System Version

Fedora 36

### Shell

Zsh

### Build Version

2022.9.0

**Comment by Daemonslayer2048** [comment]
Is anyone able to provide some insight on this?

**Comment by Daemonslayer2048** [comment]
Simply delete data.json

**Comment by sjfloat** [comment]
Thanks for the workaround!

But why was this closed? Apparently the data store was corrupted somehow.

**Comment by joshtrichards** [comment]
Not affiliated with BW, but saw this old issue. It looks like this was triggered in some code used to migrate from earlier (outdated) data storage versions. Specifically v2->v3 and v3->v4 (current version is v6):

* https://github.com/bitwarden/clients/blob/4f64ac87de912fe05bb5547eb8a85ebc7ff9f07b/libs/common/src/services/stateMigration.service.ts#L474
* https://github.com/bitwarden/clients/blob/4f64ac87de912fe05bb5547eb8a85ebc7ff9f07b/libs/common/src/services/stateMigration.service.ts#L495

Unfortunately it's challenging to dig into deeper without a copy of the `data.json` at the time in question (presumably redacted which admittedly would be more than a bit tedious to do). 

Looking at the code I'm curious whether you were authenticated at the time or not since that's one of the key ways (I think) the migration code could become unhappy.

I know it's been awhile, but any idea @Daemonslayer2048 (and/or @sjfloat) how long it had been since you'd logged in using that client installation from your report date? (alternatively: if by some stroke of luck you have the data.json in question still from that time period, does it have an activeUserId and userId field set?)

The good news is you can relatively safely and painlessly nuke the data.json when using the CLI. You can also temporarily override your existing data.json without removing it by running `bw` with an data directory overriding parameter like:
```
BITWARDENCLI_APPDATA_DIR=/home/username/.config/Bitwarden\ CLI\ TESTDELETE bw login user@domain.tld
 ```

(this'll log you in and generate a new data.json in the specified directory that is entirely independent of your existing one; note you'll need to specify the BITWARDENCLI_APPDATA_DIR with all follow-on invocations of `bw` that you want to have use that specific config data)

In any case, my guess is this would be a good issue to take up with tech support rather than as an issue here (at least until it's isolated further). Even if it is a bug, it would need some digging into your personalized configuration from the looks of it.
