### ISSUE TITLE
Password not being filled on 2nd password page after manually clicking and selecting autofill

### ISSUE THREAD

**Issue by silversword411** [bitwarden/clients#3573]
### Steps To Reproduce

1. Chromium based browser with bitwarden extension
2. goto gmail.com in incognito
3. Search bitwarden, find a google account and click autofill button in bitwarden
4. Click next button in web page
5. Previously when the password page came up, it would auto-fill the password from the identity you click the "autofill" button on on the previous page. Now you have to back up to the bitwarden, click, then click the same Login card for the site (that's now at the top). This is 2 extra, and unnecessary clicks that previously weren't there.

### Expected Result

When password page loads it should automatically fill password for previously autofilled Login 5 seconds earlier

### Actual Result

You have to manually click to get it to fill password.

### Additional Context

Something changed in the last 1-2 months so it's no longer auto-filling, previously would autofill

### Operating System

Windows

### Web Browser

Brave

### Build Version

2022.8.0

**Comment by alexpearce92** [comment]
I don't think Bitwarden can realistically do anything about that (not anything that isn't super hacky and undependable, at least). 

It sounds like Google is now separately loading the web form that has the password instead of just hiding it on the username form. If it was hidden, Bitwarden could fill it in because the textbox would already be there, just not visible. If its loaded separately, Bitwarden has no knowledge of where the password field is. 

Frankly, the password form could continue to be hidden and Google is clearing the field before showing it. Either way, this is an issue with Google, not Bitwarden.

Bitwarden's autofill could be adjusted to wait X seconds before filling in the password if a password is not filled in to give the user enough time to click "Next" on Google, but this is very prone to failure and will vary webpage to webpage.

A more appropriate fix may be to fix the browser extension's state, in that your search for "Google" in the extension would be preserved even after the extension menu closes. This would also resolve the other annoying problems with the extension, like unsaved changes being discarded if the extension closes, etc.

**Comment by daves003** [comment]
+1 to preserve the extensions state when the menu closes, that would be useful in other situations as well.

Another idea for a workaround:
Would it be possible for the extension to periodically check if the password field is present/visible and autofill once that happens? Up to a certain timeout of course (maybe around 5-10 seconds).

**Comment by silversword411** [comment]
> sounds like Google

I just used Google as an example since who doesn't have a google account to easily test. I've been trying to watch for other multi-page ID/pass ones to see if it's just google or something else. I wonder if bitwarden can tell...if it hasn't filled a password in yet, could it stay floating save a couple clicks/waits of reloading the list

**Comment by tangowithfoxtrot** [comment]
Hey, @silversword411. Thanks for reporting!

We have an issue [here](https://github.com/bitwarden/clients/issues/1621) for tracking various websites that have issues/don't work with our autofill. Please fill out the referenced Google Form to report this. That said, I recognize that Google's SSO form is one of the most commonly-used login forms, so I've also called this out in our internal communication channels.

As mentioned by @alexpearce92, some split login forms will expose the hidden password field in a way that our autofill can still interact with, some don't. If it turns out that Google's login for _does_ expose that, it's possible that we could account for it and autofill in a single step.

However, other split login form don't expose the hidden password field. For sites like that, I recommend using the [Ctrl/Command+Shift+L autofill shortcut](https://bitwarden.com/help/auto-fill-browser/#using-keyboard-shortcuts) twice -- once on the username page, and again on the password page -- to make the process a little more convenient than other autofill methods if you aren't doing that already.

Closing this for now, since this will be tracked in the aforementioned [GitHub issue](https://github.com/bitwarden/clients/issues/1621).
