### ISSUE TITLE
update changed password  creates a new login and dont have option to replace an existing

### ISSUE THREAD

**Issue by zefilipe** [bitwarden/clients#3602]
### Steps To Reproduce

1. Enter on a website, and change password
2. It shows a top bar to update
3. Click in update button

### Expected Result

Its expected that shows a option to create new login (current) or replace a existing login

### Actual Result

It only create a new login, having two logins for somme website

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

1004.0.2

### Build Version

2022.8.0

**Comment by aj-bw** [comment]
Hi @zefilipe ,

Thanks for reaching out! After testing on the current version of the Firefox browser extension ( 2022.10.1 ) in Windows, I am not experiencing the issue you are describing.

I recommend updating your browser extension and testing again to see if the issue continues. If it does, we still want to help. Feel free to contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
