### ISSUE TITLE
CLI export does not save folders

### ISSUE THREAD

**Issue by dh024** [bitwarden/clients#3615]
### Steps To Reproduce

1. Execute `bw export --format <any_valid_format>`
2. Inspect the outputted export file. Folder information for vault items is not saved in the export file.

### Expected Result

The output files from the CLI, regardless of format, should save folder information, just like exports created using the BW web vault.

### Actual Result

Folder information is absent in the CLI export files.

### Additional Context

Reported on BW community forums here:
https://community.bitwarden.com/t/bitwarden-cli-export-function-does-not-include-folder-names-and-ids/44936/2

### Operating System

macOS

### Operating System Version

MacOS Monterey 12.6

### Shell

Zsh

### Build Version

2022.9.0

**Comment by dh024** [comment]
May be related to:
https://github.com/bitwarden/clients/issues/3555

**Comment by dh024** [comment]
Appears to be fixed now in release 2022.10.0. Thanks.

**Comment by oeloo** [comment]
It is still NOT fixed in release 2022.10.0
Here is what you currently get with release 2022.10.0 :
![image](https://user-images.githubusercontent.com/98819304/196113040-ffd2dfed-3f2c-42f8-84ff-e8d36f9ea189.png)
This a serious bug.
Furthermore, how is it possible that 2 export interface give 2 different export ? It looks like this CLI exporting method is different from the website exporting method function 🤔

**Comment by dh024** [comment]
It appears this may be an inconsistent behaviour, and users are reporting they are still encountering the bug. Re-opened.
