### ISSUE TITLE
Sync from mobile to Desktop app not working

### ISSUE THREAD

**Issue by chadeldridge123** [bitwarden/clients#3620]
### Steps To Reproduce

1. Change password on the mobile app
2. Save password and then sync the mobile app 
4. Go to desktop application and run a sync
5. Password on Desktop is not the same as the correct password on mobile.

### Expected Result

Passwords should sync across platforms 

### Actual Result

Password is correct on mobile, incorrect on desktop even after a manual sync 

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.1

**Comment by alexpearce92** [comment]
Can you check the web portal to confirm that the mobile device synced the change to the server as expected?

**Comment by Larry-Sussman** [comment]
Hi @chadeldridge123, I'm unable to reproduce this issue on my end using our latest mobile and desktop apps. 
Are you still experiencing this issue? If so, this may be better handled by our dedicated Customer Success team.

Please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content for help in troubleshooting. 

The issue here will be closed, thank you!
