### ISSUE TITLE
[brew installation] Error while enabling browser integration.

### ISSUE THREAD

**Issue by iamtodor** [bitwarden/clients#3637]
### Steps To Reproduce

1. Install it with `brew install bitwarden`.
2. Open its preferences, click on `Allow browser integration`
3. Observe the issue

### Expected Result

Integrate it with browserthe 

### Actual Result

Browser integration not supported
Unfortunately browser integration is only supported in the Mac App Store version for now.

### Screenshots or Videos

<img width="320" alt="Screenshot 2022-09-28 at 10 15 43" src="https://user-images.githubusercontent.com/12586108/192726632-52f12e8e-5b9c-4b57-b7f7-2bfec7c07125.png">

### Additional Context

I saw this https://github.com/bitwarden/desktop/issues/665 issue, but it's in an archived repo; I didn't find the actual report in this repo

### Operating System

macOS

### Operating System Version

12.6 (21G115)

### Installation method

Homebrew

### Build Version

Version 2022.9.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

**Comment by Hinton** [comment]
This is a limitation on MacOS. Enabling the native integration on non MAS releases causes our helper process to get a unique random ID each time which GateKeeper blocks. This required the user to disable GateKeeper which is unfortunately not appropriate. We will continue to explore if there are ways around this but until that point we cannot support it in the other versions.

**Comment by iamtodor** [comment]
@Hinton thank you for the reply!
I did specify disable GateKeeper by env var `export HOMEBREW_CASK_OPTS="--no-quarantine"`, but still the same.

Anyway, I see your point, I don't think it's a crucial thing as I am still able to install Bitward thru AppStore and be able to you all the features. 

Please, just leave this issue open for the sake of transparency and visibility, alright?

**Comment by Larry-Sussman** [comment]
Your issue appears to be describing the expected behavior of the software (non-MAS builds [will not](https://github.com/bitwarden/desktop/issues/665#issuecomment-766991658) support browser integration). If you want this to be changed, it would be a feature request. 

We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com/) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

This issue will now be closed. Although it will be marked as closed, it will still be available for comments and updates, and you can link to it from your feature request in the forum. Thanks!

**Comment by alana-glitch** [comment]
I have opened a feature request: https://community.bitwarden.com/t/support-browser-unlock-with-biometrics-for-homebrew-installs/58295

If those who find this issue would like this feature, please consider voting for it.

**Comment by AuthorProxy** [comment]
any news? if this is not an apple requirment why this difference even exists?
