### ISSUE TITLE
Login entry favicon not displayed, for example URI https://camelcamelcamel.com

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#3639]
### Steps To Reproduce

1. In a web browser, login to your Bitwarden account
2. Create an Login entry for the website camelcamelcame.com with the URI: https://camelcamelcamel.com
![image](https://user-images.githubusercontent.com/98819304/192749994-b59dcf19-8075-41eb-b460-8bbfff8c6b0d.png)
4. Save this new Login entry
5. Go to your Login list (with the web browser, or your Windows BW app, or your Android BW app)

### Expected Result

The URI https://camelcamelcamel.com has a favicon :
![image](https://user-images.githubusercontent.com/98819304/192750177-dfc0a054-ebc4-4901-a7b2-291cdfac6e78.png)

### Actual Result

Bitwarden does not show the favicon of https://camelcamelcamel.com :
![image](https://user-images.githubusercontent.com/98819304/192749428-43c4210c-acd7-489e-9777-d6b3eb46afa7.png)

### Operating System

Windows

### Operating System Version

Windows 11 latest version 

### Web Browser

Chrome

### Browser Version

Chrome latest version 

### Build Version

BW latest version

**Comment by oeloo** [comment]
I have found that every Bitwarden icons are constructed like this:
https://icons.bitwarden.net/<domain with subdomain>/icon.png

This gives for 1st URI
- https://camelcamelcamel.com/ : **[](https://icons.bitwarden.net/camelcamelcamel.com/icon.png)**
- https://www.zara.com/ : **[](https://icons.bitwarden.net/www.zara.com/icon.png)**
- https://www.trbinance.com/ : **[](https://icons.bitwarden.net/www.trbinance.com/icon.png)**
- https://www.similarweb.com/ : **[](https://icons.bitwarden.net/www.similarweb.com/icon.png)**
- https://store.epicgames.com/en-US/ : **[](https://icons.bitwarden.net/store.epicgames.com/icon.png)**

None of them works. Bitwarden Team, can you please regenerate all you icon list ? (really all, as I can provide at least 10 other domain names with no valide Bitwarden icon.png)

**Comment by Larry-Sussman** [comment]
Hi @oeloo, thanks for the report! 

We checked the [camelcamelcamel.com](http://camelcamelcamel.com/) icon from your first example using https://icons.duckduckgo.com/ip3/camelcamelcamel.com.ico and see that they also fail to retrieve the favicon for the site. This seems to be the same issue as #2786, camelcamelcamel is using strict request filtering that prevents our cloud servers from fetching the favicon.

As mentioned in: https://github.com/bitwarden/clients/issues/2786#issuecomment-1147904524, all those affected websites may be using a configuration that prevents/forbids Bitwarden's cloud Icon service from retrieving the favicon. Unfortunately, this is out of Bitwarden's control and can't be fixed on the server where Icons are currently handled.

I believe we’d have to move the icon fetching service client-side in order to avoid this, which would be a feature request in this case. 
The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
