### ISSUE TITLE
Firefox extension not supporting Folders.

### ISSUE THREAD

**Issue by JSebMe** [bitwarden/clients#3666]
### Steps To Reproduce

1. install Bitwarden Firefox extension
2. Log into an existing vault that have some folders into it
3. Try to scroll down to show folders and open one to show its content (folders section is not existing)
4. Open any login that is supposed to be placed in a folder
5. Click the button to make modifications on the login
6. Scroll down to show the scroll-down list where it's possible to choose the folder the user want to place the login (the list show nothing)
7. Got to the settings section in the extension
8. Go to Folders (even with folders in the vault, the section shows nothing)

### Expected Result

Having folders appearing in any of those places and the features normally doable with folders

### Actual Result

Folders support is totally down

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2 version 22621.521

### Web Browser

Firefox

### Browser Version

Firefox for Windows 64 bits

### Build Version

105.0.1

**Comment by rlaveycal** [comment]
NB: If you add a folder then you get an error about dead items not being supported and the folder list then populates. The new folder is created.

**Comment by AndrewOnGitHub** [comment]
Please fix this ASAP! I can't believe something like a dropdown menu would fail in 2023.

I also [posted on Reddit](038833) about this where there is a screenshot of the bug happening.

**Comment by Camusensei** [comment]
I don't understand.
I can see the folder when I browse the vault in the extension.

@AndrewOnGitHub you should change the tone of your message. This is not a service you pay for, this is something people give their free time to. Also, your link is still broken.

My system:
OS Ubuntu 22.04.2 LTS
Firefox version 109.0 (64-bit)
Extension version: 2023.1.0

**Comment by rlaveycal** [comment]
I can confirm that it's also working for me (Win64 / FF 110, Extension 2023.1 / backend 2023.2)

**Comment by AndrewOnGitHub** [comment]
> I don't understand. I can see the folders when I browse the vault in the extension: https://i.imgur.com/C0irfTC.png

I'm not sure what the point of this is. It may work for you and sometimes it works for me. The Reddit thread (link fixed) shows it both working and not working. Obviously, it is not 100% reliable. That's why there are threads about it on both Reddit and GitHub.


> @AndrewOnGitHub you should change the tone of your message. This is not a service you pay for, this is something people give their free time to.

I agree with this when discussing a free or non-profit or fully open source situation or some bug in a trivial online game. But Bitwarden is mostly the opposite of that. I believe that Bitwarden is not 100% open source. Bitwarden is a for-profit company. Bitwarden clearly goes out of their way to give the impression of trustworthy software, which, if inaccurate, could lead to vast damage. In cases that impression turns out false on very basic elements - such as folders and a dropdown menu - even freemium users have reason to be upset.

I am new to Bitwarden so don't really know if this is the tip of the iceberg in bugginess or not... But I had a horrible experience with it a couple of days ago where I successfully signed into the browser extension which then proceeded to tell me I had *nothing* in it. I'll try to a bug report when that happens.

In your experience, how buggy has Bitwarden been? And do bugs like this tend to last or do they get fixed?

**Comment by JSebMe** [comment]
This bug that I reported a while ago isn't relevant for me now... I don't know what has changed since I opened this ticket, but the addon is now behaving correctly.

**Comment by Camusensei** [comment]
> I'm not sure what the point of this is.
Discussing, clarifying, sharing specs, trying to narrow down the cause of the problem is the point of this. This is what this chat within the ticket is for.

> even freemium users have reason to be upset.
While it is true, I think it's counterproductive to show it the way you were. But you can continue doing as you please, consider it just as me voicing my opinion. And you're free to assume that I am the only one in the world thinking like this if you want.

> In your experience, how buggy has Bitwarden been? And do bugs like this tend to last or do they get fixed?
There was this bug (no folders in Firefox) which has been fixed months ago, and another one (delay before focus on extension password prompt) which was fixed within a month.

I never suffered any other bug, and both the ones I suffered took in my view a really short time to be fixed.
I am however patently waiting for some new features I voted for.

Camusensei
