### ISSUE TITLE
bw {list, export} outputs "mac required." before expected result

### ISSUE THREAD

**Issue by Aidenwebb** [bitwarden/clients#3674]
### Steps To Reproduce

1. Log in to Bitwarden CLI - `bw login`
3. Set Session token - `$env:BW_SESSIION="<sessiontoken>"`
4. Unlock vault - `bw unlock`
5. Set Session token - `$env:BW_SESSIION="<newsessiontoken>"`
6. Export Vault `bw export --output c:/temp/bwexport/20221003.json --format encrypted_json --password <password>

### Expected Result

    Saved c:\temp\bwexport\20221003.json

### Actual Result

    mac required.
    mac required.
    mac required.
    mac required.
    Saved c:\temp\bwexport\20221003.json

### Operating System

Windows

### Operating System Version

11

### Shell

PowerShell

### Build Version

2022.9.0

**Comment by natoleet** [comment]
Can confirm the same thing happens when using command `bw get password <name>`

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue in version 2023.7.0 and was unable to do so. 

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!
