### ISSUE TITLE
otp wrongly generated on window 11

### ISSUE THREAD

**Issue by theogfx** [bitwarden/clients#3722]
### Steps To Reproduce

None, observe any generated OTP in the desktop app.

### Expected Result

Correct OTP generated in desktop app.

### Actual Result

All OTP in the desktop app are incorrect. Time is in sync between my other devices and the desktop app which is problematic, same time zone also.

On mobile (android & ios), on macosx, and on Windows 10, I have no issue at all.

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com), Chocolatey

### Build Version

Version 2022.9.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

**Comment by jivanpal** [comment]
I'm not a developer on this app, but I would hazard a guess that this is due to the way Windows handles time using the RTC (real-time clock / BIOS/UEFI clock); it prefers to set it to local time rather than UTC. Could you try changing your timezone in Windows to UTC, check that the BIOS/UEFI clock is then set to UTC time (or set it to that if it isn't), and then try generating codes again?

**Comment by Hinton** [comment]
The random component of a TOTP is time. If multiple devices show different values that usually means one of the devices are out of sync with the rest.

Can you verify your computer has "set the time automatically" enabled, and that the timezone is correct?

![image](https://user-images.githubusercontent.com/137855/196219373-ed3f1e49-7fc7-45ac-8a31-e716dbf14aec.png)

**Comment by Wolfhound905** [comment]
Thank you. I didn't notice my clock was 1 minute off.

**Comment by theogfx** [comment]
Hi, yes, I've checked that both ("set time automatically" and the correct timezone). Nevertheless, since the last update, the problem is no longer present. Maybe the system time was a bit off when I encountered the problem.

**Comment by NPittinger** [comment]
Just wanted to drop a note for anyone who finds this later.

I had the same problem with both of my Windows 11 computers after upgrading to version 22H2.  I fixed the problem by telling Windows to use UTC time instead of local time for the hardware clock.

1. Open `regedit` and navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation`.
2. Create a new QWORD Value titled `RealTimeIsUniversal` and set its value to `1.`
3. Restart your computer.
4. Set the clock.  The easiest way is to navigate to `Time and date settings` and toggling `Set time automatically` off and back on.  Use the opportunity to ensure the correct time zone is set as well.

For those not comfortable with opening `regedit`, I have attached a file that sets the value listed above.  You'll just have to remove the .txt extension before running it.  I hope someone finds this helpful.

[set-hw-time-to-utc.reg.txt](https://github.com/bitwarden/clients/files/10160290/set-hw-time-to-utc.reg.txt)
