### ISSUE TITLE
Not receiving 2FA email with code

### ISSUE THREAD

**Issue by jacobschellenberg** [bitwarden/clients#3752]
### Steps To Reproduce

1. Go to Bitwarden on any client
2. Enter username and password
3. Notice screen that shows 2FA email was sent
4. Notice no email is received
5. Click "Send verification code email again"
6. Notice no email is received still.

I updated my password and am now completely locked out of my account because I am not receiving the 2FA email code. I am using a @icloud.com address. I have submitted a support ticket but am worried that I will not receive their emails either. I clearly am able to receive emails from other sources.

When using a Recovery Code, the website displays the error: "Invalid Information. Try Again". The Chrome Network tab message says: "The Model state is invalid."

Please assist. Urgent. I am locked out of my account.

### Expected Result

I expect to receive the 2FA email with code.

### Actual Result

I do not receive a 2FA email code.

### Additional Context

I have tried logging in from multiple different browsers, extensions, 3 different mobile devices. All of them say an email was sent, yet I do not receive an email.

### Operating System

Windows, Linux, iOS

### Web Browser

Chrome, Safari, Firefox

### Build Version

2022.9.2

**Comment by TroyBW** [comment]
Hi @jacobschellenberg. This is Troy from Bitwarden Customer Support. We have received your support ticket and we are currently looking into the issue. Your assumption is correct - I did try to email you, but the email was undeliverable. Please hang tight as we investigate further. Thanks for your patience!

**Comment by jacobschellenberg** [comment]
> Hi @jacobschellenberg. This is Troy from Bitwarden Customer Support. We have received your support ticket and we are currently looking into the issue. Your assumption is correct - I did try to email you, but the email was undeliverable. Please hang tight as we investigate further. Thanks for your patience!

I have regained access to my account. I was forwarding email from my @icloud account to another account, but for some reason iCloud was not forwarding specifically the bitwarden email, but it does forward other emails. 

I did not realize the email was being completely eaten by iCloud, I thought Bitwarden was just not sending the 2FA email.

I only realized this because I turned off "Delete Forwarded Emails" from my Apple Mail and saw that Bitwarden emails started coming through without being auto deleted after being "forwarded". 

So now I'm seeing the bitwarden emails, but they are definitely not being forwarded by iCloud.

**Comment by TroyBW** [comment]
Hi @jacobschellenberg. I just tried to email you once more, but I'm not sure if it went through.

The bounces we received were categorized as "transient," meaning:
_General: The recipient's email provider sent a general transient bounce. This typically happens when the recipient has set up an "out of the office" automatic reply. This type of soft bounce generally fixes itself. If the bounce was a result of an "out of the office" reply, then the soft bounce resolves itself after the automatic reply is removed by the recipient._

Other causes for transient bounces could be:
The recipient mailbox is full.
The recipient mailbox is temporarily unavailable.
The server limits are exceeded.
The server is overloaded.

Hope this is information is helpful.

**Comment by jacobschellenberg** [comment]
> 

I have now disabled "Delete After Forwarding". Please send another email to see if it comes through.
