### ISSUE TITLE
Browser extension no longer working in Firefox 68

### ISSUE THREAD

**Issue by blackwind** [bitwarden/clients#3829]
### Steps To Reproduce

1. Install Firefox 68 on PC or Android
2. Install the Bitwarden extension
3. Click the extension's button

### Expected Result

The Bitwarden extension should load

### Actual Result

The loading spinner spins indefinitely

### Additional Context

Until v2022.9.1, you guys seem to have been on top of this. Every so often, a new version of the extension wouldn't load in Firefox 68, but a few days later, a hotfix would be released and all was well again. No such hotfix was released for v2022.9.1, and the problem persists in v2022.10.0. Currently, v2022.8.0 is the last working version.

Issue occurs on both PC and Android.

### Operating System

Windows

### Operating System Version

Windows 10 x64 21H2

### Web Browser

Firefox

### Browser Version

68

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
This is possibly related to https://github.com/bitwarden/clients/issues/3501.

Firefox 68 was first released July 2019, that's over 3 years ago. The ESR edition last revived updates a year after that, which is more than 2 years ago. Since then Firefox has released three new major versions of Firefox ESR and I would recommend upgrading to them, since using a very out of date browser version is a security risk.

While we strive to not intentionally break backwards compatibility, we also don't have the resources to test all possible combinations of browsers nor to support browsers indefinitely. We would probably accept community PRs that resolve this assuming the impact of the code is minimal.

**Comment by SylwesterZarebski** [comment]
Problem is that extension **reports** that it **supports old version**, thus it is a bug. You should never report invalid data.

**Comment by goonis** [comment]
I have Firefox 55.0.3 64bit (can't update for some reason) and have the same problem, last working  version is 2022.8.0, please update the Firefox extension or remove (_Works with firefox 42.0 and later, android 48.0 and later_) from extension description.

**Comment by justindbaur** [comment]
Hi all, I've opened a PR that will bump our minimum version so Firefox won't update your extension automatically. But this will mean you will eventually be using an unsupported version of our browser extension. Our recommendation would be updating to a supported version of Firefox but I apologize for the inconvenience if that is not possible for some of you.
