### ISSUE TITLE
Unable to login to etrade app on Android (not browser)

### ISSUE THREAD

**Issue by swamp2** [bitwarden/clients#3844]
### Steps To Reproduce

App does not trigger autofill nor option to memorize. Android 13 with latest etrade mobile app.

### Expected Result

Trigger autofill and option to memorize.

### Actual Result

Nothing from Bitwarden.

### Operating System

Android

### Operating System Version

13

### Web Browser

Chrome

### Browser Version

N/A

### Build Version

2022.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Larry-Sussman** [comment]
Hi @swamp2, thanks for the report! 

We use GitHub issues as a place to track bugs and other development related issues. It sounds like the app URI needs to be added to your login item, or auto-fill isn't working as expected. Further troubleshooting would likely be better handled by our dedicated Customer Success team. 

Please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). Two articles we'd recommend are:
- https://bitwarden.com/help/auto-fill-android/
- https://community.bitwarden.com/t/how-do-i-find-the-uri-for-an-android-app/37424

The issue here will be closed, thank you!
