### ISSUE TITLE
Bad error message when no internet

### ISSUE THREAD

**Issue by Inspirateur** [bitwarden/clients#3869]
### Steps To Reproduce

Idk if this will be enough to reproduce but:
1. Be connected to a network that doesn't grant you internet access (enterprise network in my case)
2. Try to save a new password

### Expected Result

An error prompt telling me that the password couldn't be saved because I have no internet connection

### Actual Result

The following error message
```Unexpected error:
Unexpected token '<', "<html> <s"... is not valid JSON
```

### Screenshots or Videos

Sorry for the poor pic quality

![20221021_093927](https://user-images.githubusercontent.com/22746898/197142348-0001b177-e585-45c2-a0a6-247d47a19e32.jpg)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

106.0.5249.119 (64 bits)

### Build Version

Version: 2022.10.1 Server version: 2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. From my tests in multiple environments, you should now receive a _failed to fetch_ error message when you have no internet connection.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
