### ISSUE TITLE
Vendor.js is not being appropriately created - Docker Image - On Prem

### ISSUE THREAD

**Issue by aconite33** [bitwarden/clients#3884]
### Steps To Reproduce

Download the setup file for the docker
Execute the script to install and start up the docker images.
Verify that once the install is complete, the vendorXXX.js file is missing
Confirm that you cannot log into the Bitwarden portal due to the 404.

### Expected Result

You should be able to get the login prompt on the website.

### Actual Result

A 404 happens and you end up with a endless circle loading screen.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/3675886/197583888-8f5af0e2-6b4c-45a7-b29e-a90b4e7eb844.png)

### Additional Context

This can be remediated by download the vendor javascript file from: https://vault.bitwarden.com/app/vendor.XXX.js and putting it into the docker file under /app/app file:

`docker cp vendorXXX.js {GUIDofDocker}:/app/app/`

This is same bug as reported here: https://github.com/bitwarden/web/issues/1543

I did try the `rebuild` option on the bash script, however this did not fix my issue.

### Operating System

Linux

### Operating System Version

Ubuntu 20.04

### Web Browser

Chrome

### Browser Version

Latest

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
