### ISSUE TITLE
Firefox browser extention on MacOS has error can't access dead object

### ISSUE THREAD

**Issue by dvmada** [bitwarden/clients#3918]
### Steps To Reproduce

1. on firefox, connect to your website bitwarden account
2. navigate a little until automatic lock extention occured
3. try to unlock your account in extention window

### Expected Result

have to connect to my account and display my vault in this windows

### Actual Result

display a notification error 'error can't access dead object'

### Additional Context

We have a selfhosted bitwarden server, v1.21

### Operating System

macOS

### Operating System Version

12.6

### Web Browser

Firefox

### Browser Version

106

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think this issue may have already been resolved or could be resolved by updating your instance and Bitwarden client.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
