### ISSUE TITLE
I have to click twice to copy username ans password. I am using Firefox.

### ISSUE THREAD

**Issue by Hekendorp** [bitwarden/clients#4022]
### Steps To Reproduce

4. Click on '...'
click on copy username ams paassword

### Expected Result

First click paste does work again.

### Actual Result

Now first click past does not work.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

106.0.5 64 bits

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
