### ISSUE TITLE
Edge and Firefox extensions cannot display password pop-up windows normally

### ISSUE THREAD

**Issue by Gitguygogogo** [bitwarden/clients#4043]
### Steps To Reproduce

add login and  Ask to change existing login  options in more formal websites such as "warframe.com" and "twitter.com"

### Expected Result

showing the pop-up correctly. 

### Actual Result

I've turned on the "Ask to add login" and "Ask to change existing login" options for the browser extension, but neither browser is showing the pop-up correctly. The browser and plug-ins are the latest version, other plug-ins and scripts have been disabled, and the browser password function has been disabled. The websites used include more formal websites such as "warframe.com" and "twitter.com", but none of the websites can display the above two pop-up windows normally. Both of the above functions worked fine when I used the browser's own password function, but Bitwarden was very puzzled that Bitwarden could not use, and I can only use it by manual editing at the moment.

### Operating System

Windows

### Operating System Version

win11 home 22621.819

### Web Browser

Firefox

### Browser Version

106.0.5

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Gitguygogogo and thank you for your report.

Would you be able to add some screenshots? From your description, it is currently slightly unclear what exactly the issue is.

I have a suspicion it might have to do with the browser modifying the reported screen size to resist fingerprinting. This technique has also recently been activated in Brave. 

Linking to https://github.com/bitwarden/clients/issues/1451 and https://github.com/bitwarden/clients/issues/3970

**Comment by djsmith85** [comment]
@Gitguygogogo The provided screenshot only shows the expected behavior, but not what you mean by: 

> When I operate on the form, the pop-up window as shown in the figure **does not appear normally**.

Could you please upload a screenshot displaying the issue? 

Thank you for providing the additional information about the other extensions used. There is a high likelihood that one of the extensions is causing this, but without any information what the actual issue is, no further investigation can be done.
