### ISSUE TITLE
"Invalid PIN" error after login

### ISSUE THREAD

**Issue by matteovidotto** [bitwarden/clients#4055]
### Steps To Reproduce

1. Open Desktop APP (macOS)
2. Login
3. Wait until session expired (do not kill App; Es: Lock computer and unlock after few time)
4. Login again

### Expected Result

Login succesfull

### Actual Result

![Screenshot 2022-11-17 at 13 35 41](https://user-images.githubusercontent.com/3437229/202485396-63abf5a4-c3dc-4f9a-8a66-55823c45cbe7.png)

Invalid PIN

- the password is correct
- if you copy password, kill Desktop APP and login (paste copied password) -> Login succesfull

### Operating System

macOS

### Operating System Version

macOS Monterey 12.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.1 (5129)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by matteovidotto** [comment]
Added useful screenshot to issue description

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. If you are still encountering this issue, please try restarting your device, and trying again to see if that helps.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
