### ISSUE TITLE
Auto-fill: Custom field not honoured when on https://www.spotify.com

### ISSUE THREAD

**Issue by DavidPesticcio** [bitwarden/clients#4120]
### Steps To Reproduce

1. Visit [https://www.spotify.com](https://www.spotify.com/)
   which redirects to [https://open.spotify.com/](https://open.spotify.com/)
2. Click the "Log in" button top right.
   which redirects to [https://accounts.spotify.com/en/login?continue=https%3A%2F%2Fopen.spotify.com%2F](https://accounts.spotify.com/en/login?continue=https%3A%2F%2Fopen.spotify.com%2F)
3. Right-click the checkbox for "Remember Me"
4. Select "Bitwarden | Copy Custom Field Name"
   which should equal `login-remember`
5. Modify existing login or create a new one to add a custom field accordingly.
6. Save and exit Bitwarden
7. Proceed to fill login details either with mouse or `CTRL+SHIFT+L`

### Expected Result

Username, password, and checkbox should be set accoring to login details held in Bitwarden.

### Actual Result

Username and password field auto-fills, but checkbox is left unchanged (regardless of current state)

### Operating System

Linux

### Operating System Version

Linux redacted 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Web Browser

Chrome

### Browser Version

Version 106.0.5249.119 (Official Build) for Linux Mint (64-bit)

### Build Version

Version: 2022.10.1 / Server version: 2022.10.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Lurikbolding** [comment]
Hello
 I have the same issue.
 Windows 10 + firefox 112.0.1
 plugin firefox Bitward 2023.3.1 (self hosted)

I test the 2 value of the boolean custom field : the "remember me" button will stay not checked

**Comment by atjbramley** [comment]
Hi @DavidPesticcio !

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

    mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

    browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by DavidPesticcio** [comment]
@atjbramley - how can I track the progress of this issue?

**Comment by atjbramley** [comment]
@DavidPesticcio,

Regarding autofill issues specifically, due to the nature of the requests being large in volume and everchanging based on third-party website updates, we track each of these internally. 

Once the reported autofill issue has been corrected, it will be made available in the following release. We will work to get a fix out as soon as possible - thank you for your patience.
