### ISSUE TITLE
Duplicates when importing chrome exported passwords

### ISSUE THREAD

**Issue by tathastu871** [bitwarden/clients#4130]
### Steps To Reproduce

Export passwords from chrome 
Import it to vault
Every week i export my chrome passwords and import to bit vault
But bitwarden doesnt remove duplicate results i had to manyally remove 100s of duplicates 

### Expected Result

Unique filtered duplicated

### Actual Result

duplicated results

### Operating System

Android

### Operating System Version

10

### Device

samsung

### Build Version

latest

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Moved to `clients` as import is only supported from the web-vault or cli.

**Comment by djsmith85** [comment]
Hi @tathastu871 and thank you for your report.

This is expected behaviour, as described on our [help site article](https://bitwarden.com/help/import-from-chrome/#import-to-bitwarden) related to importing from Chrome.

> ⚠️ Warning
Importing does not check whether items in the file to import already exist in your vault. If you import multiple files or import files with items already in your vault, this will create duplicates.
