### ISSUE TITLE
Chrome Web - Copying from a hidden file while in Edit Mode does not work

### ISSUE THREAD

**Issue by JaPossert** [bitwarden/clients#4133]
### Steps To Reproduce

Open bitwarden in google chrome
open a password file
Click on 'view'
Click on "edit"
Hidden password does not copy, not even the dots that it copies when in view mode that are not visible.

### Expected Result

I would expect to either see a string of dots as I do when the password is hidden in view mode
or, that is my preference, to copy the password while it is hideen (as occurs when just clicking on the password button when seeing a password file.
It would be ideal to have an (advanced) setting where one can choose if one just copies a string of dots or the actual password (this could be the default for easier onboarding of users).

### Actual Result

no copying occurs at all

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
