### ISSUE TITLE
Address record confusion

### ISSUE THREAD

**Issue by Tosslog-admin** [bitwarden/clients#4178]
### Steps To Reproduce

A: 192.168.2.99:7777 PWD: 123123
B: 192.168.2.99:6666 PWD: 321321
The above two addresses will be considered as the same website The password given is incorrect

### Expected Result

Can distinguish the address + port in detail and give the corresponding password

### Actual Result

A: 192.168.2.99:7777 PWD: 123123
B: 192.168.2.99:6666 PWD: 321321

### Operating System

Windows

### Web Browser

Microsoft Edge

### Build Version

2022.10.01  1.26.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Tosslog-admin,

the reason for this behaviour is likely, because the default match detection uses domain, which would be in your case `192.168.2.99`. 

Please try switching to use `host` as the match detection for those two 2 entries.

Further information can be found on our help-site [article](https://bitwarden.com/help/uri-match-detection/#host).

Closing this now.
