### ISSUE TITLE
Copy+Pasting Password Upon Creation Results in Needing to Copy+Paste for Password to be Correct

### ISSUE THREAD

**Issue by phalcr004** [bitwarden/clients#4180]
### Steps To Reproduce

1. Go to change master password on Bitwarden site
2. Type out new password in a .txt document
3. Type old master password in field on site
4. Copy and paste password form .txt document into new password field
5. Go to log in, typing the password exactly as written in the .txt document
6. Error: "username or password is incorrect".
7. Copy + paste password from .txt document over top of hand-written password
8. Successful log-in

### Expected Result

I expected to be able to log in by typing my password by hand.

### Actual Result

Copying and pasting the password from the .txt document correctly logs in, while hand-writing the password produces a failure. The same behaviour occurs in the extension. On Android, I was not able to log in at all, as typing by hand or copying and pasting does not work. When pasting directly over the hand-typed password, you can clearly see that all the visible characters are correct.

### Additional Context

I reset my password by copying and pasting from the .txt document for the old password and hand-typing the same password for the new password. There seems to be something not visible in the characters copied from the .txt document that causes the system to treat the password as distinct from the hand-written version. No spaces were copied from the text document, but perhaps a newline character is somehow being copied. The text document I copied from contains text on the line directly below it. I have not tested what happens if the text document ends directly after the password. Trying to manually enter a newline character into the password entry did not work, however. I have not tested this with other apps (e.g. word, excel), as I do not want to keep resetting my password. Password was always copied and pasted using ctrl c + ctrl v - have not testing right click + copy and right click + paste.

### Operating System

Windows, Android

### Operating System Version

Windows 10 version 22H2 (OS Build 19045.2251), Android 12

### Web Browser

Firefox

### Browser Version

107.0.1

### Build Version

2022.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could be unseen spaces in your .txt document, but it is hard to say for sure.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
