### ISSUE TITLE
Cycle through logins is getting stuck in a loop, repeating some and skipping others

### ISSUE THREAD

**Issue by luckman212** [bitwarden/clients#4201]
### Steps To Reproduce

# Problem

1. Go to a website that has multiple logins saved

example (microsoft.com): 

<img src=https://user-images.githubusercontent.com/1992842/206576228-01f7726a-5b27-4be1-8951-6c0a5ec180fa.png width=350>

2. Use your _"Auto-fill the last used login for the current website"_ hotkey to repeatedly cycle through the logins
3. Note that there is no rhyme or reason to the sequence.

- it is not alphabetical by Name
- it is not alphabetical by Username
- it does not appear to be based on "order saved in the vault"
- it is not "cycle through logins in vault A, then proceed to vault B, C..." etc

Often (for me anyway) it appears to get stuck cycling between the same 6-7 logins and omits entirely the other 30+.

Sometimes, when pressing the hotkey, it just fills in the exact same login that was previously filled.

Very frustrating feature!

# My suggestion

The feature should work like this:

- Pressing the hotkey auto fills the LAST USED login for that site.
- If the hotkey is pressed AGAIN, then index all the logins alphabetically A-Z by NAME OF THE BOOKMARK and begin cycling from the first one.
- There should really be a hotkey for cycle BACKWARDS in case we press the key quickly and go 1 or 2 too far, instead of needing to reach for the mouse...
- There should be a checkbox/preference something like
    - [x] Omit Logins From Shared Vaults from auto-filling via hotkey

### Expected Result

Cycling through logins should be deterministic.

### Actual Result

???

### Screenshots or Videos

If the developers want a video of this happening, I am happy to submit one privately, but due to the sensitive nature of the content I can't post it here.

### Additional Context

Related (when the cycle feature was added): https://github.com/bitwarden/clients/pull/956

Similar bugreport: https://github.com/bitwarden/clients/issues/1392

### Operating System

macOS

### Operating System Version

13.0.1

### Web Browser

Chrome

### Browser Version

108.0.5359.98

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luckman212** [comment]
Has anyone looked at this or considered the points I outlined in it?

This continues to be the most frustrating thing about Bitwarden that I bump into Every. Single. Day.

**Comment by dwbit** [comment]
Thanks for sharing an update, can you confirm what version number you are currently running?

**Comment by TroyBW** [comment]
Hi there,

When cycling through login items, the order is determined chronologically, by the last time the item was used. This ordered list can be visualized by clicking on the Bitwarden browser extension and looking at the "Tab" view, as the items are ordered in the same manner there.

We use GitHub issues as a place to track bugs and other development related issues. If you'd like to submit a feature request for the list of autofill items to be ordered alphabetically, the Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
