### ISSUE TITLE
Certain Note Contents Not Loading

### ISSUE THREAD

**Issue by c1-jack** [bitwarden/clients#4224]
### Steps To Reproduce

1. Click on the folder containing the notes
2. Click directly on one of the notes in question

### Expected Result

The note and it's contents will load.

### Actual Result

The note and it's name loads, but all other fields are blank.

### Screenshots or Videos

<img width="644" alt="Screenshot 2022-12-14 at 1 46 32 pm" src="https://user-images.githubusercontent.com/105686239/207493005-08a8fc5e-0eef-4f96-8cd0-652a69e867fc.png">

### Additional Context

Clicking on an unaffected note in the same folder first, then clicking on the notes in question loads them normally.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Have you tried performing clean reinstall of the app?

**Comment by atjbramley** [comment]
Hi @c1-jack, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a networking glitch - try logging out and back into the vault.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
