### ISSUE TITLE
Cannot close the remember password popup

### ISSUE THREAD

**Issue by aprilmintacpineda** [bitwarden/clients#4275]
### Steps To Reproduce

1. Go to a website
2. Login
3. When the popup appears, try to close it, notice that nothing is clickable on the popup

### Expected Result

We should be able to close it.

### Actual Result

We cannot close it.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/21032419/208644179-8e9809e6-762a-40e4-b6aa-9a4def51e48e.png)

### Operating System

macOS

### Operating System Version

12.6.1

### Web Browser

Chrome

### Browser Version

108.0.5359.124

### Build Version

I'm using the bitwarden extension version 2022.12.0 https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=en 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

We were unable to reproduce this issue. Could you please confirm if this issue is still visible for you?

**Comment by atjbramley** [comment]
Hi @aprilmintacpineda ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in other software on your machine.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
