### ISSUE TITLE
When adjusting a Password it resets the folder by default

### ISSUE THREAD

**Issue by Mindless999** [bitwarden/clients#4389]
### Steps To Reproduce

In both below methods the folder has been reset to the default "No folder" for me for every password that I update.
Method 1:
1. Go to 'Bitwarden Webbrowser plugin'
2. Search the password
3. Select the password
4. Click on 'Edit'
5. Scroll down to "folder"

Here you can now see that it is defaulted back to `No folder`

Method 2:
1. Change password on the website
2. Press update password in the bar from Bitwarden to update the password

After this, the password is defaulted to the `No folder`

### Expected Result

I expect it to stay in the same folder name that it already exists in.

### Actual Result

Folder defaults to `No folder`

### Operating System

Windows

### Operating System Version

Windows Server 2019

### Web Browser

Microsoft Edge, Firefox

### Build Version

Version: 2022.12.1 (Server version (Self-hosted): 2022.12.0)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dp-collection** [comment]
for reference Method 2: I did same steps and updating password delete all saved notes. 

/app: browser extension version 2023.1.0 (browser Firefox 109.0.1 64bit Windows; UserAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0)

**Comment by atjbramley** [comment]
Hi @dp-collection, 

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
