### ISSUE TITLE
1pux importer ignores timestamps

### ISSUE THREAD

**Issue by andresp** [bitwarden/clients#4391]
### Steps To Reproduce

1. Import a record with a "created" and "modified date" in the past using 1pux importer

### Expected Result

Dates are preserved and reflect the timestamp in the past

### Actual Result

Timestamps are updated to when the record was imported into Bitwarden

### Operating System

Windows

### Operating System Version

11

### Shell

PowerShell

### Build Version

2022.11.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @andresp, 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please note that on testing this, Bitwarden does import password history, as well as recording the correct timestamps for these changes.

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
