### ISSUE TITLE
1pux importer ignores attachments

### ISSUE THREAD

**Issue by andresp** [bitwarden/clients#4393]
### Steps To Reproduce

1. Import 1pux record with a file attachment or image

### Expected Result

Attachment present on imported record

### Actual Result

Record is created but no attachment present.

### Operating System

Windows

### Operating System Version

11

### Shell

PowerShell

### Build Version

2022.11.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @andresp,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
