### ISSUE TITLE
Unable to click Select file when using Send on Linux

### ISSUE THREAD

**Issue by gooseleggs** [bitwarden/clients#4402]
### Steps To Reproduce

1. Using Bitwarden Snap, Go to ''Send"
2. Click on '+'
3. Click on 'Select file '

Crashes with 
```
(bitwarden:2167291): GdkPixbuf-WARNING **: 15:13:36.382: Cannot open pixbuf loader module file '/home/kelvins/snap/bitwarden/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/kelvins/snap/bitwarden/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/bitwarden/80/data-dir/icons/elementary-xfce/status/16/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

### Expected Result

Open up a select file window

### Actual Result

Bitwarden client crashes out. 

### Additional Context

I have uninstalled Bitwarden from snap, and then re-installed.  No difference.  Running on Ubuntu 22.04 with XFCE

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.5 LTS

### Installation method

Snap

### Build Version

Ubuntu 20.04.5 LTS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @gooseleggs, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption of your installation, or a conflict with other software on your machine.

I recommend re-installing as a first step to resolve this.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
