### ISSUE TITLE
Preferences at https://vault.bitwarden.com/#/settings/preferences do not synchronize.

### ISSUE THREAD

**Issue by rokejulianlockhart** [bitwarden/clients#4439]
### Steps To Reproduce

1. Visit https://vault.bitwarden.com/#/settings/preferences.
2. Configure it.
3. Access vault.bitwarden.com via another browser.

### Expected Result

The configuration should be synchronized.

### Actual Result

The configuration is not synchronized.

### Operating System

Linux

### Operating System Version

```
uname -a
Linux beedell.rokejulianlockhart.1669806072 6.0.18-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:08:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Web Browser

Firefox

### Browser Version

```
firefox -v              
Mozilla Firefox 108.0.1
```

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

The settings you set inside the Bitwarden Web Vault (https://vault.bitwarden.com/#/) are saved locally on your browser. Making these settings persist across browser has been suggested, and it's something that's on our radar; However, I cannot promise you much on that at this stage.

Because your issue is describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by rokejulianlockhart** [comment]
@Greenderella, have you found any previous feature requests for this, or just erroneous bug reports (like this)? I'd like to not unnecessarily duplicate such a request if possible.
