### ISSUE TITLE
Security Issue: Safari and Chrome Extensions Not Locking on Mac

### ISSUE THREAD

**Issue by adamesq** [bitwarden/clients#4476]
### Steps To Reproduce

1) Change Safari and/or Chrome shortcuts for opening new private windows to use a non-conflicting shortcut (Something OTHER than CMD-SHIFT-N since BW uses this to lock extension per https://bitwarden.com/help/keyboard-shortcuts. 
2) Confirm that your new shortcut for opening private/incongnito window has properly been changed in either or both browsers.
3) TRry using CMD-SHIFT-N to lock browser extension

### Expected Result

Browser extension locks

### Actual Result

NOTHING happens. Browser extension does NOT lock ADDITIONALLY. Locking Bitwarden in the Menu Bar (main vault), locks BW there, but leaves browser extensions open and vulnerable.

### Screenshots or Videos

![Screen Shot 2023-01-14 at 5 11 40 PM](https://user-images.githubusercontent.com/34196956/212504371-cf93bd44-b9b6-40d9-bb0b-1f0b8accb26a.jpg)

### Additional Context

In this picture, you can see that Bitwarden is locked, but the extension is not. If THIS is considered normal (which seems odd), the shortcut to lock the browser extension should at least work.

### Operating System

macOS

### Operating System Version

11.7.2

### Web Browser

Chrome, Safari

### Browser Version

16.2 for Safari 

### Build Version

109.0.5414.87 for Chrome

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Various members of the team have attempted to reproduce this issue and were unable to do so, the extension locks as expected. Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist? Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists after the reinstallation, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
