### ISSUE TITLE
Extension icons disappears randomly

### ISSUE THREAD

**Issue by andreapx** [bitwarden/clients#4490]
### Steps To Reproduce

Sometimes the extension icons disappears by itself.

### Expected Result

The extension icon should always be visible

### Actual Result

The extension icons sometimes disappears.
It's always been like this, but it happened once in a while, now it has happened about twice today and 3 times yesterday.

### Operating System

Windows

### Operating System Version

10 Pro 20H2

### Web Browser

Firefox

### Browser Version

108.0.1

### Build Version

2022.12.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @andreapx ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or conflict with other extensions installed in Firefox.  I would recommend refreshing your Firefox profile:

https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
