### ISSUE TITLE
Autofill doesn't work for logins without passwords

### ISSUE THREAD

**Issue by p-himik** [bitwarden/clients#4491]
### Steps To Reproduce

1. Go to any website with a login form
2. Add a login to Bitwarden without any password
3. Try to autofill the login form

### Expected Result

The username gets filled in

### Actual Result

Nothing happens. In the JS console of the extension, I see this:
```
Uncaught (in promise) Error: Did not auto-fill.
    at Zl.<anonymous> (autofill.service.ts:158:13)
    at Generator.next (<anonymous>)
    at o (background.js:1:548869)
```

### Additional Context

Judging by the code, the issue is caused by this block in `generateLoginFillScript`:
```js
    if (!login.password || login.password === "") {
      // No password for this login. Maybe they just wanted to auto-fill some custom fields?
      fillScript = AutofillService.setFillScriptForFocus(filledFields, fillScript);
      return fillScript;
    }
```

The problem here is that `filledFields` is an empty object - the username field isn't stored there.

### Operating System

Linux

### Web Browser

Chrome

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this scenario, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by mariobrostech** [comment]
Hi,

I wanted to chime in to say that I'm also encountering this issue while using Firefox running on my Windows and macOS clients. When attempting to autofill a login for an account without a password, I see the following error message:
![image](https://user-images.githubusercontent.com/17557442/225427230-17d20745-3bbb-4853-abd3-570c45be8dd9.png)

This happens consistently for all of my login entries that don't have associated passwords. As a temporary fix, inputting any random password into the login item will resolve the issue, but this isn't ideal since I want to differentiate which accounts utilize SSO or email authentication versus logins that actually have passwords attached to them.

If there's anything else I can do to help you troubleshoot this issue, please let me know. Thanks again for your help!
