### ISSUE TITLE
Security Issue: Password history should not be kept when moving a password to a shared collection

### ISSUE THREAD

**Issue by dchecks** [bitwarden/clients#4499]
### Steps To Reproduce

1. Have an existing credential that needs to be shared but uses a personal password
2. Change password to a non-personal password, creating a password history
3. Move the credential to an Organization's shared collection
4. Users that can see the shared collection can see the password history

### Expected Result

A prompt to keep or clear the password history should be given when a password is shared if there is a password history.

### Actual Result

Users that now can see the password can also see the history of the password.

### Additional Context

Apologies, this probably isn't filed in the correct location.

### Operating System

macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

6060

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshtrichards** [comment]
Not sure this is a bug per se, but I can see where it could be an issue for some situations (like your example). It's a bit like the version history issue when sharing a Google Doc with another editor/person with write access[1].

The maintaining of password history could be made more clear (i.e. explicit) in the explanation language that already comes up when moving an existing item to an organizational vault. Also the Sharing documentation could maybe use a mention of this issue (e.g. here somewhere https://bitwarden.com/help/sharing/).

Beyond that, a potential clean workflow could be to make it so that the Clone feature doesn't copy the password history at all (or at least by default). Then the workflow becomes (1) Clone (2) Move cloned entry into organization.

This model also roughly matches what Google Docs does - if you want to share an existing document with a new editor/writer but don't want the version history to go with it, you make a copy of the document and share it [1] (and it's up to the original creator/editor to decide whether to keep the original version around/maintain both copies if the full history is important to them).

Fortunately, this issue also becomes less of an issue over time with good password hygiene - unique passwords across all sites - but I understand that's beyond the scope of your request. :-)

[1] For example:

* https://support.google.com/docs/thread/4361422/who-can-see-version-history-and-how-far-does-it-go-back?hl=en
* https://it-helpdesk.tetonscience.org/support/solutions/articles/5000718670-using-google-docs-version-history-for-good-and-evil-

**Comment by dwbit** [comment]
Thanks all, closing this one for now as it is expected behavior, but you can open a [feature request here](https://bitwarden.com/featurerequest) for voting and discussion, and I've shared the feedback with the team. 

Feel free to expand on the security concerns and include if you are using unique and randomly generated passwords or if you are adding personal information into your passwords (not recommended).

**Comment by dchecks** [comment]
I'm not going to fight for this, if a password manager leaking an immutable password history isn't a security concern so be it.

**Comment by joshtrichards** [comment]
@dwbit: Reminding the user in the documentation that transferring an entry to an organization means entry history transfers too - which may not occur to many people - might be a path. Could also let them know the easy solution is to create a new entry that won't have history (but not using Clone!)

I think @dchecks' situation isn't unheard of - passwords have a lot of "history" (pun semi-intended) associated with them and thus baggage. Think of a situation where there's been non-unique passwords used across multiple resources... then over time that's been getting fixed. It's not an overnight thing. Besides being a lot of work, it also could involve different departments, clients, affinity groups, prior employers, business partners, etc.

The user may not even have access/ability/authority to change some of them any longer!

P.S. I want the history myself *generally*, but I like having a warning or the choice - or at least having the docs make it clear so it's on me if I do it. ;-)

**Comment by dwbit** [comment]
Thanks all! This proposal has been shared with the team 👍
