### ISSUE TITLE
Windows keyboard setting reset after installing update

### ISSUE THREAD

**Issue by ugcheleuce** [bitwarden/clients#4506]
### Steps To Reproduce

This is just FYI. I have not tried to reproduce this, but the bug occurred live while I was working on my computer.  

Background: My computer uses United States International keyboard, and I have a macro in Microsoft Word that is connected to certain keyboard shortcuts e.g. Ctrl+Alt+T.  Sometimes, something happens in Windows that causes Windows to reset the keyboard shortcuts so that e.g. Ctrl+Alt+T types a thorn character.  The only way to fix this is to remove the current language in the Windows settings, add something else, and remove it, and then add the original language again in Windows settings.

Today, Bitwarden updated while I was working in Microsoft Word.  My keyboard shortcuts got reset immediately (i.e. stopped being used for the macro and started typing a thorn character) the moment Bitwarden's update had finished installing.

### Expected Result

 Installing the Bitwarden update should not reset my Windows keyboard shortcuts.

### Actual Result

 Installing the Bitwarden update reset my Windows keyboard shortcuts.

### Operating System

Windows

### Operating System Version

10 (latest)

### Installation method

Other

### Build Version

Version 2023.1.1, Shell 21.3.1, Renderer 106.0.5249.181, Node 16.16.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @ugcheleuce ,

I attempted to reproduce your issue and was unable to do so.

In particular I:

- installed Bitwarden Desktop 2023.4 on a Windows 10 machine
- bound the custom shortcut 'ctrl + alt + w' to 'bold' in MS Word
- ran the Bitwarden updater to update to 2023.5.1 while continually tapping my custom shortcut and observing that the bold text indicator was toggled on and off throughout the duration of this test.

I suspect that your issue may have been a coincidence, and unrelated to the Bitwarden update.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
