### ISSUE TITLE
"Error code 7: Traffic looks unusual" when using DNS servers

### ISSUE THREAD

**Issue by fybx** [bitwarden/clients#4526]
### Steps To Reproduce

1. Have a DNS server set using [NetworkManager](https://networkmanager.dev/)
2. `bw login`
3. Enter email and password as usual

### Expected Result

This is my first time using Bitwarden CLI. I've used Bitwarden Electron client, with and without DNS servers set and didn't get this error.

### Actual Result

"Traffic from your network looks unusual. Connect to a different network or try again later. [Error Code 7]"

### Operating System

Linux

### Operating System Version

Arch GNU/Linux 6.1.3-arch1-1

### Shell

Bash

### Build Version

2022.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi, 

Thank you for this report.  This is something that we'd like to work through with you via our support channel.  Would you please raise a ticket at https://bitwarden.com/contact/

We look forward to hearing from you!

**Comment by rumenavramov** [comment]
This issue is not for support - it is an actual bug. It seems that you have tried to improve security by adding logic that may be faulty or not tested enough, which is failing your loyal users. As an example I am sharing my experience:

I was not able to log-in to CLI because of this error on the same computer (including IP and everything else), where I was able to use the browser extension and the desktop client without any issues. This clearly indicates that it is not related to my network and the only remaining source of the problem I can think of is the code logic.

It is a good idea, but apparently needs to be refined and tested much more before you start locking people out of their vaults.

**Comment by esaporski** [comment]
I'm facing the same problem right now and it's very frustrating.
It should have an option on Account Settings to disable this kind of behavior. 

A lot of paying customers (like myself) have complained, but the Bitwarden team doesn't seem to care.
