### ISSUE TITLE
Window will not restore after Windows goes to sleep

### ISSUE THREAD

**Issue by slhussey** [bitwarden/clients#4534]
### Steps To Reproduce

1. Leave the Bitwarden window up and visible
2. Let Windows go to sleep
3. Click on the icon in the taskbar
4. Nothing happens
5. You have to right click and then click on Bitwarden

### Expected Result

Should be able to left click the icon and it should display, or even better, it should still be visible after waking Windows up.

### Actual Result

Details in the reproduce text box.

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Greetings,

I attempted to reproduce your issue with a variety of settings and was unable to do so. Please try logging out/in to the application or even restarting your device to see if that helps.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/). 

The issue here will be closed.

Thanks!
