### ISSUE TITLE
Failure to attach TouchID to Safari Browser

### ISSUE THREAD

**Issue by Larunda** [bitwarden/clients#4535]
### Steps To Reproduce

1. Log into Bitwarden app from App Store
2. Set up TouchID and allow for Browser Integration
3. Go to Bitwarden Browser extension, attempt to connect TouchID
4. Follow TouchID prompts
5. Get asked for access to Keychain

### Expected Result

The app should have authenticated Safari instantly, like it did with Chrome on the same device.

### Actual Result

An error that I've yet to find any info on looking through Github and the wider web

### Screenshots or Videos

<img width="1209" alt="Screenshot 2023-01-23 at 1 55 24 am" src="https://user-images.githubusercontent.com/29533268/213922513-61556573-1080-4596-aecc-f828d42f1056.png">

### Operating System

macOS

### Operating System Version

Ventura 13.2 Beta

### Web Browser

Safari

### Browser Version

16.3

### Build Version

2023.1.1 (6572)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dwbit** [comment]
Hey @Larunda have you tried disabling and renabling touch ID from the browser extension settings menu?

**Comment by Greenderella** [comment]
Hi @Larunda,

We are unable to reproduce this issue on our end, if @dwbit suggestion doesn't solve your issue, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

We use GitHub issues as a place to track bugs and other development related issues. You can include a link to this issue in the message content. 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). The issue here will be closed.
