### ISSUE TITLE
Chrome extension no longer recognises local URLs without domains (eg http://server/)

### ISSUE THREAD

**Issue by rd778** [bitwarden/clients#4536]
### Steps To Reproduce

1. Go to a local address that does not have a domain - for example http://server:5000/
2. Create a new login and save it. Confirm that the URI (http://server:5000/) is saved to the login details. 
3. Close browser, reopen browser, then navigate back to http://server:5000/
4. Open the Chrome extension. The website is not displayed in the logins list (no logins are displayed). 
5. If you want to autofill the login, you must search for the login (search http://server/), open it and click the autofill button.

### Expected Result

When opening the Chrome extension, the login details should appear automatically when you are on the domain (http://server/). 

### Actual Result

The login details do not appear. 

### Additional Context

This used to work (the local server logins would appear in the app without having to search). I am not sure on which version this broke, but it was working until a few weeks ago. 

### Operating System

Windows

### Web Browser

Chrome

### Build Version

 2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@rd778 Thank you for your report.

Please try changing the URI match detection to "Host" for these entries.

More information on URI match detection options can be found [here](https://bitwarden.com/help/uri-match-detection/)

**Comment by Greenderella** [comment]
Hi @rd778,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If @djsmith85 suggestion about changing the URI match option doesn't work for you, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
