### ISSUE TITLE
Scrolling/paging in items pane stops prematurely and freezes when using cursor Up/Dn / PgUp/PgDn / Home/End

### ISSUE THREAD

**Issue by DavidPesticcio** [bitwarden/clients#4589]
### Steps To Reproduce

1. Go to items pane
2. Click on first item
3. Hold down either cursor down or PgDn
4. Scrolling will stop prematurely or if using End/Home repeatedly will stop responding

### Expected Result

Cursor Up/Dn should continue to reach the end of the available items
PgUp/PgDn should continue to reach the end of the available items
End/Home should continue to behave as desired when repeated

### Actual Result

The cursor/caret stops responding after undetermined itteration per keypress or held key chosen to navigate up/dn the list of items.

### Additional Context

Subsequent selection by mouse appears to reset this behaviour.
Repeating steps will yield the same result.

Hitting TAB appears to reset this behaviour.
Repeating steps will yield the same result.

Cursor movement may be intermittent as sometimes moving up/dn can be repeated through the whole list repeatedly - until you can't, which seems to be indeterminable. At least nothing obvious stands out.

May be linked to icon update for each entry - although nothing conclusive identified.
May be linked to how the item is focussed - item loses focus and focus does not follow selection when using keys.

### Operating System

Linux

### Operating System Version

OS: Linux Mint 21 x86_64 / Kernel: 5.15.0-58-generic / DE: Cinnamon 5.4.12

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

Version 2022.11.0 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Could you please enter a ticket into our help center so we can better assist you? https://bitwarden.com/contact/ 

You can include a link to this issue in the message content. Could you also attach a screen recording of this happening? 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
