### ISSUE TITLE
Autofill requires password

### ISSUE THREAD

**Issue by Dan203** [bitwarden/clients#4590]
### Steps To Reproduce

I have a work site that requires a username but then uses Google for authentication so does not require a password. Previously I had used LastPass and was able to save just the username so that it would autofill and I wouldn't need to type it every time. When I imported my data into Bitwarden that stopped working and I couldn't figure out why. The main extension UI in Chrome would popup an error that said it was unable to fill. I even submitted the page to your report autofill report.

However I just realized the problem. Bitwarden requires that a site have a password associated with it to autofill. I assigned a random password to this entry in the vault and now it works correctly. 

### Expected Result

I expect it to autofill the username even if the password is empty

### Actual Result

It throws an error and does not fill the username

### Operating System

Windows

### Operating System Version

WIndows 10

### Web Browser

Chrome

### Build Version

109.0.5414.75

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi Dan203, 

I attempted to reproduce your issue and was unable to do so. Could you please enter a ticket on our help center so we can further troubleshoot this issue? https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
