### ISSUE TITLE
Unlock with Biometrics not Automatic on Safari/macOS

### ISSUE THREAD

**Issue by dcorbin** [bitwarden/clients#4594]
### Steps To Reproduce

1. Install and enable the extension on Safari running on macOS (Touch ID required)
2. Click the Bitwarden Icon (on the Safari toolbar)
3. Click Settings
4. Click Unlock with Biometrics (so that it is now enabled)
5. Provide Fingerprint
6. Click Settings
7. Click Lock Now
8. Click of the Bitwarden extension (allowing it to close)
9. Click Bitward Icon (on Safari toolbar)

### Expected Result

The OS TouchID dialog should show up.

### Actual Result

The "Verify Identity" dialog is shown, with the "Unlock with Biometrics" button.

### Additional Context

Clicking on the "Unlock with Biometrics" button works fine, but I should not have to.  I know there was a long thread about this feature  two years back.  It works fine on FireFox running on macOS.

### Operating System

macOS

### Operating System Version

Ventura 13.1

### Web Browser

Safari

### Browser Version

16.2 (18614.3.7.1.5)

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dcorbin** [comment]
This appears to be the original PR: https://github.com/bitwarden/clients/pull/2065

**Comment by atjbramley** [comment]
Hi David, 

Thanks for your report.

I attempted to reproduce your issue and was unable to do so. I'm not sure what could be causing this issue on your particular machine, but this does not appear to be an issue that effects all Bitwarden installations.  I'd enjoy the opportunity to try to help you via our support channels. 

We use GitHub issues as a place to track bugs and other development related issues. Please write to us using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by lobstaj** [comment]
I ran into the same problem.

Until recently, I used brave browser (chromium based) and never experienced this.

Now I started to use Firefox and this issue popped up. Not sure it's somehow non-chrome-browser related, googling seems to reveal the extension seems to work somewhat less reliably in those.
