### ISSUE TITLE
Can't delete last item in vault as it overflows the screen

### ISSUE THREAD

**Issue by thechubbypanda** [bitwarden/clients#4599]
### Steps To Reproduce

1. Go to 'vault.bitwarden.com'
2. Add a lot of items (such that you have to scroll to see the rest)
3. Scroll down to the bottom
4. Attempt to delete the last item

### Expected Result

The delete button is visible and pressable

### Actual Result

The delete button is not visible or pressable

### Screenshots or Videos

![vaultwarden-ui-issue](https://user-images.githubusercontent.com/33595996/215546282-431b71b7-3602-43b0-a100-f16e3f373400.png)

### Operating System

Linux

### Operating System Version

Arch

### Web Browser

Firefox

### Browser Version

109.0

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Greetings,

I attempted to reproduce your issue and was unable to do so. Please clear cache, cookies, etc. in your browser and disable any ad-blockers temporarily to see if that helps.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
