### ISSUE TITLE
Session expires after login

### ISSUE THREAD

**Issue by elmercatapang** [bitwarden/clients#4624]
### Steps To Reproduce

1. Go to 'Bitwarden Desktop app'
2. Proceed to login (existing user)
3. Session instantly expires after login
Bitwarden version (2023.1.1)
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

### Expected Result

Session will not expire in an instant.

### Actual Result

Just after I logged into the App, the session instantly expires and take me back to the login again

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/97313253/216187483-8abdfe3f-ccd3-4efd-b550-0773b8ae2149.png)
![image](https://user-images.githubusercontent.com/97313253/216187625-69bd955f-d353-4987-8881-87ed4c8627a9.png)

### Operating System

Windows

### Operating System Version

Microsoft Windows 10 Pro Version: 10.0.19043 Build 19043

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi elmercatapang,

I attempted to reproduce your issue using the same Bitwarden Client, on Windows 10 Pro and was unable to do so. I suspect that this might be solved by re-installing the Bitwarden Desktop Client, ensuring that you reboot after the initial uninstallation.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
