### ISSUE TITLE
Changes made in Secure Notes edit dialogue can be lost without being saved

### ISSUE THREAD

**Issue by dfluff** [bitwarden/clients#4647]
### Steps To Reproduce

1. Go to vault.bitwarden.com
2. Click on any secure note to edit it.
3. Make some edits.
4. Click elsewhere on the web browser page, outside the Edit dialogue.
5. The edit dialogue closes without a prompt or warning and without saving changes.

### Expected Result

When clicking outside of the edit dialogue when there have been changes made, I would expect the edit dialogue to either not close at all, or to warn that it is about to close the dialogue but there are unsaved changes.  I think not closing at all is probably preferable, thereby forcing a user to click Save or Cancel.

### Actual Result

The edit dialogue closes without a prompt or warning and any edits to the secure note are lost.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

102.7.0esr

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dfluff** [comment]
I should have also said, although I discovered this when I lost some information whilst editing a Secure Note, a quick test shows that the same happens when editing any other kind of record.

**Comment by atjbramley** [comment]
Hi dfluff!

Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please note that your Feature Request isn't limited to the webvault (https://vault.bitwarden.com) - you will find the same behaviour in other clients too.

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
