### ISSUE TITLE
Desktop app doesn't release window focus correctly; always stays on top of other windows.

### ISSUE THREAD

**Issue by GJasonAnderson** [bitwarden/clients#4684]
### Steps To Reproduce

1. Open the Bitwarden desktop app.
2. Open any other app.
3. The other app window loads behind the Bitwarden window. Any attempts to click on the other app's window will never put the window on the top, because Bitwarden refuses to allow any other window to be rendered on top of it.

### Expected Result

The Bitwarden window should allow other windows to be rendered on top of it.

### Actual Result

The Bitwarden window refuses to allow other windows to be rendered on top of it.

### Screenshots or Videos

[Screencast from 2023-02-07 11-31-07.webm](https://user-images.githubusercontent.com/31811561/217309102-d5f4029d-f7fe-4daa-93d6-816b2eabb8e9.webm)

### Additional Context

installed via flatpak

### Operating System

Linux

### Operating System Version

Fedora 37

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

Version 2023.1.1 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think you might have set your window for the Bitwarden app to always be on top at some point.

https://user-images.githubusercontent.com/1657434/217404091-04055bea-f5e7-40cf-be1e-930fcee7ee90.mp4

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
