### ISSUE TITLE
No phone approval vault unlock option for the Chrome extension

### ISSUE THREAD

**Issue by ccornici** [bitwarden/clients#4726]
### Steps To Reproduce

-

### Expected Result

-

### Actual Result

-

### Screenshots or Videos

extension

![image](https://user-images.githubusercontent.com/15718751/218256589-0adf6a0d-fa68-498c-9376-f6821f580d35.png)

web

![image](https://user-images.githubusercontent.com/15718751/218256880-3413eda0-b0d4-4075-8ac8-083b627e0a82.png)

### Additional Context

I've activated the passwordless login for the vault, it works on the web vault as in the bitwarden blog tutorial.
In the extension, there's no option to login via phone approval, and after I log in with the master pw, it's always gonna ask again for the pw later as per timeout settings.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

Version: 2023.1.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @ccornici,

Your issue appears to be describing the intended behaviour of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 


Thank you.
