### ISSUE TITLE
Safari Extension on macOS: Vault locks immediately after unlocking

### ISSUE THREAD

**Issue by yusufmalikul** [bitwarden/clients#4736]
### Steps To Reproduce

First of all, thank you for this amazing password manager.

I use Bitwarden for about a year. This issue only happen recently (I think since last month).

1. Set the vault timeout to a time-based value (e.g 4 hours or custom)
2. Let the extension lock
3. Click the extension

### Expected Result

Extension stay unlocked (for 4 hours).

### Actual Result

Extension locked and ask for master password.

### Screenshots or Videos

Video: https://www.dropbox.com/s/hhg5ao7krj3jggz/bitwarden%20bug%20vault%20lock.mov?dl=0

### Additional Context

Time-based value doesn't work. If I set it to 'Never' it works, the vault never locked.

### Operating System

macOS

### Operating System Version

Monterey 12.6

### Web Browser

Safari

### Browser Version

16.0 (17614.1.25.9.10, 17614)

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi yusufmalikul,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corrupted installation, or possibly an extension conflict.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by yusufmalikul** [comment]
Thank you. Reinstalling the bitwarden extension solved the issue :)
