### ISSUE TITLE
Autofill can fill in the wrong password on sites with split login screens

### ISSUE THREAD

**Issue by jjlin** [bitwarden/clients#4742]
### Steps To Reproduce

When auto-filling using the [keyboard shortcut](https://bitwarden.com/help/auto-fill-browser/#using-keyboard-shortcuts), using the shortcut repeatedly cycles between multiple logins for the same site.

However, with sites where the username and password inputs are split across two screens (https://vault.bitwarden.com/ is one example), auto-filling using the keyboard shortcut can cause the wrong password to be filled in on the password page if you go from the username to the password screen too quickly, since the extension interprets the two successive auto-fills as a request to cycle between logins.

The extension should detect split login conditions and avoid cycling between login entries when two auto-fills occur in quick succession.

### Expected Result

If you have multiple logins, auto-filling the username and password on https://vault.bitwarden.com/ via keyboard shortcut should fill in a matching username and password.

### Actual Result

Auto-filling the username and password via keyboard shortcut can fill in the password for a different account if you auto-fill the username and then auto-fill the password too quickly.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c1-jack** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by jjlin** [comment]
This is more of a general issue in the design of the autofill system, and not specific to a particular site, though.

**Comment by c1-jack** [comment]
I understand, however, reports related to autofill as a larger concept are all tracked together.

**Comment by zanardob** [comment]
This still happens to me to this day, any workarounds/settings I could try? Also where is the issue being tracked since this one was closed?
