### ISSUE TITLE
Unable to unlock my vault thru a browser extension due to Uncaught Exception

### ISSUE THREAD

**Issue by jcchikikomori** [bitwarden/clients#4743]
### Steps To Reproduce

1. Go to 'Any login website' (Cannot disclose because I was using my corporate account when I found this issue)
2. Click on 'Any login form' or Right-click on 'Any login form' >> 'Auto-fill' >> 'Unlock your vault'
3. Type your correct master password
4. Click 'Unlock' or press ENTER
5. Open Dev Tools

### Expected Result

Should unlock my vault

### Actual Result

Stuck on master password form.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4709030/218625300-07b07eb2-467b-49ba-8925-d770d3f47190.png)

### Operating System

Windows

### Web Browser

Microsoft Edge

### Browser Version

110.0.1587.41

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @jcchikikomori,

I attempted to reproduce your issue and was unable to do so on Edge 110.0.1587.41 with Bitwarden extension 2023.1.0. I'd recommend that you start with a fresh installation; Please uninstall that browser extension off your browser, remove its leftover data, reboot the machine, install it anew, and test that again. Our Download page and the locations of any leftover data are linked below.
https://bitwarden.com/help/data-storage/
https://bitwarden.com/download/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thank you.
