### ISSUE TITLE
Window times out when changing credentials

### ISSUE THREAD

**Issue by akovia** [bitwarden/clients#4748]
### Steps To Reproduce

1. Navigate to the Logout menu item. (Should really be more easily accessible)
2. Select `Log out` and confirm your choice.
3. Start entering the credentials of the account you'd like to log in with.
4. While you are entering your credentials, the window will just close and you will need to start over again.

### Expected Result

You should only have to enter your credentials once, and the window should not close while doing so.

### Actual Result

After 8-10 seconds, the window will just close, no matter what you are doing.

If you can not enter your credentials within that time, you will lose your progress and will have to re-open the window and re-enter your credentials again.

### Additional Context

This issue is slightly different between browsers. I use Brave as my main browser and this is the browser I have issues with the window closing. When I try this on Firefox/Windows, it doesn't actually close the window, but will clear your input if you haven't completed entering your credentials within the same time window as stated above.

So if you are half way through entering your master password, it will just clear the input field and you will need to start over.

I am constantly having to chase the disappearing Bitwarden window. When adding new passwords and inadvertently clicking away from from the Bitwarden window, you lose all progress and have to start over. I try to remember to pop out the window when doing anything that requires Bitwarden, but I don't always remember and am constantly having to do everything twice. I really wish you could figure out how to keep the window present until dismissed, or at least add an option for idiots like me to make this the default. 

Maybe add a short timer to keep the window present when opened, so even if the user forgets to dismiss it, it will close once time expires, but will keep it available without losing your work if you click away from it by accident or on purpose.

I would imagine this has been reported before, but I was not able to figure the keywords to hunt down the issue properly. So I apologize if this is a duplicate.

Thanks!

### Operating System

Windows, Linux

### Operating System Version

Arch Linux / Windows 10

### Web Browser

Firefox, Brave

### Browser Version

Brave: Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit) / Firefox: 109.0.1 (32-bit)

### Build Version

Version: 2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi akovia,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in an extension conflict.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/  

You can include a link to this issue in the message content, and a video of this happening would be greatly appreciated - please do not crop your video in any way!

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by akovia** [comment]
Hi @atjbramley,
Thanks for the speedy reply. I experience the same behavior in both browsers with both in private windows without any other extensions.

I don't understand how it could be an extension conflict when there are no other extensions enabled, but I'll fill out the form you linked.

**Comment by atjbramley** [comment]
@akovia - I agree that if there are no other extensions installed it sounds unlikely to be a conflict!  However, this does appear to be an isolated issue, so support would be the more appropriate channel.  We look forward to receiving your report and video over there and investigating!

**Comment by akovia** [comment]
Apparently all of this testing to troubleshoot this issue has locked me out of my account and I can no longer work without access to my vault!!

![Bitwarden-network-error](https://user-images.githubusercontent.com/10238233/218805098-9a70829d-7380-4fb8-b75a-54ad4d903f98.jpg)


I sent another support ticket, but this is absurd. I need access to my vault. We don't use a vpn so I don't have access to another network. Can I access a locally cached copy until this is fixed?

**Comment by akovia** [comment]
> @akovia - I agree that if there are no other extensions installed it sounds unlikely to be a conflict! However, this does appear to be an isolated issue, so support would be the more appropriate channel. We look forward to receiving your report and video over there and investigating!

This issue continues to be a major source of frustration. I followed your instructions and and created a ticket about this issue, referenced my details here, and also included a video showing the issue in both Brave and Firefox, with both utilizing private windows so that no other extensions were used.

Instead of getting any actual help, I was instead sent an email asking me to rate my experience. I replied by selecting the "Awful!" button, and explained again that I was still experiencing the issue and pointed out that the issue still hadn't been addressed. 

I'm happy to provide the email chain indicating the above, but I'd rather not post it here because of the sensitive data that is included.

Do I need to start over again to get some help?

**Comment by Greenderella** [comment]
Hi @akovia 

This error, it's related to our security mechanisms and protocols. If you are still receiving this error after 30 minutes, it probably means your IP continues to be flagged for malicious activity by our security systems. 

This can happen if you are connecting through a shared public IP, VPNs, proxies or Tor, because those are usually used to route malicious actions and traffic against our cloud infrastructure in order to mask the traffic's origin. Please continue to rotate your connection until you are able to operate normally again.

Also check that the browser from where you are trying to log in is up-to-date, as malicious actors often use old browsers with security flaws to carry on their activities.

We thank you in advance for your understanding. If you have any further questions, please contact us here: https://bitwarden.com/contact/

**Comment by akovia** [comment]
Seems this is getting lost with the network issue. That resolved itself later that day.

I am referring to the initial issue. `Window times out when changing credentials`
Would you mind re-reading the comment previous to the one I posted today and advise? 
https://github.com/bitwarden/clients/issues/4748#issuecomment-1454742685

Thanks

**Comment by djsmith85** [comment]
@akovia: Could you please update the browser extension to 2023.3.0 and check if you can still reproduce the initially reported behaviour (`Window closes automatically`). This might have been addressed with other changes since you reported this. If you can still reproduce, this can be re-opened, but please provide any additional details

**Comment by akovia** [comment]
@djsmith85 Fantastic!
Seems to be working now and couldn't be happier to have that thorn out of my side.

Cheers!
