### ISSUE TITLE
Default KDF iterations still 5000 when KDF Config / Iterations is null

### ISSUE THREAD

**Issue by nowasteaccount** [bitwarden/clients#4771]
### Steps To Reproduce

Even though default iterations is set to 600000, in case of any errors or if object / iterations is null, KDF iterations are still pointing to 5000. Doesn't this needs to be modified ??

apps/web/src/app/settings/change-kdf.component.html defines minimum iterations as 100000 (Believe its set to 100000 as supposed to OWASP recommended 600000 for lower devices). 

Please check if libs/common/src/services/crypto.service.ts needs to be modified to accommodate 600000 as KDF iterations in case object is null (rare case though but should have been handled accordingly)?

![image](https://user-images.githubusercontent.com/121700012/219076615-3cabd5ff-cf5b-4e72-9c82-2e406ecdab27.png)

### Expected Result

Accommodate 600000 as KDF iterations in case KDF object / iterations is null

### Actual Result

KDF iterations value is still 5000 in case KDF object / iterations is null 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/121700012/219077236-e4156b3d-2241-44d9-82a9-e907f581002e.png)

### Operating System

Windows

### Web Browser

Chrome, Firefox, Brave

### Build Version

Version 2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi!

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
