### ISSUE TITLE
Checkbox custom field not working on JIRA Server Login

### ISSUE THREAD

**Issue by hadrienbecle** [bitwarden/clients#4806]
### Steps To Reproduce

1. Add a login info for a JIRA Server instance on Bitwarden (Server = on-premises)
2. Add a custom field of type boolean with value True and name "login-form-remember-me" or "os_cookie" (or both in two custom fields)
3. Try to auto-fill on the login page (example page: https://issues.apache.org/jira/login.jsp)

### Expected Result

The checkbox to remember the login is checked

### Actual Result

The checkbox to remember the login is NOT checked

### Additional Context

Checkbox code, part of the login `form` element:

````html
<fieldset class="group ">
    <div class="checkbox" resolved="">
        <input class="checkbox" id="login-form-remember-me" name="os_cookie" type="checkbox" value="true" resolved="">
        <span class="aui-form-glyph"></span>
        <label for="login-form-remember-me" accesskey="r"><u>R</u>emember my login on this computer</label>
    </div>
</fieldset>
````

### Operating System

Windows

### Operating System Version

10 22H2

### Web Browser

Firefox

### Browser Version

102.3.0esr

### Build Version

Firefox extension 2023.1.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by hadrienbecle** [comment]
(I'm not sure it's the type of auto-fill issue you want on the Google Forms in #1621, and either way I can't load Google Forms where I am, sorry ☹️)

**Comment by Adedamola-Aina** [comment]
Hi there!
We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:
	•	mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
	•	browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform
In this case, we will go ahead and file an autofill report for you with the information you added here.
In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.
This issue will now be closed. 
Thanks!
