### ISSUE TITLE
Desktop client restarts unexpectedly

### ISSUE THREAD

**Issue by GimmeSoftwares** [bitwarden/clients#4850]
### Steps To Reproduce

1. Go to 'Desktop client' (I am using v2023.2.0)
2. Click on '"Master Password' (to log into the client .. .of course make sure you've clicked exactly within the password field)

At least once per week, the client will stop accepting input into the Master Password field and/or the desktop client will restart unexpectedly. This is extremely disruptive when typing a complicated pass phrase. 

### Expected Result

I expect that when I open the desktop client ("app"), input will default to the "Master Password" field and not require me to click within the field to allow input. I expect the client will allow me to input my entire pass phrase without disappearing, suddenly disallowing input, or popping up a notification of a new client. If there is a new client, notify me ***after*** I have entered my pass phrase then allow me to choose whether I want to restart/install the new client or wait for next time.

### Actual Result

Actual result is as described above, the client occasionally disappears while I am entering my pass phrase or for some other reason stops accepting input requiring me to click on the password entry field again.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please restart your device to see if that helps, and even attempt to reinstall the application if necessary.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
