### ISSUE TITLE
Firefox extension badge counter broken

### ISSUE THREAD

**Issue by CubeRanch** [bitwarden/clients#4865]
### Steps To Reproduce

1. In the Firefox browser extension, log in or unlock your vault.
2. Go to Settings->Options->Show badge counter and enable by checking the checkbox.
3. Go to a website that has a corresponding login in your vault.

### Expected Result

Expect to see a badge counter showing the number of corresponding logins displayed over the extension's Bitwarden logo.

### Actual Result

No badge counter is displayed.

### Additional Context

Problem began after updating to version 2023.2.1
Corresponding logins are shown correctly on the extension's Tab page.
The Vault page icon displays an accurate badge counter.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

110.0

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. This bug was noted in a previous version of the Bitwarden browser extension, but was fixed in 2023.1.0. The previous Github issue can be found here: https://github.com/bitwarden/clients/issues/4260

I recommend uninstalling the Bitwarden browser extension, then reinstalling it. If your issue persists, please write us back using our contact form, so Bitwarden support can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
