### ISSUE TITLE
Desktop App closes anytime I click COPY UserName or Password icon

### ISSUE THREAD

**Issue by sanga549** [bitwarden/clients#4869]
### Steps To Reproduce

Windows 2010 version 10.0.19045 Build 19045
Bitwarden App version 2023.1.1

1. Open Bitwarden App
2. Open one of your records
3. Click on the Copy icon for either UserName or Password.

The Bitwarden App copies the value then closes the application. You have to click Windows > Start > Bitwarden again to reopen it each time.  Often I need to copy both UserName and Password into a login form so having to re-open the Bitwarden App multiple times is a real hassle.

### Expected Result

I expect the app to stay open until I manually close it, not disappear. I checked the System Tray, it's not there when this happens so must click on Windows > Start > Bitwarden to reopen Bitwarden.

### Actual Result

When copying either the UserName or Password from the Bitwarden App, the Bitwarden App immediately closes. You have to click Windows > Start > Bitwarden again to reopen the app each time.  I often need to copy both UserName and Password into a login form which I can only do one at a time. Some forms won't auto-fill so it's a manual process in some places. 

### Operating System

Windows

### Operating System Version

Windows 2010 version 10.0.19045 Build 19045

### Installation method

Other

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @sanga549,

Thank you for this report. I attempted to reproduce this behaviour and was unable to do so; Could you please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ ? Please include a link to this GitHub report in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you.
