### ISSUE TITLE
Indicate current selected lower left corner icon on desktop

### ISSUE THREAD

**Issue by jidanni** [bitwarden/clients#4872]
### Steps To Reproduce

$ bitwarden

Now click on Vault as seen in the image, of the lower left corner of the screeen.

### Expected Result

The item we are currently using should look different.

### Actual Result

Nothing happens.

That's because we are already in the vault.

But as you see the color is the same as "send".

### Screenshots or Videos

![20230226T162254](https://user-images.githubusercontent.com/1230959/221400196-08ab3916-9219-4b09-b944-3d0925275d35.jpg)

### Operating System

Linux

### Operating System Version

Debian sid

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.2.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @jidanni, 

In the screenshot you've submitted, the highlighted 'My Vault' button has an RGB values of 255,255,255, whereas the unhighlighted 'send' buttonm and the app background, have RGB values of 249,249,249.  

Your issue appears to be describing the intended behavior of the software. If you want this to be changed to display more contrast, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by jidanni** [comment]
In the image above, I see two icons, exactly the same color,
\#249 is a medium dark shade of blue
https://encycolorpedia.com/224499

And zero icons
\#254 is a dark shade of green-cyan.
https://encycolorpedia.com/225544

Those two web pages look very different to me.

The icons in my screenshot don't.

Please ask somebody in the room to also see if that is what they see in the image above.
No I didn't swap the image.
