### ISSUE TITLE
"n is null" error when trying to authenticate with Firefox extension

### ISSUE THREAD

**Issue by gvonhagel** [bitwarden/clients#4875]
### Steps To Reproduce

1. Download Firefox extension
2. Set URL to self-hosted Bitwarden server 
3. Enter username and password (confirmed to be correct)
4. Press authenticate 
5. Receive error "n is null"

### Expected Result

I expect to authenticate 

### Actual Result

I receive an error box with the message "n is null"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/3430740/221429108-b0cd437a-4652-417a-b918-8d4833ed96a4.png)

### Additional Context

This has previously worked I recently reinstalled my OS and the extension is suddenly broken on a fresh build.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Firefox

### Browser Version

110.0

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @gvonhagel,

Thank you for your report. I attempted to reproduce this behaviour and was unable to do so. I suspect that you could be running an outdated Bitwarden server; Please check if you can update it like so (https://bitwarden.com/help/updating-on-premise/). If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ and please include a link to this issue in the message content; Please also mention if you're able to log in through the Web Vault and/or other application clients.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you.

**Comment by gvonhagel** [comment]
This was correct, it was a version issue. Thank you!

**Comment by cheako** [comment]
Is this still an issue with docker `bitwardenrs/server:latest`?  I tried to pull the image and got nothing new.

**Comment by a-0-dev** [comment]
> Is this still an issue with docker `bitwardenrs/server:latest`? I tried to pull the image and got nothing new.

Just had the same issue. The bitwardenrs container was migrated to vaultwarden, so newer versions are only published there. See https://github.com/dani-garcia/vaultwarden/discussions/1642

@others: Sorry, I know it's kind of OT here...

**Comment by AltonV** [comment]
I just got this error.
 The issue was that I forgot to enter the correct subdomain to my self-hosted server
