### ISSUE TITLE
Cannot read properties of null (read "iterations")

### ISSUE THREAD

**Issue by YDJ1991** [bitwarden/clients#4877]
### Steps To Reproduce

Can not login when use chrome extension. Selfhost url. The web login is normal.
![image](https://user-images.githubusercontent.com/33014966/221491571-7ee6cb8b-b695-468a-8072-9f3dc6daa743.png)
Version Info:
![image](https://user-images.githubusercontent.com/33014966/221492399-d989e763-3271-4858-ad4a-00d5051dc6f6.png)

### Expected Result

Login success

### Actual Result

Login failed

### Operating System

Windows

### Web Browser

Chrome

### Build Version

nngceckbapebfimnlniiiahkandclblb

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @YDJ1991,

I attempted to reproduce your issue and was unable to do so. I suspect that you're running an outdated Bitwarden server; Please check if you need to update it like so (https://bitwarden.com/help/updating-on-premise/). If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ and please include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you.
