### ISSUE TITLE
DesktopClient does not connect to private server

### ISSUE THREAD

**Issue by djjayballz** [bitwarden/clients#4911]
### Steps To Reproduce

1. Installed latest desktop client on Windows10
2. configured private Bitwarden-URL
3. enter email address + password
4. getting error "cannot read properties of null (reading 'iterations')

### Expected Result

It had worked flawlessly before updating to latest client version.
now i cannot connect to the server (yes, it is online, webinterface works)

### Actual Result

I am getting the same error on newest and older client versions. What do i do?

server side looks to work fine

### Screenshots or Videos

![bitwarden_error](https://user-images.githubusercontent.com/36049742/222458044-b4f4a726-b22a-499a-bf5c-fa5ca9480ca5.jpg)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.2.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
I attempted to reproduce your issue and was unable to do so. Could you please reach out to us via our contact page so we can look further into this? 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by djjayballz** [comment]
In the end my friend ran an older version in rust on his server.
