### ISSUE TITLE
Notes field too small in edit mode

### ISSUE THREAD

**Issue by ajargren** [bitwarden/clients#4931]
### Steps To Reproduce

1. Go to an item having a long text in the Notes field
2. The entire Notes field is visible
3. Click edit
4. The Notes field height is reduced to a few lines and most of the content is hidden

I realise this is the intended behavior but it's very annoying that you have to manually expand the field every time.

### Expected Result

The Notes field height is enough to see all/most of it´s content

### Actual Result

The Notes field height is reduced to a few lines and most of the content is hidden

### Operating System

macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.2.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by patrickhlauke** [comment]
the notes field, like most textareas in webpages/web content, can be resized with the gripper at the of the field bottom-right

![screenshot of a note, with the resize gripper highlighted](https://user-images.githubusercontent.com/895831/222967310-6dd154c9-5198-4f7c-98e3-ac3e6abc9e61.png)

having said that,while on Windows it's fairly obvious when a note's content is larger than the displayed content thanks to the very obvious scrollbar

![a large note, showing a scrollbar on the right-hand side](https://user-images.githubusercontent.com/895831/222967365-cfdb16fe-362f-4e57-b7b1-029273a2dffe.png)

on macOS the scrollbar is not shown by default - it only appears when you're actually scrolling. this does indeed look rather awkward/broken

<img width="425" alt="a note with lots of content in macOS shows no scrollbar" src="https://user-images.githubusercontent.com/895831/222967423-c3ac5548-d4ed-4ac1-9bf0-4b44a1b8241d.png">

<img width="408" alt="a note with lots of content in macOS shows no scrollbar" src="https://user-images.githubusercontent.com/895831/222967463-d06b03a5-c276-4156-8ad4-13db2763ceca.png">

It would be good to:

a) force a visible scrollbar on macOS
b) optionally, do some fancy calculation when going into edit mode to see how much content is in a textarea, and set the initial size of the textarea in HTML or CSS accordingly

**Comment by SergeantConfused** [comment]
Hi @ajargren,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.


Thank you both,

**Comment by patrickhlauke** [comment]
admittedly, if the OP didn't realise there was an actual scrollbar (as on macOS you don't actually see it until you start scrolling), they probably thought it was a bug...

**Comment by patrickhlauke** [comment]
(sorry, missed the fact that the OP was aware of the resizing)
