### ISSUE TITLE
HTTP Basic authentication does not show pop-up

### ISSUE THREAD

**Issue by mmagdy88** [bitwarden/clients#4933]
### Steps To Reproduce

Open a page that has HTTP Basic authentication, it doesn't work when Bitwarden extension is enabled.

### Expected Result

To show this pop-up:
https://imgur.com/a/QTJSV6M

### Actual Result

Shows this instead:
https://i.imgur.com/0VCcRlV.png

Didn't even ask for credentials.

### Operating System

Windows

### Operating System Version

Windows 10 21H2, Build 19044.2604

### Web Browser

Chrome

### Browser Version

Version 110.0.5481.178 (Official Build) (64-bit)

### Build Version

Version: 2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshtrichards** [comment]
Hey @mmagdy88. Just a BW user here, but I'm running the same build chrome+bw extension against an nginx server with basic auth and I can't reproduce this (so far).

I tried with autofill enabled as well as disabled in case that had something to do with it, but no change.

I'm having a hard time grasping where/when the BW extension even enters the picture for HTTP Basic Authentication.

Can you try disabling - temporarily - the BW extension outright in your Chrome (Tools->Extensions->toggle the blue bar on the Bitwarden extension listing to gray)? Then revisit the protected URL in a new browser session (make sure you don't have any background Chrome apps that continue to run to avoid session caching issues) to see if this problem goes away or remains.

Also worth trying in an Incognito session as well.

If the issue remains - and if you feel comfortable doing so - can you share your nginx.conf (or equivalent) for the relevant `location` including all associated lines starting with:
```
allow
deny
satisfy
auth_*
```
You can remove any confidential IP addresses/etc at your discretion.

**Comment by mmagdy88** [comment]
Hey @joshtrichards, thanks for your reply, when I disable BW extension, the authenticator pop-up works perfectly. In incognito mode if the BW extension is enabled the pop-up doesn't work, so it's not coming from another extension which I suspected at first.

And in regards of the nginx configuration, you can find it below:
```
                location /REDACTED {
                        satisfy any;
                        auth_basic 'Authenticated users only';
                        auth_basic_user_file "REDACTED";
                        auth_request /auth;
                        proxy_pass http://REDACTED;
                }
                location = /auth {
                        internal;
                        root /var/www;
                        include fastcgi_params;
                        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                        fastcgi_index index.php;
                        fastcgi_param  SCRIPT_FILENAME  /var/www/auth.php; #$fastcgi_script_name;
                }
```

Thanks in advance for your help.

**Comment by MarsCandyBars** [comment]
Greetings,

I attempted to reproduce your auto-fill issue with nginx/basic auth and was unable to do so. Due to the way basic auth prompts are designed, auto-filling them must be non-interactive. Please make sure you have only one vault item that has a URI that matches the one you are trying to auto-fill. If everything works correctly, you shouldn't be prompted to authenticate when you navigate to the site, because Bitwarden will have auto-filled it in the background. Please see our documentation on the topic here: https://bitwarden.com/help/basic-auth-autofill/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by mmagdy88** [comment]
Hey @joshtrichards, I really appreciate your effort trying to help me in this issue, it might be an issue with the PHP authentication script since we're using LDAP and this is what appears in the nginx logs while BW is enabled:
`open() "/data/www/htpasswd" failed (2: No such file or directory)`

If I disabled BW, this error message doesn't show up and the authentication works properly.

**Comment by mmagdy88** [comment]
> 

I already checked that article before I opened the issue and yes I tried disabling auto-fill and tried to enable it but disable that vault item in particular and still the same issue.

**Comment by LufoX11** [comment]
This exact thing started happening again with 2024.9.0 (I think) and is still happening in latest 2024.9.1. It's not something in my server since I manage several servers in different environments and it's happening in all of them.

After viewing my Apache logs it's sending by default my saved website login credentials rather than showing me the basic auth popup, assuming my saved password is the basic auth password (and it's not). Example:

Steps to reproduce the issue (Chrome):

1. With the BW extension enabled, I open a new incognito window and I go to [https://reinventatuvida.org/wp-login.php](url) which has basic auth to access the real wp login page.
2. I immediately receive a 401 Unauthorized error.
3. I close the window, disable the BW extension and open a new incognito window with the same url.
4. Basic auth popup is shown.

Apache logs in step 2:

```
[Wed Sep 25 18:08:55.996972 2024] [auth_basic:error] [pid 2021] [client 2800:40:76:e11:7877:33c6:20c5:2ae5:60530] AH01618: user shamank not found: /wp-login.php
```

"shamank" is my website login username stored in my BW vault, not the one I need to put in the basic auth popup (which is "mario"). So what's happening I think is that BW extension is somehow sending my stored username and password in vault by default as my basic auth credentials.

Take a look:

[Grabación de pantalla desde 25-09-24 19:13:58.webm](https://github.com/user-attachments/assets/d7690a7d-65f9-4d50-b68d-a58eb623bd9d)

The workaround is to put the right login credentials for basic auth directly in the url like: `https://mario:blablabla@reinventatuvida.org/wp-login.php`
