### ISSUE TITLE
Items Requiring Master Password Re-entry show information before re-validation

### ISSUE THREAD

**Issue by crespire** [bitwarden/clients#4988]
### Steps To Reproduce

1. Go to a site with credentials that require re-input of Master Password
2. Click on the Bitwarden extension which shows a list of matching items
4. Find the item in question
5. Click on the "Edit" icon (the first)

### Expected Result

Extension should prompt for password before pulling up item information.

Extension correctly prompts for password when attempting to edit or auto-fill the item.

### Actual Result

You are able to see all of the item information without re-entering the Master Password.

### Screenshots or Videos

I have updated a website to require master password re-entry to show the problem: ![git](https://i.vgy.me/SozIQd.gif)

### Additional Context

When a user turns on "Re-prompt for master password" I think it is reasonable to expect that any action relating to the item should require the password including viewing the item. On the extension, re-prompting for master password does not prevent viewing the item's information. This might be problematic as it allows you to see additional fields and any notes associated with the item, which may include recovery information, security questions, or other sensitive data.

This implementation issue also exists on the Desktop application.

### Operating System

Windows 10

### Operating System Version

Windows 10 Pro 22H2

### Web Browser

Chrome, Firefox

### Browser Version

Chrome v110.0.5481.187 - Firefox v110.0.1

### Build Version

Version: 2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @crespire,

Your report appears to be describing the intended behaviour; If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked; By the way, this (https://community.bitwarden.com/t/require-re-prompt-for-entire-item-view-edit-etc/31737) might be what you are looking for, and this thread (https://github.com/bitwarden/clients/issues/2204) might shed more light on this.

This issue will now be closed. 

Thank you.
