### ISSUE TITLE
Get password gives back the previous password after password change

### ISSUE THREAD

**Issue by ivoros** [bitwarden/clients#4996]
### Steps To Reproduce

1.
On the CLI:
- `bw get password DUMMY --session MY_SESSION_KEY`

It gives back your actual password for DUMMY.

2.
Change the password for DUMMY on e.g. the web vault.

3.
Query again with the above command, even with a new session key or after reboot.

4.
bw CLI will give back the _previous_ version of the password.

### Expected Result

bw get password answers with the _**current**_ password

### Actual Result

bw get password gives back the **_previous_** password

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Shell

Bash

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshtrichards** [comment]
The behavior you're experiencing sounds correct.

The CLI client only syncs changes made elsewhere upon login or when manually requested by running `bw sync`. A mere unlock - which generates the session key - only decrypts the local copy of your vault.

You can either run `bw sync` beforehand or be sure to logout after use (which will force a full login next time `bw` is called).

If this is an interactive situation and you prefer this behavior a command alias could accomplish this automatically. 

If non-interactively (e.g. an admin script), I sometimes directly fire a `bw sync` in my code where needed.

**Comment by Adedamola-Aina** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ivoros** [comment]
Thanks, Josh, to actually answer my question. I would have never assumed that get password is not always an "online", real-time lookup into the cloud directly. I'll add sync to my script. Thanks again!
