### ISSUE TITLE
Stuck when installing from 'snap' on Ubuntu

### ISSUE THREAD

**Issue by AliAlmasi** [bitwarden/clients#4997]
### Steps To Reproduce

1. Type 'sudo snap install bitwarden' on shell
2. Now it'll stick on 'Automatically connect eligible plugs and slots of snap "bitwarden"'

### Expected Result

I expected to see Bitwarden installed :)

### Actual Result

Installing stuck on 'Automatically connect eligible plugs and slots of snap "bitwarden"'

### Screenshots or Videos

![snap-bitwarden](https://user-images.githubusercontent.com/87055424/224996303-e464d880-7f95-4a06-9964-f8a100034f79.png)

### Operating System

Linux

### Operating System Version

Ubuntu 20.04

### Installation method

Snap

### Build Version

Latest? 

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by joshtrichards** [comment]
@AliAlmasi 

I managed to reproduce this once (and the `|` was frozen) and sort of a 2nd/3rd time. It's... inconsistent. May have to do with 
the dependencies that get installed alongside. Dunno.

Out of curiosity, how long did you wait?

In theory, as long as the `\|/` (at the far right of your screenshot) is continuing to rotate then snap is downloading/setting up stuff. 

I `<ctrl-c>` the hung one then removed and reinstalled. Then I could install without the hang (and remove) like 80% of the time without issue. Once or twice it looked like it was going to hang again, then it eventually worked.


* Is there any noticeable activity on your workstation/host during this period (i.e. CPU, disk activity, network traffic)? 
* What happens if you `<ctrl-c>` the apparently stuck install then try to use bitwarden anyway? 
* What happens if you do a `snap remove bitwarden` after using `<ctrl-c>` on the apparently stuck install? 
  - Does the remove complete successfully?
  - Can you re-install cleanly now?

Other commands that might be helpful (in another terminal window) while it's hung:
`snap changes`
`snap tasks X` (where X = the change above you want to see more detailed logging about)

**Comment by thatLeaflet** [comment]
How long did this appear for? I believe this is an issue with snap itself, it can sometimes take a few minutes for this process to finish.

**Comment by AliAlmasi** [comment]
I figured it out. It was all network's problem fault. It appears that the I.R. government (using a Chinese GFW-like system) is slowing down traffic going outside of Iran.
I tried installing using a Proxy server, and it was all fine.

**Comment by hosseinnazari1** [comment]
میشه بگین از چه پروکسی استفاده کردین ؟؟

**Comment by AliAlmasi** [comment]
چطور؟
