### ISSUE TITLE
AppImage does not support FIDO2 WebAuthn

### ISSUE THREAD

**Issue by eagerto-learn** [bitwarden/clients#5001]
### Steps To Reproduce

1. Setup your account with FIDO2 WebAuthn as your only 2FA method
2. Launch the AppImage (either from terminal or from file manager, it does not matter)
3. Login with Email and Master Password
4. Wait for 2FA prompt

### Expected Result

It should prompt you to use FIDO2 WebAuthn. If not supported, it should prompt you to use a backup login method such as recovery codes.

### Actual Result

It gives the following Error:
"This account has two-step login set up, however, none of the configured two-step providers are supported by this device.
Please add additional providers that are better supported across devices (such as an authenticator app)."

The link below "Use another two-step login method" forwards to [this](https://bitwarden.com/help/lost-two-step-device/) link instead of letting you use another two-step login method.

### Screenshots or Videos

![bitwarden](https://user-images.githubusercontent.com/51919789/225071575-78be1a6c-abc5-403b-b030-7c43b3b9fec3.png)

### Operating System

Linux

### Operating System Version

Debian Bookworm (Testing)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

Your issue appears to be describing the intended behavior of the software. Recovery codes are not intended to be used on the desktop application. WebAuthn support on the desktop app is currently only supported on Windows 10 or later. If you want this to be changed, it would need to be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
