### ISSUE TITLE
Password doesn't generate special characters

### ISSUE THREAD

**Issue by kajtek2203** [bitwarden/clients#5010]
### Steps To Reproduce

The latest version of Bitwarden for Windows doesn't generate special characters in passwords.

### Expected Result

.

### Actual Result

.

### Operating System

Windows

### Operating System Version

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @kajtek2203 ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a missed option selection - please see the screenshot below that shows special characters being generated on the latest Windows Desktop Client:

<img width="1120" alt="Screenshot 2023-03-16 at 11 14 00" src="https://user-images.githubusercontent.com/71517198/225586728-22f0e65d-f971-40b1-b728-50eb8dfcbe09.png">


We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
