### ISSUE TITLE
Unlocking with Apple Watch Unlock unavailable while in clamshell mode, Macbook Air M1

### ISSUE THREAD

**Issue by FadyFaheem** [bitwarden/clients#5030]
### Steps To Reproduce

1. Device must be either plugged into a dock, in clamshell mode, can be using or not using DisplayLink (Used for multi display handling on m1)
2. Open the application for the first time
3. No option to unlock either with touch ID or Apple watch.

### Expected Result

Being able to use the Apple Watch to unlock Bitwarden

### Actual Result

No option available to unlock while in clamshell mode.

### Operating System

macOS

### Operating System Version

Centura 13.2.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.2.0 (7249)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

Bitwarden currently doesn't support unlock with apple watch, if clamshell mode is on, then the sensor cannot be touched, so Bitwarden can use your touch ID, you can remove the clamshell mode and it would work as expected. 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
