### ISSUE TITLE
The captcha does not appear in the extension for firefox on Android

### ISSUE THREAD

**Issue by bokoyolo** [bitwarden/clients#5048]
### Steps To Reproduce

After entering the password, you need to pass the captcha, which does not appear, so it is not possible to log in

### Expected Result

To make the captcha work, or to remove it

### Actual Result

The login is not working

### Screenshots or Videos

![Screenshot_2023-03-22-13-25-42-996-edit_org mozilla firefox](https://user-images.githubusercontent.com/71700565/226891329-e6344c76-76ba-4dd1-b3b2-059c6d547e2b.jpg)

### Operating System

Android

### Operating System Version

12

### Web Browser

Firefox

### Browser Version

111.1.0

### Build Version

2023.2.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Thanks for reaching out! I'm happy to help.
​
It is not recommend to try using the add-on in your mobile browser. For Android, we offer the application through the Google PlayStore: https://bitwarden.com/download/.
 
Once it is installed, you can set up auto-fill using one of these methods: https://bitwarden.com/help/auto-fill-android/ . Please feel free to reach out with any additional questions or concerns!

We use GitHub issues as a place to track bugs and other development related issues. 

The issue here will be closed.
