### ISSUE TITLE
Extension "Pop out to a new window" resizing no longer scales to the Window width

### ISSUE THREAD

**Issue by 29039** [bitwarden/clients#5071]
### Steps To Reproduce

1. Go to BitWarden Extension icon in your browser (Chrome/Edge tested)
2. Click on "Pop out to a new window" (Top left icon)
3. Click on Vault and brows to a Login item to view (as an example)
4. Resize the Window to be wider
5. 5. The Notes section no longer fills with width of the Window

Also applies to using URL chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/popup/index.html?uilocation=popout#/tabs/vault (Edge) or chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html#/ciphers?type=1 (Chrome)

### Expected Result

Here is an example from Chrome (not updated yet - 2023.2.0):

![image](https://user-images.githubusercontent.com/61966298/227409148-5676a03b-4361-4aa2-b975-6d8ef042001b.png)

### Actual Result

Example from MS Edge (extension has been updated)

![image](https://user-images.githubusercontent.com/61966298/227409234-67b1a7c1-620b-4919-9a59-6038639fa121.png)

Additionally, this icon: 
![image](https://user-images.githubusercontent.com/61966298/227409294-566f060c-2955-4279-94d2-4f6346232f81.png)

Only goes up/down in size, not left/right

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome, Microsoft Edge

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Doohie** [comment]
Since today I notice that the extension pops out when you want to log in with Duo two-step login (see image).
This does not happen if you use another two-step method.
Why is this happening now…pretty annoying.

![Capture](https://github.com/bitwarden/clients/assets/148036118/4124685d-22ab-433f-bcf6-6ffd2bbc5305)

**Comment by trmartin4** [comment]
@29039, we believe this issue is resolved.  If you continue to experience the issue, please feel free to re-open the ticket or create a new one with reproduction steps.

@Doohie, that is due to a change in Duo's SDK, in which they are moving away from an `iframe` implementation (embedded in the popup) to a redirect-based flow that requires interaction with the browser.  Due to the ephemeral nature of the popup, this requires the user to pop it out.

**Comment by 29039** [comment]
> @29039, we believe this issue is resolved. If you continue to experience the issue, please feel free to re-open the ticket or create a new one with reproduction steps.

I tested it again and it does not seem fully resolve. When popping out, moving the window size will stretch the contents a little bit - up to about 2/5 of the screen, and then go small again, rather than being able to use up full screen space.

When using chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html#/tabs/current directly, no resize is possible. Only up/down on the textarea triangle.
