### ISSUE TITLE
Unlock Vault chooses its own autofill

### ISSUE THREAD

**Issue by Josephur** [bitwarden/clients#5079]
### Steps To Reproduce

Right click a username/password field while vault is locked, and choose Unlock Vault

### Expected Result

Vault is unlocked

### Actual Result

Vault is unlocked and if you have multiple logins for the site saved it just picks one and autofills.  Would be nice if it asked which user/pass to use but nope it just picks one.

### Operating System

Windows

### Operating System Version

Windows 11 22H2 22621.1413

### Web Browser

Chrome

### Browser Version

111.0.5563.111

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @Josephur,

Thank you for your report. It sounds like you have (Auto-Fill on Page Load) activated, and that is causing the extension to Auto-Fill the last-used matching credentials (vault item) the moment it's unlocked; If that is the case, it's the expected behaviour, and if you'd like the extension to ask you which vault item to Auto-Fill in this particular scenario, please feel free to suggest this in our community (https://community.bitwarden.com/c/feature-requests/5) and hopefully we'd incorporate your idea in a future release.

If you have a different setup, please create a support ticket through our Help Centre (https://bitwarden.com/help/) and include a link to this GitHub report, and we'll look into this.

We use GitHub issues as a place to track bugs and other development related issues; I will close this report now.


Thank you again,

**Comment by joshtrichards** [comment]
@Josephur - If you use the keyboard shortcut you can rotate through the matching logins:

> If there are multiple logins with the detected URI, the last-used login will be used for the auto-fill operation. You can cycle through multiple logins by repeatedly using the keyboard shortcut.

From https://bitwarden.com/help/auto-fill-browser/#using-keyboard-shortcuts

(By default the last used is filled in).

I personally leave Auto-Fill on Page Load off so that I have control over when/what credentials are filled in. Then I rely on a mixture of the keyboard shortcut, right-clicking and selecting the entry directly, or selecting it from the extension drop-down... depending on my mood and the circumstances.
