### ISSUE TITLE
KDF iterations on encrypted exports set to 100k

### ISSUE THREAD

**Issue by EchoDev** [bitwarden/clients#5082]
### Steps To Reproduce

1. Click on Bitwarden icon
2. Settings
3. Export vault
4. Choose file format .json (encrypted)
5. Fill in password
6. Export

### Expected Result

Higher KDF iterations on encrypted exports

### Actual Result

According to Bitwarden documentation the KDF iteration on export seem to be set to PBKDF2 with 100,000 iterations. Seeing how with the release of 2023.2.1 this was increased to 600k, should exports be adjusted too? (And maybe include an option for Argon2)

https://bitwarden.com/help/encrypted-export/

### Operating System

Windows

### Operating System Version

Win 10 x64

### Web Browser

Firefox

### Browser Version

Firefox 111.0.1

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by quexten** [comment]
I made a pull request for this a while ago. The pr makes the encrypted export have the same kdf configuration as your account settings, instead of being hard-coded. At the time argon2 support was not merged yet, so I had to rebase the PR to work with the current version. https://github.com/bitwarden/clients/pull/4479 If/once merged, it should fix this issue.

**Comment by SergeantConfused** [comment]
Hi @EchoDev,

Thank you for this report. While this matter indeed is on our radar (https://github.com/bitwarden/clients/pull/4479), your report is more of a feature request; Generally speaking, those can be submitted in our community (https://community.bitwarden.com/c/feature-requests/5). In this case, you're more than welcome to create a topic there, but I think that may not be needed since there already is a PR for this.

We use GitHub issues as a place to track bugs and other development related issues; I will close this report for now.

Thank you again,
