### ISSUE TITLE
Open desktop app logs out the browser extension

### ISSUE THREAD

**Issue by ywwry66** [bitwarden/clients#5094]
### Steps To Reproduce

First off, I want to mention this issue only happens when I update Bitwarden desktop app on the Mac App Store. The problem is that it persists for a while before fixes itself.

0. Update Bitwarden desktop app on the Mac App Store.
1. Open Bitwarden Safari extension and log in with Touch ID.
2. Open Bitwarden desktop app and log in with Touch ID.

### Expected Result

The browser extension stays logged in.

### Actual Result

The browser extension is logged out. A landing page pops up (https://bitwarden.com/browser-start/). I can understand if this only happens once. However, after several times closing and reopening the desktop app and browser extension, this behavior still happens. It will eventually go away mysteriously.

### Operating System

macOS

### Operating System Version

13.3

### Web Browser

Safari

### Browser Version

16.4

### Build Version

2023.3.1 (7892)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please reach out to us via our contact form so we can further look into your issue. https://bitwarden.com/contact/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
