### ISSUE TITLE
Bitwarden login page show private mode warning when using Firefox Multi-Account Containers addon

### ISSUE THREAD

**Issue by gy-chen** [bitwarden/clients#5115]
### Steps To Reproduce

1. Open a website using Firefox Multi-Account Containers addon.
2. Press Ctrl + Shift + L to open Bitwarden login page. The login page will show private mode warning.

### Expected Result

Bitwarden should not show private mode warning in Firefox Multi-Account Containers.

### Actual Result

Bitwarden show private mode warning in Firefox Multi-Account Containers.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6715543/228843435-c16ed373-a160-4e6a-a3ae-2ac7c3b916b3.png)

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

v111.0

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by arm32x** [comment]
I also have this issue. Another thing to note is that unlocking the vault does not work from the opened tab when the private mode warning is shown (at least when using a PIN).

**Comment by AreiousX** [comment]
Same issue on Windows, Ctrl + Shift + L to unlock and fill password will show private mode warning, no problem for non container tabs. Have to manually unlock by clicking on the extension, then Ctrl + Shift + L to autofill.
Windows 10.0.19045
Firefox 111.0.1
Browser version: 2023.3.0
Desktop version: 2023.3.1

**Comment by yureiita** [comment]
I also have this issue. The issue started after upgrading to 2023.3.0. It was working with 2023.2.0. Looks like #5138 also have the same issue.

https://user-images.githubusercontent.com/26035759/229340088-5f5dd5aa-fbe8-4710-a7e9-fa32a31c37c3.mov

**Comment by shanedk** [comment]
I'm having this issue even when I'm not using containers. If I go to Manage Extension and turn it off and back on, it behaves properly for awhile.

**Comment by scottwallacesh** [comment]
I am experiencing the same issue. I removed the Bitwarden extension and re-installed it but the problem persists.

Firefox v112.0 (64-bit) on Linux.
Multi-Account Containers extension v8.1.2.
Bitwarden extension v2023.3.0.

**Comment by KL4RKS** [comment]
OS: Windows 10 Enterprise 
  Version: 22H2 
  OS Build: 19045.2728
Firefox: 111.0.1
Bitwarden: 2023.2.1

Firefox Container Settings in about:config
- privacy.userContext.enabled: true
- privacy.userContext.newTabContainerOnLeftClick.enabled: true
- privacy.userContext.ui.enabled: true 

Open a login page in a container tab
Use CTRL+SHIFT+L while extension is locked
- Loads bitwarden unlock page (moz-extension://{{extensionID}}/popup/index.html?uilocation=popout#/lock) in a non-container tab
- asks for PIN (as setup)
- after entering PIN + ENTER, 
  - Bitwarden tab closes
  - Bitwarden extension unlocks
  - Username/password auto fill on the login (container tab)

Update Bitwarden Extension to 2023.3.0
Use CTRL+SHIFT+L while locked
- Loads bitwarden unlock page (moz-extension://{{extensionID}}/popup/index.html?uilocation=popout#/lock) in a container tab 
- Asks for password (instead of PIN) while displaying a warning about private mode
- After entering password + ENTER, 
  - Bitwarden tab remains open (as a container tab)
  - Bitwarden extension remains locked (though the icon occasionally flashes the number of login items)
  - Username/password remain blank on the login (container tab) even after manually closing the Bitwarden (container) tab

https://user-images.githubusercontent.com/2390741/230152091-01a21cc7-3eb2-4a01-88bb-478ae765d365.mp4

**Comment by difigue** [comment]
I'm having the same issue on Firefox Developer Edition 113.0b4 for Mac. Autofilling is treating containers like Private Mode, opening a new tab which after unlocked, it just returns "There are no logins available to auto-fill for the current browser tab". Been using containers for a long time but just recently adopted Bitwarden as my pass manager.

**Comment by jedfonner** [comment]
I'm having the same issue.  I mistakenly opened a new issue - #5261 which I've now closed as a dup of this one.  I am also using Multi-Account Containers.

**Comment by mmlb** [comment]
I'm having the same issue but also did notice a few other things. If I unlock the vault I get what everyone else is seeing (a new tab mentioning private mode, and "There are no logins available to auto-fill for the current browser tab"). If I try to autofill again while within the re-lock-ttl I get another tab opened asking to unlock as if in private browsing mode *but* bitwarden actually fills in the password into the fields. So it seems like its even more confused than previously thought.

**Comment by MG2R** [comment]
This issue has been closed but I don't think the PR which is supposed to fix this actually fixes this. I'm still seeing the same behavior: multi-account containers on FF breaks the auto-fill/auto-ask-for-pin functionality of the plugin for me.

**Comment by SergeantConfused** [comment]
Hi @MG2R,

Are you using extension version 2023.5.0?


Thank you in advance,

**Comment by kopach** [comment]
hi @SergeantConfused. When version `2023.5.0` going to be released? https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/ has only version `2023.4.0`
![image](https://github.com/bitwarden/clients/assets/8749624/c7ab2f21-177f-46ed-8199-95425ff0e502)

**Comment by aamirazad** [comment]
@MG2R and @kopach, The Bitwarden extension version `2023.5.0` was [released](https://github.com/bitwarden/clients/releases/tag/web-v2023.5.0) on May 31 from what I see. It fixes the issue for me running Firefox version `114.0` on Linux. Try updating.
<details><summary>Screenshot</summary>
<p>

![image](https://github.com/bitwarden/clients/assets/82281117/c12d7f81-94d0-4bb9-8ad8-4c49971e9411)

</p>
</details>

**Comment by difigue** [comment]
Not OP but it is working for me in 2023.5.0

**Comment by kopach** [comment]
I can also confirm, In version 2023.5.0 it works for me as expected
