### ISSUE TITLE
Tray icon not appearing

### ISSUE THREAD

**Issue by JohnB1776** [bitwarden/clients#5121]
### Steps To Reproduce

1. Go to 'File > Settings'
2. Click on 'minimize to tray, close to tray, all icon options' fails make icon appear in the system tray

### Expected Result

Icon in the tray as well as icon behaior that worked in previous version

### Actual Result

No icon in the system tray regardless of combination of selections in settings

### Additional Context

Version 2023.3.1
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

### Operating System

Windows

### Operating System Version

Windows 11 Version 22H2 (OS Build 22621.1485)

### Installation method

Microsoft Store

### Build Version

2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue using the same desktop app version and Windows OS version, but was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
