### ISSUE TITLE
Firefox multi-account Containers - autofill stopped working

### ISSUE THREAD

**Issue by nickwilliams-codynamic** [bitwarden/clients#5138]
### Steps To Reproduce

1. Launch firefox
2. Install multi-account containers https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
3. Launch a tab as an account container
4. Press CTRL+SHIFT+L

### Expected Result

You should be prompted to enter your vault password and Bitwarden should auto-fill the login form

### Actual Result

Bitwarden shows "Private mode support is experimental and some features are limited" - auto fill does not seem to work.
This was working until recently.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @nickwilliams-codynamic,

Thank you for your report. I attempted to reproduce this with Bitwarden browser extension 2023.3.0 in Firefox 111.0.1 with Firefox Multi-Account Containers 8.1.2, and was unable to do so; Please try installing your Bitwarden browser extension anew because a fresh installation may assist, and please check the (Privacy & Security) pane the Settings menu of your browser to see if it's set to never remember history as that may cause this. If this persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ and please include a link to this report in the body of your message.

Alternatively, you can get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you,

**Comment by scottwallacesh** [comment]
I am experiencing the same issue.  I removed the extension and re-installed it but the problem persists.

Firefox v112.0 (64-bit) on Linux.
Multi-Account Containers extension v8.1.2.
Bitwarden extension v2023.3.0.

**Comment by KL4RKS** [comment]
@zwn, I believe this is a symptom of issue #5115. Auto-fill (after unlock) should work again once that's resolved. Pull request #5116 should address both issues.

This issue doesn't specify that it's only an issue when the vault is locked, but my experience has been that auto-fill still works when the vault is unlocked. If you're having issues auto-filling when the vault is locked, that might be something different.
