### ISSUE TITLE
Logins list doesn't display single host URLs

### ISSUE THREAD

**Issue by rubencm** [bitwarden/clients#5143]
### Steps To Reproduce

1. Go to a host url like `myhost` (It seems to be working with `localhost`, so ignore the url in the sample images)
2. Click the bitwarden icon and add a login
3. Click again the bitwarden icon
4. The login you just added isn't displayed in the logins list

### Expected Result

![](https://i.imgur.com/mG6zPu2.png)

### Actual Result

![](https://i.imgur.com/PZ3bumq.png)

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c1-jack** [comment]
Hi there,

I attempted to reproduce your issue, and I think your error could have its origin in a misconfiguration of the URI match detection setting.  Exact or Host should work correctly in this scenario.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
