### ISSUE TITLE
Autosync settings for browser client

### ISSUE THREAD

**Issue by GRbit** [bitwarden/clients#5158]
### Steps To Reproduce

I'm sorry, it's not a bug report, but a feature request. Unfortunately, I'm not allowed (for some reason) to create new topics here https://community.bitwarden.com/c/feature-requests/5/none/l/new
So I've end up writing here.

I need to make my autosync work without websockets and I don't see any setting like this in bitwarden browser app. I know that websockets are better, but please, add a fallback for the old way of syncing with plain https requests every X minutes.

Appreciate all  your work, many kudos to you for such a great open source project.

### Expected Result

Be able to set up autosync to work without websockets.

### Actual Result

It's impossible.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

111.0.1 (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked. If your issue with being unable to post in the forums persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

This issue will now be closed. 

Thanks!
