### ISSUE TITLE
[Web] Login & Create account button placement is confusing

### ISSUE THREAD

**Issue by computer1up** [bitwarden/clients#5163]
### Steps To Reproduce

Not so much a bug nor a feature request (more a UX 'bug' so to speak). In our organisation, when we invite new members, they get to create a new account. However, on the account creation page, the buttons for "Create account" and "Log in" are somewhat confusingly placed. Many of our users click the "Log in" button after filling out the form on 'autopilot' so to speak, as usually a button to continue/sending in a form is placed in the bottom right. 

However, this doesn't prompt the user that their account has not been created yet and that in moving on to the login page, the previously filled in info is lost. 

This also happens sometimes when the user clicks the "Create account" button, is asked to complete a captcha, and then clicks the "log in" button to proceed. Again, this is *technically* a user thing, but it *is* a little confusing. 

My suggestion would be to move the "Log in" button somewhere else on the page and putting the. "Create account" button in a more expected place. 

### Expected Result

As described above. 

### Actual Result

As described above. 

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

Web vault, so presumably always the latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @computer1up ,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by computer1up** [comment]
Hi @atjbramley, thank you for taking a look. I disagree, this is not a feature request. I stated as such in the description.
