### ISSUE TITLE
Unable to copy custom field name in desktop client (Windows)

### ISSUE THREAD

**Issue by 0x4c6565** [bitwarden/clients#5179]
### Steps To Reproduce

View custom field, observe no way to copy custom field name without editing

### Expected Result

Able to copy field name

### Actual Result

Unable to copy field name without going into edit mode

### Additional Context

This used to be possible as the field name text could be selected, but is no longer possible.

This is possible in browser extensions by right clicking the custom field:

![image](https://user-images.githubusercontent.com/7476213/230561790-239b9c89-662c-4734-b2ea-24167aca52ea.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @0x4c6565 ,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

Please note that the 'Copy Custom Field Name' feature will copy the custom field of a form element in the DOM.  It cannot be used to copy the custom field name from a stored Bitwarden vault item.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by 0x4c6565** [comment]
My bad @atjbramley, i'll open a feature request now.
