### ISSUE TITLE
[Bug] "Open vault in sidebar" shortcut toggles the visibility of the sidebar twice

### ISSUE THREAD

**Issue by MahdiNazemi** [bitwarden/clients#5185]
### Steps To Reproduce

1. Press the shortcut key for "Open vault in sidebar"

### Expected Result

I can imagine the expected result to be one of the following:

1. Always open the sidebar (as the name suggests) regardless of whether it is already opened or closed
2. Open the sidebar if it is closed and vice versa (which suggests changing the title to something like "Toggle vault in sidebar")

### Actual Result

1. If the sidebar is closed, pressing the shortcut opens it and then closes it immediately, so the sidebar just flashes for a very short time.

2. If the sidebar is opened (by going to View -> Sidebar -> Bitwarden), pressing the shortcut closes it and then opens it immediately.

### Operating System

macOS

### Operating System Version

13.3.1

### Web Browser

Firefox

### Browser Version

111.0.1

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @MahdiNazemi,

Thank you for your report. I attempted to reproduce your issue and was unable to do so using the same version of macOS, Firefox, and Bitwarden extension. In my case, pressing OPTION+SHIFT+Y opens the Sidebar, and pressing it again closes it, both when the extension is logged out or unlocked. I'd recommend you uninstall the extension, clear any leftover data (https://bitwarden.com/help/data-storage/), reboot, and install it anew.

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ and please include a link to this report in your message.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you again,

**Comment by MahdiNazemi** [comment]
Thank you for trying to reproduce this issue.

Removing the shortcut and redefining it solved the problem for me.
