### ISSUE TITLE
Occasional garbled text (encoding issue?)

### ISSUE THREAD

**Issue by koitsu** [bitwarden/clients#5201]
### Steps To Reproduce

Unsure how to reproduce issue reliably.  I've seen this happen a couple times whilst testing Bitwarden (I began testing in January).

The purpose of this ticket is to find out if anyone from the Bitwarden team has seen this problem before, and if so, if it's something that has been fixed or not.

The attached screenshot is from January 14th, 2023.

### Expected Result

Non-garbled text.

### Actual Result

Garbled text.

### Screenshots or Videos

![bitwarden-wtf](https://user-images.githubusercontent.com/8430773/231505979-c5ed7752-1c51-47cd-aa4f-4900d301f838.png)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Brave

### Browser Version

107 or 108 of Chromium (I forget)

### Build Version

Don't remember (sorry)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error may be resolved by logging out of the extension, clearing cache, cookies, etc., restarting your device, and then logging back in.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
