### ISSUE TITLE
Launch behavior does not act as expected.

### ISSUE THREAD

**Issue by MITstud1993** [bitwarden/clients#5285]
### Steps To Reproduce

Launch Google Chrome.
Sign into Bitwarden extension.
Click on bitwarden extension and search for desired website.
chrome bitwarden extension shows desired website, and 4 options which include launch.
click on launch
Browser hangs.

### Expected Result

Should launch the desired website and autofill login fields 

### Actual Result

Spinning wheel of death/website does not launch.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

Recent

### Build Version

2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

I attempted to reproduce your issue and was unable to do so. Please ensure that your browser is up-to-date as well as the Bitwarden extension (current version as of this comment is 2023.4.0). Additionally, please try to isolate this issue by disabling any other extensions that might be active to ensure there aren't other external factors potentially interfering with the extension.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
