### ISSUE TITLE
Fails to Launch After Update on Windows 11

### ISSUE THREAD

**Issue by rzrabbi** [bitwarden/clients#5317]
### Steps To Reproduce

1. Install the latest version of the software (version 2023.3.0)
2. After using for few days a Pop-up window appeared called "Restart to update" 
3. Click on "Restart" to apply the update.
4. After the update is applied, try to launch the software.

### Expected Result

The software should launch normally and be fully functional after the update is applied.

### Actual Result

After the update, the software fails to launch.

### Additional Context

The issue occurs every time a update is applied. I am using Bitwarden for more than a year. I am facing this issue on Windows 11. Previously, on Windows 10, didn't faced this kind of issue. I have tried reinstalling the software, and it works fine after that. However, this is not a sustainable solution as I have to reinstall the software every time it updates. It would be helpful if the developers could investigate this issue and provide a fix.

### Operating System

Windows

### Operating System Version

Windows 11 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @rzrabbi,

Thank you for your report. This can happen when there is more than one installation of the desktop client, such as when it is installed once (Per User) and once more (For All Users); In this case, I recommend that you uninstall any and all the desktop clients that you have and remove all leftover data (https://bitwarden.com/help/data-storage/) and then install the desktop client anew only once; If you have more than one Windows User account, please perform this in all of them. If you'd like to take this a step further, you can download and install an older version (https://github.com/bitwarden/clients/releases) to see how it updates promptly, instead of waiting for version 2023.5. To be clear, I use Windows 11 Pro (22H2) and have updated the Bitwarden desktop client repeatedly without encountering such behaviour, and I installed it as (For All Users).

If this persists, please feel free to get in touch with us (https://bitwarden.com/help/) and please also include a link to this GitHub report, and we'll assist in troubleshooting this.

Alternatively, you can also get assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/), if you wish. 

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you again,
