### ISSUE TITLE
Windows hello prompt unlocks with just a click of the mouse!

### ISSUE THREAD

**Issue by DimitriosPi** [bitwarden/clients#5341]
### Steps To Reproduce

1. Go to 'windows hello prompt"
2. Click on 'windows hello prompt'
4. Click on '...'

### Expected Result

Windows hello prompt unlock with fingerprint or/and PIN or/and master password 

### Actual Result

Windows hello prompt unlocks with just a click of the mouse

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.4.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @DimitriosPi ,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, could you please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content, and please include screenshots or a video of this particular issue.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ados8** [comment]
Hi all,
I've had this issue for ages regarding Windows Hello on multiple devices.
I'm not sure if it's Birwarden specific as its mainly primarily the app I use for Hello authentication other than lock screen.

Anyway, it was annoying enough that I made a simple app that mitigates it completely.
It's freely available here: [](https://github.com/ados8/Hellofy)
May it make your lives easier 😉.
