### ISSUE TITLE
Blank white screen on client launch

### ISSUE THREAD

**Issue by athshean** [bitwarden/clients#5343]
### Steps To Reproduce

1. Launch BitWarden client via .AppImage

### Expected Result

BitWarden client launches (and the UI is visible)

### Actual Result

The window just shows a white screen.

### Screenshots or Videos

![Uploading Screenshot from 2023-05-01 21-45-16.png…]()

### Additional Context

![Screenshot from 2023-05-01 21-45-16](https://user-images.githubusercontent.com/107076468/235874544-57368f42-ccee-4ab3-8839-5362a85464e6.png)

Installed via .AppImage

The problem is fixed if I close BitWarden and re-launch it.
The problem is more likely to occur on boot and BitWarden runs at startup.

It does not happen all the time. It only happens sporadically (once every three to four boots). And it is difficult to ascertain what causes it.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.2 LTS

### Installation method

Other

### Build Version

Version 2023.4.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @athshean

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, could you please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

You can include a link to this issue in the message content, and please include screenshots or a video of this particular issue.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.
