### ISSUE TITLE
Badge counter is not showing causing issue with Autofill

### ISSUE THREAD

**Issue by vandriot** [bitwarden/clients#5349]
### Steps To Reproduce

1. Open a website where you have a login saved in Bitwarden
2. Check the badge counter on the Bitwarden extension icon, no number is showing
3. Try to trigger the AutoFill shortcut (CTRL+SHIFT+L)

### Expected Result

You should see a number on the Bitwarden extension icon telling you how many login you have for this website. 
You should be able to press CTRL+SHIFT+L to trigger the AutoFill.

### Actual Result

The icon remains the same without any number showing like you had no login for the website. 
When I press the shortcut to autofill, nothing happens. 

### Screenshots or Videos

![2023-05-03 19_57_29-](https://user-images.githubusercontent.com/22450119/236004167-a9002642-0ad5-4feb-8c5f-4e23d91453ca.png)

### Additional Context

If you go to Settings > Options, disable and enable the option "Show badge counter", the badge counter starts to work. 
The AutoFill still doesn't work.
It is just a temorary fix, if you reload the web page, the counter disapears again.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

112.0.5615.138 

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try clearing cache, cookies, etc. in your browser and restarting your device to see if that helps resolve the issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
