### ISSUE TITLE
Remove the password length limitation

### ISSUE THREAD

**Issue by Marin-Kitagawa** [bitwarden/clients#5387]
### Steps To Reproduce

Why are you limiting the passwords to just $5000$? I may have password with length of even $10000$. That's my wish. Remove this

This is the error I get.
`The field Password exceeds the maximum encrypted value length of 5000 characters.`

### Expected Result

No password limitations

### Actual Result

The field Password exceeds the maximum encrypted value length of 5000 characters.

### Operating System

Windows, Linux

### Web Browser

Microsoft Edge, Opera, Brave

### Build Version

I am using web-based import from Dashlane 

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c1-jack** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
