### ISSUE TITLE
Safari extension fails login when using system biometrics.

### ISSUE THREAD

**Issue by Snarj** [bitwarden/clients#5390]
### Steps To Reproduce

1. Go to Safari > Bitwarden extension > Settings
2. Toggle 'unlock with biometrics' to checked.
3. Lock or close/reopen browser to get login biometrics prompt
4. Fail to log in after successful biometrics authentication with error:

"Account missmatch The desktop application is logged into a different account. Please ensure both applications are logged into the same account."

### Expected Result

Successful login to safari extension.

### Actual Result

Failure.

### Additional Context

Biometric login works perfectly on desktop Bitwarden client so it's unlikely to be a problem with biometrics, OS, or keychain.

Has failed in this way for years, on intel, m1, and M1 Pro systems. Tested OS have been macOS 11, 12 and 13. Reinstalling Bitwarden does not resolve it. Reinstalling macOS does not resolve it.

### Operating System

macOS

### Operating System Version

11, 12, 13

### Web Browser

Safari

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @Snarj,

I attempted to reproduce this and was unable to do so. I suspect that the desktop client is logged into a different account and/or another application is interfering with the communication between the extension and the desktop client; I would test this in a different browser, such as Chrome, to check if it's isolated to Safari in order to know how to proceed. To be clear, I tested this with Bitwarden 2023.4.0, Safari 16.4, and macOS 13.3.1 (a) whilst the desktop client was logged into a single account and it worked as expected.

We use GitHub issues as a place to track bugs and other development related issues. If this persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/help/ and please include a link to this report in the message content.

Alternatively, you can seek assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.


Thank you,

**Comment by Snarj** [comment]
> We use GitHub issues as a place to track bugs and other development related issues.
That is what this is, a bug.

There are several other closed reports that all explain the exact same behaviour. It has been reported and continues to persist. A quick google gives two more people with the exact same error and no resolution.

https://github.com/bitwarden/clients/issues/2522

https://www.reddit.com/r/Bitwarden/comments/11tj1wu/unlock_with_touch_id_on_mac/


Please consider reopening and fixing this bug.
