### ISSUE TITLE
Font Size Change changes back after restart

### ISSUE THREAD

**Issue by VKWL** [bitwarden/clients#5393]
### Steps To Reproduce

1. Change the Font Size (larger)
2. Close Bitwarden
3. Start again
4. Font size is back to the original setting :(

### Expected Result

I expect it to remain to my changes

### Actual Result

it reverts back to the original font size

### Operating System

macOS

### Operating System Version

13.3.1a

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try restarting your device and uninstalling/reinstalling the application. If you are unable to resolve the issue with those steps, please contact us via our Help Center: https://bitwarden.com/help/

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
