### ISSUE TITLE
Ask to add login not saved across installs

### ISSUE THREAD

**Issue by smartinellimarco** [bitwarden/clients#5405]
### Steps To Reproduce

1. Disable ask for login
2. Reinstall the extension or app (in mozilla, chrome, safari)
3. Log into a website

### Expected Result

Ask to save login disabled

### Actual Result

Ask to save login enabled

### Operating System

macOS, Linux

### Web Browser

Chrome, Safari, Firefox

### Browser Version

Any

### Build Version

Version: 2023.4.0  Server version: 2023.4.3 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment]
Hey there,

it's actually the intended behavior of cookies to store settings locally and not across different browsers or sessions. This means that if you uninstall the app or clear out your browser session, the cookies (and your saved settings) will also be erased.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
