### ISSUE TITLE
cli client still requires passwor to unlock, thus API key useless

### ISSUE THREAD

**Issue by tessus** [bitwarden/clients#5408]
### Steps To Reproduce

1. add your API client id and secret as env vars
2. `bw login --apikey`
3. try to create a send

### Expected Result

I should be able to create a send.

The whole reason for using API key(s) is to not expose a password and being able to rotate the key(s) at any time. 
So, using API keys in a bash script is the way to go.

Yet, I can't use the client, because I still have to unlock the vault, which requires... my master password. Hmmm. I am not going to put that in a script...

### Actual Result

I have to unlock the vault with my master password, which renders the API keys useless.

### Operating System

macOS, Linux

### Operating System Version

macOS 13.x, 10.14, 10.15. Fedora 37, 37. Debian 11

### Shell

Bash

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tessus** [comment]
I do not know, if this is a bug or intentional behavior. I tried to start a discussion, but they are used to propose code changes or ask whether code will be merged. Not really a discussion about the product.

Either way, if this is intentional behavior, please explain the logic behind this. How is someone supposed to use `bw` in a script without having to expose the master password?

I am also more than happy to use a different way (mail, forum, smoke signals, ...) to discuss this. Please advise.

**Comment by atjbramley** [comment]
Hi @tessus,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

Send is currently an Individual (i.e. not Organisational) feature, and as such creating a Send requires logging into the Individual Vault, for which authentication requires the master password.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by tessus** [comment]
@atjbramley Thanks a bunch for the reply.

I do not necessarily want to have it changed, but rather have a discussion about the design. I will certainly create a forum post, but I hope that bw devs are also in the forum. It won't make sense to discuss this with community members.

I believe there should be a difference between accessing the vault and craeting a send.

Accessing the vault should be guarded by a user/pwd login (which returns a session key) or an API login, and unlock (which also creates a session key).
The same is true for editing and listing sends.

However, for creating a send a login with the user's API client id/secret should be possible without having to unlock te vault. Otherwise using sends in scripts is pretty much impossible unless it is interactive (in which case I probably wouldn't need a script).

Also, creating a send should not be an organizational feature. It is still supposed to be an individual one.

Anyway, I will start a discussion on the forum. Let's see what happens... ;-)

**Comment by fredrikburmester** [comment]
Hi, did this ever change? I want to use an automated workflow but it doesn't seem possible without using the password?

**Comment by tessus** [comment]
Not that I'm aware of. I haven't been able to create sends in an automated fashion. Without using a password that is.

My solution was to create a separate user that is used for sends only. This password I can share with workflow pipelines.

**Comment by sandramars** [comment]
Hello, the same here. We want to automatize changing passwords and has to use apikey to access, then unlock with pasword to get it done.
It would be better if you can generate an API key with permissions to change some passwords, and rotate it from time to time if necessary.
Regards,

Sandra
