### ISSUE TITLE
Windows 11 Hello Facial Recognition Does Not Unlock BitWarden

### ISSUE THREAD

**Issue by jonatino** [bitwarden/clients#5425]
### Steps To Reproduce

1. Enable Windows 11 Hello with a compatible facial recognition camera (I'm using Dell WB7022).
2. Setup bitwarden to allow Windows Hello unlocking
3. Try to unlock using facial recognition

### Expected Result

BitWarden should unlock using Windows Hello facial recognition in the same way it unlocks when using a Windows Hello pin.

### Actual Result

The following dialog pops up, and after attempting to click Ok, the dialog just keeps showing up over and over again without ever unlocking BitWarden.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/1808569/5f9a07d0-c78c-4cc0-851a-22f4fc59a03f)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or corruption.  I would recommend:

- logging in with your master password
- removing Windows Hello support
- rebooting
- re-adding Windows Hello support

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jonatino** [comment]
@atjbramley I've already preformed those steps before creating this issue. This issue has the same behavior #5372 which is already a known bug.

**Comment by ssssamstrup** [comment]
I'm experiencing the same issue. Bitwarden is updated and Firefox extension is 2024.2.1.
