### ISSUE TITLE
Traffic from your network looks unusual. Connect to a different network and try again later [Error code 7]

### ISSUE THREAD

**Issue by shbrainard** [bitwarden/clients#5426]
### Steps To Reproduce

1. Go to Bitwarden Chrome Icon
2. Login
3. Enter password
4. Receive Error message

### Expected Result

I should be able to log on.

### Actual Result

Just now, with no change in my browser settings or internet connection, I was logged out of the Chrome Bitwarden extension, and am given the error message above whenever I try to log back in.

Chrome version: Version 113.0.5672.92 (Official Build) (x86_64)
OS: mac OS 12.6.5

I am able to use the iOS clients and even the Desktop app on this same computer, both connected to the same modem.  This definitively appears to be an issue with the Browser plugin.

I have rebooted my computer & browser to no avail.

### Operating System

macOS

### Operating System Version

12.6.5

### Web Browser

Chrome

### Browser Version

Version 113.0.5672.92 (Official Build) (x86_64)

### Build Version

Version: 2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
Hello everyone,

Thank you all for your input. This report appears to be describing the intended behaviour of the software; You can learn more about this here (https://bitwarden.com/help/unusual-traffic-error/) and you're more than welcome to follow the steps outlined in the guide to troubleshoot this.

We use GitHub issues as a place to track bugs and other development-related issues; This thread will now be closed.

Thank you again,

**Comment by shbrainard** [comment]
I disagree. None of the fixes to this issue in the link you supplied apply in this case:

1) I am not using a VPN or proxy server
2) I am not using Tor
3) My web browser and Bitwarden client are up to date
4) I have tried rebooting my router and computer

Importantly, the fact that this error persists in the browser, but not in the Desktop app or iOS app suggests it is indeed a bug.

 If the intended behavior of this feature is only to limit unusual traffic coming from one potential method of using Bitwarden, I guess I can't argue with you.  But that would be a pointless and very annoying intended behavior.

**Comment by Josephur** [comment]
They seem to not care about this, a few of us have complained about this and are told this is expected behavior.  I'm all for trying to keep a product secure, but if your making it so your product is not saving new password changes, and is so tedious to use then people will just go elsewhere.  There has got to be a way to implement the feature that keeps the product secure and also allow people to function.  The VERY least it could do is say hey your coming from an insecure IP location so the changes will only be saved locally until you return to a secure location in which time they will be synchronized to our servers.

Many of us use VPNs as normal activity and have IP addresses that change frequently from our ISPs, and those address ranges often get pegged in black list databases because someone at some point had the IP we're now using at not fault to our own... resetting our routers or reconnecting our VPNs is NOT a solution, it's only a half baked lord I hope they get a new IP and it's not on the blacklist too.... and maybe it'll work for them afterwards.

**Comment by shbrainard** [comment]
Yeah, after going back and forth with the support team, it seems the devs just added my IP address to a whitelist, and then it worked again.  Adjusting their template response to Github issues to be less patronizing & just explain that this is the only solution at the moment would definitely be appreciated.
