### ISSUE TITLE
Autofilling with shortcut key fills username that is different from corresponding password when multiple accounts exist 

### ISSUE THREAD

**Issue by yudhv** [bitwarden/clients#5436]
### Steps To Reproduce

1. Create multiple accounts for amazon.com (I have 5)
2. Go to [AWS consoler Sign In](https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3FhashArgs%3D%2523%26isauthcode%3Dtrue%26nc2%3Dh_ct%26src%3Dheader-signin%26state%3DhashArgsFromTB_us-east-2_4d9933c2894e37ca&client_id=arn%3Aaws%3Asignin%3A%3A%3Aconsole%2Fcanvas&forceMobileApp=0&code_challenge=O0CgZRsn17h6e7oGU0rH6c5-jpjYLf0XyuGcv19upxs&code_challenge_method=SHA-256)
3. Use a shortcut key to autofill the first username and press Enter
4. Use the shortcut key again on the next screen to autofill the password
5. Username and password incorrect message is shown. 

Tested only on Chromium (MS Edge) extension. 

### Expected Result

The password on the next screen (Step 3) should be coming from the same account where the username came from in the prior screen (Step 2). 

### Actual Result

Username comes from a different account than the password, thus causing a mismatch. 

### Additional Context

This happens only in cases where the username and password fields are not on the same page. When on different pages, the extension does not remember which username was chosen previously, and therefore selects a different item for password sometimes, thus causing a mismatch. 

PS - it would be really nice to select a default option from many accounts in the case where you prefer one account, but can't afford to lose the other accounts either. 

### Operating System

macOS

### Web Browser

Microsoft Edge

### Build Version

112.0.1722.39 (arm64)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @yudhv,

Thank you for your report. I attempted to reproduce your issue and was unable to do so. To be clear, I tested this with Edge on macOS and Firefox on Windows, and pressing the keyboard shortcut to perform Auto-Fill on the Password stage resulted in entering the Password from the same vault item that the Username/Email address were entered. I'd recommend making sure that you have no other Password Managers running on that browser. If this behaviour persists, please feel free to get in touch with us (https://bitwarden.com/help/) so we'd troubleshoot this together; Please try to test this in other browsers on that same machine to check if it's isolated to Edge, and please also include a link to this GitHub report in your message.

Alternatively, you can seek assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you again,
