### ISSUE TITLE
Firefox add-on does not redirect back when I have entered the master password

### ISSUE THREAD

**Issue by algomaster99** [bitwarden/clients#5553]
### Steps To Reproduce

1. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> on a new browser session. You are redirected to a different tab to enter the master password.
2. Once the password is entered correctly, one is not redirected back to the original page, which is contrary to the behaviour on Chrome.

### Expected Result

One should be redirected.

### Actual Result

One is not redirected.

### Operating System

Linux

### Operating System Version

Ubunut 22.04 LTS

### Web Browser

Firefox

### Build Version

109.0.1 (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try clearing cache, cookies, etc. in your browser, and then trying again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by algomaster99** [comment]
Hello again! I have reproduced the error in the following screencast. I hope it helps.

[Screencast from 2023-06-02 21:38:25.webm](https://github.com/bitwarden/clients/assets/35191225/bb2a77f2-20d9-419c-a0ba-5ba091b07465)

**Comment by algomaster99** [comment]
This may be an issue with [firefox container tabs extension](https://support.mozilla.org/en-US/kb/containers). However, this has been magically fixed now. Thanks!
