### ISSUE TITLE
Dark theme and full width layout settings do not persist (self hosted)

### ISSUE THREAD

**Issue by vinnyperella** [bitwarden/clients#5554]
### Steps To Reproduce

1. Log in to Web vault and go to Account Settings -> Preferences.
2. Change theme to "Dark", check "Display full width layout", then select "Save" at the bottom.
3. Log in to web vault with another browser, or log out of current session clear browser data and log in again.

### Expected Result

Dark theme and full width layout persist.

### Actual Result

Theme is reverted back to default "Light" and the full width layout is unchecked.

### Additional Context

It looks like these settings are being saved in the browsers local storage which is why clearing the browser data reverts the settings.

### Operating System

Linux

### Operating System Version

Ubuntu

### Web Browser

Firefox

### Browser Version

115.0

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development-related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
