### ISSUE TITLE
Chrome extension does not request 2FA when locked or logged-out

### ISSUE THREAD

**Issue by bernklh** [bitwarden/clients#5587]
### Steps To Reproduce

1. Be logged-in the chrome bitwarden extension
2. Click on 'Settings'
3. Click on 'Log out'
4. Wait for you to be logged out
5. Log in with master password

You get acces to the vault without 2FA

### Expected Result

When login via master password, bitwarden extension also asks for 2FA

### Actual Result

When login via master password, bitwarden extension does not ask for 2FA

### Operating System

Windows

### Operating System Version

10.0.19044

### Web Browser

Chrome

### Browser Version

114.0.5735.110

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @bernklh ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.  Please see our FAQ article on this below:

https://bitwarden.com/help/twostep-faqs/#q-why-is-bitwarden-not-asking-for-my-enabled-two-step-login-method

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
