### ISSUE TITLE
Click twice Windows 11

### ISSUE THREAD

**Issue by andyberks** [bitwarden/clients#5599]
### Steps To Reproduce

Click on 'desktop icon in fully updated Windows 11 when Bitwarden is not open.
The app doesn't open. You have to click on the icon a second time to get the app to open. 
This is not good behavior. It should only be necessary to click on the desktop icon once to open the app. 

### Expected Result

App should open on one click

### Actual Result

App doesn't open until the icon is clicked a second time. 

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.5.0 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

I attempted to reproduce your issue with the same environment and was unable to do so.

https://github.com/bitwarden/clients/assets/1657434/4d2360fb-54e3-4ea6-b7c5-a32faeaa9a7c

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by egrogg** [comment]
Hello,

I uploaded this file to show that I have to click twice to get the app to open on windows 11.

Not sure what the issue is but, here is the video...


https://github.com/user-attachments/assets/28d9940e-9e63-47fd-8a0b-10234dced55e

**Comment by andyberks** [comment]
This looks like a request I submitted 14 months ago. I have a vague
recollection that it was necessary to click multiple times to get things to
happen when I submitted this, but the problem is now resolved. Thanks

Andrew H. Berks, Ph.D., J.D.
Patent Attorney
Berks IP Law PLLC
85 Broad St 17th Fl
New York NY 10004 (US)
mobile: +1 845-558-7245 <http://voice.google.com/calls?a=nc,%2B18455587245>
<http://voice.google.com/calls?a=nc,%2B18455587245>
<http://voice.google.com/calls?a=nc,%2B18455587245>
***@***.***, berksiplaw.com  freship.com
LinkedIn <https://www.linkedin.com/in/andyberks/>
