### ISSUE TITLE
Installing freshly built unpacked extension gives errors on chrome

### ISSUE THREAD

**Issue by Polve** [bitwarden/clients#5644]
### Steps To Reproduce

1. checkout latest code
2. follow build instruction
3. load extension on chrome
4. go on extensions page
5. press the "errors" button on bitwarden extension

### Expected Result

no errors (?)

### Actual Result

I see these errors in the report page:
> Unrecognized manifest key 'applications'.

> Unrecognized manifest key 'sidebar_action'.

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/1634436/17ad8e82-99a1-4e79-96d8-5edf2b886b70)

### Operating System

Linux

### Operating System Version

Ubuntu 23.04

### Web Browser

Chrome

### Browser Version

114.0.5735.133

### Build Version

Version 114.0.5735.133 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Polve and thank you for your report.

This only occurs, when loading the extension unpacked. The keys mentioned from the manifest file are only supported on certain browsers. During the [bundling](https://github.com/bitwarden/clients/blob/master/apps/browser/gulpfile.js) of the specific browser packages those are removed as needed. 

The warning related to Manifest v2 is due to Google wanting to migrate to Manifest v3. For this case there is a separate build that can be used with `npm run build:mv3` vs `npm run build` (v2).

As these issue are unrelated to the packaged versions I am closing this now.
