### ISSUE TITLE
Desktop client (macOS) creates empty "tmp" folder

### ISSUE THREAD

**Issue by potesto** [bitwarden/clients#5652]
### Steps To Reproduce

1. Launch Bitwarden desktop client
2. Observe empty "tmp" folder created in Users/My_Username

### Expected Result

No folders should be created

### Actual Result

An empty folder named "tmp" is created in Users/My_Username

### Operating System

macOS

### Operating System Version

Big Sur 11.7.8

### Installation method

Homebrew

### Build Version

Version 2023.5.1 (9424)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the expected behavior of the software. If you want this to be changed, it would be a feature request. If this behavior is causing a problem in your environment, please contact Bitwarden support so we can provide additional assistance: https://bitwarden.com/contact/

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by dnicolson** [comment]
The forums don't seem to be tracking this, but I would suggest reopening this issue.

It's not clear from https://github.com/bitwarden/clients/commit/d1011870f0212d717da7c72a94a107da60900cc4 why Bitwarden needs to create a `tmp` directory in a user's home directory, it definitely seems like an anti-pattern.

Why not `/tmp` or at least a hidden directory like `~/.bitwarden/tmp`?
