### ISSUE TITLE
Cannot accept organization invite using device for login

### ISSUE THREAD

**Issue by WizADSL** [bitwarden/clients#5678]
### Steps To Reproduce

1. Get invited to an orgranization
2. Click the invitiation
3. Attempt to accept the invitation by logging into you vault using device unlock (I tested this in a desktop browser)

### Expected Result

Once logged into the vault you should see the organization status message informing you that you acceptance has to be confirmed

### Actual Result

You are just logged into your vault and no messages about organization membership appear

### Operating System

Windows

### Operating System Version

Windows 10 22H2

### Web Browser

Chrome

### Browser Version

114.0.5735.134

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @WizADSL, 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by WizADSL** [comment]
It may be expected behavior but there is no indication to the user that a master password login in required in order for the invitation to be accepted.  Perhaps the page that is linked to in the email received as a result of the invitation could have the login with device option removed or a message could be displayed about the requirement.
