### ISSUE TITLE
Should be saving both the username and email used on a site

### ISSUE THREAD

**Issue by WeebNetsu** [bitwarden/clients#5682]
### Steps To Reproduce

1. Go to any website that let's you sign up with a username and email
2. Click on sign up
3. Click save data to Bitwarden

### Expected Result

Both your email and username gets saved

### Actual Result

Your username gets saved

### Additional Context

A lot of websites makes you log in with your email and not your username, if you have multiple different emails this becomes an issue, as your password manager does not remember what email you used for the site, since it decided to save your username instead. A good solution to this could be to add an email field to the saved data in Bitwarden, then it can save both the username and email at the same time, or add the email to the notes (what I have to do manually, every time after signing up to a website)

### Operating System

Windows, Linux

### Web Browser

Chrome, Firefox, Brave, Vivaldi

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @WeebNetsu, 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
