### ISSUE TITLE
Bitwarden Linux desktop application don't save "stay connected"

### ISSUE THREAD

**Issue by realjench** [bitwarden/clients#5688]
### Steps To Reproduce

Hi.

I love your app. But since a moment even when you check stay connected on 2FA, it ask 2FA every time.

Version 2023.5.1
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

### Expected Result

Don't ask 2FA

### Actual Result

Ask 2FA

### Operating System

Linux

### Installation method

Snap

### Build Version

Version 2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @realjench ,

I attempted to reproduce your issue and was unable to do so.

Specifically:

- I installed Bitwarden 2023.5.1 on Debian via snap
- I logged into an account protected by a Yubikey 2fa
- I used the Yubikey to pass 2FA, selecting the 'remember me' button as I did so
- I logged out and back into the account repeatedly, and was never re-prompted for 2FA

I think your error could have its origin in a misconfiguration or corruption of your installation.  Please try performing a clean re-install, and then using the remember-me feature again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by atjbramley** [comment]
Hi @realjench, 

We use GitHub issues as a place to track bugs and other development related issues.  We do not offer tech support via GitHub.

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

**Comment by realjench** [comment]
Alright, thanks
