### ISSUE TITLE
Bitwarden is always in the foreground

### ISSUE THREAD

**Issue by astral-alpaca** [bitwarden/clients#5727]
### Steps To Reproduce

1. Start the Bitwarden Desktop app on macOS
2. Switch the focus to any other app

### Expected Result

Bitwarden moves to the background

### Actual Result

Bitwarden stays in the foreground overlaying the focused app.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/110965023/624285c6-99d6-40af-9312-205dc04d9f28

### Operating System

macOS

### Operating System Version

13.4.1

### Installation method

Mac App Store

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @astral-alpaca 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration; could you sign in your username and master password to see if issue persists if yes then may i suggest that you reinstall the Bitwarden desktop app; 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by astral-alpaca** [comment]
Ok, it was my fault 😅 There is an option to always show the window on top: 

![Screenshot 2023-07-06 at 06 48 59](https://github.com/bitwarden/clients/assets/110965023/0b979ef5-626c-4bc5-b313-be06a722d725)

Thanks for following it up though!

**Comment by jschwalbe** [comment]
That fixed my problem! Thanks!
