### ISSUE TITLE
Poor vault UX on desktop: undismissable "Go premium" banner window

### ISSUE THREAD

**Issue by iDubok** [bitwarden/clients#5735]
### Steps To Reproduce

1. Being under free account with verified email, go to the main vault page on web (Chrome): https://vault.bitwarden.com/#/vault
2. As you can see, "Go Premium" banner is neither dismissable nor collapsible, and it takes 1/4 of the usefull screen width (on a regular Full HD 1920px wide display).
 ![image](https://github.com/bitwarden/clients/assets/13876501/912b3745-b990-4063-9fe6-f741fc43eccb)
3. I see the desire to get more premium users, but I guess it would not hurt to place that banner (even undismissable one) above the vault table/grid, i. e. make it horizontal.

### Expected Result

The name column is wide enough on a regular desktop display, so it can display more text without ellipsis.

### Actual Result

The main content (vault table) space is taken by undismissable "Go premium" banner window, so the width of the name column is not sufficient.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

114.0.5735.199

### Build Version

2023.5.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @iDubok ,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
