### ISSUE TITLE
Bitwarden MacOS client cannot start

### ISSUE THREAD

**Issue by furballcoder** [bitwarden/clients#5736]
### Steps To Reproduce

1. Click on Bitwarden app.
2. Stuck on loading screen.

I have tried deleting and re-installing the app from Mac App Store and the issue still occurs.

See screenshot:

<img width="943" alt="Screen Shot 2023-07-04 at 11 35 14 AM" src="https://github.com/bitwarden/clients/assets/2327988/7909f26b-85b9-436c-b8f3-b11b05ae7b72">

### Expected Result

Bitwarden starts and I can look up my passwords as usual.

### Actual Result

Bitwarden could not start successfully and just loads forever.

### Operating System

macOS

### Installation method

Mac App Store

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @furballcoder, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption of your application, and would recommend a clean reinstall as follows:

- uninstall using AppCleaner (https://freemacsoft.net/appcleaner/)
- reboot your machine
- reinstall from the App Store

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, including your macOS version and details of the machine you're using Bitwarden on so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
