### ISSUE TITLE
Error : Can't Decrypt

### ISSUE THREAD

**Issue by GuizmoFR** [bitwarden/clients#5740]
### Steps To Reproduce

Login to your first account
Swtich to your second account
Login to your second account
All passwords are shows "Error : cant't decrypt"

### Expected Result

after login-in onto my second account, i have too see my password normally

### Actual Result

i didn't see my passwords.
I see at the place of my password the text "Error : can't decrypt"

### Screenshots or Videos

<img width="231" alt="Capture d’écran 2023-07-05 à 08 04 18" src="https://github.com/bitwarden/clients/assets/94701556/853e4390-4fff-4a30-ae6f-a850ecf97174">

### Operating System

macOS

### Operating System Version

Ventura 13.4.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

This is probably a bug in our visual interface. On which client are you experiencing this issue? 

If the issue is on the Web app or the browser extension, could you please clear all site data? Here is a guide on how to achieve this on the different browsers: https://www.contentstack.com/docs/developers/how-to-guides/clear-caches-and-cookies-in-different-browsers/ 

Could you also try signing in on a different browser or client if that doesn't resolve the issue?

If this is desktop client issue, could you please try to perform full clean reinstall? 

Thank you!

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/3057
