### ISSUE TITLE
List items/collections returns empty

### ISSUE THREAD

**Issue by UntiIted** [bitwarden/clients#5760]
### Steps To Reproduce

I couldn't say that this is reproducible with 100% consistency, but it happens often enough to be disruptive. Bitwarden is running on a self-hosted instance.

Commands run:
1. bw login --sso
2. bw sync
3. bw unlock
4. bw list collections

### Expected Result

Bitwarden lists all collections, regardless of organization.

### Actual Result

Bitwarden returns an empty list.

### Additional Context

bw status returns correct details, including server url and status. Last sync was performed just a few minutes ago.

What's interesting is that list org-collections returns correct results (i.e. `bw list org-collections --organizationid $organization.id`).

bw list items also returns empty but there is no org-items equivalent with which I could test.
Both list items and collections returns empty regardless of search/filters used.

Running this any number of times will produce the same result. Lock/sync/logout does not necessarily fix it either, although sometimes reboot and relogin fixes it.

### Operating System

Windows

### Operating System Version

11

### Shell

PowerShell

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please make sure your Bitwarden instance is running the latest version on the server. Information on updating your self-hosted Bitwarden instance can be found here: https://bitwarden.com/help/updating-on-premise/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
