### ISSUE TITLE
iOS bitwarden app failed login persistent "an error has occurred"

### ISSUE THREAD

**Issue by LEMD49** [bitwarden/clients#5762]
### Steps To Reproduce

0. reinstall bitwarden iOS app
1. click on bitwarden app to launch
2. enter user email
3. enter master password
4. log in
5. see message AN ERROR HAS OCURRED
6. NOTE ok with same credentials on macOS app and browser 

### Expected Result

failed login on iOS app but ok on others such a macOS app and browser

### Actual Result

failed to login

### Operating System

iOS

### Web Browser

Safari

### Build Version

na

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a network issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
