### ISSUE TITLE
Generate command doesn't use most options

### ISSUE THREAD

**Issue by Wdeb1** [bitwarden/clients#5787]
### Steps To Reproduce

1. Get Bitwarden CLI for windows (version 2023.5.0)
2. Open Powershell to the executable's location
3. execute command: bw generate --passphrase --words 3 --separator - --includeNumber --capitalize

### Expected Result

A passphrase of 3 words with Capital letters on each word separated by a dash with at least 1 word paired with a number.
e.g.

Testing2-Random-Password

### Actual Result

A password of the default 14 characters with capital & normal letters, numbers, and special characters.

e.g.
@C9rPP2%B*%5#e

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/139242091/08a0b2fe-fd4e-4359-9195-80ad48b2ce55)

### Additional Context

Same situation whether the cli was downloaded as stand-along executable or via Chocolatey.

The only option the generate command actually uses is the --length one.

### Operating System

Windows

### Operating System Version

19045.3086

### Shell

PowerShell

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please _bw logout_ and then log in again, does the issue persist?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Wdeb1** [comment]
@MarsCandyBars  Thanks for looking into this.

I did also fill in the contact form for this issue, they're looking into it.

I tried command several times with even device reboots in between and different methods of logging in (sso, apikey, regular login) and unlocking but the issue persists on my side.

As I am trying to use the bitwarden cli on windows, i tried the command on both command prompt and powershell but both gave the same erroneous behavior.
