### ISSUE TITLE
Arc browser integration does not work

### ISSUE THREAD

**Issue by fgeierst** [bitwarden/clients#5811]
### Steps To Reproduce

1. In Arc browser install the chromium bitwarden extension
2. In the Bitwarden Desktop app enable the checkbox "Allow browser integration"
3. In the Arc browser Bitwarden extension click on "Settings"
4. Click on "Unlock with biometrics"

### Expected Result

I can unlock Bitwarden vault with biometrics inside the Arc browser.

### Actual Result

An error message is shown "Browser integration is not set up"

### Screenshots or Videos

<img width="513" alt="Bildschirmfoto 2023-07-13 um 11 14 44" src="https://github.com/bitwarden/clients/assets/22551442/9730a66e-a24e-41c2-9387-e99bb0d5a6c2">

<img width="394" alt="Bildschirmfoto 2023-07-13 um 11 13 05" src="https://github.com/bitwarden/clients/assets/22551442/5ebef741-4db4-4644-b6f8-a7b5ba0c352c">

### Operating System

macOS

### Operating System Version

13.4.1

### Web Browser

Chrome

### Browser Version

Not Chrome, but Arc Browser 0.111.0

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @fgeierst, 

Despite being based on Chromium, Arc is not currently a supported browser.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
