### ISSUE TITLE
Edge logic for popout window

### ISSUE THREAD

**Issue by Chaython** [bitwarden/clients#5841]
### Steps To Reproduce

1. Open popout
3. right click popout on taskbar
4. pin to taskbar
5. click the pin
6. [edge/extensions](edge://extensions/) is opened

### Expected Result

Click the pin, it should open the popout window

### Actual Result

[edge/extensions](edge://extensions/) is opened

### Additional Context

I know this isn't necessarily a bug... But you should be able to accomplish opening the popout window by doing some modifications to the background.js and browser action in manifest.json

### Operating System

Windows

### Web Browser

Microsoft Edge

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @Chaython, 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
