### ISSUE TITLE
autohide not working in certain situations

### ISSUE THREAD

**Issue by T2MWorks-Mitch** [bitwarden/clients#5843]
### Steps To Reproduce

1. auto hide is enabled 
2. open a Desktop (MacOS) session 
3. search for an account in the search bar
4. hover mouse over an account on filtered results  
5. right click an account ( highlifght bar on left side of account object becomes grey) 
6. on the right click menu select copy password

if you left click first at step 5 ...

1. highlight  bar on the left side of password becomes blue 
2. right click and copy password 

### Expected Result

 window should minimize to tray but it does not 

if you  left click first so the object is highlighted and bar turns blue,   it works 

### Actual Result

3. window minimizes to tray 

### Operating System

macOS

### Operating System Version

MACOS ventrua 13.4.1

### Installation method

Mac App Store

### Build Version

Version 2023.5.1 (9424)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @T2MWorks-Mitch 

I attempted to reproduce your issue and was unable to do so. I think the issue or behavior you are referring to could have its origin in a misconfiguration. Could you record the steps and share a short clip to assist us understand what you are experiencing. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by T2MWorks-Mitch** [comment]
I have reproduced and recorded the issue - how do I send you the screen capture ?

**Comment by T2MWorks-Mitch** [comment]
@Adedamola-Aina were you able      To view the video
