### ISSUE TITLE
Signed up for 2FA on my laptop and I am still signing in via password.

### ISSUE THREAD

**Issue by midnightstarr** [bitwarden/clients#5845]
### Steps To Reproduce

4. Click on '...'

### Expected Result

I was expected to go to my phone to log in via laptop. But I don't see that.

### Actual Result

Just logging in using my password. No 2FA whatsoever.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

Version 114.0.5735.199 (Official Build) (64-bit)

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think the behavior you are describing may be explained by this note in the Bitwarden Help Center: https://bitwarden.com/help/twostep-faqs/#q-why-is-bitwarden-not-asking-for-my-enabled-two-step-login-method

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
