### ISSUE TITLE
After latest update, Bitwarden app / plugin show only blank view

### ISSUE THREAD

**Issue by vilsutin** [bitwarden/clients#5879]
### Steps To Reproduce

1. Open Bitwarden OS X app
2. Close the app
3. Open again -> opens with blank screen.

or:

1. Open Bitwarden OS X app
2. Click on bitwarden icon on Chrome plugin -> nothing happens

- I need to restart computer and avoid starting Bitwarden OS X app in order to access the vault in Chrome/Brave plugin.

### Expected Result

Display vault.

### Actual Result

Blank view.

### Screenshots or Videos

https://cln.sh/Vz0ghx1j

### Operating System

macOS

### Operating System Version

13.4.1 (22F82)

### Installation method

Mac App Store

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @vilsutin ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption of your local installation, and would suggest a re-install as a first recourse.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by vilsutin** [comment]
Hi, I traced the issue to a corrupt local network config so indeed, I can verify this issue was local and not considering Bitwarden. Sorry for the trouble and thanks for a quick reply.
