### ISSUE TITLE
2FA codes are wrongly generated (tested against Authy)

### ISSUE THREAD

**Issue by tbogard** [bitwarden/clients#5902]
### Steps To Reproduce

once you copy the code to use it in bitwarden to generate a 2FA code, it doesn't work compared with the same implementation as used on Authy.

### Expected Result

It should generate a correct 2FA code

### Actual Result

codes are not working with the correct key

### Operating System

Windows

### Web Browser

Brave

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I suggest you set both the Time and the Time Zone of your device to Automatic, and try to use the 6-digit TOTP codes that the Bitwarden TOTP Generator is showing you then. I mention this as incorrect 6-digit TOTP codes usually stem from having the incorrect Time and/or Time Zone set on the device that’s generating the codes and/or is validating them.

You can learn more on this here: https://bitwarden.com/help/authenticator-keys/ 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
