### ISSUE TITLE
I can't log in to Bitwarden from the ios app

### ISSUE THREAD

**Issue by martinfr01** [bitwarden/clients#5904]
### Steps To Reproduce

1. Go to 'iOs app'
2. Click on 'login with master password'

### Expected Result

app login : OK

### Actual Result

I want to connect to bitwarden iOS app from my new iPhone, but I can't, and a message appears : "Traffic from your network looks unusual. Connect to a different network or try again later. [Error Code 7]"
I've never had issues with Bitwarden before that

### Operating System

iOS

### Web Browser

Chrome

### Build Version

16.6

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Could you please restart your mobile device, wait 30 minutes, and then try again? Furthermore, you may review additional information on this error here: https://bitwarden.com/help/unusual-traffic-error/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
