### ISSUE TITLE
Windows Hello prompt does not have focus

### ISSUE THREAD

**Issue by ReK42** [bitwarden/clients#5916]
### Steps To Reproduce

1. Have Bitwarden desktop signed in, with both PIN and biometric unlock enabled.
2. Have Bitwarden plugin locked
3. Click on Bitwarden plugin icon

### Expected Result

The Windows Hello prompt appears in the foreground and scanning your fingerprint will unlock the plugin.

### Actual Result

The Windows Hello prompt appears, sometimes in the foreground, sometimes in the background. Even when it appears in the foreground, it does not have focus: scanning your fingerprint will not unlock the plugin until you also click on the Windows Hello prompt.

### Operating System

Windows

### Operating System Version

Windows 11 Enterprise 22H2 22621.1992

### Web Browser

Firefox

### Browser Version

Firefox 115.0.2

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/5287

**Comment by ReK42** [comment]
> Duplicate of #5287

This is likely related, but not identical, to that issue. In my case, even when the prompt opens in the foreground, it does not have focus. If you scan your fingerprint it does not work, but then signs in immediately once you click on prompt.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue, but was unable to do so. I think your error could have its origin in a settings misconfiguration or conflict on your PC.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by N173M43R** [comment]
This is STILL a bug months later.

**Comment by jalari06** [comment]
> This is STILL a bug months later.

Hello, just thought I would jump in and say that I am not related to this project, meaning I've never used it, but I was trying to find out why suddenly my windows Hello pop up is no longer focused. Its the exact same issue you describe, but its happening with any app that uses it so I do believe this to be a windows bug and not something specific to this project. My laptop does not have this issue, only my desktop, so clearly something on it was changed and now it wont have focus when it appears. It's driving me crazy and I hope I can find a solution, but I just thought I would let you know that I don't believe it to be an isolated issue to this project.

It started a few months ago and the only thing I know that changed around that time is I got a new Logitec Pro Wireless Mouse that requires their G Hub software. Since getting this mouse, I have had other issues happen, so its possible its related. My laptop does not currently have it installed, so I may try to install it and see if the problem starts on my laptop too.

**Comment by N173M43R** [comment]
> > This is STILL a bug months later.
> 
> Hello, just thought I would jump in and say that I am not related to this project, meaning I've never used it, but I was trying to find out why suddenly my windows Hello pop up is no longer focused. Its the exact same issue you describe, but its happening with any app that uses it so I do believe this to be a windows bug and not something specific to this project. My laptop does not have this issue, only my desktop, so clearly something on it was changed and now it wont have focus when it appears. It's driving me crazy and I hope I can find a solution, but I just thought I would let you know that I don't believe it to be an isolated issue to this project.
> 
> It started a few months ago and the only thing I know that changed around that time is I got a new Logitec Pro Wireless Mouse that requires their G Hub software. Since getting this mouse, I have had other issues happen, so its possible its related. My laptop does not currently have it installed, so I may try to install it and see if the problem starts on my laptop too.

I believe you have a seperate issue then. This issue is easily repeatable by installing the latest version, verifying that windows hello is broken, then rolling all the way back to version 2023.3.2, verifying that windows hello works like it always should have, rinse, repeat.

To a certain extent one must sacrifice convenience for security, but an in ability to focus a security window your own app calls up speaks to shoddy programming. Not to mention that when I emailed support about this they insisted I was lying and that this bug has never existed before informing me that the best solution was to just use a different competing app.

**Comment by jalari06** [comment]
> > > This is STILL a bug months later.
> > 
> > 
> > Hello, just thought I would jump in and say that I am not related to this project, meaning I've never used it, but I was trying to find out why suddenly my windows Hello pop up is no longer focused. Its the exact same issue you describe, but its happening with any app that uses it so I do believe this to be a windows bug and not something specific to this project. My laptop does not have this issue, only my desktop, so clearly something on it was changed and now it wont have focus when it appears. It's driving me crazy and I hope I can find a solution, but I just thought I would let you know that I don't believe it to be an isolated issue to this project.
> > It started a few months ago and the only thing I know that changed around that time is I got a new Logitec Pro Wireless Mouse that requires their G Hub software. Since getting this mouse, I have had other issues happen, so its possible its related. My laptop does not currently have it installed, so I may try to install it and see if the problem starts on my laptop too.
> 
> I believe you have a seperate issue then. This issue is easily repeatable by installing the latest version, verifying that windows hello is broken, then rolling all the way back to version 2023.3.2, verifying that windows hello works like it always should have, rinse, repeat.
> 
> To a certain extent one must sacrifice convenience for security, but an in ability to focus a security window your own app calls up speaks to shoddy programming. Not to mention that when I emailed support about this they insisted I was lying and that this bug has never existed before informing me that the best solution was to just use a different competing app.

Ahh, okay, apologies. I was not aware or did not notice that you were able to go back to an old version and confirmed that work again on those version. Since I was not related to this project but had nearly the same issue, I thought maybe something larger was going on, but does not sound like my case is related to yours then. Sorry for bothering you.

**Comment by ReK42** [comment]
This issue went away at some point for me but is now re-occurring with the following versions:

- Windows 11 24H2
- Firefox 137.0.2
- Bitwarden Desktop 2025.3.0
- Bitwarden Firefox Extension 2025.3.2

As before, Windows Hello prompts initiated from the desktop program work correctly. Windows Hello prompts initiated from the browser extension pop under the browser and require manually selecting the window to focus it before they will authenticate. It is now consistent in that auth attempts from the browser will always appear in the background.

**Comment by jalari06** [comment]
Yeah, I've been forced to live with it. Its super annoying and I have yet to find a solution to it. I am forced to stick with Windows 11 23H2 because 24H2 introduced so many bugs that affected me(Video files no longer showed any of the video info when viewing a list of them in File explorer, or even when checking the properties of a video), so I found a way through a registry edit to prevent windows from updating past this version until they fix those bugs. There were other issues I had, but that was my primary annoyance. I had hoped that going to 24H2 would solve the windows hello issue, but still no luck. At some point I may be forced to format, reinstall and check it as I run each set of updates to see which one breaks windows hello.

**Comment by Deembe** [comment]
I've rolled back the Firefox extension to the 2024.12.4 release as an avoidance as this is an accessibility issue for me. I'm an RSI sufferer so I try to avoid unnecessary pointer movements. The extension causing the Windows Hello to appear in the taskbar means moving the pointer from  browser shortcuts bar at the top of the screen to the Windows Taskbar at the bottom and then move my finger to the fingerprint readed once the dialog has focus. 

Will this be fixed or do I have to forego updates to maintain usability?

**Comment by Deembe** [comment]
Version 2025.5.0 fixed for me. Thanks

**Comment by RainrZufall** [comment]
Problem is back for me since 2025.7.0

**Comment by True-Weevil** [comment]
Problem is back for me using 2025.7.0

**Comment by Deembe** [comment]
Yes, the biometric window no longer has focus, we have regression, the problem has returned.

Bitwarden Version 2025.7.1
Firefox  Version 141.0.3
