### ISSUE TITLE
Unlock with windows hello option not visible in settings

### ISSUE THREAD

**Issue by webez** [bitwarden/clients#5919]
### Steps To Reproduce

1. File->Settings
2. Secturity

### Expected Result

Unlock with hello windows option

### Actual Result

No option visible

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/37178316/0c648a14-73ba-4832-ab80-97b745881c3b)

### Additional Context

Windows hello is enabled with biometric option
![image](https://github.com/bitwarden/clients/assets/37178316/65670857-00c0-40e7-a52b-3b431f0c992b)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.7.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Thank you for your report!

We use GitHub issues as a place to track bugs and other development related issues. Please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!
