### ISSUE TITLE
No matching of logins (in Tab section) for singlename domain (i.e. domains with no .com, .net, .org, etc. qualifier)

### ISSUE THREAD

**Issue by glidingthrough** [bitwarden/clients#5945]
### Steps To Reproduce

I have single name domains on my Tailscale network, e.g. myserver = 100.xxx.xxx.xxx. To access a self-hosted service, I use http(s)://myserver/nameofservice.

Some of these are password protected and Bitwarden doesn't match the saved login credentials with the URL, so the Tab section of the extension (used in the sidebar in Firefox) doesn't show anything, even when the respective URI is listed under the saved credentials.

This only happens for single name domains, not IP addresses or the usual .com, .net, etc.

### Expected Result

That domains without a `.` in them are still matched in the Tab section of the web browser extension, so I can click to autofill the credentials.

### Actual Result

The Tab section states that there are no logins available to autofill...

### Operating System

Windows, Linux, Android

### Web Browser

Firefox

### Browser Version

115.0.3

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by glidingthrough** [comment]
Also known to affect Android client

**Comment by atjbramley** [comment]
Hi @glidingthrough, 

I attempted to reproduce your issue and was unable to do so.  In particular, I:

- put up a service with username and password fields (grafana) on port 80 on localhost
- set localDNS so that 'grafana' directed to localhost
- noted that I could visit this login page by visiting http://grafana in my browser
- created a vault item for this page, using the 'host' matching optin
- noted that autofill was available when using this setting, and that the entry showed up in the 'tab' section of the browser extension

 I think your error could have its origin in a misconfiguration.  Can I confirm that you're using the 'host' matching option?  Our documentation on this can be found here:

https://bitwarden.com/help/uri-match-detection/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by glidingthrough** [comment]
@atjbramley THANK YOU!!! You've saved me a great deal of time. Only sorry I wasn't aware of the URI match detection settings sooner 😅 Greatly appreciate the help.
