### ISSUE TITLE
Unable to login to Firefox addon on MacOS

### ISSUE THREAD

**Issue by techionltd** [bitwarden/clients#5947]
### Steps To Reproduce

Clean install of Firefox
Install Bitwarden addon
Attempt to log in to add on

### Expected Result

Successful login and access to vault items

### Actual Result

Add on will not log in, gives an error "Username or password is incorrect. Try again".
Logging into a browser tab with the same credentials is fine (see screenshot)

### Screenshots or Videos

<img width="1440" alt="Screenshot 2023-08-03 at 12 59" src="https://github.com/bitwarden/clients/assets/3950050/e46d74a6-d044-4d72-9cfe-23fef6531fe6">
<img width="1440" alt="Screenshot 2023-08-03 at 13 08" src="https://github.com/bitwarden/clients/assets/3950050/ef2208c7-273b-4393-8a05-c9f53ff45b41">

### Operating System

macOS

### Operating System Version

11.7.8

### Web Browser

Firefox

### Browser Version

116.0

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @techionltd,

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists,  please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
