### ISSUE TITLE
Enabling biometric authentication on the firefox extension fails if the registry path for firefox is HKLM\Mozilla\NativeMessagingHosts

### ISSUE THREAD

**Issue by Solarapollo05** [bitwarden/clients#5952]
I found this comment on an earlier issue, which has now been closed. However the comment was added after the issue was closed, and is still a bug in the latest version (2023.7.1)

> I've been experiencing this issue as well: the [manual fix mentioned above](https://github.com/bitwarden/clients/issues/2258#issuecomment-1019969507) worked fine, right until the "Allow browser integration" checkbox is unchecked and checked again.

> Unchecking the option deletes the registry key as expected (nothing appears in the console log), but rechecking it fails to recreate the registry key, with the following console log:
```
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.bitwarden
starting server on  /tmp/app.bitwarden
starting TLS server false
starting server as Unix || Windows Socket
{"HKLM\\SOFTWARE\\Mozilla\\Firefox":
12:57:26.532 > Not finding registry HKLM\SOFTWARE\Mozilla\Firefox skipping.
```

> Note that the registry key here is looking in **HKLM** (HKEY_LOCAL_MACHINE) and not **HKCU** (HKEY_CURRENT_USER) as mentioned in [Hinton's comment](https://github.com/bitwarden/clients/issues/2258#issuecomment-1019933401).

> _____

> HKCU:
![image](https://user-images.githubusercontent.com/1628474/231355806-d4b2e066-e5f5-4a96-b177-bb67e2642212.png)

> HKLM:
![image](https://user-images.githubusercontent.com/1628474/231355752-228b82ea-99d4-421a-bed4-dd50a6e199e3.png)

> Chrome/Chromium check and Firefox check:
![image](https://user-images.githubusercontent.com/1628474/231359073-273bc899-f032-4773-8b34-04c88bd3234f.png)

> Note that Bitwarden always checks HKCU for Chromium browsers, and HKLM for Firefox.
_____

> For reference, I'm using Firefox 112.0 (64-bit).

> I found a post in 2016 (https://discourse.mozilla.org/t/installing-via-registry-in-firefox-64-bit/6064/7) that references a `Mozilla\Firefox` key in HKLM, and even older posts referencing `Mozilla\Mozilla Firefox`.

> From what I can tell about HKLM & HKCU, which one's used depends on whether Firefox is installed for the current user only (HKCU), or for all users of the computer (HKLM).
_____

> ## TL:DR;
> This issue probably only appears for single-user installations of Firefox.
In this case, Bitwarden couldn't find the `Mozilla\Firefox` key within HKLM, because it's in HKCU.

_Originally posted by @serin113 in https://github.com/bitwarden/clients/issues/2258#issuecomment-1504633044_

I experienced the same bug, which I fixed by manually creating the registry key, and I can happily provide logs, screenshots, ect.

Apologies if I am mistaken in creating this issue, please let me know if there is another process I should follow instead :)

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by serin113** [comment]
Looking into the current code in the master branch, the issue is still there.

___
## Investigation of Bitwarden's checks & Firefox's registry keys

Based on the method definition for `createWindowsRegistry` in [`apps/desktop/src/main` on line 298](https://github.com/bitwarden/clients/blob/8dc11a6f120cf91b0a2b129514f52528b9deaa43/apps/desktop/src/main/native-messaging.main.ts#L298):
`private async createWindowsRegistry(check: string, location: string, jsonFile: string)`
1. it first checks `HKLM\\SOFTWARE\\Mozilla\\Firefox` if it exists, and if it does:
2. it creates `HKCU\\SOFTWARE\\Mozilla\\NativeMessagingHosts\\com.8bit.bitwarden`

Of note, Firefox has two possible install modes: **per user**, and **global**.

This is where the registry inconsistency (probably) comes in: Firefox can choose install its registry keys in either `HKCU`, `HKLM`, or (possibly) both. Even the [Firefox source docs for telemetry](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/install-ping.html) don't have a specific fixed location where the keys would be:

> had_old_install (both)
> - True if at least one existing installation of Firefox was found on the system prior to this installation.
> - full: Checks for the installation directory given in the Software\Mozilla\${BrandFullName} registry keys, **either HKLM or HKCU**
> - stub: Checks for the top level profile directory %LOCALAPPDATA%\Mozilla\Firefox


This issue of not being able to find the right registry key for Firefox was also encountered in [`mozilla/node-fx-runner`](https://github.com/mozilla/node-fx-runner/issues/73): it's a known inconsistency.

## Possible solution
[Their solution](https://github.com/mozilla/node-fx-runner/pull/74#discussion_r613339794) was to check under `HKCU` first, then fallback to checking `HKLM`.

___
This is probably the root of other issues of the same bug: #6169, #6156, and probably other ones related to biometrics not working in Firefox.

(tagging @Krychaz)
