### ISSUE TITLE
Linux desktop client crashes on picking a theme

### ISSUE THREAD

**Issue by petertaylor3** [bitwarden/clients#5969]
### Steps To Reproduce

Using Ubuntu 23.04 and the official .deb package, the application will crash when choosing a theme.

1. Go to File > Settings > App Settings
2. Click on "Theme" drop down
3. The application crashes

### Expected Result

The drop down should appear and allow the user to select a theme.

### Actual Result

The dropdown appears. It is the correct size to fit the three themes. However, the text for the themes do not show (should be light, dark, nord). The application become completely unresponsive. After a minute or so, Ubuntu offers to kill the frozen application.

### Screenshots or Videos

![Screenshot from 2023-08-05 11-55-34](https://github.com/bitwarden/clients/assets/127117648/2e923262-97e2-4dd9-968a-d8a6580e4fe5)
![Screenshot from 2023-08-05 11-55-12](https://github.com/bitwarden/clients/assets/127117648/eb136e41-b02c-4f02-bd9a-5c005400522d)

### Operating System

Linux

### Operating System Version

Ubuntu 23.04

### Installation method

Other (deb from Github releases page)

### Build Version

Release desktop-v2023.7.1 (Bitwarden-2023.7.1-amd64.deb). Same issue was there in desktop-v2023.5.0.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @petertaylor3 

I attempted to reproduce your issue and was unable to do so. may i ask that you do a clean install by clearing the items in this folder https://bitwarden.com/help/data-storage/ after which you then install the Bitwarden app again. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks
