### ISSUE TITLE
Browser extension autofill causes login failure on krafton.com (Account for PUBG: Battlegrounds Game)

### ISSUE THREAD

**Issue by ev4x** [bitwarden/clients#5994]
### Steps To Reproduce

1. Go to https://accounts.krafton.com/login 
2. Click on Right Click Bitwarden Autofill or CTRL + SHIFT + L
3. Click Login

### Expected Result

Login succesfull

### Actual Result

You have failed user validation, please try again later. 

### Screenshots or Videos

![krafton](https://github.com/bitwarden/clients/assets/129671265/6957c7dd-1afb-48bc-983b-6cd135947d2b)

### Additional Context

When copy the password manually and paste it in login is succesfull you may need to wait a bit until new login is possible than reload page and try with copy paste and it will be working but it should also work with autofill

### Operating System

Windows

### Operating System Version

Win10

### Web Browser

Chrome, Firefox

### Browser Version

Firefox 116.0.1 and Chrome 115.0.5790.111

### Build Version

Firefox 2023.7.1 and Chrome 2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the vault item you are using to auto-fill.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
