### ISSUE TITLE
Error with Windows

### ISSUE THREAD

**Issue by fbgfsdg4** [bitwarden/clients#6019]
### Steps To Reproduce

When I click on the bitwarden app icon, it doesn't open at the top of all windows. Удаление и переустановка приложения. Не помогло

### Expected Result

***

### Actual Result

****

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/142053590/f65e70ac-cec1-47df-8176-2d50804046a2)  
![image](https://github.com/bitwarden/clients/assets/142053590/6d123fd3-4d58-4036-830d-c3026167b71a)

### Additional Context

****

### Operating System

Windows

### Operating System Version

Windows 10 Pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Версия 2023.7.1 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @fbgfsdg4,

I am unable to reproduce this behaviour; After activating (Always on top) I am able to launch the Bitwarden desktop client (Direct Download) and it would show up on top of everything else, including the Windows Hello prompt. Could you please contact us (https://bitwarden.com/help/) so we'd assist you in troubleshooting this? Please feel free to include a link to this GitHub report.

Alternatively, you can seek assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.

Thank you,
