### ISSUE TITLE
Doesn't work with pCloud.com login overlay popup

### ISSUE THREAD

**Issue by bpsib** [bitwarden/clients#6023]
### Steps To Reproduce

1. Go to 'www.pcloud.com'
2. Click on 'Sign in'
3. Click on Bitwarden to autofill pCloud login details

### Expected Result

The email field in the popup should be filled.

### Actual Result

The email and password field behind the popup where it says join pCloud is filled.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/5899155/b63ebecb-7fd8-415b-a52a-7c8934a325c5)

### Additional Context

It works if I manually enter my email address then use Bitwarden for the password.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

115

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @bpsib,

Thank you for bringing this to our attention. Due to the nature of Auto-Fill, we track such report internally using different Forms depending on the platform:

Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, I have gone ahead and filed a report on your behalf for that URL; In the future, please feel free to use the forms above directly.

I will close this GitHub report now.

Thank you,

**Comment by Orlandoke** [comment]
Same issue with Windows 11 and browser Chrome.
