### ISSUE TITLE
Windows app occasionally prevents shutdown with exception breakpoint error

### ISSUE THREAD

**Issue by trugty** [bitwarden/clients#6036]
### Steps To Reproduce

Shutdown Windows 11 PC as normal, with Bitwarden desktop running in background

### Expected Result

Bitwarden is closed and Windows continues to shutdown

### Actual Result

Occasionally, Bitwarden shows an application breakpoint error which prevents shutdown:
```
---------------------------
Bitwarden: Bitwarden.exe - Application Error
---------------------------
The exception Breakpoint
A breakpoint has been reached.
 (0x80000003) occurred in the application at location 0x00007FF7B3EA7E01.

Click on OK to terminate the program
---------------------------
OK   
---------------------------
```

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/10658000/ae46bef6-fdd4-402d-b547-4e6a2d7e528e)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. You might try uninstalling and reinstalling the Bitwarden Windows application and then see if you're able to recreate the issue.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by popy2k14** [comment]
@trugty i have the exact same issue:

<img width="548" height="247" alt="Image" src="https://github.com/user-attachments/assets/cb164bc2-b0af-47a8-b58b-c2f8079f0fc8" />

Did you ever solve this issue?

**Comment by trugty** [comment]
Sadly not. It is still happens (but not every time), I've just had to watch to make sure shutdown continues which obviously isn't great..

**Comment by popy2k14** [comment]
Yeah, i am also doing this now :-( not really great...

Can you reopen this issue (i have no permissions for this)?

**Comment by Dennis14e** [comment]
I have the same problem, and so far on different PCs. On a new computer, I initially used the Microsoft Store version of Bitwarden, and there was no software exception. Since I replaced it with the normal Windows version, this unknown software exception has been occurring sporadically again.

**Comment by pstalman** [comment]
Just want to share that I can reproduce it by opening the Desktop App, edit an item and not saving. When I restart I receive this exact same error. Tried this on Windows 11 (10.0.26200.8457) and desktop app version from winget (2026.3.1).

Let other setting window open does not seem to give an error (like keeping Import screen open).
