### ISSUE TITLE
Empty dropdown menues in linux desktop client

### ISSUE THREAD

**Issue by VitBK** [bitwarden/clients#6071]
### Steps To Reproduce

1. Go to main screen
2. Click on 'View' or 'Account' menu
Also this problem occurs in File -> Settings -> Preferences -> 'Clear clipboard' dropdown menu. In this case application freezes and only force quit helps.

### Expected Result

Selected dropdown menu should be rendered correctly

### Actual Result

Empty dropdown menu 

### Screenshots or Videos

![Screenshot from 2023-08-19 01-05-34](https://github.com/bitwarden/clients/assets/50338025/ed6dca01-9c59-49cb-bc87-b362c39a4a2e)
![Screenshot from 2023-08-19 01-12-55](https://github.com/bitwarden/clients/assets/50338025/ad428d50-5ce4-40cf-af4d-705a033d1da7)

### Additional Context

clear installation via snap

### Operating System

Linux

### Operating System Version

22.04.1-Ubuntu

### Installation method

Snap

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of snap or the operating system.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
