### ISSUE TITLE
Windows - Need to disable/enable Windows Hello after every reboot

### ISSUE THREAD

**Issue by boardlord1** [bitwarden/clients#6072]
### Steps To Reproduce

1. Reboot laptop
2. Desktop app doesn't show Windows Hello as a login option, need to unlock with master pwd
3. Go to Settings, where Windows Hello IS activated. Disable, then re-enable
4. Windows Hello login for the desktop app (and thus browser) works again (until the next reboot)

### Expected Result

BW desktop app should be able to use Windows Hello without needing to disable it and re-enable it after every reboot.

### Actual Result

See in "Steps To Reproduce"

### Operating System

Windows

### Operating System Version

2022H2, 19045.3324

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @boardlord1,

Thank you for your report. Could you please create a support ticket for this matter (https://bitwarden.com/help/) so we'd assist you with troubleshooting this? I ask because I am unable to reproduce this in testing, and I also did not encounter it myself in daily use; Please include a link to this GitHub report in your message.

Alternatively, you can seek assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.

Thank you again,
