### ISSUE TITLE
An error has occured - Bitwarden Application, Web Vault and web browsers extensions

### ISSUE THREAD

**Issue by adnanhassan79** [bitwarden/clients#6135]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'New Item'
3. Click on 'Create any login'
4. While saving records or login
5. Getting error "an error has occurred" 
6. More details on the error: "An unhandled server error has occurred"
records

### Expected Result

save item

### Actual Result

Getting error "an error has occurred" 
6. More details on the error: "An unhandled server error has occurred"
records

### Screenshots or Videos

![BW-Error](https://github.com/bitwarden/clients/assets/143484845/e655890e-c59b-451f-a1d5-11ae796c4d79)

### Additional Context

this have started to show to often now, it was not the case in the past

### Operating System

Windows

### Operating System Version

W10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Baptistecottey** [comment]
Faced same issue yesterday. Use older version, 2023.7.0 : https://github.com/bitwarden/clients/releases/tag/desktop-v2023.7.0

Once account configured you can upgrade to 2023.8.0

**Comment by atjbramley** [comment]
Hi @adnanhassan79 ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a network issue between your clients and our servers.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
