### ISSUE TITLE
Biometrics Not Working On Firefox

### ISSUE THREAD

**Issue by GrouchyM** [bitwarden/clients#6169]
### Steps To Reproduce

1. Click Bitwarden extension in Firefox browser
2. Watch as nothing happens with biometrics, spins and then fails

### Expected Result

That my password manager acts like all other password managers and opens with biometrics.

### Actual Result

Spins, fails, doesn't unlock.

### Operating System

macOS

### Web Browser

Firefox

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by GrouchyM** [comment]
Used to work just fine until 5 days ago when Bitwarden updated the desktop app but didn't bother updating the Firefox extension. This is a case of a version mismatch, when are we getting updated extensions?????????

**Comment by buzzwebly** [comment]
I'm having an issue too, I think it may be because Desktop has updated to 2023.8.2 but Firefox extension is still at 2023.7.1
I seem to recall reading somewhere that with the changes in 2023.8.2 the extension must be at the same release level. It's been released, but for some reason Firefox site is not updated yet and is still offering 2023.7.1 extension on download.

**Comment by cbbit** [comment]
Hi there,

Thank you for this report.

We have made some changes to the way that biometrics work in this release. Please wait until both your desktop app and your client apps are updated to 2023.8.2 - this will restore biometric functionality.

In the meantime, please unlock your client apps using the master password or PIN.

I apologize for the inconvenience.

If your issue persists, after both the desktop app and browser extension are both on 2023.8.2 please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

**Comment by Sunsper** [comment]
I hope Mozilla will update the extension in their store soon, because this sucks a bit.

**Comment by 7h3Cub3** [comment]
Had the same issue at computer restart this morning and found that post, i found a way to fix it in the meantime, download from BW github the Browser v2023.8.2 file corresponding to your browser, in my case "dist-firefox-2023.8.2.zip" for firefox, rename the zip as xpi, then go into your extension page, and select "install from a file", you can then install the newer 2023.8.2 browser extension and biometric work again, you will get a security prompt because the addon not coming from the firefox store. In the meantime it works !

**Comment by buzzwebly** [comment]
That doesn't work for me, I believe it only works if you're running the developer version or one of the nightly builds, where it's expected that you may be running unsigned code.  I'm not running dev or nightly, so I'll just wait.

**Comment by gerard-mccann2** [comment]
This issue definitely sucks ... sorry for being negative but it is a big enough bummer to my PC workflow that I felt I had to say so. My master password is ridiculous so having to type it each time I fire up Firefox following a system reboot is painful. This is the only workaround I can find unless I want to change to a different browser or drop my password/config security, which I don't.

Really appreciate this being fixed sooner than later. Thanks

**Comment by brian-kneebone** [comment]
It would be nice if the browser extension let you optionally type in the master password without disabling browser integration in the desktop app. If I was just a Firefox user that's fine, but it breaks my other browser integrations. I briefly see this prompt, but it disappears to quickly. For what it's worth, I removed the extension from Firefox and re-added and the store is still showing only version 2023.7.1. Looking forward to this getting fixed.

**Comment by iamironz** [comment]
I have pretty much the same issue: after attempting to unlock with my fingerprint (I see a macOS system prompt and then touch the fingerprint sensor) the progress bar just keeps spinning but nothing happens. 
Works just fine on Safari.

**Comment by artpoli** [comment]
I had to switch the biometric unlock off because it stopped working completely.
While there is no any issues with biometrics in Chrome, I'm experiencing biometrics issues in Firefox for a long time.
Establishing a new browser integration didn't help.

**Comment by 3Domse3** [comment]
@cbbit 
I can't even log in using the master password or any method at all. I already tried removing the addon and reinstalling it, now I can't set up my account and it only says the account doesn't exist or the password is wrong (it isn't)... :(

**Comment by goose-ws** [comment]
Are there builds of the updated browser extension I can manually install until the new version is available through Mozilla? I have a really long password that is very obnoxious to type.

**Comment by pgm83** [comment]
I've found if i restart desktop app, then biometrics works again for the extension (2023.7.1) so that's been my workflow for the last few days

**Comment by biglu91** [comment]
Same issue. Workaround that works for me is downgrading desktop app to version 2023.7.1

**Comment by timothyleerussell** [comment]
This is a bit painful (as already expressed by others).

Also, if you have the browser plugin set to auto ask for verification on launch, there doesn't appear to be a way to enter your password as it auto pops the windows hello dialog when you click on the extension icon. You can authenticate or cancel, it doesn't matter to the extension, which is not receiving the data.

To login (by providing the master password), I had to remove and reinstall the Firefox extension.

**Comment by goose-ws** [comment]
> Same issue. Workaround that works for me is downgrading desktop app to version 2023.7.1

This workaround solved it for me, until the browser extension can be updated.

Quick link for others wanting to roll the desktop client back to 2023.7.1: https://github.com/bitwarden/clients/releases/tag/desktop-v2023.7.1

**Comment by GrouchyM** [comment]
At this point, I don't even think this is Bitwarden's problem anymore. Every browser I've tried has the updated extension EXCEPT Firefox. I believe this is Mozilla dragging their feet, not Bitwarden.

**Comment by biglu91** [comment]
> > Same issue. Workaround that works for me is downgrading desktop app to version 2023.7.1
> 
> This workaround solved it for me, until the browser extension can be updated.
> 
> Quick link for others wanting to roll the desktop client back to 2023.7.1: https://github.com/bitwarden/clients/releases/tag/desktop-v2023.7.1

Yeah but beware on restarting the desktop app: it will update automatically. Fortunately downgrading doesn't require uninstalling the newer version and settings changed are not reset.

**Comment by gerard-mccann2** [comment]
I got fed up with waiting for a resolution and based on what other posters said, have moved to Brave browser. It's on version 2023.8.2 which works perfectly with biometrics.

Wish this had never happened, but the silver lining is I get over to a browser that seems to be taking over from Firefox privacy-wise anyways...

Whether the issue root cause is Bitwarden or Firefox, hopefully with Brave there will be no repeat issues going forward. Cheers to all other posters for their suggestions/workarounds. I think moving browser is the best option for me from all those possibilities.

**Comment by GrouchyM** [comment]
> I got fed up with waiting for a resolution and based on what other posters said, have moved to Brave browser. It's on version 2023.8.2 which works perfectly with biometrics.
> 
> Wish this had never happened, but the silver lining is I get over to a browser that seems to be taking over from Firefox privacy-wise anyways...
> 
> Whether the issue root cause is Bitwarden or Firefox, hopefully with Brave there will be no repeat issues going forward. Cheers to all other posters for their suggestions/workarounds. I think moving browser is the best option for me from all those possibilities.

I did the same as you yesterday. I turned all the crypto crap off and Brave has been great! I've had enough of Firefox at this point.

**Comment by fromorbonia** [comment]
Just adding to the bug data here, I'm on Windows 10, the popup on Firefox for the biometric check comes up. It recognises my fingerprint, closes the pop up. However, Bitwarden remains locked on the browser window.
Chrome working no problem. Looking forward to fix :-). This only started when I upgraded to 2023.8.2, and problem remains with 2023.8.3
Thanks

**Comment by cili7** [comment]
This was fixed for about a day... now the problem has come back again. Firefox, biometrics not working with Bitwarden addon. Registers the fingerprint, but Bitwarden remains locked. "Windows Hello" biometrics works for everything else on the system- including the standalone Bitwarden app. Firefox addon remains broken :(.

**Comment by sgloutnikov** [comment]
@cili7 you can log in with the master password and enable PIN login until the FireFox addon gets updated in the addon store.

**Comment by serin113** [comment]
See [this comment](https://github.com/bitwarden/clients/issues/2258#issuecomment-1019963086) on #2258 for the temporary fix:

(in `HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\` create a new key)
> key: com.8bit.bitwarden
> value: C:\Users\<username>\AppData\Roaming\Bitwarden\browsers\firefox.json


This issue has been [confirmed](https://github.com/bitwarden/clients/issues/5952#issuecomment-1706769302) by a member of the team on #5952.

**Comment by Skaewlkr** [comment]
I tested all the suggested fixes but the problem still remains. I unlock the Extension via biometrics and I get the "waiting for confirmation from dekstop" message. 

Yesterday I discovered something interesting that maybe could be helpful finding the problem. I tested different settings within the desktop app and found out that if the desktop app is unlocked, the biometrics in my browser extension work. This works fine until the timeout is reached and the desktop app locks again.

In addition, this only works if I unlock the desktop app with my master password. If I unlock it with biometrics or a pin, the extension won't accept the biometrics and I get the mentioned message. 

I could now set the timeout for the desktop app to "restart" or "never" but what would be the point using biometrics in the browser extension at all if the desktop app is unlocked all the time? In this case I could also just set the timer for the browser extension to never and just keep the exntesion unlocked all the time without the need of using the desktop app.

At the moment, I see no benefit in using biometrics or a pin within my extension, if I have to keep my desktop app unlokced all the to for it to work.

I hope this information can somehow be helpful to find a solution for the problem...

**Comment by aimuz** [comment]
I have the same problem with librewolf (Firefox-based) browser on macOS

**Comment by aimuz** [comment]
When I install this plugin manually, he is able to work correctly https://github.com/bitwarden/clients/releases/tag/browser-v2023.8.3

**Comment by cili7** [comment]
I gave up on waiting. Uninstalled Firefox and went for Brave instead. Just disable all the crypto crap and its actually a very fast, secure, and private browser. Works perfectly with Bitwarden as is, along with other sites that Firefox seems to have trouble with (like CBA in AU for instance). Bye bye Firefox, it was nice while it lasted.

**Comment by 4x0v7** [comment]
Same issue here with Waterfox, extension stuck on 2023.7.1. Can confirm that installing `dist-firefox-2023.8.3.zip` manually by dragging and dropping onto Add-ons Manager fixes the issue

**Comment by blxckbxrd** [comment]
@4x0v7, I'm doing the same on Firefox Developer Edition. You just have to temporarily enable unsigned add-ons by toggling `xpinstall.signatures.required`, and it works fine.

@cili7, ngl Brave's crypto vibes are kind of sus. If you want to, give [LibreWolf](https://librewolf.net/) a try. It comes pre-loaded with @gorhill's ad blocker and gently hardened. If I ever get tired of Firefox, I will use that. You would have to temporarily enable unsigned add-ons by toggling `xpinstall.signatures.required`, grab version 2023.8.3 of the Bitwarden add-on from [here](https://github.com/bitwarden/clients/releases/download/browser-v2023.8.3/dist-firefox-2023.8.3.zip), and add it manually.

**Comment by buzzwebly** [comment]
The extension works, the real question is why has it not been updated yet on the Firefox add-ons site when it's been updated everywhere else? Is it a Bitwarden submission delay or a Firefox approval delay? I don't know what the add-ons update process is..

**Comment by blxckbxrd** [comment]
@buzzwebly, I really want to know too. I put my foot in it in the other thread by saying that I thought Firefox might be the one dragging its heels, but there is no evidence of that. We could take bets, or... has anyone raised the issue with Mozilla yet?

**Comment by Tipoff4317** [comment]
@buzzwebly @blxckbxrd 

I don't know the add-ons update process is.  My observation of BW Firefox extension is, once it drops on Github, it takes approximately a week to become available in the Firefox store, unless it isn't, which normally will be followed by another BW browser update.  This is what happened this time, 8.2 on Aug 26, then 8.3 on Sept 6.  Compare this with 7.1 which dropped on July 13, and became available on July 18.

Nobody has elucidated this process yet, but there was an Firefox extension developer who said his extension usually becamse available immediately, but it was unclear if his was a "Recommended Extension" like BW or not.

The general assumption people have had was, there is an extra validation time between BW-Firefox, which is why the availability always lags.  

Since you both are on Github and you may be able to keep focused attention on BW releases, you may want to consider doing updates manually.  Monthly/Bi-monthly updates sometimes have hickups like this, and delaying the updates may smooth things over by not immediately updating if there is a significant hickup.  Also, some people delays updates in hope of not getting caught in supply-chain attacks.  This is a trade-off with not getting immediate updates for 0-day attacks.  In the past, BW had released at least one update, which later turned out to incorporate a fix for a vulnerability later published by a 3rd-party, all without saying anything themselves about it pre- and post- release.

**Comment by Moonstone3010** [comment]
The Firefox extension has finally been updated. However, note [here](https://addons.mozilla.org/pl/firefox/addon/bitwarden-password-manager/) says that the last update was on 7.09.2023 O_o

**Comment by 3Domse3** [comment]
It's working for me again too. Can log in to my account after reinstalling and forcing the installation of the current version by that :)

**Comment by fromorbonia** [comment]
Works for me too! :-)  - in settings is says version = 2023.8.3, with last updated 13 Sep 2023. Foolishly I didn't take a note of the previous Firefox version, but long pipeline for Firefox makes sense.

**Comment by timothyleerussell** [comment]
This issue appears to have been resolved by Mozilla publishing the extension.

**Comment by Sunsper** [comment]
Yeah, Mozilla finally updated the extension in their Add-on Store. Please close this issue.
