### ISSUE TITLE
Credit Card number display format issue

### ISSUE THREAD

**Issue by gaiking-uk** [bitwarden/clients#6177]
### Steps To Reproduce

1. Go to `Types > Card`
2. Click on a saved Credit Card [C/C]
3. Click the 👁️ icon to view the C/C number

### Expected Result

The C/C number should be displayed as 4 blocks of 4 numbers, e.g. ...
`1234 5678 1234 5678`

This is way the C/C number is shown when ***editing*** the C/C number...
![When editing](https://github.com/bitwarden/clients/assets/37931190/657a9a30-48a8-4c02-ba96-a4ed9b7df181)

### Actual Result

The C/C number is displayed in a strange format, specifically...
`1234 567 8 12 34 5 678`

![When viewing](https://github.com/bitwarden/clients/assets/37931190/490f1550-ab72-4eb1-8a23-2f99f5bfee24)

### Operating System

Windows

### Operating System Version

Win 11 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the formatting of the credit card number. Please remove the spaces when entering the card number.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by gaiking-uk** [comment]
> I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the formatting of the credit card number. Please remove the spaces when entering the card number.

Hi @sammbw -- Thanks for the quick reply. I realise you have closed the issue already, but just wanted to follow-up and say that I deleted the C/C number and entered it again making sure there were no spaces.

Interestingly...
- ✅ This does *fix* the number format / display when ***viewing*** the C/C number -- i.e. it shows as `1234 5678 1234 5678`
- 😕 However this introduces the flip-side of the issue as then when ***editing*** the C/C number, it shows as `1234567812345678`, which admittedly is not terrible but at the same time is not ideal as it makes the number a little harder to read and check the digits have been entered correctly.

Is it possible for BitWarden to use an input mask when entering / editing a C/C number? -- i.e. the user types the literal string `1234567812345678` however as this is typed, BitWarden appears to insert a space after every 4th digit... As in, the way it often appears when typing a C/C number into a checkout page for example?

Cheers,
Martin

**Comment by Snoopman** [comment]
I have the same issue.
The number of digits is the same across all cards on my account:
4 digits
whitespace
3 digits
whitespace
1 digits
whitespace
2 digits
whitespace
2 digits
whitespace
1 digits
whitespace
3 digits

<img width="213" alt="image" src="https://github.com/user-attachments/assets/9aad27f8-ead5-44b3-9192-511221474b6c">
