### ISSUE TITLE
Account switcher absent.

### ISSUE THREAD

**Issue by rokejulianlockhart** [bitwarden/clients#6178]
### Steps To Reproduce

0.	```sh
	flatpak upgrade com.bitwarden.desktop # https://github.com/flatpak/flatpak/issues/3097#issuecomment-1485782474
	flatpak upgrade com.bitwarden.desktop --commit d2448f67658be6e5dad73ad2b5d0db0877e52e71bfc0f1d27f90cd00d9c57474
	flatpak run com.bitwarden.desktop
	```
0.	Login (if there isn't usually a switcher at login)

### Expected Result

I should be able to switch accounts. "Log out >" shows two accounts authenticated.

### Actual Result

I'm unable to switch accounts.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/42837531/034ac35e-95d0-4574-ad93-9c0aeb8b66ae) ![image](https://github.com/bitwarden/clients/assets/42837531/270b1d67-7df5-4cbf-a848-461d10c9be78)

### Additional Context

<blockQuote>

Version 2023.8.2
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

</blockQuote>

### Operating System

Linux

### Operating System Version

cpe:/o:opensuse:tumbleweed:20230828

<details>

```pwsh
Get-Content -LiteralPath '/etc/os-release' | Select-String 'CPE_NAME'
```

<blockQuote>

```log
PS /home/rokejulianlockhart> Get-Content -LiteralPath '/etc/os-release' | Select-String 'CPE_NAME'

CPE_NAME="cpe:/o:opensuse:tumbleweed:20230828"

PS /home/rokejulianlockhart>
```

</blockQuote>

</details>

### Installation method

Flatpak

### Build Version

2023.8.2

<details>

```sh
flatpak upgrade com.bitwarden.desktop --commit d2448f67658be6e5dad73ad2b5d0db0877e52e71bfc0f1d27f90cd00d9c57474
```

</details>

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @rokejulianlockhart,

Thank you for this report. What happens if you uninstall your desktop client and install version 2023.8.2 from scratch? I'd like to know if you encounter this only when upgrading.

To be clear, I am able to switch accounts with a fresh installation of version 2023.8.2 of the desktop client via Flatpak.

As a side note, please keep in mind that we do not maintain the flatpak release (https://community.bitwarden.com/t/bitwarden-should-manage-its-flathub-application/30823).


Thank you in advance,

**Comment by rokejulianlockhart** [comment]
It's returned!

![image](https://github.com/bitwarden/clients/assets/42837531/fd92e89f-47bc-4de0-ab0e-8eb05334eae7)
