### ISSUE TITLE
Firefox popup issues

### ISSUE THREAD

**Issue by archer46** [bitwarden/clients#6184]
### Steps To Reproduce

Use Firefox, try to open popup using default keyboard shortcut of Ctrl+Shift+U while cursor in text field.

### Expected Result

Popup window should open normally

### Actual Result

Instead, the character "u" will be typed into the text field.

### Operating System

Linux

### Operating System Version

6.4

### Web Browser

Firefox

### Browser Version

117

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by podbiker** [comment]
For some reason the Firefox Add-On is out of date. Mozillas official add-on store lists version 2023.7.1 which was released on July 13 and added to the Add-On store in July 18. The latest version was released in the beginning of last week and has not yet made it to the Mozilla Add-On store.

**Comment by Adedamola-Aina** [comment]
Hello podbiker, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, could you reinstall the extension or update to a more recent version. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
