### ISSUE TITLE
Chrome plugin cannot be authenticated through Windows Hello after reboot (when using multiple accounts?)

### ISSUE THREAD

**Issue by xJayMorex** [bitwarden/clients#6187]
### Steps To Reproduce

1. Reboot PC
2. Open browser
3. Open Bitwarden plugin
4. Try to authenticate using Windows Hello (using the fingerprint reader in my case)

### Expected Result

Chrome plugin is authenticated and passwords can be accessed.

### Actual Result

Error message that connection to desktop client is lost.

Also, at this point, the desktop client is missing the Windows Hello login button for the given Bitwarden account (the other accounts have it) and requires the master password to log in, which is a major hassle. After logging in using the master password, I have to disable and then re-enable the browser plugin integration option in settings (multiple times on some occasions) before I am able to use Windows Hello to access my passwords through the browser plugin.

### Additional Context

This is happening with multiple Windows users (as in my case there are multiple Bitwarden accounts signed in through multiple Windows users).

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2

### Web Browser

Chrome

### Browser Version

ungoogled-chromium 115.0.5790.99

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please make sure that your desktop app is installed using our .exe installer (https://bitwarden.com/download/). The app store version won't work with the integration. If you're unsure, you could just uninstall the current one, and install using the .exe installer.

After you're sure that it is from our .exe installer, do these steps:
1. Reboot the laptop to ensure we're in a fresh state.
2. Make sure the browsers are not running.
3. Start the Bitwarden desktop app, open settings, uncheck the "Browser integration" option, then close the settings page
4. Open the settings again, check/enable the "Browser integration" option
5. Start the browser and try to enable the Biometrics unlock.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
