### ISSUE TITLE
Bitwarden stuck on loading after first close

### ISSUE THREAD

**Issue by jonaskohl** [bitwarden/clients#6202]
### Steps To Reproduce

1. Install Bitwarden for Firefox
2. Sidebar opens
3. Log in
4. Close sidebar
5. Click on extension icon

### Expected Result

The extension popup opens like normal

### Actual Result

Only a gray screen with the loading spinner will appear

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/23175424/8adc0082-2859-4e82-ad35-ffa95d4444dc

### Additional Context

Inspecting the extension via about:debugging#/runtime/this-firefox > Bitwarden > Inspect yields hundreds of the following exception in the console:

<details>
<summary>Error</summary>
<pre>
Uncaught (in promise) TypeError: can't access dead object
    get memory-storage.service.ts:9
    state state.service.ts:2913
    Ha background.js:1
    Ha background.js:1
    state background.js:1
    defaultOnDiskLocalOptions state.service.ts:2736
    Ha background.js:1
    Ha background.js:1
    defaultOnDiskLocalOptions background.js:1
    getVaultTimeoutAction state.service.ts:2309
    Ha background.js:1
    Ha background.js:1
    getVaultTimeoutAction background.js:1
    getTimeoutBasedStorageOptions state.service.ts:2893
    Ha background.js:1
    Ha background.js:1
    getTimeoutBasedStorageOptions background.js:1
    getAccessToken state.service.ts:220
    Ha background.js:1
    Ha background.js:1
    getAccessToken background.js:1
    getIsAuthenticated state.service.ts:1718
    Ha background.js:1
    Ha background.js:1
    getIsAuthenticated background.js:1
    getIsAuthenticated browser-state.service.ts:47
    pl background.js:1
    pl background.js:1
    getIsAuthenticated background.js:1
    getAuthStatus auth.service.ts:241
    Qe background.js:1
    Qe background.js:1
    getAuthStatus background.js:1
    shouldLock vaultTimeout.service.ts:112
    eu background.js:1
    eu background.js:1
    shouldLock background.js:1
    checkVaultTimeout vaultTimeout.service.ts:60
    o background.js:1
[memory-storage.service.ts:9:21](webpack:///libs/common/src/platform/services/memory-storage.service.ts)
</pre>
</details>

With a link to this page: https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/

### Operating System

macOS

### Operating System Version

10.9

### Web Browser

Firefox

### Browser Version

78.15.0esr (64-Bit)

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @jonaskohl 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, could you uninstall the adblocker, DNS or VPN, then reinstall the Bitwarden extension and let us know if the issue persists.  

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
