### ISSUE TITLE
Linux Application stuck on opening

### ISSUE THREAD

**Issue by Oleksii909** [bitwarden/clients#6215]
### Steps To Reproduce

1. Go to web app add 2fa.
2. Login on web with 2fa success.
3. Open app in android - relogining request with 2fa-> success.
4. Open app on linux -> app running and stuck. Also logout option is not respond in app on linux.

### Expected Result

![зображення](https://github.com/bitwarden/clients/assets/73876066/666c9b2b-9663-42a9-aec0-5bdef33301d2)

### Actual Result

...

### Operating System

Linux

### Operating System Version

Mint basedon ubuntu 

### Installation method

Snap

### Build Version

223.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @Oleksii909, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a network glitch or corruption of your local data.  Please try:

- logging out and back in again
- reinstalling, including ensuring that all local data is removed 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
