### ISSUE TITLE
Endless Loading before login

### ISSUE THREAD

**Issue by chriMay** [bitwarden/clients#6216]
### Steps To Reproduce

1. Open Bitwarden Desktop
2. Loading screen
3. Short (1/2 s) appearance of login screen
4. endless loading circle

### Expected Result

Open the vault and accessing my passwords

### Actual Result

endless loading screen 

### Operating System

Linux

### Operating System Version

Linux Mint 21.2, Cinnamon

### Installation method

Snap

### Build Version

Version 2023.8.3 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment]
Hi @chriMay 


I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
