### ISSUE TITLE
Child collections are moved to the root when the parent collection is renamed

### ISSUE THREAD

**Issue by MariaPaypoint** [bitwarden/clients#6217]
### Steps To Reproduce

1. Go to a collection which has some child collections
![image](https://github.com/bitwarden/clients/assets/64310483/4313203f-6a20-43e4-8b38-d50994044e68)

2. Rename it
![image](https://github.com/bitwarden/clients/assets/64310483/aa71e3d8-454d-4412-b4b5-5bc97803fa62)

### Expected Result

The collection is renamed, and its content is the same.

### Actual Result

The collection is renamed, but its content (child collections) is moved to the root.
![image](https://github.com/bitwarden/clients/assets/64310483/1ee38797-0b94-4eda-b1e9-d2107ecd8d5a)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @MariaPaypoint, 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.  You can add your voice to the existing request here:

https://community.bitwarden.com/t/shared-sub-folders-to-organize-items-inside-collections-nested-inheritance/873

Please note that nested collections are currently for display-purposes only. They will not inherit items, access, or permissions from their "parent" collection:

https://bitwarden.com/help/about-collections/#nested-collections

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by MariaPaypoint** [comment]
Thank you, atjbramley, for the quick reply. I have voted for the future request you linked.

However, I suppose that the described behavior of the web client when renaming is a bug. 

I assume that recursively renaming nested collections is a possible solution for the web client. On the other side, for a user manually transferring hundreds or thousands of collections (which **suddenly** ended up in the root) is extremely laborious (if there are many collections and the structure is complex, as we have after import from KeePass).
