### ISSUE TITLE
Error: No encrypted user key found

### ISSUE THREAD

**Issue by prewk** [bitwarden/clients#6260]
### Steps To Reproduce

1. Go to any client of the latest version (even the Web Vault!)
2. Attempt to log into it

### Expected Result

I get logged in

### Actual Result

`Error: No encrypted user key found` appears.

### Screenshots or Videos

<img width="570" alt="Screenshot 2023-09-11 at 22 45 13" src="https://github.com/bitwarden/clients/assets/640102/3b0223e5-cb0c-441a-b67a-e2b25ee28629">

### Additional Context

**Workaround**: As per [this reddit thread](https://www.reddit.com/r/Bitwarden/comments/1694vsn/error_no_encrypted_user_key_found/) I downloaded `Bitwarden 2023.7.1` desktop app and can successfully log in and see my passwords, thankfully! No other client works.

More and more people will drop into that reddit thread and with this GitHub issue the problem's hopefully more visible.

### Operating System

macOS

### Operating System Version

13.5.2, iOS 16.6.1

### Web Browser

Chrome, Safari

### Browser Version

Version 116.0.5845.179

### Build Version

 2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by maxinfet** [comment]
This issue affects the chrome extension, web client and Android app, I put together a summary in this reddit [thread](https://reddit.com/r/Bitwarden/s/DpzbkcepU9). The list of clients I listed is not exhaustive it just happens to be the clients I use and tested.

**Comment by JasonZhang0320** [comment]
Hi there,

Same issue for me. Recently my bitwarden ios app crashed again and again. Also, the web page can't be logged in, saying no encrypted user key found.

**Comment by Greenderella** [comment]
Hello,

We appreciate your report and the time you've taken to bring this issue to our attention.

I wanted to let you know that the engineering team is aware of the problem, and they are actively working on resolving it. The fix is currently in the code review stage, and you can track its progress using the following links:

Mobile Repository: [Pull Request #2769](https://github.com/bitwarden/mobile/pull/2769)
Clients Repository: [Pull Request #6195](https://github.com/bitwarden/clients/pull/6195)

We appreciate your patience and understanding as we work towards a solution.

**Comment by prewk** [comment]
Appreciate it! After weeks of not being able to access the vault we switched to 1Password. We used the free tier in BW so can't complain :)
