### ISSUE TITLE
Windows SO bitwarden Desktop App Image doesn't load

### ISSUE THREAD

**Issue by ernzturm** [bitwarden/clients#6284]
### Steps To Reproduce

1. Start Windows "Type here to search" on Windows 10 Pro Version 22H2
2. Type Bitwarden 

### Expected Result

the bitwarden DesktopApp Image

### Actual Result

A blank Image

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/44079185/97952dba-00eb-40be-b45b-fed7a20692a3)

### Operating System

Windows

### Operating System Version

22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in an issue with the installation.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
