### ISSUE TITLE
Firefox addon: Remove item from collection prompts error

### ISSUE THREAD

**Issue by scheinercc** [bitwarden/clients#6306]
### Steps To Reproduce

1. Open extension popup via browser toolbar icon
2. "Edit" any entry which is part of a single collection
3. On the edit screen scroll to "Collections >" and click
4. On the collections screen untick that single collection in order to remove that item from it

### Expected Result

Item gets removed from collection

### Actual Result

Error pops up instead: You must select at least one Collection

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/817856/ab4b2094-5f07-471d-bf7a-7c5c20d42723)

### Operating System

macOS

### Operating System Version

13.5.2 (22G91)

### Web Browser

Firefox

### Browser Version

118.0b8

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @scheinercc, 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

In particular, items stored in Organisations must belong to at least one collection.  This error message is showing that you are not allowed to store an item in an organisation without it being part of a collection.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by scheinercc** [comment]
Leaving this here for others who might find this ticket: https://bitwarden.com/help/org-faqs/#q-how-do-i-unshare-an-item-from-my-organization
