### ISSUE TITLE
Desktop application just keeps spinning in start-up

### ISSUE THREAD

**Issue by mjaakkol** [bitwarden/clients#6324]
### Steps To Reproduce

1. Go to 'Open application'

### Expected Result

Bitward should offer me an option to login

### Actual Result

Application flashes quickly something in the beginning and then enters into spinning. Most  of the menu options grayed out.

### Screenshots or Videos

![Screenshot 2023-09-18 070658](https://github.com/bitwarden/clients/assets/15266727/f9ccb1f1-70d8-4f1c-b717-23522244e164)

### Additional Context

Web and other OS access works fine their access to my Bitward account in cloud seems to be OK

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @mjaakkol,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption of your installation, and would encourage you to re-install.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
