### ISSUE TITLE
"bw list org-members" ignores "--collectionid"

### ISSUE THREAD

**Issue by atoponce** [bitwarden/clients#6344]
### Steps To Reproduce

After logging in and exporting the environment variable, execute:

    $ bw list org-members --organizationid $OID --collectionid $CID

### Expected Result

Expected is a filtered listing of organization members in the provided collection. When executing `bw list org-members --collectionid $CID` without `--organizationid $OID` fails:

    $ bw list org-members --collectionid $CID
    `organizationid` option is required.

So providing both `--collectionid $CID` and `--organizationid $OID` should list only the users in the provided organization's collection:

    $ bw list org-members --collectionid $CID --organizationid $OID
    # filtered list of organization members in the given organization

### Actual Result

Every user in the organization is returned, regardless if they are a member of that organization or not. Providing `organizationid $OID` ignores `--collectionid $CID` and returns all members in the organization, rather than those requested by the `--collectionid $CID` filter:

    $ bw list org-members --collectionid $CID --organizationid $OID
    # listing of all organization users returned

### Operating System

Linux

### Operating System Version

Debian Sid

### Shell

Zsh

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @atoponce,

Thank you for your report. It appears that you are describing the intended behaviour of the CLI; It cannot combine those two parameters to show only organizational members with access to a specific collection.

If this is important to you, you're more than welcome to submit this as a Feature Request; You can sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

We use GitHub to track unintended behaviours and development-related matters; This report will now be closed. 

Thank you again,
