### ISSUE TITLE
TOTP Auth Token saved on mobile android version does not match on windows desktop version

### ISSUE THREAD

**Issue by bsmo2000** [bitwarden/clients#6377]
### Steps To Reproduce

1. add a totp auth token on the mobile app version for android. 
2. sync the vault
3. open desktop app on windows 11 pro
4. access saved totp auth token and try to login to device/app
5. auth tokn does not match what is on mobile app

### Expected Result

auth token on desktop app should match mobile app

### Actual Result

incorrect auth token syncrinization or bug

### Operating System

Windows

### Operating System Version

windows 11 build 22000.2416

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @bsmo2000,

Thank you for your report, could you please check that time and dates are set up correctly on your devices.

Kind regards,
Daniel

**Comment by SergeantConfused** [comment]
Hello @bsmo2000,

Thank you for reporting this. I tested this between my Windows 11 Pro machine and my Android 12 device, and I am unable to reproduce this. This is most likely stemming from incorrect Time and/or Time Zone settings; Please set both the Time and the Time Zone to Automatic on both device and test that once more; I say this because invalid/incorrect 6-digit TOTP codes can stem from having the incorrect Time and/or Time Zone set on the device that's generating the codes and/or is validating them.

If this behaviour persists, please create a support ticket (https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report.

Alternatively, you can also seek assistance from other Bitwarden users in our community forums (https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.

Thank you again,
