### ISSUE TITLE
Bitwarden automatically opens a window on each website with a master password re-promptet entry

### ISSUE THREAD

**Issue by chraebsli** [bitwarden/clients#6389]
### Steps To Reproduce

1. Create a login in Bitwarden with the option “re-prompt master password” enabled
2. Go to this website

### Expected Result

Noting happens/ username gets filled out if field is available

### Actual Result

If the page is loaded, Bitwarden opens in a new window like in the image below (red border)

### Screenshots or Videos

![bitwarden-error](https://github.com/bitwarden/clients/assets/73113302/86422e10-521a-47e8-a80e-edb9893e734a)

### Additional Context

This happens with EVERY website when there is the re-prompt with the master password enabled, and it matches the URI. Also on websites with no such field.

If you have a workaround for this issue, please write a comment because it gets really annoying if you just go to another page, and it comes up again.

### Operating System

Windows, Linux

### Operating System Version

Windows 11; Linux Manjaro (Kernel v6.1, Plasma v5.27.8)

### Web Browser

Brave

### Browser Version

1.58.131

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of browser settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by chraebsli** [comment]
I updated the issue description with the new information we found out that the "autofill on page load" option must be enabled.

**Comment by cagonzalezcs** [comment]
Wanted to give a response to this for users who are looking for a way to resolve this issue. 

This issue specifically occurs due to the work done within https://github.com/bitwarden/clients/pull/5621 

Originally, vault items with master password re-prompt turned on were unable to autofill using context menu or keyboard actions. The work done to facilitate that behavior requires that we open the extension's popup window in some manner allowing the user the ability to enter their master password to fill the vault item. 

Users are now able to fill vault items that require a master password re-prompt, but the fix for that feature did introduce the bug referenced in this ticket. [Work has already been merged in to fix this bug.](https://github.com/bitwarden/clients/pull/6189) That work will effectively turn off "autofill on load" for any master password re-prompt protected items. This will instead force a user interaction for autofilling a master password re-prompt protected item through either the keyboard shortcut or the context menu.

The work for that fix is set to be released in the `2023.10` release.

A current workaround for the moment would be to either turn off the global setting for `Auto-fill on load`, or go to the individual vault items that are auto-filling and turn off the `Auto-fill on load` feature for the vault item that is master password re-prompt protected.

**Comment by cagonzalezcs** [comment]
@bwbug 

I've provided a reply to that ticket. It'd be a good idea to keep discussion for that issue in that thread.
