### ISSUE TITLE
Null MasterKey when logged in via Touch ID

### ISSUE THREAD

**Issue by jakubwojcik** [bitwarden/clients#6397]
### Steps To Reproduce

1. Open Bitwarden desktop app
2. Enable **Unlock with Touch ID** and **Ask for Touch ID on launch**in settings
3. Create a **Login** entry with minimum info: name, username, password, **enable Master password re-prompt option**
4. Lock the vault
5. Login via Touch ID
6. Navigate to the created Login item
7. Click **Toggle the visibility** or **Copy password** button next to the password field
8. Enter your master password

### Expected Result

Password will be shown / copied to the clipboard.

### Actual Result

Password is still hidden / non-copied. There is an error in the console:

```javascript
error_handler.ts:45 ERROR Error: Uncaught (in promise): Error: Invalid parameters.
Error: Invalid parameters.
    at useClass.<anonymous> (crypto.service.ts:244:13)
    at Generator.next (<anonymous>)
    at r (main.js:1:188749)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:456407)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
```

### Screenshots or Videos

![SCR-20230925-kzee](https://github.com/bitwarden/clients/assets/9906494/a60e57f9-bfbf-4cd2-b5ae-7534f1ec0602)

### Operating System

macOS

### Operating System Version

13.5.2

### Installation method

Mac App Store

### Build Version

2023.8.4 (11864)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @jakubwojcik, 

I attempted to reproduce your issue in 2023.9 and was unable to do so. I think your error could have its origin in an outdated version - please update to 2023.9 to resolve this.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
