### ISSUE TITLE
Master Password Reprompt Popup Window

### ISSUE THREAD

**Issue by MRobi1** [bitwarden/clients#6401]
### Steps To Reproduce

Go to any page requiring master password re-prompt

### Expected Result

Password reprompt in order to autofill login page.

### Actual Result

A new popup window has started appearing on the right side asking for the master password reprompt. And it appears over and over and over again every single time a new page loads, or trying to fill in a text box input, or clicking on a drop down. And every time it pops up it changes the browser focus to the popup for the reprompt. This is occurring well after the initial login is completed and for as long as that site is in use.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

latest

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try uninstalling the Bitwarden extension and re-installing it to see if the issue persists.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by cagonzalezcs** [comment]
@MRobi1 

Thank you for the bug report. Please refer to [this comment](https://github.com/bitwarden/clients/issues/6389#issuecomment-1739836296) for a workaround until 2023.10 is release, as well as an explanation of what is triggering the window to popup in that manner.
