### ISSUE TITLE
Deleting entry resets item list to default (first) position

### ISSUE THREAD

**Issue by OrnoCav** [bitwarden/clients#6435]
### Steps To Reproduce

1. Go to Desktop Application
2. Click on 'All items' (or any folder)
3. Scroll down to and select any entry that scrolls the first item off top of the view
4. Click on 'delete' and 'yes'

### Expected Result

Item list remains in current/last position

### Actual Result

Item list resets to default first item after any item is deleted

### Operating System

Windows Pro 10.0.19045

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.0

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
