### ISSUE TITLE
multiple item selection issues

### ISSUE THREAD

**Issue by OrnoCav** [bitwarden/clients#6436]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/
2. Login & Scroll to anywhere in list
3. Click on multiple item selections

### Expected Result

1) Top bar actions relating to multiple item selection remain in view regardless of list position
2) larger multiple item selection box (matching icon size)
3) accidental/misregistered click on item instead of selection box does not clear selection list
4) item list column should be adjustable or at least scaling to available width (webui and desktop app)

I will also note an expectation that the desktop app at least match the functionality of the webui, pertinently being the lack of multiple item selection functions 

### Actual Result

1) top bar option scroll off page
2) item tick box is a quarter the icon size, leading to issues with 3
3) accidental/misregistered click on list item clears active selections
4) webui shows less item text via column width than the desktop app, did not realize this until I had both open side by side while investigating another issue

### Operating System

Windows

### Web Browser

Chrome, Brave (both current)

### Build Version

WebUI 2023.9.1

**Comment by jtodddd** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
