### ISSUE TITLE
webauthn-mobile-connector.html doesn't respect callbackUri

### ISSUE THREAD

**Issue by AChep** [bitwarden/clients#6468]
### Steps To Reproduce

Open `webauthn-mobile-connector.html` with `parent=test://callback` and `data.callbackUri=test://callback`. Click the Return button.

### Expected Result

The browser opens provided callback URL.

### Actual Result

The browser opens hardcoded `bitwarden://webauthn-callback`, as seen here https://github.com/bitwarden/clients/blob/a42cea857052ad0338cb4427f265fac1d569da4b/apps/web/src/connectors/webauthn.ts#L6

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

master

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AChep** [comment]
If you clarify whether I should use `parent` or `data.callbackUri` then I can submit a PR that fixes this issue. This is kinda blocking me from adding Fido2WebAuthn to Keyguard, as I want to avoid relying (and competing with) the `bitwarden://` URI scheme.

**Comment by AChep** [comment]
Added a PR that uses `data.callbackUri`.

**Comment by Greenderella** [comment]
Hi there,

I have escalated this report for further investigation. If you have more information that can help us, please add it below.

Thanks!

**Comment by AChep** [comment]
As a side note, I did add a handler for `bitwarden://webauthn-callback` to Keyguard, which might affect a small percentage of people who have both apps installed.

**Comment by trmartin4** [comment]
Hello @AChep. After considering this change, we will not support arbitrary callback URIs from Bitwarden-controlled web assets. A callback URI was deemed insecure since it allows for arbitrary redirection from a Bitwarden-managed URL. Those kinds of open redirects allow for a attacks which utilize the trust garnered by our company to lull victims into a false sense of security. In general, we will only support redirects to Bitwarden-controlled software from Bitwarden cloud services at this time.
