### ISSUE TITLE
Captcha connector doesn't respect callbackUri

### ISSUE THREAD

**Issue by AChep** [bitwarden/clients#6470]
### Steps To Reproduce

Open captcha connector with `parent=test://callback` and `data.callbackUri=test://callback`. Complete the challenge.

### Expected Result

The browser opens provided callback URL.

### Actual Result

The browser opens hardcoded `bitwarden://captcha-callback`, as seen here 
https://github.com/bitwarden/clients/blob/20564f2f546e367be45528778d1b63a08eb44d05/apps/web/src/connectors/captcha.ts#L85

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

master

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I have escalated this report for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by trmartin4** [comment]
Hello @AChep. After considering this change, we will not support arbitrary callback URIs from Bitwarden-controlled web assets. A callback URI was deemed insecure since it allows for arbitrary redirection from a Bitwarden-managed URL. Those kinds of open redirects allow for a attacks which utilize the trust garnered by our company to lull victims into a false sense of security. In general, we will only support redirects to Bitwarden-controlled software from Bitwarden cloud services at this time.
