### ISSUE TITLE
Bitwarden spams browser start webpage

### ISSUE THREAD

**Issue by dorjanbenic** [bitwarden/clients#6488]
### Steps To Reproduce

While having Bitwarden installed update Bitwarden or MacOS. After Bitwarden/MacOS update finish the process and your system/browser restarts new tab will be opened at location https://bitwarden.com/browser-start.

### Expected Result

Expected result is that https://bitwarden.com/browser-start does not load as app extension is already installed in Safari. If it does load it should not load every time Bitwarden/MacOS update completes.

### Actual Result

After Bitwarden/MacOS update finish the process and your system/browser restarts new tab will be opened at location https://bitwarden.com/browser-start.

It happens every time Bitwarden restarts after update and/or when Mac restarts after update. If I just restart Mac or Safari without update, it does not happen.

### Screenshots or Videos

<img width="1436" alt="Screenshot 2023-10-01 at 12 00 46" src="https://github.com/bitwarden/clients/assets/39588255/18ade0a2-572e-4dc4-b1ca-89ce868633b5">

### Additional Context

It was been happening ever since I installed Bitwarden on my Mac (end of 2022). It seems to me that app does not understand that it was installed long ago and it is under impression that it was just installed so every time when I update it opens mentioned tab every time.

Before I reported this but I have tried to reinstall Bitwarden. I uninstalled it and restarted my system, then installed it again from MAS. Once I installed and configured app I had three same tabs opened at location https://bitwarden.com/browser-start. First two opened as I was interacting with extension and app for the first time. Third one was opened as I was opening app for the second time which never happened before. I did click on browser integration toggle in app before closing the app.

### Operating System

macOS

### Operating System Version

Venture 13.6

### Installation method

Mac App Store

### Build Version

Version 2023.9.1 (12289)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @dorjanbenic ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or corruption of your Bitwarden Installation.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by andrewkr** [comment]
This happens to me also on my Macs which have (or had) macOS 13 installed. I haven’t had to do a major update of Bitwarden since upgrading to macOS 14.xx so I don’t know if the same bug will continue.

I’m also fairly certain that my Mac is using 10.15.xx (Catalina) doesn’t suffer this bug.

If it is a misconfiguration as you suggest it might be, I wouldn’t even know where to begin to look. A corrupted installation? So, completely delete Bitwarden from that machine and re-install from scratch?

If I encounter the same bug again, I’ll try and remember to, first, take note of which version of macOS I was using, second, which version of Bitwarden I just updated to, and third, to completely remove Bitwarden from that machine and then reinstall.

However, that’s a lot of things to remember to do for an old bloke like me! And secondly, these things usually occur at a time when there is not usually time to stop and think about all of those steps, especially the last one, completely removing and performing a fresh installation.

Nevertheless, I shall try.

Andrew
