### ISSUE TITLE
"Launch unlock or login in new window when auto-filling" feature breaks for swaywm.

### ISSUE THREAD

**Issue by AlexChalk** [bitwarden/clients#6489]
### Steps To Reproduce

1. Start [swaywm](https://github.com/swaywm/sway/) and firefox.
2. Do not unlock the vault (yet).
3. Go to a page with log in credentials saved.
4. Enter keyboard shortcut to autofill.

### Expected Result

Visible unlock page.

### Actual Result

Broken/not visible unlock page.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/22868730/ee11ff6e-c9c8-497e-9ce3-562e59e93ba0)

### Additional Context

A solution for me would just be a setting to open the unlock page in a new tab (extension v8.X behaviour). 

### Operating System

Linux

### Operating System Version

NixOS 23.05.3976.32dcb45f66c0 (Stoat) x86_64

### Web Browser

Firefox

### Browser Version

118

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Aniketxmishra** [comment]
It seems like you're experiencing an issue with SwayWM and Firefox when trying to autofill login credentials. To help you troubleshoot and potentially resolve this issue, here are some steps you can follow:

1. **Check Software Versions:**
   - Ensure that you are using the latest versions of both SwayWM and Firefox, as updates may include bug fixes and improvements.

2. **Confirm Autofill Settings in Firefox:**
   - Open Firefox.
   - Go to the Firefox menu (three horizontal lines in the upper right corner).
   - Click on "Options" or "Preferences" (depending on your operating system).
   - Navigate to "Privacy & Security."
   - Make sure "Logins and Passwords" is enabled.
   - Check if "Ask to save logins and passwords for websites" is turned on.
   - Also, check if "Use a master password" is enabled and set if you want to use a master password.

3. **SwayWM Configuration:**
   - Check your SwayWM configuration for any keybindings or settings related to window management and focus behavior. These settings could potentially interfere with the unlocking of the vault.

4. **Vault or Password Manager:**
   - If you're using a third-party password manager or vault (other than Firefox's built-in password manager), ensure it's properly integrated with both Firefox and SwayWM.

5. **Try a Different Window Manager:**
   - To determine if the issue is specific to SwayWM, you can try switching to a different window manager temporarily and see if the problem persists.

6. **Check Error Logs:**
   - Check SwayWM and Firefox logs for any error messages or warnings that may provide more details about the issue.

7. **Community Support:**
   - Search for the specific issue you're facing in forums or communities related to SwayWM and Firefox. Others may have encountered similar problems and found solutions.

8. **Report the Issue:**
   - If you can't find a solution, consider reporting the issue on the official GitHub repositories or support forums for SwayWM and Firefox. Provide detailed information about your setup, including versions, configurations, and steps to reproduce the problem.

9. **Temporary Workaround:**
   - As a temporary workaround, you might need to manually unlock your vault before attempting to autofill login credentials in Firefox. This may involve running a command or interacting with your password manager.

Remember to create backups and be cautious when making changes to your system configuration. It's essential to understand the potential consequences of any changes you make to avoid causing further issues.

**Comment by wooque** [comment]
Experiencing the same, I would rather have option to open this page in new tab like it was working before, than new window.

**Comment by AlexChalk** [comment]
I added this code in my sway config which makes the new behaviour usable:
```
for_window [app_id="firefox" title="Bitwarden — Mozilla Firefox"] {
  floating enable
}
```
Closing the issue as a result.
