### ISSUE TITLE
Ctrl+Shift+L autofill not working anymore on Firefox (Linux)

### ISSUE THREAD

**Issue by ad-on-is** [bitwarden/clients#6494]
### Steps To Reproduce

For some reason, Ctrl+Shift+L does not autofill anymore.

I tried disabling all FF extensions, to see whether another one occupies the shortcut, but with no avail.
Temporarely changing it to Ctrl+Alt+L works, but changing it back to Ctrl+Shift+L again stops working. Also, I don't get a warning from FF that it internally occupies this shortcut. 

Does anyone have any idea what might be going on? 

### Expected Result

Ctrl+Shift+L should outfill/cycle through the available credentials

### Actual Result

Ctrl+Shift+L does nothing

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

118

### Build Version

2023.9.1

**Comment by jpjonte** [comment]
Same here on macOS 13.4.1, Firefox 118.0.1 and Bitwarden 2023.9.1.

**Comment by ad-on-is** [comment]
LOL... actually... I just found that the shift-key of my custom built keyboard would sometimes not trigger. Now it works

**Comment by bpsib** [comment]
Same here on Firefox in Windows 11 after the extension updated. I find the keyboard so useful to save time and I am not a patient guy. This regression needs fixing ASAP.

**Comment by ericrbg** [comment]
Can confirm also on macOS 13.4.1 (c), FF 117.0.1 and Bitwarden 2023.9.1; this has been repro'd on 118.0.1 so it's not a firefox update issue.

**Comment by bpsib** [comment]
Shift+Alt+Y also doesn't work anymore to show the Bitwarden sidebar. This is a real nuisance. The update to 2023.9.1 seems to have broken all the keyboard shortcuts in Firefox.

**Comment by JohannesDeml** [comment]
Same for me on MacOS 13.4.1 and FF 118.0.1 with bitwarden 2023.9.1
Also verified that the shortcut is set correctly and was working before on that machine.
![image](https://github.com/bitwarden/clients/assets/4518980/56d59e1a-cd05-46bc-803e-70d46d5c14d2)

**Comment by atjbramley** [comment]
Hi @ad-on-is,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or other software 'hijacking' these shortcuts - in particular for this case you mentioned that your custom keyboard caused the error.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ericrbg** [comment]
There has been multiple other people reproing - how is this just closed?

**Comment by leonardehrenfried** [comment]
I can also confirm that the shortcut doesn't work on Linux with Firefox 118.0. I would welcome this being re-opened.

**Comment by bpsib** [comment]
Shift+Alt+Y now works again for me but not Ctrl+Shift+L. A workaround I have found that works is to change the shortcut to something such as Ctrl+Alt+L.

**Comment by kschat** [comment]
Same issue here with Firefox 118.0 on Linux. Restarting the browser instance fixed the issue, but that's not really a proper solution. This issue should be reopened.

**Comment by JohannesDeml** [comment]
Works now again for me as well, I think restarting the browser was necessary.
