### ISSUE TITLE
Bitwarden asks to save password when really it's not logged in

### ISSUE THREAD

**Issue by jdeibele** [bitwarden/clients#6513]
### Steps To Reproduce

When I log into a site (using Keychain in Safari on my Mac), Bitwarden will ask me if I want to remember a password that it's already saved.

![Screenshot 2023-09-07 at 09 17 55](https://github.com/bitwarden/clients/assets/264802/f866dfc3-7320-43d8-9aea-69a853bbc77e)

### Expected Result

I expect Bitwarden to say "you're not signed into Bitwarden".

### Actual Result

In the screenshot I've attached, clearly the Bitwarden vault is locked.  

You're using one error message for two completely different situations.

### Screenshots or Videos

![Screenshot 2023-09-07 at 09 17 55](https://github.com/bitwarden/clients/assets/264802/fb0a7272-670b-42df-9893-e5181443a99d)

### Operating System

macOS

### Operating System Version

Sonoma, Ventura, Monterey

### Web Browser

Safari

### Browser Version

Safari released versions (I upgrade whenever a new version comes out)

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. Upon selecting "save," you will be prompted to enter your master password before anything is added to your vault. It's also likely that the existing item has a URI setting of "Exact" instead of "Base Domain," preventing Bitwarden from recognizing the login credentials. 

If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
