### ISSUE TITLE
Login window in Firefox not rendered well with sidebar open

### ISSUE THREAD

**Issue by dirvo** [bitwarden/clients#6531]
### Steps To Reproduce

1. Start Firefox (latest version) with the Bitwarden add-on installed and configured.
2. Open the bookmarks sidebar.
3. Open a web page that requires authentication.
4. Press Ctrl+Shift+L to fill.
5. A _new window_ opens to login to Bitwarden (this used to be a tab working just perfect).

### Expected Result

Two possible expected results:

A: A new tab opens to enter the master password (as it used to be).
B: A new window opens that allows to easily enter the password, i.e. no additional UI elements of the browser are shown. In particular, the side bar, URL bar, bookmark bar etc. should not be visible in the popup.

Ideally, there should be an option to keep the current behaviour of just opening a separate tab instead of a window.

### Actual Result

The new windows opens with toolbars and sidebars open, leaving only little space for the actual page content.

### Screenshots or Videos

<img width="366" alt="firefox_DIvWFty537" src="https://github.com/bitwarden/clients/assets/1919798/b0e5b824-c36d-422e-961c-3c5d2fae5d27">

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

118.0.1

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @dirvo,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

In particular, you can find more information on the reasons behind your described behaviour at the issue below:
https://github.com/bitwarden/clients/issues/6412#issuecomment-1739853982

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by dirvo** [comment]
@atjbramley I understand the reasoning behind the change (partly); however, I disagree, that the current solution works as intended. The width of the login window should be at least as wide so that the input into the master password field is visible. As you can see in my screenshot, the content width is only about 80 px.

**Comment by dirvo** [comment]
@atjbramley I can confirm that this is indeed profile-related and does not happen with a fresh profile.

**Comment by hirschferkel** [comment]
As I can see, it is not profile related but related to the origin tab.
So if sidebar with Bookmarks is open in the login screen, the new window Pup Up for Bitwarden will have an open bookmark sidebar, too.

Actually this is not wanted, I think.
