### ISSUE TITLE
creating a text Send does not show option to hide text by default

### ISSUE THREAD

**Issue by tessus** [bitwarden/clients#6544]
### Steps To Reproduce

1. Go to `Send`
2. Click on `+` to create a new send
3. Choose `Text` as type
4. Click on `Options`

### Expected Result

There should be an option `When accessing the Send, hide the text by default`.

### Actual Result

No such option exists.

### Screenshots or Videos

<img width="663" alt="image" src="https://github.com/bitwarden/clients/assets/223439/dc5b67f4-7948-461e-bf45-06a04eeb1886">

### Additional Context

The option shows up **after** the Send has been created and one navigates to the Send to edit it.

### Operating System

macOS

### Operating System Version

10.14.4, 13.5.2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.1 (12289)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could be because you have selected the "File" option rather than the "Text" option. In your screenshot, the "file option" is selected, and the option to hide the text would not be visible.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by tessus** [comment]
@TroyBW you are wrong. it is not fromn a file send:

<img width="649" alt="image" src="https://github.com/bitwarden/clients/assets/223439/b6a5a1d8-57b3-452b-ab9a-bece3e7c0239">
<img width="622" alt="image" src="https://github.com/bitwarden/clients/assets/223439/d6417196-d999-4186-b8f3-2725c3191cc3">

It is just that the UI does not fit on one screen. I have also selected "text" in the screenshot of the first post.

**Comment by TroyBW** [comment]
My apologies, I am able to reproduce this issue in specifically the Bitwarden desktop application. 

This is issue is not present in the Bitwarden browser extension, the Bitwarden mobile app, or the Bitwarden Web App (vault.bitwarden.com). 

The issue will remain open. Thanks!

**Comment by tessus** [comment]
No worries, maybe I should have added `Desktop` somewhere, but I used the "desktop issue template" thus I thought it would be mentioned someehere anyway.
