### ISSUE TITLE
Autofill on firefox loads bitwarden in separate window

### ISSUE THREAD

**Issue by StevenMassaro** [bitwarden/clients#6545]
### Steps To Reproduce

Path 1:
1. Enable autofill on page load
2. Create a login that requires master password reprompt
3. Go to a page that you have a password for, it does not reproduce on all pages, but it reproduces for me on github.com
4. Observe that the bitwarden window loads in a separate window

Path 2:
Same steps as above, but don't enable autofill on page load. Instead, use the autofill keyboard shortcut.

### Expected Result

Bitwarden dialog box opens as part of the existing firefox window, not a separate window.

### Actual Result

Bitwarden dialog box opens as a separate window.

### Screenshots or Videos

![Animation](https://github.com/bitwarden/clients/assets/25826807/5db4af37-1e61-4d13-a2a1-55a2215e7139)

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

118.0.1 (64-bit)

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @StevenMassaro, 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

In particular, please see this discussion here for an explanation of this behaviour:

https://github.com/bitwarden/clients/issues/6412

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by atjbramley** [comment]
Thanks @StevenMassaro, 

This constant looping of the auxiliary window is not intended behaviour, and classifies as a bug.  This has now been flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.  In particular, a recording similar to the one you've made above on a second site would be valuable.

Thanks once again!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/6545#issuecomment-1765149557

@jonas-w, that looks like a different issue to me.

**Comment by Jamie4224** [comment]
This is also a problem when using an extension that permanently pins a tab in every window, since the window does not close after the autofill, see my reaction here: https://github.com/bitwarden/clients/issues/6707#issuecomment-1784177023

**Comment by WrichikBasu** [comment]
> The main issue I have with this approach is that the new window appears multiple times after the auto-fill has succeeded.  

Came here to report this issue. Seems to have popped up from the latest version, wasn't there before. It's irritating like nothing else. Hope the team solves it soon.

**Comment by mjlehrke** [comment]
Glad this has been reported. This bug is insanely annoying.

**Comment by StevenMassaro** [comment]
It looks to me like this problem no longer exists. I think this commit fixes it: https://github.com/bitwarden/clients/commit/c75f6c28eb1440d8a25e3629024b6bd6fee905cc
