### ISSUE TITLE
Suddenly this extension thinks regular tabs are private mode tabs

### ISSUE THREAD

**Issue by gerroon** [bitwarden/clients#6575]
### Steps To Reproduce

Open a page

Click on the extension

### Expected Result

It should work like it is in non private mode

### Actual Result

This Firefox (117.1 Windows 11) addon suddenly think that all tabs are private mode tabs. I think there was an automated update last nigth since this was working fine yesterday.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/8519469/b4ba9669-fb78-448a-913e-0d1aacc284c0)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

117.1

### Build Version

2023.9.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Do you possibly have your Firefox browser settings adjusted so that regular windows behave as private?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
