### ISSUE TITLE
Master password reprompt opens new window on sites already logged into

### ISSUE THREAD

**Issue by Mukhilm** [bitwarden/clients#6598]
### Steps To Reproduce

The description below assumes that "Auto-fill on page load" has been enabled.

1. Enable "Master-password re-prompt" for a login item.
2. Launch the corresponding web page.
3. If you are already signed into the page the Master-password re-prompt will still open a new window

### Expected Result

Master-password re-prompt window should only appear when signing into a page

### Actual Result

1. Bitwarden will keep opening a new window every time I click a link on a web page already signed into like amazon, turbotax etc, which makes these sites practically unusable. The re-prompt window should not be opening up on sites I've already logged into. I've had to disable the autofill since it breaks site usability.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/22032143/c8a7cf1d-73cb-439f-bfaf-17f054ddc1a7)
![Screenshot from 2023-10-16 15-59-47](https://github.com/bitwarden/clients/assets/22032143/febac2f0-6db4-4835-9845-2f3a0469ee3e)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.3 LTS

### Web Browser

Chrome

### Browser Version

117.0.5938.132

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. This behavior was changed recently, and was acknowledged here: [#6412](https://github.com/bitwarden/clients/issues/6412#issuecomment-1739853982)

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
