### ISSUE TITLE
"Logged in as __$1__ on bitwarden.com."

### ISSUE THREAD

**Issue by ejain** [bitwarden/clients#6611]
### Steps To Reproduce

1. Wait for the app to get into a state where it shows "Logged in as __$1__ on bitwarden.com." when locked (unsure how to reproduce)
2. Attempt to unlock the vault with the master password

### Expected Result

Vault is unlocked

### Actual Result

Can't unlock the vault

### Screenshots or Videos

![bitwarden](https://github.com/bitwarden/clients/assets/1323903/94bdf59e-5df5-40e4-af52-5f590ab01980)

### Additional Context

This problem started several versions back.

### Operating System

macOS

### Operating System Version

13.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ejain** [comment]
If I click logout when the app is in this state, I get a never-ending spinner. I can get back to normal by pretending that the account wasn't added already, and instead selecting "Add account" (and going through the 2FA process etc).

**Comment by johanvandyck** [comment]
I have the same behavior. Another workaround is 
- stop the client
- delete the content of the folder C:\Users\myuseraccount\%AppData%\Roaming\Bitwarden
- start the client.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, but don't worry, this is normally just a visual bug. 

If you are experiencing this while using the web app, please follow these steps:
1. Exit your current browser window.
2. Open a new browser window.
3. Try to log in into either https://vault.bitwarden.com or https://vault.bitwarden.eu, depending on which region your Bitwarden account is registered. You can find more information about server geographies here: https://bitwarden.com/help/server-geographies/ 

If you are experiencing this issue on the desktop app, please follow these steps:
1. Stop or close the Bitwarden desktop application.
2. Delete the content of the desktop app folder. The specific location for this folder can be found in the provided link, and it depends on the client you are using: https://bitwarden.com/help/data-storage/#on-your-local-machine 
3. After deleting the folder content, try to log in again to the Bitwarden desktop application.

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ejain** [comment]
Please see https://community.bitwarden.com/t/bw-for-windows-logged-as-1-without-reason-impossible-to-logout/57345, this issue has been reported by several users. I'd say that having the app get in a bad state that requires you to wipe out all local data is a bit more than a "visual bug"...
