### ISSUE TITLE
I got a weird HTML non-formatted error message after editing an item

### ISSUE THREAD

**Issue by FaviFake** [bitwarden/clients#6625]
### Steps To Reproduce

1. Go to an item
2. I edited the name of the item (not the URI) from "dashboard.magic.link" to just "magic.link".
3. It was taking a long time to load, so I cancelled and edited the title again. This time it was quick.
5. I edited a few other items under it.
6.  After about 10-20 seconds this weird error message popped up:
```
An error has occurred.
<html> <head><title>502 Bad
Gateway</title></head> «body»
1 >502 Bad
Gateway</h 1 ></center> «h r»
</bodp a padding to
disable MSIE and Chrome friendly
error page a padding to
disable MSIE and Chrome friendly
error page a padding to
disable MSIE and Chrome friendly
error page a padding to
disable MSIE and Chrome friendly
error page a padding to
disable MSIE and Chrome friendly
error page a padding to
disable MSIE and Chrome friendly
error page
```

### Expected Result

No error message.

### Actual Result

![image](https://github.com/bitwarden/clients/assets/86537048/dd5c5605-e899-4721-8f7a-bd2ba5ef9055)

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/86537048/dd5c5605-e899-4721-8f7a-bd2ba5ef9055)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

Version 120.0.6062.2 (Official Build) dev (64-bit)

### Build Version

Version 2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can troubleshoot: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
