### ISSUE TITLE
Adguard make bitwarden alwasys show loading icon in Firefox

### ISSUE THREAD

**Issue by benzBrake** [bitwarden/clients#6634]
### Steps To Reproduce

1. Click Bitwarden button on the toobar.
2. Bitwaren shows the loading icon.

### Expected Result

Only display loading when clicked for the first time

### Actual Result

Loading will be displayed every time when I click the buton

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/11323774/23a97173-9c41-4098-b931-420bb48e6cc1

### Additional Context

I am using a self server.
As you can see in the video, there is no problem clicking in the Vivaldi browser.
Not always like that, but it happens several times a day

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

119.0

### Build Version

20231016204538

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue but was unable to do so. I think your error could have its origin in a misconfiguration. Could you please uninstall the adblocker, VPN, or DNS, then reinstall the Bitwarden extension to see if the issue persists? In some cases, VPN or adblocker browser extensions may interfere with the connection between the Bitwarden app and server.

Furthermore, please ensure that you are using the latest release of the Firefox extension (v2023.9.2): https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thank you.
