### ISSUE TITLE
Red screen of death

### ISSUE THREAD

**Issue by zpetschek** [bitwarden/clients#6639]
### Steps To Reproduce

1. Unlock app
2. Search and copy password from an account
3. Leave Bitwarden running in background for at least 5 min
4. Return to Bitwarden to see a solid red window.

These are not good steps to reproduce because it was just running in the background. I have similar issues with Bitwarden at least twice a week for years. Other scenarios is an unintelligible text block in the window, or a different color filling the window.
<img width="1062" alt="Screen Shot 2023-10-19 at 12 42 45 PM" src="https://github.com/bitwarden/clients/assets/24416573/9f62498c-4ec8-4d30-8a6b-d5fa3a193c3e">

### Expected Result

I expected to see Bitwarden return to the lock screen because it's set to lock after 5 minutes of inactivity

### Actual Result

Bitwarden window is solid red. Only the buttons to close and minimize the window are visible.

### Screenshots or Videos

<img width="1062" alt="Screen Shot 2023-10-19 at 12 42 45 PM" src="https://github.com/bitwarden/clients/assets/24416573/20e5024a-c132-47b2-b213-ae5776432bc3">

### Additional Context

Are there logs or anything that I can send from the app?

### Operating System

macOS

### Operating System Version

12.6.8

### Installation method

Mac App Store

### Build Version

Version 2023.9.3 (12828)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could be hardware related. You may try updating your macOS to the latest version or contacting Apple support. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
