### ISSUE TITLE
Windows setup removes existing files in install folder

### ISSUE THREAD

**Issue by matbech** [bitwarden/clients#6673]
### Steps To Reproduce

1. Copy bw.exe (bitwarden CLI) to %programfiles%\Bitwarden
2. Install the Bitwarden desktop client from here: https://bitwarden.com/download/

Or alternative:
winget install bitwarden.bitwarden

### Expected Result

The installer does not remove any existing file in the install folder

### Actual Result

The setup removes all existing files in the install folder

### Operating System

Windows

### Operating System Version

10.0.*

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. As part of the standard Bitwarden desktop application installation process, all contents of the "C:\Program Files\Bitwarden" are removed. If you want this to be changed, it would be a feature request. Alternatively, you may install the Bitwarden CLI client in another location.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by matbech** [comment]
The setup is not supposed to delete existing files. It's a bug and not a feature request.
