### ISSUE TITLE
Full List of Collections not Visible on Add/Edit Item dialog

### ISSUE THREAD

**Issue by rgibson-kfx** [bitwarden/clients#6675]
### Steps To Reproduce

1. Generate or access an organization with at least 140 collections.
2. Attempt to create a new login (or other item type) and assign ownership to this organization.  Alternately, attempt to edit an item in any existing collection within this organization.
3. Examine the list of assignable collections.

### Expected Result

All collections to which I have access should appear on this list, all of which are currently visible in the collection list on the left navigation tree in the main portion of the application.

### Actual Result

Of the 137 collections in our organization, the final 2 do not appear for me to add items to them.

### Additional Context

Also note that this same bug appears in the web-based vault interface as well, with the exact same behavior.

### Operating System

Windows

### Operating System Version

11

### Installation method

Chocolatey

### Build Version

2023.9.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of collections or their permissions.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
