### ISSUE TITLE
DuckDuckDuckGo says that I need to restart BW to resend…… and then it faults

### ISSUE THREAD

**Issue by lalicatala** [bitwarden/clients#6710]
### Steps To Reproduce

Previously arrange for BW to be the source for PW bin DDG.

Today, launched DDG.

Alert: BW failed to sync and need to relaunch BW.
Did So.
Problem remains

DuckDuckGo version 1.60.1

### Expected Result

BW would resync with DDG

### Actual Result

BW did not resync with DDG

### Screenshots or Videos

![SS 2023-10-26 at 17 47 31](https://github.com/bitwarden/clients/assets/9818367/5ab145bb-defb-4a18-b518-a3fa0afe5673)

### Operating System

macOS

### Operating System Version

13.6

### Web Browser

Safari

### Browser Version

Version 17.0 (18616.1.27.111.22, 18616)

### Build Version

Version 17.0 (18616.1.27.111.22, 18616)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @lalicatala, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption of your installation, and recommend:

- uninstalling DuckDuckGo with AppCleaner (https://freemacsoft.net/appcleaner/)
- rebooting your machine
- reinstalling DuckDuckGo and reconfiguring the Bitwarden integration

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
