### ISSUE TITLE
Firefox: In browser extention, unable to change seperator character for password generator

### ISSUE THREAD

**Issue by harrismcc** [bitwarden/clients#6714]
### Steps To Reproduce

1. Go to bitwarden extension in Firefox
2. Click on Generator
3. Attempt to type into separator field

### Expected Result

Would expect to be able to type in the separator field, and to have the change apply

### Actual Result

Unable to type in the field, separator does not change

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/740503/2ea1f317-0eb3-4af1-ae2c-e3cac4524ffc

### Additional Context

Using Firefox version 119.0
Using Bitwarden extension version 2023.9.2

### Operating System

macOS

### Operating System Version

13.4.1

### Web Browser

Firefox

### Browser Version

119.0

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

After selecting the separator field, click the right-directional key before backspacing once. Try typing the desired separator character you'd like to use after that. It's important to note that the separator field has a one-character limit.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by harrismcc** [comment]
Thanks, that right-arrow trick seemed to do it!
