### ISSUE TITLE
The window steals focus when the vault locks due to inactivity timeout

### ISSUE THREAD

**Issue by h3ndrk** [bitwarden/clients#6744]
### Steps To Reproduce

1. In the app settings, configure a "vault timeout" to, e.g., 1 minute
2. Close the desktop app
3. Open the desktop app
4. Unlock your vault
5. With your vault unlocked, focus another window
6. Wait until the vault timeout triggers and locks your vault

### Expected Result

Locking via "vault timeout" should happen silently in the background and it should never disrupt my workflow when it locks itself again. Please never steal window focus in the desktop app.

### Actual Result

I have configured a 15 minute timeout which means that 15 minutes after using the desktop app, my workflow will be disrupted because the desktop app steals window focus and is on top of all windows. If I'm typing at the moment, I will continue to type in the desktop app window. I need to change the window back where I was working before, which is annoying.

### Operating System

Linux

### Operating System Version

Arch Linux with GNOME 45

### Installation method

Other

### Build Version

Version 2023.9.2  
Shell 24.8.8  
Renderer 112.0.5615.204  
Node 18.14.0  
Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed.

**Comment by pcolaianni** [comment]
It's sad to not see this innovative _intended behavior_ also on smartphones: it would be great to get a phone call every time the device locks the screen due to inactivity.

Jokes aside, the behavior that @h3ndrk kindly described is sadly still present, one year later.

**Comment by hevanaa** [comment]
This is very annoying behavior. I cannot believe it's by design. Please fix!
When I'm working with other software, I don't want another program to steal focus in the middle of me typing or doing some graphics work, and show me that it's locking itself. If it's configured in settings to lock itself, I should be able to trust the configuration. It shouldn't interrupt my work and tell me about it. A notification is enough.

**Comment by calvinrw** [comment]
@NovaSilentium This behavior has annoyed me enough that I have no problem resurrecting this thread.  This is *not* a feature request; it is a bug. No sane person would consider a window stealing focus to perform what should be a background task to be intended behavior. This issue should be reopened.

Edited to add: This bug is still present in Desktop v2026.3.1 for Linux (Debian 13).

**Comment by MrCurlsTTV** [comment]
Issue is still present on latest release.

**Comment by mangowxlf** [comment]
> Issue is still present on latest release.

this issue has been around for 3 years, it has been very distracting in my time using bitwarden
