### ISSUE TITLE
Unable to link to item within browser extension popup

### ISSUE THREAD

**Issue by airtonix** [bitwarden/clients#6745]
### Steps To Reproduce

1. Open the browser extension popup or full window
2. Find any item in your vault
3. attempt to find a way to link to it 
4. right click it... or
5. open its details ...
6. discover that you cant

### Expected Result

be given the option to do this from the extension: 

https://bitwarden.com/help/link-to-an-item/

### Actual Result

no such option exists

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @airtonix, 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by airtonix** [comment]
It's not a feature request...

this is a bug.

**Comment by airtonix** [comment]
https://community.bitwarden.com/t/see-and-copy-the-guid-of-an-item-in-the-user-interface/41811/4
