### ISSUE TITLE
Note with Master password reprompt can be seen without having to insert master password again.

### ISSUE THREAD

**Issue by denispaluca** [bitwarden/clients#6756]
### Steps To Reproduce

1. Create a new secure note.
2. Activate master password reprompt.
3. Save and close the note.
4. Close the extension.
5. Open the extension again and click on the note.

### Expected Result

Similar to the web app of Bitwarden (vault.bitwarden.com), you should be blocked from seeing the note directly.
Instead you should be prompted to insert the password again.

### Actual Result

The secure note and its contents are shown directly.
Only when you try to edit, you are reprompted for the password.

### Operating System

Linux

### Web Browser

Chrome

### Browser Version

119.0.6045.105

### Build Version

2023.9.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
