### ISSUE TITLE
Unable to Login/sync on Brave Browser via Extension

### ISSUE THREAD

**Issue by abuturabofficial** [bitwarden/clients#6762]
### Steps To Reproduce

1. Few days ago it stopped syncing.
2. Logged out and tried to log back in
3. Got error `An error has occurred, failed to fetch`

### Expected Result

Should sync/login normally.

### Actual Result

Got error

```
An error has occurred
Failed to fetch
```

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/68259771/a106e6ed-90c9-4a44-931b-6da4be5d6096)

### Additional Context

I can normally login on `vault.bitwarden.com` via Brave-browser, so apparently it's an extension specific issue. Similar kind of issue was present in the bitwarden extension on Firefox in the previous release which was fixed, but it botched the login on Brave.

### Operating System

Linux

### Operating System Version

Fedora 38

### Web Browser

Brave

### Browser Version

Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @abuturabofficial 

Thank you for bringing this to our attention.

I am unable to reproduce this issue.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form so we can continue troubleshooting. https://bitwarden.com/contact/

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!
