### ISSUE TITLE
Password history shows up as empty

### ISSUE THREAD

**Issue by weissli** [bitwarden/clients#6768]
### Steps To Reproduce

1. Go to a login entry - with a number of recorded password changes
2. Click on view
3. Scroll down to and click on password history

### Expected Result

a listing of my password history for the login

### Actual Result

It show up saying no 'There are no passwords to list.'

### Operating System

macOS

### Installation method

Mac App Store

### Build Version

Version 2023.10.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by podbiker** [comment]
Same Issue here, as of version 23.10.0 only the standard clipboard is used for copy and paste. Clipboard history stays empty.

I understand, that using the clipboard history can pose a security risk for users on a Microsoft account where the clipboard history is synced between devices.
It would still be nice to be able to enable the use of the clipboard history via a toggle within the desktop client. Perhaps make "clear clipboard" mandatory to increase security for users of a Microsoft account. Or limit it to users of a local account with a corresponding tooltip.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
