### ISSUE TITLE
Microsoft Edge: Cannot be auto-filled

### ISSUE THREAD

**Issue by kreake** [bitwarden/clients#6809]
### Steps To Reproduce

1. Go to reolink surveillance camera site
2. Click on Bitwarden "Autofill credentials"

### Expected Result

Credentials are filled in

### Actual Result

Credentials are not filled in

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/13981717/8063b622-659c-4aa3-bc79-1758f880bb42)

### Additional Context

Cannot be reproduced on Firefox. Still works with Version 2023.9.2

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

119.0.2151.44

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chungr** [comment]
+1 I have this same issue with other websites where autofill was previously working in an earlier version of Bitwarden.

Both for automatic autofill of passwords (autofill on page load) and when clicking on a login when clicking on the bitwarden icon and then a matching login for a website, nothing happens and I have to copy the password and paste it in.

Another example where this happens:

1. Go to https://disneyworld.disney.go.com/login?returnUrl=%2Fplan%2F
2. Type in username email.
3. Click continue, when prompted for password, autofill on page load does not work.  Also clicking on bitwarden icon and then clicking a matching login does not result in password being entered.

**Comment by MartinFalatic** [comment]
Wonder if this is related to [#6434](https://github.com/bitwarden/clients/pull/6434)?

**Comment by sammbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by MartyMacGyver** [comment]
You'd think that when the extension worked fine before and then suddenly stops working, you'd want to know about it promptly, not with some vague report that doesn't even ask about the version of the extension you're using. 2023.10.x appears to have regression issues - I hope you're looking into THAT rather than one-offs like this.
