### ISSUE TITLE
Browser extension always is the first passkey device to try, prevent me use my physical device to auth directly

### ISSUE THREAD

**Issue by CoelacanthusHex** [bitwarden/clients#6824]
### Steps To Reproduce

1. Go to any site support passkey, and plug in a registered fido device (such as a Yubikey)
2. Try any function needs passkey authentication

### Expected Result

I can just use my physical device to authenticate, with no extra steps.

Please provide an option to 
1. disable the passkey function completely
2. or let it work only when no physical device is plugged in
3. or let it work only when there is a passkey for this site in Bitwarden

### Actual Result

I must wait for a window of Bitwarden to pop, and then click 'Use Browser', and then touch my device to use.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Firefox

### Browser Version

121.0a1 (2023-11-03)

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bradfordzhang** [comment]
Same need

**Comment by nfischer** [comment]
I'm having the same issue in the Bitwarden browser extension (Chrome extension). This bug has broken 2FA for me, but there's a workaround.

I previously registered a yubikey to use as a second factor on a bunch of websites. When I log into the site with username + password, the website asks me to tap my security key as my second factor. At this point, Bitwarden shows a popup which says "no passkeys found for this application." This makes sense because I never registered a passkey for this website. Unfortunately, it seems as though Bitwarden is blocking the website from seeing my yubikey, so this is preventing me from logging in.

I found a workaround. The Bitwarden popup has a button called "use browser." If I click this button, then the Bitwarden popup goes away and I can tap my yubikey as expected. This workaround is not immediately obvious though, so I suspect a lot of yubikey users are unable to get into their websites until they figure this out.

**Comment by nfischer** [comment]
I found https://www.reddit.com/r/Bitwarden/comments/17psqx6/bitwarden_launches_passkey_management/. The comment from reddit user xxkylexx says there's a couple fixes in 2023.10.2 which I think will help this:

> a. Automatically fall back to the native "use browser" option when no passkeys exist in Bitwarden for a given website. The vault must be unlocked for us to know no passkeys exist.
> b. Fall back to the native "use browser" option when closing the Bitwarden passkey window.

I'm still using version 2023.10.1, but when 2023.10.2 is available for me I'll try it out and see if this addresses my concerns.

**Comment by mrsarm** [comment]
I'm getting the same issue, and the @nfischer's workaround allowed me to use my key as well.

If this was intended by design: change how the browser access the FIDO keys, and with a really hard to find button that looks more like a label at the button left of the dialog that appears, you really need to rethink the UI, although I also think that even improving the UI to make the "use browser" (button?... link?) more visible and understandable is still a bad idea, and is not clear (again, because a bad UX) why the plugin tries to ... replace ? my key.

**Comment by Xavron** [comment]
The two above aren't enough for all situations because human randomness is greater. Give full control to decide to each person instead of trying to guess it. Guessing will be wrong x amount of the time.

If not caring about having to users click then its fine as it is with user understanding adjustments to the UI for sure. Most users won't know what "use browser" means here.

**Comment by jonessanderson** [comment]
The "use browser" option still does not work for me. I connect through RDP, and the official Microsoft RDP client passes through FIDO2 without issue. Since the bitwarden update, I am no longer able to authenticate (even when selecting "use browser") -- it no longer populates the Windows Security/Windows Hello prompt that allows me to choose security key, enter my pin, and login.

Edge Web Store still does not offer the .2 update that is supposed to allow exemption for specific sites. Regardless -- even the exemption I don't think is a reasonable solution to this. Some websites auth through an URL that isn't always obvious when using SSO, so it can be difficult figuring out which sites need to be excluded.

Bitwarden please provide us an option to STOP bitwarden from taking control over our authentication process. It has been almost a week now where this is seriously hindering mine and my colleagues work flows.

**Comment by SniperFodder** [comment]
The intercept should be an Opt-In choice, not the default. It took me 5 or so minutes to even find the use browser button when randomly Bitwarden started intercepting my hardware key when trying to auth with my Azure/Entra ID. I don't use Bitwarden to store those secrets, and I probably never will since that defeats the purpose of the hardware key in the first place.

I use multiple browsers to help segregate some of the accounts I use, and as a work around I use the hardware keys to login to some of those accounts, so I don't have to login to Bitwarden multiple times, once for each browser.

**Comment by litori** [comment]
Using bitwarden extension on firefox windows.  Signing in on apple.com using passkey fails now because bitwarden is intercepting the request.  It doesn't even show use browser anymore.  Had to disable the extension entirely to bypass.  Please give the users the ability to bypass.

**Comment by nfischer** [comment]
I just tried extension version 2023.10.2 and it seems to fix my use case. I tried logging into a couple different websites with my yubikey as 2FA and there were no issues. Thank you for a quick fix!

**Comment by TroyBW** [comment]
Hi there,

This issue should be addressed in the 2023.10.2 release. The new behavior now is to automatically fall back to using the browser if no passkeys are found in Bitwarden vault.

This issue will now be closed. 

Thanks!

**Comment by ChestersGarage** [comment]
UGH.  This issue drives me nuts!!!  I don't use Bitwarden for passkey actions and I need it to GO AWAY!!

**Comment by Tipoff4317** [comment]
@ChestersGarage 

Another user here.  Settings > Notifications > Ask to save and use passkeys (uncheck).  If this doesn't work, it would be a new bug.
