### ISSUE TITLE
macOS version shows blank screen when launched

### ISSUE THREAD

**Issue by NachmanRoss** [bitwarden/clients#6825]
### Steps To Reproduce

4. Click on 'Bitwarden icon'

### Expected Result

I expect the app to open and show my saved credentials. The Bitwarden Safari plugin is working fine.

### Actual Result

The app opens but the screen is completely blank except for my name in the top right. Resizing the window doesn't have any effect. 

### Screenshots or Videos

![Bitwarden](https://github.com/bitwarden/clients/assets/44656971/185691ad-4042-4c22-8e8c-effdda433f5f)

### Additional Context

I'm running macOS Sonoma 14.1 on an Intel MacBook Pro 2019

### Operating System

macOS

### Operating System Version

14.1 Sonoma

### Installation method

Mac App Store

### Build Version

Version 2023.10.0 (13355)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try uninstalling and reinstalling your app to see if this issue resolves.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Amndeep7** [comment]
Believe this is a dupe of https://github.com/bitwarden/clients/issues/6691
