### ISSUE TITLE
New version of Chrome plugin makes pages laggy

### ISSUE THREAD

**Issue by Ted-Liang** [bitwarden/clients#6829]
### Steps To Reproduce

I updated the latest version yesterday, and when I accessed the local page http://192.168.0.64/ today, the page got very stuck.
Web pages also load slower.
I have tested it many times and it is caused by this extension. After turning on Incognito, only this plug-in was left, and the page was very stuck. After disabling this plug-in, the operation speed of the page returned to normal.
Because there are some privacy issues in the local network, it is not convenient to take screenshots or restore videos. I hope the developer can find the reason elsewhere.
My temporary solution is to temporarily disable this plug-in when not using it.

### Expected Result

Page loading speed is normal

### Actual Result

Browsing the local web http://192.168.0.64/ web page loading slows down

### Operating System

Windows

### Operating System Version

win10

### Web Browser

Chrome

### Browser Version

119.0.6045.124

### Build Version

2023.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
i there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed
