### ISSUE TITLE
keyboard shortcut for auto-fill login (Ctrl + Shift + L) not working on Firefox

### ISSUE THREAD

**Issue by ProgPete** [bitwarden/clients#6831]
### Steps To Reproduce

1. Login to Bitwarden browser extension.
2. Open a webpage to login to.
3. Ctrl + Shift + L should autofill but it doesn't.

### Expected Result

Login fields should be filled after pressing keyboard shortcut.

### Actual Result

Login fields stay empty. Nothing happens.

### Operating System

Linux

### Operating System Version

Mint 21.2 Cinnamon

### Web Browser

Firefox

### Browser Version

119.0

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @ProgPete, 

I attempted to reproduce your issue and was unable to do so.  In particular, on a bare-metal installation of Linux Mint 21, I attempted to use the Ctrl-shift-L shortcut to autofill on various websites.  I did not encounter any difficulties.

I think your error could have its origin in a misconfiguration or conflict with other software on your machine.  You could try to re-add the shortcuts via Firefox's extension settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will remain closed.

Thanks!
