### ISSUE TITLE
Unable to auto-fill

### ISSUE THREAD

**Issue by DjKilla2** [bitwarden/clients#6832]
### Steps To Reproduce

1. Go to 'various web sites'
2. Click on 'login or fill form'

### Expected Result

Logins and forms should be filled in.

### Actual Result

Logins and forms aren't filled in or fields within forms aren't filled in.

### Additional Context

Auto fill issues with version 2023.10.1. I’m using Firefox 119.0.1 and multiple web site forms are either unable to fill the form or some fields in the form are not filled in. Never had any issues filling the form with previous versions. I’m guessing Microsoft Edge has the same issues.

There's lots of posts on the Bitwardin Community Forum about this issue.

https://community.bitwarden.com/t/unable-to-auto-fill-the-selected-item/59916/8

https://community.bitwarden.com/t/autofill-problem-with-schwab-com/59938/2

### Operating System

Windows

### Operating System Version

Windows 10 Home 22H2 64-bit

### Web Browser

Chrome, Microsoft Edge, Firefox, Brave

### Build Version

2023.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@DjKilla2 

Thank you for the bug report, can you please link a couple of these `various sites` that you are referencing?

We have a [known issue](https://github.com/bitwarden/clients/pull/6726) that was introduced by work that optimized the collection of page details which has been fixed for the next release. However, if other issues are present I'd like to know so that we can resolve them ASAP within the current sprint.

**Comment by umut-nb0** [comment]
I'm using Chrome browser and I'm having the same problem. After the 2023.10 update, autofill does not work on many sites. When I open Bitwarden and click on the existing account it shows an error message.

Also, the CTRL+Shift+L shortcut no longer works.

![filen-bug](https://github.com/bitwarden/clients/assets/147916475/5b5c5d70-87d9-4114-9de4-d88a41ca8342)

**Comment by cagonzalezcs** [comment]
@bwbug Thank you for providing those, yeah in each of the cases the bugfix linked above resolves the issue. 

To mitigate the recent concerns that have been appearing, we've flipped off a feature flag that introduced these optimizations until we can resolve the problems encountered and release them. 

To ensure that you are loading the older version of autofill, please re-sync your browser extension and reload the page that you are attempting to autofill on. This should update the feature flag reference in your extension, and trigger loading of the old version of autofill when visiting a web page.

**Comment by cagonzalezcs** [comment]
In this specific instance, yes that's correct. We architected the refactor of `autofill.js` with the intent that if anything went wrong in the v2 version, we could quickly fallback to the v1 version of the feature. Autofill v2 has been active in production for about a month at this point, but this recent release introduced the true first improvements to the feature. 

As we are encountering issues, we are flipping back to the v1 implementation until we can resolve the problem through either a hotfix or standard release. Currently, the only difference between v1 and v2 is the ability to fill ShadowDOM elements (which was introduced with the most recent release). 

So with that said, users will need to sync the extension to immediately update that feature flag.

**Comment by DjKilla2** [comment]
I'm a little late replying but here's some additional info. At the moment, auto-fill is working again in Firefox 119.0.1 with Bitwardin 2023.10.1 probably because the v1 was re-implemented. You wanted some additional links so I'll do my best to post a few that I remember.

https://medicinecabinetamoe.com/
https://www.reddit.com/ (logging in)
https://www.verymerrymartins.com/
https://www.littlepotatoes.com/holiday-happiness/
https://www.ramseysolutions.com/giveaway/ramsey-cash-giveaway
https://www.midwestliving.com/tailgatesweeps

Either the forms did not fill in or some fields weren't filled in or logging in (username/password) did not fill in. There's lots more than this but I would need to test v2 to list more web sites.

**Comment by cagonzalezcs** [comment]
@DjKilla2 

Thank you, that's incredibly helpful. I can confirm that the fix we have in place within the `master` branch allows autofill to occur on all of those URLs. 

I'm closing this thread for now, please let me know if any other unexpected issues present themselves. We can re-open the thread if necessary.

**Comment by htims05** [comment]
I am still having the same non auto-fill issue.  schwab.com as example.  I have 2023.10.1 extension version installed on Librewolf on Debian.  I force synced it then reloaded schwab and received the auto-fill error.  If I downgrade the extension it works....just as it has in the past.

**Comment by cagonzalezcs** [comment]
> I am still having the same non auto-fill issue. schwab.com as example. I have 2023.10.1 extension version installed on Librewolf on Debian. I force synced it then reloaded schwab and received the auto-fill error. If I downgrade the extension it works....just as it has in the past.

Could you try a different browser and see if the problem persists with the `2023.10.x` extension? It's possible that some kind of cache for the value is still present on your browser...

I just tested within Chrome and am able to autofill.

**Comment by htims05** [comment]
> > I am still having the same non auto-fill issue. schwab.com as example. I have 2023.10.1 extension version installed on Librewolf on Debian. I force synced it then reloaded schwab and received the auto-fill error. If I downgrade the extension it works....just as it has in the past.
> 
> Could you try a different browser and see if the problem persists with the `2023.10.x` extension? It's possible that some kind of cache for the value is still present on your browser...
> 
> I just tested within Chrome on `v2023.10.2` and am able to autofill.

 Tried with Firefox as well - it worked once, then when I re synced the extension and the page it gives me the red auto fill error within the extension. Tried on windows 11 with firefox too - same issue.  Deleted all history/cache and it still gave the same error.

**Comment by cagonzalezcs** [comment]
@htims05 So this is going to sound like an odd request... but are you able to autofill `auth.max.com` with some credentials?

If that's the case, then somehow you're still using the autofill v2 script to trigger fill... I'm not sure on how that would be the case, unless somehow the tool we are using for feature flagging takes time to propagate changes... we'd have to investigate if that were the case, but it would also mean that you eventually would receive an update to the flag value (I know that's not a great solution by any means).

**Comment by cagonzalezcs** [comment]
Right, so that shouldn't be possible to do if you were on autofill v1. 

Somehow your client is still receiving the feature flag for v2, and not updating. I'll look into it to see why that might be the case, but downgrading for now will be the alternative fix for now. 

Are you self-hosting your server by chance? Or potentially connecting to the EU cloud server?

**Comment by htims05** [comment]
> Right, so that shouldn't be possible to do if you were on autofill v1.
> 
> Somehow your client is still receiving the feature flag for v2, and not updating. I'll look into it to see why that might be the case, but downgrading for now will be the alternative fix for now.
> 
> Are you self-hosting your server by chance? Or potentially connecting to the EU cloud server?

Self-hosted.

**Comment by cagonzalezcs** [comment]
I see, yeah that would make sense.

I spoke with one of our other devs who is more familiar with self hosted instances and he gave the following feedback:

> You should be able to create a file, like this:

`./bwdata/core/launch-darkly/flags.json`
```
{
  "flagValues": {
    "autofill-v2": false
  }
}
```

> Then run `./bitwarden.sh rebuild && ./bitwarden.sh restart`

This should set the feature flag within your extension from a self-hosted instance.

**Comment by htims05** [comment]
Is this going to be fixed in a future release for self hosted clients - instead of this one-off modification, it seems I'd be better served to just downgrade the extension and wait for an official fix - if there is one?

**Comment by cagonzalezcs** [comment]
> Is this going to be fixed in a future release for self hosted clients - instead of this one-off modification, it seems I'd be better served to just downgrade the extension and wait for an official fix - if there is one?

There is a fix for this problem already merged within `master`. I'm unsure if we are going to hotfix the extension for this however, but I'll confirm with my manager. 

As for the EU flag, I'm checking with the team to see if there is a difference between the US and EU servers for this. From my knowledge, there shouldn't be any differences between the two... but I'll report back once I find out more.

**Comment by Gerardv514** [comment]
What is the difference in autofill v2?

**Comment by cagonzalezcs** [comment]
Just posting to confirm that we use a singular feature flag on both the US and EU servers. Users who are using cloud hosting with Bitwarden should be loading v1 completely.

**Comment by cagonzalezcs** [comment]
@bwbug Yes, any website that uses custom web components (which leverage the ShadowDOM) can be tested. 

Another good example is - https://www.royalcaribbean.com/account/signin

**Comment by jancona** [comment]
I know this issue is old, but I'm experiencing this issue on many sites, starting in the last week or so. For example, I was unable to autofill my Github login in order to comment on this issue. I'm especially seeing it almost every time I try to use a Bitwarden identity to autofill  a form. Let me know if I you'd rather I open a new issue.

Bitwarden Version: 2023.12.1 Server Version 2023.12.1
OS version: MacOS Monterey 12.7.2
Browser: Brave using the official extension installed from the Chrome Web Store
Browser version: 1.61.109 Chromium: 120.0.6099.144 (Official Build) (x86_64)

**Comment by cagonzalezcs** [comment]
@jancona 

So the issue you're referring to should be resolved in the upcoming release of the Bitwarden extension. I tested autofill with the recently cut release branch, and filling on the link you provided works. The problem does exist for the current extension however, and the fix for that can be seen here - https://github.com/bitwarden/clients/pull/7209

**Comment by felix2380** [comment]
Auto -fill does not work in pCloud and must be copied manually.Firefox extension version 2023.12.1.I should mention that I have tried all the auto-fill methods in my pCloud account and it doesn't work.In my Twitter account the auto-fill method [Show auto-fill menu on form fields--When field is selected(on focus)  ] it works only partially, username enters but not password,the auto-fill method with Ctrl+Shift+L as well as the other methods work.In my Microsoft outlook account the auto-fill method that is mentioned in the Twitter account doesn't work at all [Show auto-fill menu on form  fields--When field is selected(on focus) ] ,Ctrl+Shift+L method and the other methods work too.Thank you very much!

**Comment by vixrodriguez** [comment]
I installed the Bitwarden Chrome Extension on the Brave Browser, and I found some sites where autofill is not working.
Below is a list.
1. https://www.bancasinhorarios.com.ec/BOLI-ebanking/seguridad/login.htm
2. https://bancaweb.pichincha.com/pichincha/login
3. [LifeMiles](https://sso.lifemiles.com/auth/realms/lifemiles/protocol/openid-connect/auth?client_id=lifemiles&response_type=code&scope=openid&login_hint=wst&ui_locales=en&redirect_uri=https://www.lifemiles.com/oauth-signin/&state=1708098436361&micrositeParams=%7B%27Access-Level%27%3A%20%270%27%2C%20%27Redirect-Uri%27%3A%20%27%27%7D) First, click on "Continue with LifeMiles number or username" to visit login website. When the first time page is loaded, the field LifeMiles number or username is empty, but you can choose the username from extension.

If I find other sites, I will create a new comment

**Comment by marksherman** [comment]
Reporting more `various sites`:

Microsoft ADFS (which for my world appears on a domain-specific login page. This one's a big deal. (if you want to see it, open http://eclearn.emmanuel.edu and it will redirect you to the login page that no longer autofills)

On all sites where i've experienced the problem, BitWarden did successfully match the site to the right identity, it just refuses to fill.

**Comment by burningwidget** [comment]
I have been getting this issue since Nov 2023, and continue to think an update would fix.
To articulate what happens its exactly as above:
Login to Bitwarden Browser Extension (Auth into it)
Auto-fill does not work via the drop down or right click autofill. 
Fill from the drop down gives the standard error "Unable to auto-fill the selected item on this page. copy and paste the information instead."
If I wait a period of time, sometimes 1min, some times 5, then it just magically starts working.
-----
From what I have experienced, something has to do with timing with the extension. As it will work after "some time".
This is the case on EVERY website that fill is tried. Every site tried works after it "magically" starts working in a few minutes.

-----
I read about autofill v1 to v2 and all that...I have just not researched it as its not a bother if the browser is open all day and I am auth'd into bitwarden. If I boot up, then auth to bitwarden in the extension, then try, it ALWAYS FAILS for a period of time.

Hope that helps.

**Comment by Gerardv514** [comment]
> ## I have been getting this issue since Nov 2023, and continue to think an update would fix.
> To articulate what happens its exactly as above:
> Login to Bitwarden Browser Extension (Auth into it)
> Auto-fill does not work via the drop down or right click autofill.
> Fill from the drop down gives the standard error "Unable to auto-fill the selected item on this page. copy and paste the information instead."
> If I wait a period of time, sometimes 1min, some times 5, then it just magically starts working.
> From what I have experienced, something has to do with timing with the extension. As it will work after "some time". This is the case on EVERY website that fill is tried. Every site tried works after it "magically" starts working in a few minutes.
> 
> I read about autofill v1 to v2 and all that...I have just not researched it as its not a bother if the browser is open all day and I am auth'd into bitwarden. If I boot up, then auth to bitwarden in the extension, then try, it ALWAYS FAILS for a period of time.
> 
> Hope that helps.

This issue has been closed for more than a year and a half now. I would suggest opening a new issue, with as much details/logs as possible, and there you could link to this issue if you needed.

**Comment by burningwidget** [comment]
Open another issue for the exact same thing. Makes sense, or is it to eliminate tracking that it was never really fixed?
Just to point out some metrics, 22 posts to this thread AFTER closed.
 
Also to point out the person that closed it.

Yeah, issue still continues, on not a few selected URL's but on EVERY URL.

Whatever, this is your world, we are just trying to bitwarden in it.



> [@DjKilla2](https://github.com/DjKilla2)
> 
> Thank you, that's incredibly helpful. I can confirm that the fix we have in place within the `master` branch allows autofill to occur on all of those URLs.
> 
> I'm closing this thread for now, please let me know if any other unexpected issues present themselves. We can re-open the thread if necessary.

**Comment by Gerardv514** [comment]
I mean this issue also points to a build from 2023, does that mean your on that?

That's what I mean..provide fresh new insight of what's going on in your specific environment. Could be the same thing on the front end, but it's different on the back end. Also it can't be that wide spread of an issue since we would hear of more users reporting. 

So it could be something with your specific setup. Also most people aren't looking at closed issues, especially Bitwarden themselves, they would be looking at open items.

Sure one could reopen this but again I doubt you would have permissions to it because you're not the issue owner. But do what you think, I've tested and don't have this issue so must not be an issue in code.

**Comment by burningwidget** [comment]
No, I am on current version and this is still happening.
I won't waste time here. You seem to be more interested in getting internet updoots by placing useless comments than much anything else, as you have added nothing to the actual comment outside of "muh start a new thread"

So this is a waste of time, for a product that I actually pay for.
Thus, it makes me seek alternatives like going back to Last Pass since its not cucked by GoTo anymore.
Enjoy your internet points. Good luck in your layoffs, welcome to costco, I love you.

**Comment by cagonzalezcs** [comment]
@jprusik @MGibson1 

Just bumpin' y'all.

**Comment by Gerardv514** [comment]
@jprusik @MGibson1 @cagonzalezcs 

Any insight, or direction you can provide?

@burningwidget just to be clear I am only a self hosted Bitwarden user. Not sure how layoffs, at my primary job, which is public service btw, has anything to do with the private company of Bitwarden.

**Comment by jprusik** [comment]
Hi all! I wanted to leave a note here that autofill is a broad category of functionality (inline menu, hotkeys, extension fill) across multiple Bitwarden clients. Because of this, a given fix may solve issues with some websites/cases and not others. To help us better understand and triage issues, please create individual issues for specific cases.

That said, the @bitwarden/team-autofill-dev team completed significant work on identified autofill issues recently. I've spot-checked a handful of the sites mentioned here and elsewhere and found autofill to work as expected (with the latest `clients` build of `main` on Chrome):

```
https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx
https://account.mayoclinic.org/ (access via https://onlineservices.mayoclinic.org/content/staticpatient/showpage/patientonline)
https://accounts.firefox.com/
MailJet
https://www.royalcaribbean.com/account/signin
https://www.schwab.com/
https://www.bancasinhorarios.com.ec/BOLI-ebanking/seguridad/login.htm
https://bancaweb.pichincha.com/pichincha/login
LifeMiles First
```

Do note, this issue thread is closed, so posting here (as opposed to an open or new issue) will have poor visibility to our teams who can resolve issues.
