### ISSUE TITLE
Constant High cpu load >120% by bitwarden app even in the background [macOS]

### ISSUE THREAD

**Issue by Licenser** [bitwarden/clients#6858]
### Steps To Reproduce

1. Start the app
2. log in
3. Watch it eat all your CPU

### Expected Result

When not in use I expect the app to use no or virtually no resources

### Actual Result

The app uses over a full CPU core, constantly, draining the battery and costing moeny

### Screenshots or Videos

<img width="271" alt="image" src="https://github.com/bitwarden/clients/assets/119093/96d124a1-abe2-4395-acee-835ce2b5d0c7">

### Operating System

macOS

### Operating System Version

12.7.1

### Installation method

Mac App Store

### Build Version

Version 2023.9.3 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @Licenser ,

I attempted to reproduce your issue and was unable to do so. In particular, I installed Bitwarden + several browser extensions + the CLI tool on macOS Monterray on an Intel macbook pro, and noted that the CPU usage was not similar to your own.

I think your error could have its origin in a corruption of your installation and would encourage:

- reinstallation via appcleaner (https://freemacsoft.net/appcleaner/)
- updating to the latest version

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
