### ISSUE TITLE
Search is broken..

### ISSUE THREAD

**Issue by Snacko** [bitwarden/clients#6862]
### Steps To Reproduce

1. Go to app on desktop pc.
2. Login and do a search for T-mobile

### Expected Result

Only matches to the search are displayed.

### Actual Result

results from search, AND everything else in the database is displayed.

### Additional Context

It used to only display what matched my search.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there, bwbug is correct, the Lunr search is causing the behavior you are seeing. If you want to search solely for T-Mobile, you can search the following: >+name:T-Mobile
More information on this topic can be found here: https://bitwarden.com/help/searching-vault/#wildcards-and-advanced-search-parameters

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
