### ISSUE TITLE
Amazon.it: passkey issues during autofill

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/clients#6867]
### Steps To Reproduce

1. Go to 'https://www.amazon.it/'
2. Click on 'Accedi'
3. Type the key combination `CMD + SHIFT + L`
4. Click on 'Continua'

### Expected Result

I would expect it to ask for the passkey and then log in, without asking to enter any other data (TOTP included).

### Actual Result

In my case, the TOTP is required to log in. Otherwise, you can access directly.

### Screenshots or Videos

I cannot add screenshots, videos or anything else due to the presence of sensitive data.

### Operating System

macOS

### Operating System Version

Sonoma 14.1.1

### Web Browser

Chrome

### Build Version

119.0.6045.123 (Official Build) (arm64)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @fabriziobagala,

Thank you for your report. Could you please get [in touch](https://bitwarden.com/help/) with us and detail how you enrolled a passkey from Amazon into your Bitwarden browser extension and what 2FA settings you have set up in your Amazon account so we'd examine this? I ask because I am unable to reproduce this behaviour. Please remember to include a link to this GitHub report in the body of your ticket.

We use GitHub issues as a place to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
