### ISSUE TITLE
Unlock with pin doesn't persist after version 2023.8.4 and earlier

### ISSUE THREAD

**Issue by bugz8unny69** [bitwarden/clients#6875]
### Steps To Reproduce

1. Go to Settings
2. Set Vault timeout greater than 'On browser restart'
3. Click on 'Unlock with pin' and set PIN.
4. Navigate away from the tab
5. Return back to the tab

### Expected Result

'Unlock with pin' to persist and function when the vault time's out.

### Actual Result

The checkmark is cleared (setting reset)

### Additional Context

This issue began recently with Firefox browsers on Linux and Windows. Downgrading as old as 2023.8.3 fixed the issue for me.

### Operating System

Windows, Linux

### Operating System Version

Zorin OS 16.3 and Windows 11 23H2

### Web Browser

Firefox

### Browser Version

119

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @bugz8unny69 ,

I attempted to reproduce your issue and was unable to do so.  In particular I:

- using Ubuntu and macOS with Bitwarden 2023.10.2
- set PIN timeouts to both 'immediately' and 'never' 
- and tried to reproduce your steps

I was not able to do so - the PIN was always requested, and remained configured after repeated locking/unlocking cycles.

I think your error could will likely be solved by a re-installation of the extension.  In particular, we fixed an issue with similar symptoms to this in 2023.9.1

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
