### ISSUE TITLE
Endless loading spinner

### ISSUE THREAD

**Issue by iliveinveselka** [bitwarden/clients#6878]
### Steps To Reproduce

1. Open desktop application
2. See endless loading

### Expected Result

Usual application working

### Actual Result

Endless loading spinner

### Screenshots or Videos

![Знімок екрана 2023-11-13 204329](https://github.com/bitwarden/clients/assets/150724350/17c8a61d-bc81-4f00-bb2d-cc9baf41726d)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Microsoft Store

### Build Version

Версія 2023.10.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by utansocker** [comment]
Same issue for me on Ventura 13.6.1 and Safari 17.1 (18616.2.9.11.10, 18616) using Bitwarden 2023.10.1 (13648).

**Comment by erwan-gueno** [comment]
I have the same problem on the Firefox 119.0.1 addon on Windows 11. I saw, in debug mode, that there is an undefined variable in the "isMobile" function of the utils.ts file (a substr(0 , 4)). Hope this can help.

**Comment by Namistai25** [comment]
Same issue. 
After entering the Master Password, the desktop application starts to load endlessly.

**Operating System:** Windows 10 v22H2 (compilation 19045.3693)

**BitWarden:**
v2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

https://vault.bitwarden.com/ and Android app are working fine.

**Comment by acirasa** [comment]
The error on console is:
`ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'profile')
TypeError: Cannot read properties of undefined (reading 'profile')
    at useClass.<anonymous> (state.service.ts:2030:13)
    at Generator.next (<anonymous>)
    at r (main.js:1:265825)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:1279516)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)`

The failed request is; **https://identity.bitwarden.com/connect/token**
The json error response is: `{"error":"invalid_grant"}`

Hope it help.
Best Regards

**Comment by roquestrongo** [comment]
Same issue here, the problem persists since around a month and was happening with the previous BW Windows App Version already. 

Web an Android App works fine for me. 

v2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64
Microsoft Windows [Version 10.0.19045.3448]

Regards

Roque

**Comment by trmartin4** [comment]
Hello.  The Engineering team is researching this issue an would like to get some help pinpointing the root cause.

@iliveinveselka and @roquestrongo, can you also examine the DevTools for your desktop instance (View | Toggle developer tools) and see if you see the `{"error":"invalid_grant"}` and a failed request to the `token` endpoint that was reported above?

Thank you for your help.

**Comment by STaRDoGG** [comment]
I'm seeing this now in the latest Windows client and a self-hosted VaultWarden:

![image](https://github.com/bitwarden/clients/assets/1524526/80fccc00-5f7a-4dab-8836-2fd7b31a20af)

It happened after I added a second account to the Win Client. It worked fine at first switching back and forth a couple times between accounts, but then it just freaked out when trying to switch. The list of logins only showed the generic favicon for them all, and nothing at all for any text for them; just a list of generic favicons. And trying to keep switching back and forth with the switcher at the top-right just kept the 1st account selected and the list looking the same as I just described.

After quitting and re-starting the client a few times (including confirming no BW processes are still running) after that I'm now just stuck with an endless spinner (which also means I can't use the Windows Hello connection to login to my browser extensions).

The console shows this:

![image](https://github.com/bitwarden/clients/assets/1524526/007d1670-a0a0-4cc5-9f9a-c81f1d0a74c3)

I haven't tried rebooting yet because I have a lot of apps open right now with dev stuff open in them that I don't want to close.

**Comment by serban-dobroiu** [comment]
@trmartin4 
Hi, seeing the same behaviour on Kubuntu 22.04 - endlessly spinning spinner and failed requests to the token endpoint (https://identity.bitwarden.com/connect/token).

**Comment by nmrad-91** [comment]
Feedback on @STaRDoGG remediation. This worked on Mac..
`rm ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/data.json`

**Comment by JGSV** [comment]
> Feedback on @STaRDoGG remediation. This worked on Mac.. `rm ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/data.json`

This also worked on Windows 10! Thanks!
Deleted '...\AppData\Roaming\Bitwarden\data.json' and the issue seems to be resolved.
