### ISSUE TITLE
Items with passkeys attached still appear in Inactive two-step login report

### ISSUE THREAD

**Issue by wnelson03** [bitwarden/clients#6880]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/reports/inactive-two-factor-report
2. You will see items that have a passkey attached in this list. It seems these items shouldn't be shown in that list.

### Expected Result

The client should exclude items with a passkey from Inactive two-step login report. 2FA isn't necessary in these cases. It wouldn't add greater security being stored in the same Bitwarden item.

### Actual Result

Items with a passkey are shown in the list of Inactive two-step login items.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/83034852/290ef0d1-6541-41bf-bc7b-23cc89d71f1a)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Build Version

2023.10.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
