### ISSUE TITLE
BitWarden Extension Triggers Google Meet Extension Alert

### ISSUE THREAD

**Issue by sdaitzman** [bitwarden/clients#6895]
### Steps To Reproduce

1. Go to 'https://meet.google.com'
2. Start a meeting

### Expected Result

I join the Google Meet call and it behaves normally

### Actual Result

A banner displays across the top that reads "You have extensions installed that may affect the quality of your call."

When I disable the Bitwarden Chrome extension, the banner does not appear. When I re-enable it, it re-appears consistently.

### Screenshots or Videos

<img width="887" alt="Screenshot 2023-11-16 at 10 23 53 AM" src="https://github.com/bitwarden/clients/assets/1499476/009753e9-f877-47c5-8f48-8551bd724805">

### Operating System

macOS

### Operating System Version

14.1 (23B74)

### Web Browser

Chrome

### Browser Version

Version 119.0.6045.123 (Official Build) (x86_64)

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try uninstalling and re-installing your Bitwarden extension and/or disabling other extensions in your browser. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by dwestness** [comment]
I run the self-hosted vaultwarden instance
After updating from 1.29.0 to 1.30.1 last night we started to experience the same thing with all installed browser extensions with google meet as well for what it's worth.
