### ISSUE TITLE
Reconsider `$HOME/tmp` directory for macOS desktop client

### ISSUE THREAD

**Issue by crncnnr** [bitwarden/clients#6896]
### Steps To Reproduce

1. Open `Bitwarden.app`
2. `$HOME/tmp` directory is created

### Expected Result

This directory should be created elsewhere, out of sight of the user.

### Actual Result

`$HOME/tmp` is created, which is confusing/vague/not clear that Bitwarden is the source of this directory, it's out of place, and clutters up `$HOME`.

```
$ ls -1
Applications
Desktop
Developer
Documents
Downloads
Library
Movies
Music
Pictures
Public
tmp
```

### Additional Context

This directory has been driving me crazy, it took months to isolate Bitwarden as the culprit. It eventually got to the point that I was paranoid that malware could be the source, so I reinstalled macOS from scratch. Bitwarden was one of the first apps I reinstalled, and that's when I finally figured it out.

It's somewhat ironic that Bitwarden/a password manager was the source of my paranoia!

As far as I understand it, this folder is used for IPC; however, it really should be created elsewhere, e.g. Bitwarden already creates `~/Library/Application Support/Bitwarden`.

Related #5652 

### Operating System

macOS

### Installation method

Homebrew

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @crncnnr , 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by crncnnr** [comment]
I don't believe this issue should be closed, it is not a feature request.


Similarly #5652 should not have been closed either, at least one other person has suggested reopening it.
