### ISSUE TITLE
Not possible(?) to run bw.exe in parallel

### ISSUE THREAD

**Issue by meichthys** [bitwarden/clients#6898]
### Steps To Reproduce

1. On Windows, open two powershell terminals
2. Run `./bw login` on both
3. Run `./bw unlock` on terminal a
4. Run `./bw get` to test  (works)
5. Run `./bw unlock` on terminal b <-This Invalidates terminal a session
6. Try running `./bw get` on terminal a

### Expected Result

There should be a way to run paralell instances of the bitwarden client on the same machine.
For automation purposes, we have python programs that call bw.exe, but if two programs call bw.exe near the same time, the second program to call it will invalidate the session key that first program had - thus causing the first program's authentication calls to fail unless the first program unlocks the vault again. 

### Actual Result

Terminal a session key is invalidated and must be unlocked again.

### Additional Context

Is there a better way to keep session keys active after another CLI session key is created, or is there a way to use an existing session key to unlock the vault?

### Operating System

Windows

### Operating System Version

11

### Shell

PowerShell

### Build Version

2023.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in not recycling the existing session key for the second terminal session.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
