### ISSUE TITLE
Traffic from your network looks unusual. Connect to a different network or try again. [Error Code 2

### ISSUE THREAD

**Issue by esaporski** [bitwarden/clients#6909]
### Steps To Reproduce

1. Run `bw login user@email.com`

### Expected Result

Login to Bitwarden with the CLI client.

### Actual Result

Traffic from your network looks unusual. Connect to a different network or try again. [Error Code 2

### Additional Context

I don't know how many times we will need to create those tickets before the Bitwarden team fixes this **BUG**.
This is a known bug that was already posted here and on [community.bitwarden.com](https://community.bitwarden.com/search?expanded=true&q=traffic%20from%20your%20network%20looks%20unusual) many times.

I already opened a ticket and they keep asking for my public IP address, but my ISP gives me a dynamic public IP, so this is **NOT A SOLUTION**.

### Operating System

Linux

### Operating System Version

Linux popos-pangolin 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 x86_64 x86_64 GNU/Linux

### Shell

Zsh

### Build Version

2023.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

This is an error, and not a bug with the software - please get in touch with support using the links below to try and troubleshoot this further.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by esaporski** [comment]
I did! But everytime they ask for my public IP address, so I'm allowed to login again. The problem is that I have to do this every single time this happens.
Clearly not a solution. I would like to have a disable toggle on my account. This is a bug.

**Comment by esaporski** [comment]
Nobody has any idea why this happens. An option to disable it would be nice.

**Comment by rmarliere** [comment]
I'm also having the same issue on macOS Sonoma 14.1.1 and CLI version 2023.10.0. I already restarted the router and got a new IP and still not working. Then I tried NordVPN using a USA server and it worked.

**Comment by esaporski** [comment]
Even with Mullvad VPN I couldn't make it work @rmarliere

**Comment by rmarliere** [comment]
I contacted Bitwarden support and they fixed it for me. Now it's working.

**Comment by arthurcgc** [comment]
I'm also having this problem, already reset the router, checked every config to see if BW would suspect anything but everything seems normal on the router side... 
It's odd because the 'Traffic from your network looks unusual. Connect to a different network or try again. [Error Code 2' returns almost instantly when trying to login, which to me seems more like a bug and not some security check result

**Comment by welrbraga** [comment]
It has affected me too. I've never had this problem till two or three weeks ago.

Suddenly I can't connect with bw cli on my vault either on my work or my home network.

The worst thing about it is that I were migrating many scripts I use everyday to get passwords on my bw account, instead of maintain them in ordinary files.

But after that event, I me getting a step back and even been a paid user, I will use a Keepass alternative till it become surpassed.

**Comment by arthurcgc** [comment]
@sammbw could you reopen this issue? it seems to be related exclusively to bw command line client... Also, I've noticed that all of us having this problem currently reside in Brazil so it can be an issue with bw client -> our ISP (probably CLARO).

**Comment by sammbw** [comment]
@arthurcgc This isn't a bug, it's an error, and needs to be addressed as such - there is no code based fix for this issue, so a GitHub issue is not the correct way to address this. This issue needs to be dealt with on a case-by-case basis, and users will need to contact us to have this remedied.

You can read more about the error here: https://bitwarden.com/help/unusual-traffic-error/

You can use this form to contact us: https://bitwarden.com/help/

**Comment by arthurcgc** [comment]
Error says: "traffic from your network looks unusual"
If the traffic from my network is clearly not unusual then the error message is **false**, thus, generating an **unusual behavior** which is called a **Bug**

**Comment by ralforle** [comment]
i’ve now also been hit by this error and it seems to be very strange to me.

I use the same wifi for my desktop, my mobile and my tablet. So all these devices use the same network with the same IP-address to the outside.
From my mobile and my tablet as well as from the firefox-plugin for bitwarden I can connect to my Bitwarden Vault without any issues.

But when I try to use the desktop application, then I get this error about the unusual traffic. But the issue cannot be, that my IP is blocked for unusual traffic as all the other devices/application can connect using this IP.
So what is going on here?
This seems to be definitely a bug in the software.

**Comment by 13k** [comment]
Can the engineering team please look at this issue more closely?

There are several inconsistencies in behavior that suggests this is a bug ().

In my case, I can use all clients (web and desktop on Linux, macOS and Windows) except the CLI.

How is this a networking/IP issue, or a simple error, when two clients on the same machine behave differently?

It's either client code sending bogus data to the servers, or server code mishandling correct client data.

And yes, I've already been through support tickets that didn't solve the issue.
