### ISSUE TITLE
Firefox Add-on - "Unlock with PIN" is not saved when enabling and then exiting window

### ISSUE THREAD

**Issue by stefano-u** [bitwarden/clients#6912]
### Steps To Reproduce

1. Open the Bitwarden add-on (on Firefox)
2. Go to Settings
3. Enable "Unlock with PIN"
4. Enter a PIN
5. Close Bitwarden add-on window by clicking anywhere else on your screen
6. Re-open the Bitwarden add-on
7. Go to Settings again
8. Notice how "Unlock with PIN" is not enabled

❗ See temporary workaround to this issue here: https://github.com/bitwarden/clients/issues/6912#issuecomment-1818005026 ❗

### Expected Result

"Unlock with PIN" should remain checked

### Actual Result

"Unlock with PIN" does not remain checked when re-opening Bitwarden window

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/18121592/49164056-b995-48e0-b801-87f279944833

### Additional Context

1. Tested on Firefox Beta v120.0 (32bit) 
    - ![image](https://github.com/bitwarden/clients/assets/18121592/f71a6d56-6cba-4b3d-aaef-56d8819eedef)
2. All browser data was cleared by going to:
    1. Firefox Settings
    2. Cookies and Site Data
    3. Clear Data...
    4. Select "Cookies and Site Data" and "Cached Web Content"
3. Bitwarden add-on data was cleared in Firefox by:
   1. Type `about:debugging` in URL
   2. Click "This Firefox"
   3. Find "Bitwarden" in the list of add-ons
   4. Select "Inspect" button
   5. Go to "Storage" tab
   6. Right-click all items in the left-panel and select "Delete All"
           - ![image](https://github.com/bitwarden/clients/assets/18121592/6968df83-f504-4b4e-953e-bba10ea07e93)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

120.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by stefano-u** [comment]
I found a temporary work-around to this.

1. Go to Settings
2. Enable "Unlock with PIN"
3. Modify the "Vault timeout" to "1 minute"

https://github.com/bitwarden/clients/assets/18121592/b5601994-ec2f-435e-82e1-8f85797a705f

**Comment by NovaSilentium** [comment]
Hi there!

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfugration due to the web vault and browser extension depending on your web browser, there are unique "timeout" scenarios to consider which may explain the behavior you are experiencing. Please review these scenarios outlined here: 
https://bitwarden.com/help/vault-timeout/#web-and-browser-extension-timeouts

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
