### ISSUE TITLE
Extension breaks namecheap.com passkeys

### ISSUE THREAD

**Issue by Arsalan-Zahid** [bitwarden/clients#6977]
### Steps To Reproduce

*Specifically on namecheap.com when setting up security keys, not sure if it does this on other websites*

1. Go to Profile->security (when logged in) 
2. Click on "Manage" under the Two factor authentication section
3. Click on Device Authentication (U2F)
4. Type in the password, copy the codes, click next
5. Enter a name for the key, i.e. "Bitwarden"
6. It displays "Something went wrong while registering your device. Please try again."
(If you disable the extension, it should work)

### Expected Result

I expected it to properly save the passkey to my vault, since yubikeys and passkeys both use the same underlying technology, and it works when I disable the extension.

### Actual Result

It didn't work at all and errored as in the screenshot.  However, when I disabled my bitwarden extension and tried to do it again, it offered to save the passkey on my device as usual.

### Screenshots or Videos

<img width="880" alt="image" src="https://github.com/bitwarden/clients/assets/50848963/964299ed-b44c-4dec-ad65-ed8b94eab045">

### Additional Context

Let me know if you need any more information.

### Operating System

Windows

### Operating System Version

Windows 11 Home 22H2

### Web Browser

Microsoft Edge

### Browser Version

Version 119.0.2151.72 (Official build) (64-bit)

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue today and was unable to do so in both Edge + Windows, and Firefox + Ubuntu. I think your error could have its origin in a passkey that may already saved for that credential. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
