### ISSUE TITLE
会影响浏览器的cloudflare人机验证

### ISSUE THREAD

**Issue by hack11112** [bitwarden/clients#6994]
### Steps To Reproduce

1.打开浏览器
2.登录一个使用cloudflare进行人机验证机制的网站

### Expected Result

能通过人机验证

### Actual Result

无法通过

### Operating System

Windows

### Operating System Version

w11

### Web Browser

Chrome

### Build Version

new

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misused Captcha.
The captcha is something we use to help protect accounts from malicious login attempts. The captcha attempts to target suspicious browsing behaviour.

Typically, this can be triggered by VPNs (or IP addresses associated with large amounts of traffic), proxies, or extensions that block JavaScript (ad blockers, cookie cleaners, etc). Unfortunately, the detection can't be perfect, so you may sometimes encounter a captcha when attempting to log in to your vault. If you are using any of these tools, could you please disable it and try to log in again?

Remember, after you complete the captcha you should click on the Verify/Check button, wait until the captcha gets verified and after that, you must click on the Login button:

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
