### ISSUE TITLE
Copy from password field per select and strg+c not working

### ISSUE THREAD

**Issue by 0verEngineer** [bitwarden/clients#7023]
### Steps To Reproduce

1. click on show password
2. highlight the password
3. copy
4. noting in the system clipboard

### Expected Result

Password should be copied to the system clipboard

### Actual Result

Password not copied into the system clipboard

### Additional Context

Flatpak version 2023.10.1

### Operating System

Linux

### Operating System Version

Kubuntu 23.10

### Installation method

Other

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I see that you're using the Flatpak version. The Flatpak versions are not officially managed by Bitwarden. I recommend installing Bitwarden from our official Bitwarden page: https://bitwarden.com/download/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by 0verEngineer** [comment]
Ah ok, i would suggest your company should really look into flatpak, it works everywhere distributions and will become the standard way of app distribution on linux in the future.
