### ISSUE TITLE
Moving item from trash to another folder results in apparent deletion of all other items

### ISSUE THREAD

**Issue by mikehd1959** [bitwarden/clients#7046]
### Steps To Reproduce

1. Go to Trash
2. Select item in Trash
3. Drag item from Trash to any folder

### Expected Result

4. Look for other items in any folder
5. Folders are empty

### Actual Result

6. Items are visible in Chrome browser extension and on bitwarden web.
7. Exit desktop app and re-launch, items are back in desktop app.

### Operating System

Windows

### Operating System Version

10 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.10.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so since it is not possible to drag items to different locations in the Bitwarden Windows desktop app.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located at our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
