### ISSUE TITLE
Web UI doesn't show item count in filters

### ISSUE THREAD

**Issue by kubedzero** [bitwarden/clients#7065]
### Steps To Reproduce

- Log in to Bitwarden on a desktop web browser such as Chrome and look at the UI

### Expected Result

Each filter on the left side should show the count of items within. The Android app does this.

### Actual Result

Each filter does not show its item count

### Screenshots or Videos

Web UI
![Screenshot 2023-12-01 at 10 19 12](https://github.com/bitwarden/clients/assets/51148401/cfc3c371-95f1-4884-8b1f-84d3e41fb3d0)

Android App:
![image](https://github.com/bitwarden/clients/assets/51148401/dbe41a3d-3883-4f26-803f-6a2671189d96)

Chrome Plugin:
![image](https://github.com/bitwarden/clients/assets/51148401/f2bd7904-dd15-407e-b803-d9086d003028)

### Additional Context

I am able to see counts next to each filter in Android and the Chrome plugin, so I assume it's a bug that there is not feature parity with the WebUI

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by cbbit** [comment]
@kubedzero Item counts are not available in the 'Filter' view of the web vault at this time. As a result, this is the intended behavior of the software.
