### ISSUE TITLE
Passkey Registration Not Working in Firefox and Sway

### ISSUE THREAD

**Issue by newasan** [bitwarden/clients#7079]
### Steps To Reproduce

1. Go to: https://www.passkeys.io
2. Sign up: With an email
3. Click on: Create a passkey

### Expected Result

Bitwarden prompt to store the passkey: https://bitwarden.com/help/storing-passkeys

### Actual Result

No passkey pop-up, but a new window is opened with a looking glass on a black background

### Screenshots or Videos

![out](https://github.com/bitwarden/clients/assets/4480551/f9b2e3b1-7e63-4ef6-96c3-207a75916b6b)

### Additional Context

This also happens on: https://demo.yubico.com/playground

### Operating System

Linux

### Operating System Version

6.6.3-arch1-1

### Web Browser

Firefox

### Browser Version

120.0.1-1

### Build Version

2023.10.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the way your browser is handling the pop-out prompt window.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
