### ISSUE TITLE
Synchronisation error | Vault can not be synched with Bitwarden EU Server

### ISSUE THREAD

**Issue by foss-fan023** [bitwarden/clients#7127]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'Synch vault'

### Expected Result

1. Bitwarden client sychronises the vault to the Bitwarden EU Server
2. After successful synch, a prompt is telling the user 'Synchronisation successful'

### Actual Result

Prompt is telling the user 'Synching failed'

### Screenshots or Videos

![grafik](https://github.com/bitwarden/clients/assets/67341295/a965aed3-065f-4ec8-ade8-971ad607fed6)

### Additional Context

Everything worked fine so far, but after the update of the Bitwarden client to the below mentioned version 2023.12.0 the synchronisation does not work anymore (see error description above).

### Operating System

Windows

### Operating System Version

11 Enterprise 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0 with synch to Bitwarden EU Server

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a network misconfiguration

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
