### ISSUE TITLE
Browser "Vault timeout"/"Custom" does not work

### ISSUE THREAD

**Issue by panos8899** [bitwarden/clients#7157]
### Steps To Reproduce

1. Open a Firefox browser (or Chrome or MS Edge)
2. Click on the Bitwarden icon
3. Click on the Settings button
4. In the Security section click the "Vault timeout" dropdown, and select "Custom"
5. Then, in the fields below the "Vault timeout" dropdown, select a large value, eg. 15 hours or 20 hours (haven't tried with other values).
6. For "Vault timeout action" select "Lock".

### Expected Result

I expect that the "Custom" setting will persist after a browser restart. So that if I close the browser and after a little while reopen it, the Vault will still be unlocked.

### Actual Result

After a browser restart the Vault is locked.

### Additional Context

Sometimes I notice this behavior with the desktop app too, i.e. I have set the desktop app Vault timeout to Custom and 20 hours Lock. Usually, I have no problem with vault locking with the desktop app (not tried it with PC restart). But sometimes, even though the 20 hours have not passed the Vault gets locked.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome, Microsoft Edge, Firefox

### Browser Version

Firefox 120.0.1 (64-bit), Chrome Version 120.0.6099.71 (Official Build) (64-bit), Edge Version 120.0.2210.61 (Official build) (64-bit)

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @panos8899,

Thank you for your report. That is the expected behaviour; If the browser is closed, the extension would lock unless the vault timeout is set to (Never), and we detail this matter in our [Help Centre](https://bitwarden.com/help/vault-timeout/).

If you'd like this to be changed, please feel free to [join our forums](https://community.bitwarden.com/signup) and check if a similar request already exists. If there already is one, you can vote for it and contribute to any discussions about it; If not, you can create a new request so that it can be properly tracked. By the way, [this feature request](https://community.bitwarden.com/t/vault-timeout-delay-on-browser-restart/19114) might be helpful.

We use GitHub to track bugs and other development related issues; This report will now be closed. 

Thank you again,
