### ISSUE TITLE
Sync vault operation fails

### ISSUE THREAD

**Issue by wormi4ok** [bitwarden/clients#7170]
### Steps To Reproduce

1. Click on File -> Sync Vault

### Expected Result

Vault on the desktop app is synchronised with the web

### Actual Result

Syncing failed error message

### Screenshots or Videos

<img width="574" alt="Screenshot 2023-12-11 at 09 36 20" src="https://github.com/bitwarden/clients/assets/282550/e5d75875-23ca-420b-b1ae-ed15e3db884a">

### Additional Context

There are no errors in the console or network tab in developer tools. `https://api.bitwarden.eu/sync` endpoint responds with 200.

### Operating System

macOS

### Operating System Version

Ventura 13.4

### Installation method

Homebrew

### Build Version

Version 2023.12.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @wormi4ok 

Thank you for your report. 

I attempted to reproduce your issue and was unable to do so. I think you should log out of the desktop app and re-login to  see if the issue persists. 

Should the issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

**Comment by Dizirgee** [comment]
I had same issue today, i think it could be related to last update, as i noticed sync failure errors twice today with one new entry into vault and one edit. 
However above advice to logout and login seems to fixed the problem
current desktop version (on win10):
Version 2023.12.0
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

**Comment by llimllib** [comment]
I also experienced this, on the firefox extension, version `2023.12.0`

**Comment by devurandom** [comment]
Same here, Firefox 120, Bitwarden 2023.12.0.
