### ISSUE TITLE
Firefox Android Bitwarden plugin does not allow to login at bitwarden.eu

### ISSUE THREAD

**Issue by coder66** [bitwarden/clients#7186]
### Steps To Reproduce

When installing the BW plugin in Firefox 120 under Android, there are only options to login to bitwarden.com or own server. Bitwarden.eu is missing and thus unable to login.

Also there is no default login option set, you only see an arrow but no text. There should be a default option set.

### Expected Result

Ability to select bitwarden.eu

### Actual Result

Option "bitwarden.eu" is missing from selection

### Operating System

Android

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

120

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser. For Android, Bitwarden recommends using the Bitwarden mobile app, which can be downloaded from either the [Google Play Store](https://play.google.com/store/apps/details?id=com.x8bit.bitwarden&hl=en_US&gl=US) or from [F-Droid](https://mobileapp.bitwarden.com/fdroid/). 

If additional assistance is needed, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

The issue here will be closed.

Thanks!
