### ISSUE TITLE
Bitwarden 2023.12.0 closes itself when undocked

### ISSUE THREAD

**Issue by p1nkyy** [bitwarden/clients#7203]
### Steps To Reproduce

1. Go to Bitwarden window
2. Click on the arrow button that says 'Pop up to a new window'
3. An undocked Bitwarden window would pop out.

### Expected Result

In previous versions, the window will stay open even after I clicked several saved websites / credential.

### Actual Result

In the newest version, the window closed after I clicked one saved website/credential

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cagonzalezcs** [comment]
@p1nkyy 

Thank you for providing this bug report. Are you still seeing this issue within the extension?

There were a number of fixes that were released back in late December that should have resolved this problem, and I'm not seeing any issues with navigating the popped out vault at this point. 

If this issue is still persisting, please comment with details and we can move forward from there. For now, I'm closing this ticket as it seems that the reported issue has been addressed and is currently not replicable.
