### ISSUE TITLE
Folder list is blank

### ISSUE THREAD

**Issue by munrobasher** [bitwarden/clients#7204]
### Steps To Reproduce

1. Upgrade to 2023.12.0
2. On opening Windows client, folder list is empty

### Expected Result

Folder list should be displayed as in previous versions.

### Actual Result

Folder list is blank, Edit vault item and folder entry is blank. Drop down list of folders is blank.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/13134946/2ae7ec88-14ff-442f-93f9-b81690d88d16)

### Additional Context

At first thought all folders lost but this problem is only with the latest Windows client. The browser extension, web site and mobile apps are all okay.

### Operating System

Windows

### Operating System Version

10 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try fully logging out of your Bitwarden desktop app and logging back in to see if the issue persists. If it does, please try reinstalling the desktop app. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located at our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by munrobasher** [comment]
Surely this **is** a bug? Anyway, sign out and back in resolved it.
