### ISSUE TITLE
Bitwarden hijacks my browsers yubikey authentication and requires me to log in to bitwarden in order to use it to authenticate.

### ISSUE THREAD

**Issue by ceramicskull** [bitwarden/clients#7207]
### Steps To Reproduce

1. Be logged out of bitwarden
2. Log into a site using a yubikey
3. Bitwarden will hijack the browser yubikey authentication request and prompt you to login before you can use your yubikey
4. Login to bitwarden and then tap your yubikey. 

### Expected Result

That the yubikey result goes through your browser without going through bitwarden. Atleast allow this to be turned off. 

### Actual Result

Bitwarden hijacks the yubikey authentication request and forces you to login to bitwarden before being able to use your yubikey. 

### Additional Context

The reason this is a specific issue is because I use 2 password managers. I use keepass for work passwords and then I have a personal bitwarden manager that I use for personal passwords. I keep the bitwarden extension on my work browser as I might login to personal services on my work computer, like email, or linkedin, etc... but wish to not store this in with my work passwords. It is also against company policy to use bitwarden for my work passwords. The problem arises when trying to login to a company website using my yubikey and bitwarden thinks I have to authenticate through bitwarden to use my yubikey. I don't want to keep bitwarden logged in all the time, only when I am accessing personal accounts. 

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.3 LTS

### Web Browser

Firefox

### Browser Version

121.0 (64-Bit)

### Build Version

2023.12.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the **Ask to save and use passkeys** option.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jan--m** [comment]
> Regardless, if the above two options don't meet your needs, what you're asking for would be a [Feature Request](https://community.bitwarden.com/c/feature-requests/pm-feature-requests/55), not a bug.

I'm curious how something that was working fine before, but is now causing a problem for our users is "not a bug"

**Comment by janmashat** [comment]
> Regardless, if the above two options don't meet your needs, what you're asking for would be a [Feature Request](https://community.bitwarden.com/c/feature-requests/pm-feature-requests/55), not a bug.

I'm curious how something that was working fine before, but is now causing a problem for our users is "not a bug"
