### ISSUE TITLE
Only the first of multiple chrome sessions can use biometric unlocks

### ISSUE THREAD

**Issue by pacanukeha** [bitwarden/clients#7219]
### Steps To Reproduce

1. Create multiple chrome sessions (user profiles)
2. Launch one, install the chrome extension, enable biometric unlock.
3. Reboot. Launch a different one, install the chrome extension, enable biometric unlock.
4. Reboot. Launch both sessions/profiles. In one, unlock with biometrics. In the other, try to unlock with biometrics.
5. Close both sessions. Launch the session that was unable to unlock. Try to unlock.
5. Repeat steps 4 and 5 and perform the unlock in whichever order you chose to verify that the problem isn't session specific.

### Expected Result

Both profiles can unlock with biometrics.

### Actual Result

Only the first profile to be unlocked in a windows user session can use biometrics.  Any others need to use the pass phrase. 

### Additional Context

Exiting and restarting the bitwarden desktop application doesn't make a difference, only a windows restart.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Version 120.0.6099.71 (Official Build) (64-bit)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. When utilizing a new browser profile, the extension settings are set to their default values. As a result, it would be necessary to reconfigure the settings in the new profile.

If you would like this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
