### ISSUE TITLE
Firefox extension doesn't actually login with webauthn

### ISSUE THREAD

**Issue by Joibel** [bitwarden/clients#7224]
### Steps To Reproduce

Using Firefox (120.0.1) on amd64 linux with browser extension 2023.12.0 and yubikey registered for webauthn
1. Using the extension button enter your username
2. Enter your password
3. Open in new tab and Authenticate WebAuthn with your key
4. ![image](https://github.com/bitwarden/clients/assets/1827156/96a87ede-b16e-42a1-9040-b5eab5981361)
5. Imagine you're logged in, but find you're back at step 1.
6. Do it all again because you think you're wrong, and find out you're not.

Ticking "Remember me" doesn't affect the result, neither does unticking it.

### Expected Result

You can access your vault from the browser extension

### Actual Result

The browser extension asks you to login.

Get frustrated and login to https://vault.bitwarden.com successfully with the same credentials and use good old copy and paste to achieve your logins today.

### Operating System

Linux

### Operating System Version

Nixos 23.11

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so on my Arch Linux machine running the latest version of Firefox.

If you have performed a clean installation of the extension already by removing any leftover data (https://help.bitwarden.com/article/where-is-data-stored-computer/), I suggest you try to refresh your Firefox's profile following their instructions: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings and try again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
