### ISSUE TITLE
Firefox 120.0.1 + Bitwarden 2023.12.0: Unlock with PIN, Lock with Master Password on Browser Restart not working

### ISSUE THREAD

**Issue by casualsailo** [bitwarden/clients#7229]
### Steps To Reproduce

1. Uninstall Bitwarden extension
2. If it exists, delete folder from %AppData%\Roaming\Mozilla\Firefox\Profiles\your_profile\storage\default\moz-extension+++[UUID]^userContextId=[integer]
3. Close and relaunch firefox
4. Install Bitwarden from https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/
5. Allow extension to run in private windows
6. Go to Bitwarden extension -> Settings
7. Change **vault timeout** -> 30 minutes
8. Click on **Unlock with PIN**
9. Enable **Lock with master password on browser restart**
10. Set PIN and click OK
11. The **Unlock with PIN** box is checked
12. Move to a different tab (Tab/Vault/Send/Generator)
13. Go back to Settings tab
14. The **Unlock with PIN** is unchecked

### Expected Result

I expect bitwarden to allow unlocking with PIN until I restart the browser. If there is a browser restart, it would require the master password

If the **Lock with master password on browser restart** option is unchecked, then setting the PIN works

### Actual Result

If you enter a PIN and check the **Lock with master password on browser restart** box, it initially appears to be successful with the box checked

But if you refresh the bitwarden extension settings page, the setting did not save. The unlock with PIN box is no longer checked. This is not the expected behavior

If I keep trying, I discovered that the unlock with pin setting does eventually save. But this is random; sometimes it works after the 2nd try, sometimes takes more than 10 tries

### Operating System

Windows

### Operating System Version

Windows 10 22H2

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in trying to set these settings in a private/incognito session - Bitwarden stores these settings in a cookie, and incognito session cookies do not persist.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by scottwallacesh** [comment]
I still see this issue and I'm not using any private/incognito sessions.

I can make the option "stick" if I disable the `Lock with master password on browser restart` option.

**Comment by scottwallacesh** [comment]
I still see this issue and I'm not using any private/incognito sessions.

I can make the option "stick" if I disable the `Lock with master password on browser restart` option.

Browser: Firefox 118.0.1 (64-bit) (NixOS)
BW Extension: 2023.12.0

**Comment by scottwallacesh** [comment]
Same on Firefox 120.0.1 (64-bit) (NixOS)
