### ISSUE TITLE
Chrome extension fails to launch desktop application for Biometric application

### ISSUE THREAD

**Issue by Moulick** [bitwarden/clients#7306]
### Steps To Reproduce

1. Launch fresh Chromium based browser (edge, chrome)
2. Try to unlock Bitwarden Vault.
3. Bitwarden extension tries to launch Bitwarden Desktop to use Biometric authentication
4. Bitwarden Desktop fails to open. The desktop app icon flashes for a few milliseconds in the Dock and crashes.

### Expected Result

Bitwarden Desktop application to launch and prompt for TouchID, and unlock vault

### Actual Result

The desktop app icon flashes for a few milliseconds in the Dock and exits. The vault remains locked

### Screenshots or Videos

<img width="375" alt="image" src="https://github.com/bitwarden/clients/assets/15780903/3327fb42-62ef-4533-a352-96e064dda499">

### Operating System

macOS

### Operating System Version

14.2.1

### Web Browser

Chrome, Microsoft Edge

### Browser Version

120.0.6099.129

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @Moulick ,
I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.
Could you follow this process for deleting items in this folder based off how you installed Bitwarden on your machine :

macOS
- Standard installations: ~/Library/Application Support/Bitwarden
- Mac App Store: ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden
After completing the deletion of the folder, could you initiate the process of Biometrics again and let us know if any issues persists.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.
The issue here will be closed.
Thanks!

**Comment by Moulick** [comment]
@daniellbw Cleaned up both locations, and reinstalled bitwarden from the app store, the browser extension is not able to launch the application. For you, is the browser extension able to launch the application from scratch, aka if the desktop application has been exit, then try to unlock vault in the extension?

**Comment by djsmith85** [comment]
@Moulick Taken from https://bitwarden.com/help/biometrics/#tab-browser-extension-2vCWb5iFg4OqKS0B2xXpqW

> For all except Safari, the Bitwarden desktop app must be logged in and running in order to use unlock with biometrics for a browser extension

**Comment by Moulick** [comment]
Interesting, 1password is able to launch the application as well to handle the Biometric flow. I hoped Bitwarden could also do the same
