### ISSUE TITLE
New taskbar instance when app is updated in Windows / Icon does not stay pinned

### ISSUE THREAD

**Issue by jspanos71** [bitwarden/clients#7316]
### Steps To Reproduce

1. Install the desktop client in Windows and open the application
2. Pin the desktop icon to the taskbar (right-click icon in taskbar or start menu, select "Pin to taskbar"
3. Leave application open or close it.  Icon should stay on the taskbar since it is pinned
4. Wait for a new version of the desktop client to be installed / updated
5. After new client update is installed, opening Bitwarden from the existing pinned entry will spawn a new taskbar icon 

### Expected Result

Pinning the application icon should keep the icon on the taskbar, and in the position where it was placed by the user.

### Actual Result

The pinned icon remains after the update, but it launches a second icon that is not pinned.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/3599357/faa5cfed-071b-4d92-814a-9e49efc5df69)

### Operating System

Windows

### Operating System Version

Windows 11 - all versions

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0 - all versions that I've used since early in 2023

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Does this issue remain if you uninstall Bitwarden and reinstall it?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jspanos71** [comment]
I reinstalled and this issue still happens.  It happens on all windows 11 machines that I've used (3 different machines).

**Comment by Aldnoa19** [comment]
Hello, i have the same problem for a long time. Have to repin app to bar after every update and then after some time the issue happens again.

<img width="600" height="157" alt="Image" src="https://github.com/user-attachments/assets/2d0ad3fa-a4e1-4723-8303-bfab24ac49d7" />
