### ISSUE TITLE
After Update AppImage in Dark Mode Doesn't Display and Text

### ISSUE THREAD

**Issue by discoweasel** [bitwarden/clients#7355]
### Steps To Reproduce

1. Update to AppImage Version 2023.12.1 on Fedora 39

Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

### Expected Result

Can no longer see text fields or text displayed.

### Actual Result

After updating a working AppImage and implementing no other changes, the AppImage isn't displaying anything. I can "see" the cursor blinking for the password box but when logged in, all that can be seen is dark.

I am unable to switch the appimage to light mode as I can't see anything. 

I did switch all desktop settings to light mode and default themes, but the settings seem to be specific to the AppImage.

Version 2023.12.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

### Screenshots or Videos

![Screenshot from 2023-12-24 14-51-34](https://github.com/bitwarden/clients/assets/24635388/95d80b92-4226-4d93-b831-e8d451fa334c)
![Screenshot from 2023-12-24 14-54-33](https://github.com/bitwarden/clients/assets/24635388/fd878690-07d9-4607-bdc2-27d034800d14)

### Additional Context

Using Wayland on Gnome 45.2

### Operating System

Linux

### Operating System Version

Fedora Linux 39 (Workstation Edition) Linux 6.6.7-200.fc39.x86_64

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @discoweasel,

Thank you for reporting this. I recommend that you first try refreshing the interface by clicking on View > Reload, and proceed with deleting that .AppImage and downloading a [few new copy](https://github.com/bitwarden/clients/releases/tag/desktop-v2023.12.1) and using that if reloading the interface did not assist; I say this because I was unable to reproduce this behaviour on Fedora 39 with Bitwarden .AppImage 2023.12.1.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
