### ISSUE TITLE
Under windows 11, bitwarden can open off screen.

### ISSUE THREAD

**Issue by johnmcleodvii** [bitwarden/clients#7356]
### Steps To Reproduce

1.  It requires you start on a dual monitor system.  I have a laptop where the main screen is the laptop and the secondary monitor is to the laptops left.  It is not a reflection of the laptop monitor, but is an extension.  I have not tried this if the secondary monitor is to the right, but the same problem may exist.
2. Move the bitwarden window to the secondary monitor.
3. Use bitwarden there.
4. Shutdown the computer.
5. :Go on the road".  Disconnect the monitor and start the laptop.
6. Open Bitwarden.

### Expected Result

I expect to see the bitwarden window open on th elaptop screen.

### Actual Result

I believe the bitwarden is still opening in the same location, but there is no screen there.  

### Operating System

Windows

### Operating System Version

Windows 11 Home.  21H2.  22000.2538.  Windows Feature Experience Pack 1000.22001.1000.0

### Installation method

Other

### Build Version

2023.12.1 Shell 25.9.1 Renderer 1140.5735.289 Node 18.15.9 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in Windows not handling the primary monitor correctly. You can try using **Windows Key + Shift + Arrow Key Left or Right** to move the application window across while it's in focus.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by tarrouye** [comment]
This should not be closed, this is still an issue to this day. It is easily reproducible by adding an extra monitor, moving Bitwarden to that monitor, then disconnecting the monitor. Bitwarden will always open on the screen that no longer exists. 

Win + Shift + Arrow Key does nothing to move it back to the proper screen. 

It shouldn't be complicated for Bitwarden to detect the current screens and display its window on one of them. 

Please fix :)

@sammbw

**Comment by djsmith85** [comment]
Possible duplicate of https://github.com/bitwarden/clients/issues/2617

**Comment by lsteger1983** [comment]
Yes, duplicate of #2617 
Had this bug several times already, REALLY annoying.
Always had to set "x": 0 or "y": 0 in data.json under global window, restart Bitwarden app and then it reappeard on the main monitor again.

Please fix it soon, thanks.

**Comment by josephgavin** [comment]
> I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in Windows not handling the primary monitor correctly. You can try using **Windows Key + Shift + Arrow Key Left or Right** to move the application window across while it's in focus.

This solution does not work for me neither does this:

> Alt+Tab to make sure Bitwarden is 'selected'
> Alt+Space, then M to trigger 'Move'
> Drag the Bitwarden window onto the visible screen
> Profit (but still please fix xd)

Please advise another work around or fix this issue

**Comment by justinleahy** [comment]
Necroposting because I just ran into this issue and my fix was same as above but instead of 'Move' do 'Maximize'
