### ISSUE TITLE
addy.io (forward email generator) stopped working

### ISSUE THREAD

**Issue by mrx23dot** [bitwarden/clients#7363]
### Steps To Reproduce

Go to Firefox 
open addon

![image](https://github.com/bitwarden/clients/assets/4163396/3a78dd7e-ed4c-458e-94ce-ef704d47a905)

generate new

### Expected Result

new random email should be generated.

https://app.addy.io/settings/api
says my API key has been just used,
so request goes in, maybe doesn't get back.

Used to work great a few weeks ago.

### Actual Result

![image](https://github.com/bitwarden/clients/assets/4163396/394a596f-f37f-4f34-88a1-9880400dbae9)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

Version 2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @mrx23dot, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or corruption of your existing configuration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
