### ISSUE TITLE
Vault syncing fails on Windows

### ISSUE THREAD

**Issue by roccobarbi** [bitwarden/clients#7372]
### Steps To Reproduce

1. Add a new set of credentials from the mobile app or the web version;
2. if they were created with the mobile app, sync it;
3. Go to 'File'
4. Click on 'Sync vault.'

### Expected Result

The vault is synced.

### Actual Result

Syncing failed error message (while the internet is working as expected).

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/7573768/7276ac30-f527-445d-99a2-c8330d6c4ba5)

### Operating System

Windows

### Operating System Version

Windows 11 Pro Version	10.0.22621 Build 22621

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by XLTIQUE** [comment]
J'ai le même problème.

**Comment by atjbramley** [comment]
Hi @roccobarbi ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a stale session cookie.  Please try logging out and back in (n.b., please log out of your vault - simply locking it will not have the same effect  https://bitwarden.com/help/vault-timeout/ )

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
