### ISSUE TITLE
Auto-fill on form fields on Odoo.com makes the page crash

### ISSUE THREAD

**Issue by sqvdotbe** [bitwarden/clients#7381]
### Steps To Reproduce

When using auto-fill on form fields for all Odoo databases and the Odoo.com website itself an error is shown. Maybe the Bitwarden code injection is a bit too intrusive?

Go to https://www.odoo.com/web/login

or

Go to https://55711862-master-all.runbot173.odoo.com/web/login

### Expected Result

No error and be able to logon.

### Actual Result

Error:
`UncaughtPromiseError
Uncaught Promise > Permission denied to access property "nodeName"
Error: Permission denied to access property "nodeName"
    TAG/Sizzle<@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:1975:212
    elementMatcher/Sizzle<@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:2006:135
    superMatcher@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:2025:49
    Sizzle.select@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:2043:36
    Sizzle@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:1914:8
    find@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:2057:50
    jQuery.fn.init@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:2062:71
    jQuery@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:1877:58
    UpdateUi@https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:12137:472
    @https://odoocdn.com/web/assets/41954657-8ae08b8/1/web.assets_frontend_lazy.min.js:12140:100`

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/116297943/ba5550be-622c-4afa-8978-228864b0fe35)

### Additional Context

Also on other simple fields of the Odoo crm when you go to Contacts and want to add an e-mail address to the contact, Bitwarden autofill on on form fields makes the Odoo page crash. The only way is to disable Bitwarden autofill on form fields.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome, Microsoft Edge, Firefox

### Browser Version

Any

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
