### ISSUE TITLE
Can not login to bitwarden vault on Firefox Extension

### ISSUE THREAD

**Issue by cyberboh** [bitwarden/clients#7395]
### Steps To Reproduce

1. Go to Extension
2. Enter bitwarden email.
3. Click on Login 
4. Enter Master Password
5. Error appear

### Expected Result

I can login to firefox extension

### Actual Result

Error occured

### Screenshots or Videos

![cant login](https://github.com/bitwarden/clients/assets/99109969/1c472694-369a-43bb-9928-ee31aef80959)

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

121.0

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @cyberboh 

I attempted to reproduce the issue you have described and was unable to do so . I think your error could have its origin in a misconfiguration. Could you please reinstall the extension?

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
Thanks!

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/4076
