### ISSUE TITLE
Back/forward navigation causes page to reload and drop its state

### ISSUE THREAD

**Issue by rpiosi** [bitwarden/clients#7419]
### Steps To Reproduce

1. Go to google.com
2. Serach something
3. Visit result
4. Go back to results

### Expected Result

Google loads its previous state entirely from memory. No reload is needed with its public Cache-Control header of html document.

### Actual Result

Google reloads, state of interaction is lost and scroll position with it.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/7120725/4f0fa59e-ebd9-4978-b9d9-91a83411a5a7

### Operating System

Windows

### Operating System Version

Experiencing it in Ubuntu as well.

### Web Browser

Chrome

### Browser Version

120

### Build Version

120.0.6099.130

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. You might try uninstalling and re-installing the extension from the Chrome extension store. You can find that link on our downloads page: https://bitwarden.com/download/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
