### ISSUE TITLE
Extension does not honor disabled "Ask to add/update existing login" option

### ISSUE THREAD

**Issue by bwbug** [bitwarden/clients#7431]
### Steps To Reproduce

1. In **Settings > Options**, disable "Ask to add login" "Ask to update existing login" options.
2. Log in to a website that is not stored in the vault, or into a stored account using an updated password.

### Expected Result

Bitwarden browser extension should honor preference to not ask to add or update the password &mdash; i.e., Bitwarden should _not_ display the banner prompt.

### Actual Result

The banner prompt is displayed.

### Screenshots or Videos

The screenshot below shows the options in the browser extension (verifying that the options "Ask to add/update existing login" are disabled), as well as the Banner that had popped up when logging in.

![image](https://github.com/bitwarden/clients/assets/109386143/42772773-67ee-4545-87ac-c92f2950dc79)

### Additional Context

I will attempt to do further testing to determine whether this is limited only to specific websites.

### Operating System

Windows

### Operating System Version

Windows 11 Version 22H2 (Build 22621.2861)

### Web Browser

Chrome

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
There is currently a bug with the extension where it will not correctly honour the excluded domains list, so while clicking “Never” will add the domain to the excluded list, it isn't being read properly.

This will be fixed in an upcoming version release of Bitwarden, for now, I can't provide a workaround but rest assured this will be fixed shortly.
https://github.com/bitwarden/clients/issues/1641
