### ISSUE TITLE
Bitwarden Browser Extension not prompting when adding a passkey for github authentication 

### ISSUE THREAD

**Issue by Thibault2ss** [bitwarden/clients#7436]
### Steps To Reproduce

1. Navigate to github.com > `Settings` > `Password & Authentication`
2. Click on `Add a Passkey`
3. On the new page click on `Add Passkey`

### Expected Result

Bitwarden browser extension prompts for new passkey creation.

### Actual Result

The Bitwarden browser extension is not prompted for adding a new passkey there. Only the default browser-level webauthn prompt is prompted:
<img width="464" alt="image" src="https://github.com/bitwarden/clients/assets/20459279/a6e667b6-b7f0-4971-a33d-11ffda59803d">

### Additional Context

Maybe something could help resolve: I have my own app where I use webauthn authentication, and I had the same issue of the bitwarden extension not prompting (that was on `navigator.credentials.get` though, not on `navigator.credentials.create`, so maybe it's not the same issue in this case). I had to remove the option `mediation: 'required'` for the Bitwarden extension to prompt when requesting that `navigator.credentials.get`.

### Operating System

macOS

### Operating System Version

Ventura 13.2.1

### Web Browser

Brave

### Browser Version

v1.61.109

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by coroiu** [comment]
GitHub creation is not related to #7302 which is an issue when using an already created passkey! We are looking into this issue and will let you know when we have more information :)

Regarding the additional context comment about `mediation`: That is expected behavior since Bitwarden does not yet support mediated requests.

**Comment by Greenderella** [comment]
Hi @Thibault2ss 

I'm unable to replicate this issue with the passkey creation on GH, both the passkey creation and login process work as expected with the Bitwarden extension Version 2024.1.0 and Chrome Version 120.0.6099.225:
![creationGH](https://github.com/bitwarden/clients/assets/5418577/7967e913-e5c1-4fac-97f9-2da47d1b14e8)

I recommend you try updating your extension and browser and check that no other extension or configuration is interfering the process.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
