### ISSUE TITLE
Different TOTP codes for bank site between authy and Bitwarden

### ISSUE THREAD

**Issue by maillota** [bitwarden/clients#7441]
### Steps To Reproduce

1. Log on to firsttechfed.com
2. Go to profile and then security
3. Enable 2FA code generation (removing any others first)
4. Copy code into account settings in browser extension
5. Add same code to Authy using camera capture
6. Observe different codes despite same time zone and consistency across all other TOTP tokens.

### Expected Result

Same token is generated on both devices

### Actual Result

A different token is generated only for this particular site. Other TOTP tokens work fine and consistently between authy and bitwarden.

### Operating System

Windows, Linux

### Web Browser

Chrome

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in an out-of-sync system clock, as TOTP codes rely on the clock sync to be correct. If the codes generated by Bitwarden are accepted during two-factor authentication, then there is no issue to remedy here.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by maillota** [comment]
Just to follow up and provide a bit more info, I agree with your assessment
that it's a clock / timing issue as I've noticed that though they are out
of sync, the non-bitwarden client is behind (that is, shows the same token
30/60 seconds later). It's odd that this is specific to this site though,
the same two clients/devices show identical tokens on the same timer for
other sites. I've invalidated my token so I could share it with you incase
that helps: XT3CG3IJIBGU7NWBCZ7E5G5SSAFRGZIH

Thanks!
