### ISSUE TITLE
Wrong password shown

### ISSUE THREAD

**Issue by CountTo10Boogie** [bitwarden/clients#7465]
### Steps To Reproduce

1. Create a password
2. Log out of Bitwarden web
3. Log back into Bitwarden web

### Expected Result

Expected to see the correct password

### Actual Result

The password shows the incorrect password or potentially an old password
After some time the correct password shows

### Operating System

Windows

### Web Browser

Chrome

### Build Version

don´t know

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @CountTo10Boogie ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a caching issue, or a confusion of the accounts in use.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by SamedYalcin** [comment]
Reviving an old thread. I had this issue just now. In my android phone and PC Google Chrome extension, password for an account shows a wrong or potentially an old one. However the password in the Microsoft Store app is correct.
