### ISSUE TITLE
Snap app does not honor max vault timeout policy

### ISSUE THREAD

**Issue by mennomenno** [bitwarden/clients#7503]
### Steps To Reproduce

1. In the Ubuntu snap app select settings
2. Set vault timeout to say 1 hour while the organization policy has maxed this at 15 minutes
3. Save

### Expected Result

An error message that the max timeout is 15 minutes and the timeout being unchanged or set at 15 minutes.

### Actual Result

Timout set at a value > max

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Snap

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @mennomenno ,

I attempted to reproduce your issue and was unable to do so. Please see the error display when trying to reproduce your query.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.
Thanks!

<img width="953" alt="Screenshot 2024-01-12 at 11 32 04" src="https://github.com/bitwarden/clients/assets/152835204/6164168c-bc3b-4534-a718-b780bbe85e5c">
