### ISSUE TITLE
Passkey URL Doesn't exist

### ISSUE THREAD

**Issue by TheKourosh** [bitwarden/clients#7504]
### Steps To Reproduce

1. Go to 'Account settings'
2. Click on 'security'
3. Scroll down to 'Log in with passkey'
4. Click on 'Learn more about passwordless'

### Expected Result

Bitwarden Login With Passkey Document show up.

### Actual Result

Uh oh. 404 Error Page Shows up.

### Screenshots or Videos

![bitwarden404](https://github.com/bitwarden/clients/assets/14193021/b00ce1ef-9bdd-412f-9787-8356421f2758)

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2024.1.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @TheKourosh, 

I attempted to reproduce your issue and was unable to do so. I think your error could be down to accessing the URL in a brief window during which it was not available.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
