### ISSUE TITLE
Bitwarden hijacks some Global Media Hotkeys

### ISSUE THREAD

**Issue by kazerniel** [bitwarden/clients#7507]
### Steps To Reproduce

1. Launch Bitwarden
2. Play some music in Winamp
3. Try to use the "Previous Track" or "Next Track" global media hotkeys
4. Nothing happens
5. Close Bitwarden
6. Hotkeys work again

### Expected Result

For Bitwarden to leave those hotkeys alone.

### Actual Result

See above.

### Additional Context

I think it may be an Electron issue, bc I used to have the same happen with another Electron app (just different hotkeys affected). The problem went away there after a while, so maybe it was something that the app's dev did, rather than the Electron devs 🤷‍♂️

https://github.com/hovancik/stretchly/issues/1059

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

As long as Bitwarden is running, the preferred hotkeys will be available for use. If you would like to change your assigned hotkeys, you can navigate to the Bitwarden browser extension > Settings > Auto-fill > Auto-fill keyboard shortcut and change them there! 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by kazerniel** [comment]
I'm sorry but your response does not seem to refer to my issue at all.

I only have this problem with the desktop client, not the browser extension.

And none of the hotkeys on the webpage linked from that menu are the global media hotkeys on the keyboard.
