### ISSUE TITLE
On MacOS 10.14 updated automatically on unsupported version

### ISSUE THREAD

**Issue by daitarn** [bitwarden/clients#7528]
### Steps To Reproduce

1. Nothing, It auto updates

### Expected Result

Do not update to an unsupported version!

### Actual Result

On MacOS it updates automatically from 2023.12.1 to 2024.1 which needs 10.15 to run.

### Operating System

macOS

### Operating System Version

10.14.6

### Installation method

Other

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by spiderman666** [comment]
Having same issue on OSX 10.13.6

**Comment by daitarn** [comment]
> Having same issue on OSX 10.13.6

Try [this method](https://github.com/bitwarden/clients/issues/2565#issuecomment-1418266884), not ideal, but should work. If you have BitWarden as a startup item it could load before the Script, so either try to remove BitWarden from the startup items and add it after the Script, or remove BitWarden from the startup items altogether.

Don't know why BitWarden doesn't have an option to disable updates!?

**Comment by daitarn** [comment]
> > > Having same issue on OSX 10.13.6
> > 
> > 
> > Try [this method](https://github.com/bitwarden/clients/issues/2565#issuecomment-1418266884), not ideal, but should work. If you have BitWarden as a startup item it could load before the Script, so either try to remove BitWarden from the startup items and add it after the Script, or remove BitWarden from the startup items altogether.
> > Don't know why BitWarden doesn't have an option to disable updates!?
> 
> Thanks! I will take a look. For the moment, after doing a manual downgrade of Bitwarden to v2023.12.1 , I have just been blocking the Bitwarden Electron Helper with [LuLu](https://github.com/objective-see/LuLu) to prevent the auto update.

Didn't think about blocking the update, getting old, a better idea than making an app.

**Comment by spiderman666** [comment]
> 
> Didn't think about blocking the update, getting old, a better idea than making an app.
> 
> Now, I don't want to block the sync, so what domain have you blocked?

LuLu (firewall) blocks the bitwarden helper app module accessing the entire network, so while it prevents auto-update, it also breaks sync.  Unfortunately, from my quick tests its 'all or nothing' at the moment. I was hoping it was just going to be a temp fix until the devs either change the "minimum os version" flag or offer a legacy version of their app. If anything pre OSX 10.15 has been deprecated then it looks like I will be forced to use their website/browser version and abandon the desktop client.

**Comment by Greenderella** [comment]
Hi @daitarn, 

Thank you for bringing your request to our attention. We appreciate your feedback and understand your concern regarding Bitwarden's behavior on macOS 10.14 (Mojave).

At this time, we do not support the request to prevent Bitwarden from updating. However, we encourage you to sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

It's important to note that Apple ended support for macOS 10.14 (Mojave) in October 2021, which means that it is no longer receiving security updates and patches from Apple. Running security applications like Bitwarden on an unsupported and unpatched system can potentially expose your system to security vulnerabilities. We strongly recommend considering the security implications of this.

We use GitHub issues as a place to track bugs and other development related issues. This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Have a nice day.
