### ISSUE TITLE
Bitwarden Causing error when trying to add 2FA Credential in CheckMK

### ISSUE THREAD

**Issue by cclarke591** [bitwarden/clients#7551]
### Steps To Reproduce

Go to a self hosted instance of CheckMK, create an account, and go to setup a 2FA credential.

### Expected Result

While logged into CheckMK, the expected result is to go to the Two-factor authentication section of the account. Click Add credential, and add a passkey or hardware key.

### Actual Result

With Bitwarden installed in the browser (Firefox), clicking on the "Add Credential" causes a red "Registration failed: Invalid 'sameOriginWithAncestors' value" to come up.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/42067868/c4b2e5af-82dc-4d1e-a9fd-6b426a586197)

### Additional Context

Running Bitwarden in Edge seems to work okay, along with running a private browser window in firefox, without Bitwarden allowed to run in the private window.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 10.0.22621 Build 22621

### Web Browser

Firefox

### Browser Version

121

### Build Version

121

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Apologies for the delay, I attempted to reproduce your issue and was unable to do so but am perhaps misunderstanding the issue. Is this still happening for you?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

Since I am unable to reproduce this, the issue here will be closed but if you write support and this is determined to be a bug and not specific to your device/setup/etc. we can always come re-open this issue if needed.

Thanks!

**Comment by Jetro97** [comment]
Same behaviour here. I have the same problem with firefox: tried with Edge and it was working so installed Bitwarden on Edge and retried getting the same error.
I'm using self-hosted Vaultwarden, but the browser plugin is the bitwarden original one.

To reproduce the issue:
- Standard self hosted installation with HTTPS (in my case nginx on a different machine, as in this test instance i don't have multiple public IPs)
- Fresh Edge installation: it works
- Install Bitwarden on Edge: stop working

Maybe it can be an error on bitwarden side? I'm asking first here because that's working on all other sites.

Many thanks

**Comment by avluis** [comment]
Still an issue unfortunately -- need to use a Guest profile or disable Bitwarden extension to be able to add entries; basically, unable to make use of Bitwarden Passkeys on Checkmk 😢

**Comment by antonlydell** [comment]
This issue is similar to [Unknown errorCode "Invalid 'sameOriginWithAncestors' value" when signed in to Bitwarden browser extension](https://github.com/bitwarden/passwordless-client-js/issues/62) using passwordless-client-js.
