### ISSUE TITLE
v2024.1.0 brower extension does not seem to allow me to define more than one self-hosted server

### ISSUE THREAD

**Issue by jalbstmeijer** [bitwarden/clients#7562]
### Steps To Reproduce

1. Go to 'Logging in on'
2. Click on ' self-hosted'
3. Look for a way to define an other self-hosted server

### Expected Result

Being able to define multiple 'self-hosted' servers with their own name/label.

### Actual Result

Only one  'self-hosted' configuration seems available.

### Operating System

Linux

### Web Browser

Brave

### Browser Version

1.61.114

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @jalbstmeijer 

Thank you very much for letting us know about the difficulties with account switching in the extension.

If you have defined a selfhosted server and want to add another, click on either .com or the .EU region, then click on the selfhosted again, this will allow you to define a new selfhosted server. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.
Thanks!
