### ISSUE TITLE
Latest desktop client version 2024.1.0 causes visual artifacts

### ISSUE THREAD

**Issue by siosond** [bitwarden/clients#7586]
### Steps To Reproduce

1. Install or update to version 2024.1.0

### Expected Result

There should be no visual artifacts like with the previous versions (2023.12.1 and below).

### Actual Result

There are visual artifacts when the application contents are being rendered.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/13352896/07575054-28da-4033-9a8d-61f4027f7b5a

### Additional Context

This happens specifically on the Windows desktop client of Bitwarden, regardless whether installed directly from bitwarden.com, the Microsoft Store, or even GitHub.

### Operating System

Windows

### Operating System Version

10.0.22631.2861

### Installation method

Direct Download (from bitwarden.com), Microsoft Store, Other

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I suggest you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing. Here is a guide to find any leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
