### ISSUE TITLE
Desktop App never loads vault, loads infinitely, even after multiple updates and uninstalling/re-installing [Windows 10]

### ISSUE THREAD

**Issue by Mikeureko** [bitwarden/clients#7601]
### Steps To Reproduce

1. Start the desktop app
2. ... That's all I know. I have no idea what could've changed it.

### Expected Result

The loading screen should only last a few seconds at most, then ask for the master password.

### Actual Result

Instead, the loading screen stays perpetually.

### Screenshots or Videos

Just imagine the spinning loading circle screen it always shows before asking for the master password, going forever and never stopping (even after letting it "load" for 12+ hours). 

### Additional Context

This has been happening for about 6 months, only on my desktop app; Brave extension works flawlessly, and mobile app works flawlessly as well. This has been true even despite receiving and installing at least half a dozen updates, and uninstalling/reinstalling twice. 

### Operating System

Windows

### Operating System Version

10.0.19045 Build 19045, and a few previous versions that I don't have on record. 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Mikeureko** [comment]
... Well, after starting Bitwarden desktop once more (and after having previously hit "add account" before closing it directly prior to this re-opening), it asked for my e-mail, and then master password, and logged in fine. 

I can only speculate that what fixed it had to do with either:

1. Closing and opening it again after this specific update (even though I did the same thing before to no success)
2. Clicking the account dropdown menu at the upper-right corner and clicking "add account" before closing possibly got the program out of some weird infinite loop

Do with this post what you will. It could still be relevant for some users, or perhaps you guys totally fixed it and I found out immediately after posting this bug report. Not sure if this is grounds for hitting the "close with comment" button; if you are able to do that and you see fit to, by all means, go for it. I'm sure someone will post about it somewhere if they encounter this issue themselves going forward. 

Thanks for all your hard work.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try uninstalling the app one more time and remove all files located here: https://bitwarden.com/help/data-storage/#on-your-local-machine
Once those files are removed and the app is completely uninstalled, you can reinstall it. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
