### ISSUE TITLE
Unable to login. Error: "Failed to fetch".

### ISSUE THREAD

**Issue by xv4t9pxo** [bitwarden/clients#7605]
### Steps To Reproduce

1. Go to 'Login'
2. Enter password.
3. Error thrown. "An error has occured: Failed to Fetch"

### Expected Result

Login!

### Actual Result

"An error has occured: Failed to Fetch"

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. There are a few different scenarios that may cause this error, please contact the support team directly for troubleshooting as we use GitHub issues as a place to track bugs and other development related issues. 

If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
