### ISSUE TITLE
bitwarden keeps trying to reload when on login page.

### ISSUE THREAD

**Issue by WKuva** [bitwarden/clients#7615]
### Steps To Reproduce

1. Download Bitwarden desktop app on windows machine
2. create account/login
3. restart machine
4. open bitwarden and try to lgin.

It will keep reloading the page making it impossible to login.

### Expected Result

no constant refreshing. The constant refreshing makes it impossible to login and access my passwords. The browser extension still works so I can use that in the mean time.

### Actual Result

Constant refreshing making it impossible to login.

### Screenshots or Videos

I tried to record it but the recording function of "snipping tool" of windows also bugged out so I also sent a bug report of that.

### Operating System

Windows

### Operating System Version

Windows 11 version 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.1.0, Shell 27.2.0, Renderer 118.0.5993.159, Node 18.17.1, Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please uninstall the browser desktop, remove all files from this location https://bitwarden.com/help/data-storage/#on-your-local-machine, and reinstall the desktop app. You should be able to log in and view your items successfully after that. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
