### ISSUE TITLE
Cannot create subfolder in folders of own vault 

### ISSUE THREAD

**Issue by icegood** [bitwarden/clients#7627]
### Steps To Reproduce

Extension for chrome proposes for creation only next types of items:
login/card/identity/secure note

### Expected Result

menu for creation of folder is proposed

### Actual Result

no creation of folder menu present

### Additional Context

settings/folders  lacks of this feature as well as web browser and, i suspect, whole backend

### Operating System

Linux

### Operating System Version

ubuntu 23.10

### Web Browser

Chrome

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @icegood,

Thank you for reporting this. I was able to create a new folder and another nested folder via the Chrome extension (2024.1.0); Please make sure that you are following the steps outlined in [this guide](https://bitwarden.com/help/folders/#tab-browser-extension-4YoIIiIv67T68BdhWdAwOM) in order to create a new folder via a Bitwarden browser extension.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by icegood** [comment]
Accordingly to proposed guide you can create only top-level folder. No subfolders.
It was mentioned as: 
"settings/folders lacks of this feature as well"
