### ISSUE TITLE
"Log in with device" not shown after vault gets locked

### ISSUE THREAD

**Issue by septatrix** [bitwarden/clients#7629]
### Steps To Reproduce

1. Log in to the web vault (by any means).
2. Manually lock the vault.

### Expected Result

The option to "Log in with device" should still be offered

### Actual Result

"Log in with device" is not shown, instead only entering the master password is possible.

### Screenshots or Videos

Normal/initial log in:
![image](https://github.com/bitwarden/clients/assets/24257556/14e4574a-dba6-47d3-9f6a-dd839697b85f)

After the vault got locked:
![image](https://github.com/bitwarden/clients/assets/24257556/0b05aa4d-66cd-430b-90a3-4cee23f1f38a)

### Additional Context

This also happens in the extension and the desktop app.

### Operating System

Linux

### Operating System Version

Fedora 39

### Web Browser

Firefox

### Browser Version

121.0.1

### Build Version

2024.0.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @septatrix,

Thank you for your report. Please read [this](https://bitwarden.com/help/unlock-with-pin/#understanding-unlock-vs-log-in) so that you and I would be on the same page with regard to terminology; Now, whilst you can log in using a device, as outlined [here](https://bitwarden.com/help/log-in-with-device/), unlocking can be done using only the master password in the Web App and that is why you're shown that; With regard to desktop clients and browser extensions, you may be able to use a [PIN](https://bitwarden.com/help/unlock-with-pin/) or [biometrics](https://bitwarden.com/help/biometrics/) as well.

If you'd like to be able to also unlock a logged-in Bitwarden client using a device, please consider joining the [Bitwarden community](https://community.bitwarden.com/c/feature-requests/5) and submitting this as a suggestion directly on the feature request page.

We use GitHub to track bugs and other development related issues; This issue here will now be closed.


Thank you again,

**Comment by septatrix** [comment]
> Thank you for your report. Please read [this](https://bitwarden.com/help/unlock-with-pin/#understanding-unlock-vs-log-in) so that you and I would be on the same page with regard to terminology;

I am aware of the difference of log in vs unlock/decrypt though in this case both can be done using the "Log in with device" mechanism. The linked page also states that unlocking with a device is possible and for a fresh log in (i.e. not unlocking a re-locked vault) this also works:

> [...]
> 1. Logging in will always require you to use your master password or [login with device](https://bitwarden.com/help/log-in-with-device/) to gain access to the [account encryption key](https://bitwarden.com/help/account-encryption-key/) that will be needed to decrypt vault data.
>
> [...]

This is also explained under the [How it works](https://bitwarden.com/help/log-in-with-device/#how-it-works) section of the help page about device login. In short: The clients requests login and sends a one-time public key, Bitwarden notifies registered devices and when the user confirms the login on one of those devices they send back the master key encrypted by the key issued by the client.

So please reopen this issue again.

**Comment by septatrix** [comment]
@SergeantConfused Could you please reopen this? As I explained above this is not a request for a new feature but a bug report about an already existing feature being implemented incompletely/inconsistently
