### ISSUE TITLE
New Item window closed without prompting to save when unknowingly clicked the close  

### ISSUE THREAD

**Issue by vijayambattu** [bitwarden/clients#7633]
### Steps To Reproduce

1. Go to 'Bitwarden Desktop'
2. Click on 'Add Item ' Button 
3. Add the entries for the new item
4. Click on 'Close [x] window button'
5. Bitwarden closes without prompting to save the Unsaved item hence losing the credentials

### Expected Result

1. Go to 'Bitwarden Desktop'
2. Click on 'Add Item ' Button 
3. Add the entries for the new item
4. Click on 'Close [x] window button'
5. Bitwarden Should warn about an unsaved item and ask for Saving or discard the changes.

### Actual Result

1. Go to 'Bitwarden Desktop'
2. Click on 'Add Item ' Button 
3. Add the entries for the new item
4. Click on 'Close [x] window button'
5. Bitwarden closes without prompting to save the Unsaved item hence losing the credentials

### Screenshots or Videos

![Screenshot 2024-01-21 194550](https://github.com/bitwarden/clients/assets/126710438/e891c6de-844d-4065-9604-2579bc78b86a)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @vijayambattu,

Thank you for your report. The Bitwarden Community Forums has a [Feature Requests](https://community.bitwarden.com/c/feature-requests/ ) section for submitting, voting for, and discussing such requests.

Please feel free to sign up and to search if this request already exists there; If so, you can vote for it and contribute to any discussions about it and if not, you can create this request there so that it can be properly tracked.

We use GitHub to track bugs and development related issues; This report will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions via the forum.

Thank you again,
