### ISSUE TITLE
Inline auto-fill menu doesn't work reliably

### ISSUE THREAD

**Issue by thericle** [bitwarden/clients#7635]
### Steps To Reproduce

Go to a site with a login form and click inside the username or password field.

### Expected Result

The inline menu or Bitwarden icon should appear inside the field.

### Actual Result

Sometimes the expected result happens, and sometimes nothing happens, even on the same site.

### Additional Context

I know there is a form for sites that don't work, but this is a different issue, where some sites always work, some sites never work, and some sites work sometimes. I haven't found a way to predict this behavior. It seems random.

Some sites that work only sometimes:
proton.me
wattpad.com
pornhub.com
discord.com

I've tried with LastPass (I know) and it works way more reliably. I realize this is a new feature for Bitwarden, but I think it needs some further work.

### Operating System

Windows

### Operating System Version

11 Pro 23H2

### Web Browser

Chrome

### Browser Version

120

### Build Version

2024.1.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different forms depending on the platform:
- mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
- browser extension (this one has an inline auto-fill menu option): https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
