### ISSUE TITLE
Corrupted output solely in sidebar for vault entry after passkey addition.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bitwarden/clients#7641]
### Steps To Reproduce

1.	Visit https://github.com/sessions/trusted-device?return_to=%2Fsettings%2Fsecurity.
1.	Register a new key with Bitwarden.

### Expected Result

This is obvious.

### Actual Result

1.	Error 500.
1.	*	Bitwarden sidebar is unable to display content of https://vault.bitwarden.com/#/vault?search=github.com&itemId=da37ced2-546e-4481-b9f7-accc01382414.
	*	The passkey has actually been registered with GitHub. I verified.

### Screenshots or Videos

1.	**https://addons.mozilla.org/firefox/downloads/file/4211087/bitwarden_password_manager-2024.1.0.xpi**

	1.	**Sidebar**

		This hasn't been able to display the entry since I added the passkey:

		> ![image](https://github.com/bitwarden/clients/assets/42837531/d6cc3b8d-a1c7-466f-8236-9348cecbc554)

		*An example is available at https://github.com/bitwarden/clients/files/14012398/title.HTML.JSON5.zip.*

		Vault sync doesn't change anything.

	1.	**Window**

		Weirdly, this works, however:

		> ![20240122T145355GMT](https://github.com/bitwarden/clients/assets/42837531/bca1598f-b362-48ed-9f89-46fec43b5b07)

1.	**`flatpak install https://dl.flathub.org/repo/appstream/com.bitwarden.desktop.flatpakref; flatpak update com.bitwarden.desktop --commit 'ae93038c697855f1e754bd945fc8eed56d64d24837acf28e7b9ca9cf9a340810'`**

	This works:

	> ![20240122T144817GMT](https://github.com/bitwarden/clients/assets/42837531/66f05e0b-df1b-4413-aeae-62e1c4093156)
	
	*Apologies for the convoluted command. See https://github.com/flatpak/flatpak/issues/3097#issuecomment-1484796387.*

### Additional Context

https://community.bitwarden.com/t/how-can-i-delete-a-passkey-from-a-login-item/59794/33?u=rokejulianlockhart

### Operating System

Linux

### Operating System Version

cpe:/o:opensuse:tumbleweed:20240118

### Web Browser

Firefox

### Browser Version

https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-121.0.1-1.1.x86_64.rpm

### Build Version

https://addons.mozilla.org/firefox/downloads/file/4211087/bitwarden_password_manager-2024.1.0.xpi

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, the passkey saving process gets completed successfully, and the entry gets correctly displayed on Firefox's sidebar. This probably just a visual glitch, I recommend for you to log out from your account completely (not just lock: https://bitwarden.com/help/vault-timeout/#vault-timeout-action) and log back in. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

We use GitHub issues as a place to track bugs and other development related issues. The issue here will be closed.

Thanks!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/7641#event-11571894144

@Greenderella, this needs to be reopened. I've just experienced this issue on another vault entry, one which I haven't modified for some time.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/7641#issuecomment-1909221701

@Greenderella, I just added a passkey to https://vault.bitwarden.com/#/vault?search=onlyfans&itemId=6ceca3d6-55a4-439a-b6bf-af8200d571c0, and exactly the same issue occurred immediately. This needs to be reopened!

**Comment by RokeJulianLockhart** [comment]
@Greenderella, it continues to occur. Why does this remain closed?
