### ISSUE TITLE
logins not being fetch for 'carrd.co'

### ISSUE THREAD

**Issue by postonsundays** [bitwarden/clients#7646]
### Steps To Reproduce

1. Go to 'https://carrd.co/login'
2. Open Bitwarden extension

### Expected Result

Carrd login details are displayed.

### Actual Result

Carrd login details are not displayed and have to be searched for by searching for"carrd" within the popup.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @postonsundays,

Thank you for this report. This is happening because that domain is a [Public Suffix](https://publicsuffix.org/list/public_suffix_list.dat), so not all webpages on that domain would use the same set of credentials or directly relate to the domain. If you'd like the Bitwarden browser extension to match a vault item with that domain, you can change the [URI match rule](https://bitwarden.com/help/uri-match-detection/) within that vault item to Host.

We use GitHub to track bugs and other development related issues; This report will now be closed.

Thank you again,
