### ISSUE TITLE
Desktop application is either stuck on top or behind everything else

### ISSUE THREAD

**Issue by jeremy-rifkin** [bitwarden/clients#7710]
### Steps To Reproduce

When I launch the desktop application it will either be stuck on top of all other windows or behind all other windows.

### Expected Result

The desktop client should behave like a normal window

### Actual Result

When I try to alt tab to it in the later instance it briefly flickers to focus but then goes behind all other windows. This renders the application unusable.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
