### ISSUE TITLE
Desktop client sporadically forgets login details (server url, email address)

### ISSUE THREAD

**Issue by jklpuzo** [bitwarden/clients#7763]
### Steps To Reproduce

Wait ~ a week

### Expected Result

remember my self hosted server url and email address

### Actual Result

it forgets my self hosted server url and email address

### Additional Context

This bug is around for a long time. It always looks like I just installed Bitwarden and after entering my credentials I get the "New Device Logged In From Windows" mail as well.

### Operating System

Windows

### Operating System Version

10 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a file corruption or an Antivirus or anti-malware tools that are preventing Bitwarden from saving your details.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
