### ISSUE TITLE
MacOS - App stuck on the loading icon

### ISSUE THREAD

**Issue by Callisto88** [bitwarden/clients#7769]
### Steps To Reproduce

1. Launch the desktop app

### Expected Result

Application to be running

### Actual Result

Loading icon and got stuck here

### Screenshots or Videos

![Screenshot 2024-02-01 at 18 12 32](https://github.com/bitwarden/clients/assets/5821908/15c265c7-089b-4807-9f11-57ddf413678f)

### Additional Context

Version 2023.12.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture arm64

### Operating System

macOS

### Operating System Version

14.2.1 (23C71)

### Installation method

Mac App Store

### Build Version

Version 2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I recommend uninstalling the Bitwarden desktop application and restarting your device. Once your device has powered on, please download and install the desktop application. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form.

The issue here will be closed.

Thanks!
