### ISSUE TITLE
Bitwarden broken

### ISSUE THREAD

**Issue by Abdillah** [bitwarden/clients#7784]
### Steps To Reproduce

1. Open sidebar Bitwarden on Firefox
2. Fill in with one account until OTP prompt.
3. Open extension popup and login with another account.
4. Tada! The extension broken.

### Expected Result

Either the session out or not.

### Actual Result

The extension broken.

### Screenshots or Videos

![2024-02-02_11-19](https://github.com/bitwarden/clients/assets/3030950/52d4d580-ee08-409d-ab9f-2dbfc040ccbb)

### Operating System

Linux

### Operating System Version

Linux 6.1.73 #1-NixOS

### Web Browser

Firefox

### Browser Version

121.0.1 (64-bit)

### Build Version

2024.1.1 extension broken can't see

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in trying to authenticate into two accounts at once using the same extension session - I'd recommend using the Account Switching feature recently introduced if you wish to switch between accounts.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Abdillah** [comment]
Yes, the broken state only occurred when trying to log in using two different sessions, both can't complete.

Imagine, I have two accounts. Then, I try to log in inside the popup with account #A until the OTP prompt and the popup is disturbed and disappear. I then logged in through the sidebar because I was annoyed that it may be disappear again.

Now with the #B account. Then suddenly my Bitwarden crashes. Must reinstall.
