### ISSUE TITLE
Single Label Domains not getting recognized 

### ISSUE THREAD

**Issue by 4erf** [bitwarden/clients#7792]
### Steps To Reproduce

1. Go to a single label domain website. 
2. Open Bitwarden browser extension
3. Click on Add
4. The URL field should be pre-filled with the current URL
5. Add any user and password and save. 
6. Check if the website is getting recognized by Bitwarden (a little blue square with number 1)

### Expected Result

The site should be recognized and when Bitwarden extension is opened it should offer the option to auto-complete.

### Actual Result

The site is not recognized, the option to auto-complete is not there. User is forced to manually navigate to the entry in the corresponding folder.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/43388082/463db19a-f9ad-43ca-b337-60ed031d0e33)
![image](https://github.com/bitwarden/clients/assets/43388082/583c3954-d9b1-4a7c-b5a7-10061badcd31)

### Additional Context

To access single label domains in my installation of Windows it is required to add a trailing dot `.` to the URL, as can be seen in the screenshot. 

This could be the cause of the Bitwarden parser failing to recognize this URL.

Seems related to #6590. The solution proposed works, but it would be ideal if it works when the URL is being added automatically by Bitwarden. Also, the solution will prevent me from matching different paths.

### Operating System

Windows

### Web Browser

Brave

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
