### ISSUE TITLE
Auto-fill button doesn't pop up on some websites

### ISSUE THREAD

**Issue by argentzz** [bitwarden/clients#7854]
### Steps To Reproduce

1. Go to 'https://www.instagram.com/?hl=en'
2. On username field, bitwarden auto-fill button does not appear
3. After using the auto-fill hotkey (ctrl+shift+L for me) it shows up 

### Expected Result

When opening the page I was hoping to see the auto-fill button right away

### Actual Result

The button doesn't show up until after using the hotkey

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/159413846/33e4b86d-9aba-4c69-bf86-199c826035b6)
![image](https://github.com/bitwarden/clients/assets/159413846/f07e6a44-c739-49be-a6a6-03ad5073a80b)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

Version 121.0.6167.161 (Official Build) (64-bit)

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @argentzz ,

Thank you for this. I tried to replicate this and see what you've highlighted.
The reason you see the autofill icon immediately pop up on some sites depends on whether the application itself auto focuses on these form fields. Instagram is an example of one that does not do this. But sites such as the one attached below,( Facebook.com) have the autofocus on form fields. So this is not an issue with the Bitwarden autofill, but more of a difference in how different sites handle this

<img width="1044" alt="Screenshot 2024-02-08 at 13 23 44" src="https://github.com/bitwarden/clients/assets/152835204/33f7e4e9-035b-4df7-8235-77aeda51bd31">

If you feel like this should be different please check the Bitwarden Community Forums, it has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/
Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.
