### ISSUE TITLE
Auto Fill Does Not Work For an E-Commerce

### ISSUE THREAD

**Issue by bilgilendir** [bitwarden/clients#7904]
### Steps To Reproduce

1. Go to https://www.idefix.com/  
2. Click on [Giriş Yap](https://www.idefix.com/giris) (top right)
3. Try to auto fill
4. It does not work for password field

### Expected Result

It works for both fields

### Actual Result

Works for username but not for password field

### Additional Context

```
<input autocomplete="on" name="password" type="password" id="floating_2bb4348d-87ff-491b-adeb-862e03a92812" class="h-[3.125rem]  bg-[#F5F5F5] pt-[1.375rem] pb-[0.563rem] border-[#29202033] rounded block z-10 px-4 py-[0.969rem] w-full outline-none peer undefined disabled:cursor-not-allowed" placeholder=" " maxlength="" value="">
```

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2024.1.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
