### ISSUE TITLE
Bitwarden re prompts for master password right after unlocking vault, doesn't prompt for touchId

### ISSUE THREAD

**Issue by Tassil0** [bitwarden/clients#7916]
### Steps To Reproduce

1. open bitwarden and unlock vault with master password/touchid
2. try to copy password
3. bitwarden requires to enter master password again

### Expected Result

Open bitwarden and unlock vault with master password/touchid and don't reprompt master password right after. Should use touchId for unlocking on macos, or at least user should be able to disable this.

### Actual Result

Bitwarden redundantly forces me to enter master password again and doesn't let me use touchId.

### Operating System

Windows, macOS

### Installation method

Homebrew, Chocolatey

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. It sounds like you may have master password re-prompt enabled: https://bitwarden.com/help/managing-items/#protect-individual-items

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
