### ISSUE TITLE
Latest update 2024.2.0 suddenly causes selection of wrong login when there are multiple logins for the same domain.

### ISSUE THREAD

**Issue by troy-work** [bitwarden/clients#7949]
### Steps To Reproduce

Having multiple logins for the same domain, but with different subdomains.
1. Go to 'Log In Page'
2. Click on 'CTRL-SHIFT-L'
The wrong login started being used suddenly on 2/13/2024
Prior to this it worked.
When I examined each login, now I suddenly was missing the second login. Where there had been two, now there was only the first ones that had been entered.
To make it work, I had to switch from the default detection to the begins with detection.
I don't know if the last update also had a DB migration, but something caused me to lose the second logins which I had been using form many months.

### Expected Result

I expect to still have the logins I had been using for months, and to have the correct credentials entered.

### Actual Result

I no longer had the second logins. The first 'wrong' credential was entered.

### Additional Context

Example urls.
int.buildserver.com/login     (had both the Administrator login and MyUser login)
oct.buildserver.com/login     (had both the Administrator login and MyUser login)
Four logins in all to the same domain, two per subdomain.

### Operating System

Windows

### Operating System Version

OS Name	Microsoft Windows 10 Pro Version	10.0.19045 Build 19045

### Web Browser

Chrome

### Browser Version

Version 121.0.6167.161 (Official Build) (64-bit)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by troy-work** [comment]
BTW, changing from default detection to begins with detection allowed this to function again. I did also have to 'cycle' the logins by using 'CTRL-SHIFT-L' twice.
So, it is working again, albeit it differently----and only after I had to enter the 'missing' logins. (why I suspect there was possibly a DB migration witht he update)

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I'm glad you've gotten it up and running!

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.
Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.
Thanks!
