### ISSUE TITLE
Version 2024.2 - multiple Bitwarden accounts disappear/removed even without switching in the desktop app

### ISSUE THREAD

**Issue by FBR-RLNS** [bitwarden/clients#7950]
### Steps To Reproduce

Since the last update bitwarden randomly removes bitwarden accounts.
I have/had 3 accounts linked in the Bitwarden app

- a self hosted company account
- a bitwarden.com account with a @gmail.com account
- a bitwarden.com account with a @<company>.<be/com/.. > account

Every day since the upgrade, 1 or 2 accounts of the 3 accounts are randomly removed from the desktop app. 
Even when inactive - without switchen the accounts - they disappear or are removed and I have to re-add them.
But they disappear the same day.
The software has been removed/reinstalled, but that doesn't seem the resolve the issue.

### Expected Result

I expect to be able to use the 3 account in the desktop app and not be removed/disappear

### Actual Result

Every day since the upgrade, 1 or 2 accounts of the 3 accounts are randomly removed from the desktop app. 
Even when inactive - without switchen the accounts - they disappear or are removed and I have to re-add them.
But they disappear the same day.

### Operating System

Windows

### Operating System Version

Windows 11 - 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

 Version 2024.2.0 Shell 28.1.3 Renderer 120.0.6099.199 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @FBR-RLNS 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or vault time out settings. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
