### ISSUE TITLE
Inline autofill stops working if you disable both "Ask to add login" and "Ask to update existing login"

### ISSUE THREAD

**Issue by MooseExplorer637** [bitwarden/clients#7980]
### Steps To Reproduce

1. Open Bitwarden browser extension
2. Click on Settings
3. Scroll down to Options
4. Disable "Ask to add login" and "Ask to update existing login"

### Expected Result

The user should be able to disable both "Ask to add login" and "Ask to update existing login" in Bitwarden browser extension settings without making the inline autofill stop working.

### Actual Result

If you disable both "Ask to add login" and "Ask to update existing login" in Bitwarden browser extension settings, inline autofill will stop working completely. If you enable either one of these options, the inline autofill begins to work as expected.

### Operating System

macOS

### Operating System Version

macOS Sonoma 14.3.1

### Web Browser

Safari, Firefox, Brave

### Browser Version

Safari: 17.3.1 Firefox: 122.0.1 Brave: 1.62.165

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @MooseExplorer637

Thank you for bringing this to our attention. What you are describing appears to be the intended behavior of the software. 

The inline autofill uses the said functionality to save items and add new items into the vault; you can still use the [context menu](https://bitwarden.com/help/auto-fill-browser/#context-menu) and [keyboard shortcut](https://bitwarden.com/help/auto-fill-browser/#keyboard-shortcuts) for autofill purposes. 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
