### ISSUE TITLE
Bitwarden Send Text - Field doesn't allow 1000 characters

### ISSUE THREAD

**Issue by SirecTechnologies** [bitwarden/clients#7985]
### Steps To Reproduce

1. Create a new Text Send.
2. Paste 700 characters.
3. Click Save.

### Expected Result

Send is Saved and a link is generated.

### Actual Result

Error message appears saying "The field Text exceeds the maximum encrypted value length of 1000 characters".

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/123199175/1251cc3e-299d-445a-9943-4e798866920a

### Operating System

Windows

### Operating System Version

Windows 11 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.1.0 Shell 27.2.0 Renderer 118.0.5993.159 Node 18.17.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. As clarified by @bwbug, this is the expected behaviour and it's detailed [here](https://bitwarden.com/help/create-send/) under Type > Text. If you'd like Bitwarden Send to support larger Text Sends, please feel free to submit this as an improvement suggestion in the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/pm-feature-requests/55).

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you all again,
