### ISSUE TITLE
Inline auto-fill menu does not appear until extension is opened first

### ISSUE THREAD

**Issue by 4fosaefp** [bitwarden/clients#8036]
### Steps To Reproduce

1. Go to any website's login page
2. Click on the username or password field

### Expected Result

Auto-fill menu appears beneath the selected field

### Actual Result

No auto-fill menu appears

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/115563922/eac0bb88-ac3d-41b8-8d13-b9bab0e97f85

### Additional Context

After I open the Bitwarden extension, then click on the field, the auto-fill menu will appear. If I refresh the page, the issue occur again. Please see the video.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

122.0.1

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of Inline AutoFill. https://bitwarden.com/help/auto-fill-browser/#enable-the-inline-auto-fill-menu
https://bitwarden.com/help/auto-fill-browser/#use-the-inline-auto-fill-menu

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located at our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by 4fosaefp** [comment]
I already followed the guide to enable inline autofill. That's why I believe this is a bug. I apologize if this is the wrong place to report it.
I'm not the only one who experience it either. There's a [reddit comment](https://www.reddit.com/r/Bitwarden/comments/1awfss6/comment/krhae0k/?utm_source=share&utm_medium=web2x&context=3) mentioning the same issue

**Comment by misaif** [comment]
open "Ask to add login" and "Ask to update existing login"

**Comment by 4fosaefp** [comment]
> open "Ask to add login" and "Ask to update existing login"
> 
> #7980

This solves it, thanks!
