### ISSUE TITLE
Inline field does not show until the Bitwarden extension is opened

### ISSUE THREAD

**Issue by Rytoxz** [bitwarden/clients#8043]
### Steps To Reproduce

1. Go to website with autofill URL set
2. Click on login field
3. Inline autofill does not show
4. Click on Bitwarden extension icon
5. Click back on login field
6. Inline autofill does show

### Expected Result

Inline autofill should show on all login prompts when the Bitwarden extension is unlocked but has not been clicked on.

### Actual Result

The inline autofill does not show until it is clicked even if unlocked.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/134399545/89f4c4b0-ee5e-412a-80d8-cf3afbdffcda

### Additional Context

The inline field doesn't show until the Bitwarden extension is opened (even when unlocked) and doesn't persist across a site refresh or other sites. Pinning and unpinning the extension icon also makes no difference. Both inline field options behave the same. Uninstalling and reinstalling the extension does not fix.

### Operating System

Windows, macOS

### Operating System Version

Windows 22631.3155
MacOS 14.3.1

### Web Browser

Firefox

### Browser Version

Firefox 123

### Build Version

2024.2.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,
I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration either in your browser or other extensions that might affect this. You can also have a look at using the autofill shortcuts(https://bitwarden.com/help/auto-fill-browser/#keyboard-shortcuts)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
Thanks!

**Comment by cagonzalezcs** [comment]
Wanted to add on to the support team response.

So I think I know why this might be happening, and likely it's because you do not have the options to "Ask to add login" or "Ask to update existing login" set within your extension.

Those shouldn't be requirements for triggering the inline menu though, and the resolution for this should be relatively simple to implement and test.

I'll keep this ticket closed, since the resolution for this issue is known by the autofill team, but please know that a fix for this is being worked on. I'll likely tag this ticket in the PR once we have the fix in review.

**Comment by cagonzalezcs** [comment]
Sounds good, glad to hear that resolve the issue for now.

A fix for this is now in code review - https://github.com/bitwarden/clients/pull/8050
