### ISSUE TITLE
`bw list items` does not include fields

### ISSUE THREAD

**Issue by jeffa5** [bitwarden/clients#8094]
### Steps To Reproduce

1. Run `bw list items`
2. Observe that records which should have a fields key do not

### Expected Result

Items that have fields set in other clients should have those fields visible in this output.

### Actual Result

The fields are not visible.

### Operating System

Linux

### Operating System Version

NixOS

### Shell

Zsh

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could be due to running 2023.12.0 - I was not able to replicate this in 2024.2.0.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jeffa5** [comment]
It does seem fixed in 2024.2.0, thanks!
