### ISSUE TITLE
No lock of Bitwarden after hibernation OS X

### ISSUE THREAD

**Issue by hirschferkel** [bitwarden/clients#8126]
### Steps To Reproduce

Bitwarden will not lock the browser add-on in Firefox OS X after hibernation mode. It will just be active. I would call this a serious bug.
Seems like the timout will not check for current time on the running machine.

<img width="379" alt="Bildschirmfoto 2024-02-28 um 08 50 13" src="https://github.com/bitwarden/clients/assets/16016422/51b654bc-7ca1-430a-a323-b6c0763bb22f">

### Expected Result

It should lock after e.g. 15 minutes in any case, as soon as the absoulte time hast passed the Bitwarden set timeout.

### Actual Result

Bitwarden still active after hours of inactivity in hibernation mode.

### Operating System

macOS

### Operating System Version

12.7.2

### Web Browser

Firefox

### Browser Version

115

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @hirschferkel ,


Thank you for reaching out! 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption or conflict within your browser environment.  It would be worth uninstalling and reinstalling Bitwarden from your machine once more, this time deleting all local files manually: https://bitwarden.com/help/data-storage/#on-your-local-machine.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.

Thanks!

**Comment by hirschferkel** [comment]
@daniellbw Thanks, I'll give it a try.

**Comment by hirschferkel** [comment]
It did not work out. On two different machines lockout in hybernation does not work.
