### ISSUE TITLE
Error with Sony login : breaks pop-up form

### ISSUE THREAD

**Issue by Draky50110** [bitwarden/clients#8149]
### Steps To Reproduce

Hello.

When on PlayStation store (https://store.playstation.com) and click on login link on up right, it goes to https://my.account.sony.com/sonyacct/signin/?duid=0000000700090100e550ed93e482e7ccd24a1f9a0a91e064e0948a1b023ff2d58eb7155f0ee191f8&response_type=code&client_id=e4a62faf-4b87-4fea-8565-caaabb3ac918&scope=web%3Acore&access_type=offline&state=e535b73665cd4978eeba8a4c745cc692356810f7a1f83aaf447182f4fa974d05&service_entity=urn%3Aservice-entity%3Apsn&ui=pr&smcid=web%3Astore&redirect_uri=https%3A%2F%2Fweb.np.playstation.com%2Fapi%2Fsession%2Fv1%2Fsession%3Fredirect_uri%3Dhttps%253A%252F%252Fstore.playstation.com%252Ffr-fr%252Fpages%252Flatest%26x-psn-app-ver%3D%2540sie-ppr-web-session%252Fsession%252Fv5.35.0&auth_ver=v3&error=login_required&error_code=4165&error_description=User+is+not+authenticated&no_captcha=false&cid=92eb4860-0a01-4f9d-a5b8-a9df54fe2a3b#/signin/input/id and shows a pop-up form (JS ?).

If BitWarden browser extension is enabled, an error is displayed when you click inside ID (email) field and you can't login.
You must disable the browser addon to login with the form.

Maybe same kind of problem than #8049 ?

### Expected Result

Login page + login action possible...

![image](https://github.com/bitwarden/clients/assets/1558487/a6948e92-5664-4eab-93fa-351bb1e9b2e8)

### Actual Result

Error : 

![image](https://github.com/bitwarden/clients/assets/1558487/49e333bf-cd85-4312-8ef3-b6ba0ac5f8ca)

### Operating System

Windows

### Operating System Version

Not relevant

### Web Browser

Firefox

### Browser Version

Not relevant (up to date one)

### Build Version

2024.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by Draky50110** [comment]
Thanks a lot for letting me know about this.
Will follow the next update :)
