### ISSUE TITLE
unlock with pin browser extension

### ISSUE THREAD

**Issue by abdodz1234** [bitwarden/clients#8197]
### Steps To Reproduce

unlock with pin on browser restart not  working  in firefox  only master password

### Expected Result

should work

### Actual Result

should work

### Operating System

Linux

### Operating System Version

archlinux

### Web Browser

Firefox

### Browser Version

123.0

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration in your Vault Timeout Options: https://bitwarden.com/help/vault-timeout/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
