### ISSUE TITLE
ADP 2 step login changes username on autofill

### ISSUE THREAD

**Issue by bradlis7** [bitwarden/clients#8212]
### Steps To Reproduce

1. Go to https://workforcenow.adp.com/theme/index.html
2. Autofill User ID.
3. Click Next
4. Password will not autofill.

### Expected Result

I expect password to automatically fill if password field is added dynamically.

### Actual Result

I can't autofill at all. Bitwarden doesn't seem to know that the password field was added.

### Additional Context

A month ago, it would autofill, but if you used Ctrl-L shortcut on the username, hit enter, and then use Ctrl-L again, it would use the next username in the list, and ADP would hide the password box. If I have multiple logins for this site, I would have to use the mouse to select the same login. It would be nice if this worked better.

### Operating System

Windows

### Operating System Version

Windows 10 Pro Version 22H2 19045.4046

### Web Browser

Firefox

### Browser Version

124.0b7

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bradlis7** [comment]
I'm also seeing issues on other sites where the password field is added dynamically as well.

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by jprusik** [comment]
A note from work over at https://github.com/bitwarden/clients/pull/16901

The ADP site will always kick you back to the first step (hide the password field) if you alter the username in any way (even if you replace it with the same value). You can test this behaviour manually, without any password manager:

https://github.com/user-attachments/assets/6caadd9c-7027-415e-bf74-805801239680

(The ADP login is basically saying "you have a different username? go back to the first step"; we don't have any control over that behaviour)
