### ISSUE TITLE
Safari extension spinning circle

### ISSUE THREAD

**Issue by hoonkai** [bitwarden/clients#8213]
### Steps To Reproduce

1. Open Safari
2. Click on extension button in Safari

### Expected Result

The usual login UI should appear

### Actual Result

Spinning circle persists

### Screenshots or Videos

![Screen Shot 2024-03-06 at 2 44 30 am](https://github.com/bitwarden/clients/assets/14197204/ea7f8b93-4e25-4914-bb13-591c2d9cb4ae)

### Operating System

macOS

### Operating System Version

11.6.1

### Web Browser

Safari

### Browser Version

14.1.2

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Have you tried uninstalling the extension and reinstalling it to see if it makes a difference? There are some other troubleshooting steps we can look into but will need to gather some more information privately.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
