### ISSUE TITLE
windows hello

### ISSUE THREAD

**Issue by ali-agh** [bitwarden/clients#8259]
### Steps To Reproduce

4. Click on '...'

### Expected Result

windows hello does not work again 

### Actual Result

windows hello does not work again 

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.2.1 Shell 28.2.4 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @ali-agh ,

I attempted to reproduce this issue and was unable to do so. I think your error could have its origin in a misconfiguration. 
Could you please share a screenshot with details on what you are clicking such as '...'

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
