### ISSUE TITLE
Bitwarden permanently erases data when the application auto-locks

### ISSUE THREAD

**Issue by zwsren435** [bitwarden/clients#8276]
### Steps To Reproduce

1) Make a vault item, but don't save it
2) Wait for the vault to time-out
3) Any information in that item is permanently deleted

This bug encourages users to increase the auto-lock period, which has serious and substantial security implications for users who use Bitwarden in public (i.e. almost all of them)

### Operating System

Every Bitwarden client has this issue

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
