### ISSUE TITLE
Javascript imports from windows.net

### ISSUE THREAD

**Issue by ckujau** [bitwarden/clients#8290]
### Steps To Reproduce

While trying to upload attachments to an item, the following message was printed:
```
An error has occurred.
NetworkError when attempting to fetch resource. 
```

The developer console logged:

```
Blocked by NoScript
https://bitwardenxx5keu3w.blob.core.windows.net/attachments-v2/....
```

Of course, explicitly allowing `.windows.net` made the attachment upload succeed, but I'm kinda worried that Bitwarden fetches scripts from a 3rd party site here. Can't this be served from the `bitwarden.com` domain?

### Expected Result

Bitwarden should only load scripts or objects from `bitwarden.com`

### Actual Result

Bitwarden loads scripts from a `windows.net` domain.

### Operating System

Linux

### Operating System Version

Fedora 39

### Web Browser

Firefox

### Browser Version

123.0.1

### Build Version

2024.2.5

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaliX-Dev** [comment]
I think that's a completely normal behavior, since Bitwarden use Azure as their storage backend and seems to use it as their blob provider service too.
https://bitwarden.com/help/data-storage/
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction

For the second link, go to the Storage accounts section, you'll find a verily similar link example.

**Comment by ckujau** [comment]
For some general purpose application I wouldn't mind that much, but for a password manager I think that's an isssue. There are no guarantees that this blob of software from `windows.net` will be the same tomorrow. (Yes, someone could take over the `bitwarden.com` website and replace stuff too, but at that point we have bigger problems.)

**Comment by Hinton** [comment]
HI @ckujau,

The application is not loading javascript from the `windows.net` domain. But rather directly uploading and downloading attachments to azure, this allows for more efficient handling of attachments improving speed and the size that can be handled. Feel free to confirm this yourself by looking at the [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) rules of the website. `windows.net` is only allowed under `connect-src` not `script-src`.

The attachments themselves are encrypted prior to upload, and part of the decryption process is to validate the mac which ensures the content cannot change.

Closing this since no javascript can be imported from windows.net.
