### ISSUE TITLE
Auto-fill for a custom field with a specific name is not working

### ISSUE THREAD

**Issue by ioqy** [bitwarden/clients#8300]
### Steps To Reproduce

Since this field is on an internal website that can not be reached from the internet I can't name the URL. But setting the `id` of the username field with the developer tools on different login pages (like https://github.com/login or https://accounts.google.com) has the same result. So the bahaviour does not seem to be exclusive to the internal website, but has something to do with the value of the `id`.

1. Add a custom field with the name `pvBody_PageTemplate_innerHolder_ctrlLogon_txtUsername` and any value to an item in the vault.
2. Go to a login page like https://github.com/login or https://accounts.google.com and change the `id` of the username field to `pvBody_PageTemplate_innerHolder_ctrlLogon_txtUsername` with the developer tools of the browser.
3. Use auto-fill on the page

### Expected Result

The field with the `id` value `pvBody_PageTemplate_innerHolder_ctrlLogon_txtUsername` to get filled with the value of the custom field.

### Actual Result

The field with the `id` value `pvBody_PageTemplate_innerHolder_ctrlLogon_txtUsername` gets filled with the normal username.

On the internal website the password is also not filled with auto-fill and auto-fill on page load is not working at all.

### Additional Context

The auto-fill with the custom field `pvBody_PageTemplate_innerHolder_ctrlLogon_txtUsername` (and password) worked until a few weeks ago.

Also auto-fill on page load was working on the internal page until a few weeks ago.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Microsoft Edge, Firefox

### Browser Version

Firefox: 123.0.1 and Edge: 122.0.2365.80

### Build Version

2024.2.0 and 2024.2.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@ioqy 

Thank you for the bug report, this issue is known and will be resolved with the merging of https://github.com/bitwarden/clients/pull/8117 

The problem comes as a result of a fix which attempts to invalidate search fields based on textual metadata context within the field. Your field contains a string value within the id that incorrectly invalidates the field as search input.

This fix will be coming in an upcoming release of the extension. Closing this thread for now, but please feel free to continue discussion as necessary.
