### ISSUE TITLE
`Search Send` and `Search vault` exists but `Search tab` cannot be found

### ISSUE THREAD

**Issue by bilogic** [bitwarden/clients#8303]
### Steps To Reproduce

![image](https://github.com/bitwarden/clients/assets/946010/aa7e1c91-802b-497e-9e2d-28f2158d6792)
![image](https://github.com/bitwarden/clients/assets/946010/d905c853-3d53-4d39-9f4c-25992b652ff8)
![image](https://github.com/bitwarden/clients/assets/946010/8665489f-ff63-412c-9f2b-c58590523fa6)

### Expected Result

The search bar should be `Search tab` when under `Tab`

### Actual Result

When under `Tab`, search bar shows `Search vault` 

### Operating System

Windows, macOS

### Operating System Version

Windows 10 and Sonoma

### Web Browser

Chrome

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
