### ISSUE TITLE
Search word doesn't search within notes

### ISSUE THREAD

**Issue by valtoree** [bitwarden/clients#8329]
Hi so when i search for a word or some numbers it doesn't pickup the information I put in the notes section within the login entries.
Can we get this?
Or is it a bug? 🤷
Thanks for all your awesome work. 🙏

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misunderstanding of the basic versus full-text search, as covered in this knowledge article: https://bitwarden.com/help/searching-vault/#basic-search

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
