### ISSUE TITLE
Desktop application stop to work on iMac Intel

### ISSUE THREAD

**Issue by CBBD-Manuel** [bitwarden/clients#8331]
### Steps To Reproduce

Just open Bitwarden application

### Expected Result

The login Window

### Actual Result

A black & White window with all greyed out menus.

### Screenshots or Videos

<img width="1956" alt="Capture d’écran 2024-03-14 à 11 30 40" src="https://github.com/bitwarden/clients/assets/52541341/311aa622-29da-4d01-aa44-c7d1d747bca7">
<img width="515" alt="Capture d’écran 2024-03-14 à 11 30 54" src="https://github.com/bitwarden/clients/assets/52541341/57bd8a90-24a2-43f0-a5f2-33079b16cc7e">
<img width="799" alt="Capture d’écran 2024-03-14 à 11 31 06" src="https://github.com/bitwarden/clients/assets/52541341/a606dbfc-cb75-4760-92d0-b559da1108a2">

### Operating System

macOS

### Operating System Version

12.7.4   iMac (Retina 5K, 27-inch, Late 2015)

### Installation method

Mac App Store

### Build Version

Version 2024.3.0 (21897)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there!

We are aware of this and are currently investigating it. 

To address the issue you're experiencing with the Bitwarden macOS desktop app, please follow these steps:

- Close the Bitwarden desktop app if it's open.
- Uninstall the existing Bitwarden app from your system. You can do this by dragging the application icon to the Trash and emptying the Trash.
- Download and install the standalone version from here: https://vault.bitwarden.com/download/?app=desktop&platform=macos&variant=dmg
- Launch the Bitwarden app from your Applications folder after installation.

Please note that this version doesn't support the Safari extension. However, you can use the Bitwarden extension in Chrome, Firefox, Edge, Brave or any other supported browser as an alternative: https://bitwarden.com/download/#downloads-web-browser

You can track the progress of this issue here: https://github.com/bitwarden/clients/issues/8003  

We're actively investigating and hope to resolve it in an upcoming release.

This issue will now be closed.

Thanks!
