### ISSUE TITLE
Unable to sign in to Discord with Established Security Key on Edge & Arc browser

### ISSUE THREAD

**Issue by ne0-ai** [bitwarden/clients#8352]
### Steps To Reproduce

1) Open Discord.com on any chromium based browser like Arc or Microsoft Edge
2) Try signing on, Discord recognizes that you can sign in with Security Key
3) Try signing in with Security Key saved in Extension

### Expected Result

Sign in should be successful.

### Actual Result

Get an error "Security Key Authentication Failed"

### Screenshots or Videos

![Discord Error](https://github.com/bitwarden/clients/assets/77515993/28559d14-ebab-4f96-bfca-ab3e42760d63)

### Additional Context

This used to work well, started getting this error since last two days. Passkey was created on March 2nd and has worked well until day before yesterday. I get this issue on both Microsoft Edge and Arc.
Looks like security key still works in Safari. So the issue seems to be with Chromium based browser.

### Operating System

macOS

### Web Browser

Microsoft Edge

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Have you confirmed that your browsers and extensions where this issue is occurring are fully up to date? 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by coroiu** [comment]
@jtodddd I was able to reproduce this by:

(using Chrome 122.0.6261.129)

- Manually downloading `2024.2.0` 
- Creating passkey
- Manually upgrade to `2024.2.1` 
- Try to use passkey

Currently troubleshooting...

**Additional info**
I was not able to reproduce the issue if the passkey is created in `2024.2.1`. I have not tried updating to `2024.3.0`

**Comment by coroiu** [comment]
**Solution**
We recommend that users overwrite any passkeys that stop working with a new passkey from the app or service. If you are not able to log in to your account without your passkey (don’t have any backup codes saved or any alternative 2FA method registered) you can downgrade you browser extension to version 2024.2.0. Please contact support if you need help with this!

**Conclusion**
The error is the result of how Discord is built to react to the changes that we made in `2024.2.01` to properly describe our passkeys with the  `backupEligibility` flag (i.e. marking them as synced). These flags are part of the draft for the upcoming L3 version of the `WebAuthn` specification, and have been added as part of our effort to keep up to date with the latest specification. Sadly the change turns out to be incompatible with Discord.

Unfortunately we cannot roll back this change because that would invalidate passkeys created after `2024.2.1`. The passkeys would also be incompatible with upcoming iOS and macOS integrations.

**Comment by escape0707** [comment]
@coroiu I'm getting no passkey found for this application error now even if the passkey is created and registered yesterday. Is it related?

**Comment by coroiu** [comment]
@escape0707 hard to say without more info, but I'd say the there is a low probability that they are related. This issue was more of limitation on Discords side, while "passkey not found" is generally due to something on the Bitwarden side. I recommend creating a new issue with more info so we can try to reproduce it!

**Comment by LinuxMeow** [comment]
I had problem using my Yubikey to log in from my web browser. However, after I disabled Bitwarden temporarily, it worked as expected. In case someone is facing the same problem, until better solution or actual fix is made, just disable quickly bitwarden extension and log in. If this is your specific case. If not I guess something else is causing the problem for you.

**Comment by BakedCrossiant** [comment]
Can anyone from the Bitwarden side reopen this issue, it is still present in the discord web app.
