### ISSUE TITLE
Unlock with biometrics occasionally fails on Chrome Extension 2024.2.1

### ISSUE THREAD

**Issue by solzard** [bitwarden/clients#8399]
### Steps To Reproduce

1. Log in to the same single account on both Chrome Extension and the Desktop app.
2. Enable `Unlock with biometrics` on Chrome Extension.
3. Enable `Allow browser integration` on the Desktop app.
4. Enable `Require verification for browser integration` on the Desktop app.
5. Lock a vault on the browser.
6. Try to unlock on browser with biometrics.

### Expected Result

Unlock the vault.

### Actual Result

The Chrome extension fails to unlock and shows the message below.
>Account missmatch
>The desktop application is logged into a different account. Please ensure both applications are logged into the same account.

### Screenshots or Videos

![Screenshot 2024-03-20 at 20 52 37](https://github.com/bitwarden/clients/assets/29563481/0cb8866b-6caa-40e3-b126-12cd136fa438)

### Additional Context

I'm experiencing an issue with unlocking with biometrics feature.

The problem began after I updated the extension to version 2024.2.1. 
Everything was working smoothly before the update, and the issue doesn't occur every time. 
Sometimes, after attempting to unlock my vault a few times—ranging from once to several days—it refuses to unlock. 

Temporarily fixing the issue by disabling and then re-enabling the extension, or locking and then unlocking the desktop app, only works for a short period before the problem reoccurs.

Although the error message says `The desktop application is logged into a different account`, I have only one account logged in.

I've attempted several solutions, but unfortunately, none have resolved the issue:
- Logging out of the extension
- Logging out of the desktop app
- Deleting the extension
- Deleting the desktop app
- Clearing all system cache using OnyX

Here are the details of my system setup:
- OS: macOS 13.6.5 (22G621)
- Desktop app: Version 2024.3.0
- Chrome extension: Version 2024.2.1
- Browser: Brave Browser Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (arm64)

### Operating System

macOS

### Operating System Version

13.6.5 (22G621)

### Installation method

Mac App Store

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
I attempted to reproduce your issue and was unable to do so. This error typically happens when the Desktop application is logged into a different account.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
