### ISSUE TITLE
Auto-fill doesn't remember last used login

### ISSUE THREAD

**Issue by casualsailo** [bitwarden/clients#8425]
### Steps To Reproduce

This is using the windows desktop browser extension

1. Have at least 2 logins for any website. Let's assume first login with username **apple@email.com**, and second login with username **banana@email.com**
2. Use username **banana@email.com** for the website
3. Lock the vault
4. Press Ctrl + Shift + L to activate auto-fill
5. A pop-up will prompt you to enter the PIN/password to unlock the vault
6. Type in PIN/password, and press enter on the keyboard
7. The extension auto-fills username **apple@email.com**, which was NOT the last used login

### Expected Result

The extension should be auto-filling with the last used login (banana@email.com), but it did not

### Actual Result

The extension auto-fills the wrong login

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
