### ISSUE TITLE
Brave Browser ignoring vault timeout

### ISSUE THREAD

**Issue by johanjohan** [bitwarden/clients#8426]
### Steps To Reproduce

Setting the vault timeout to N minutes changes nothing: the vault remains open all the time even after a browser restart.
This is a serious security issue.

It closes as expected in Firefox and in the Desktop app.

### Expected Result

vault should lock

### Actual Result

vault stays wide open

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/6679464/83a300ad-8ed6-45d6-94cb-9e9dcc797bbb)

### Operating System

Windows

### Operating System Version

OS Name	Microsoft Windows 10 Pro Version	10.0.19045 Build 19045

### Web Browser

Brave

### Browser Version

Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)

### Build Version

2024.2.1 server 2024.2.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please check to see if there are any available updates in the Brave browser, and apply them. If you are still experiencing an issue, please contact Bitwarden support and we'll be happy to assist further.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!

**Comment by johanjohan** [comment]
@TroyBW Thank you. The issue occurs after you undock the plugin window from the browser ("pop out to a new window"). I contacted support. It stays unlocked on my system which may expose it. If I didn't perceive it as an issue, I wouldn't have raised the matter on GitHub.
