### ISSUE TITLE
Unable to access items of the "Unassigned" collection of an organization

### ISSUE THREAD

**Issue by tryauuum** [bitwarden/clients#8446]
### Steps To Reproduce

I accidentally used a wrong collection ID when moving items from one collection to another. The result was that the items are now not in any collection.

But I don't have a way to access them via cli anymore to solve my mistake 

### Expected Result

I would expect bw cli to not move items to an invalid collection id in the first place and to return an error instead

Alternatively, I would like a way to see the items in the unassigned collection via bw cli.

### Actual Result

Can't get the items from the unassigned collection!

I've tried this:
```
bw list items --organizationid 44179f4f-61c8-46a4-b56a-a4f6a34b555c --collectionid null 
```
but it returns something weird

### Operating System

Linux

### Operating System Version

ubuntu 22.04

### Shell

Bash

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Are you able to access your unassigned items by using the following command? 
`bw list items --organizationid YOUR-ORG-ID --collectionid unassigned`

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
