### ISSUE TITLE
TOTP code *and key* visible in cleartext on every item in web vault.

### ISSUE THREAD

**Issue by NicholasConrad** [bitwarden/clients#8471]
### Steps To Reproduce

1. Go to 'any web vault item with a TOTP key entered'

### Expected Result

The "TOTP Key" field allows anyone with its' contents to generate an arbitrary number of valid TOTP codes, thereby giving an attacker complete control over one factor in an MFA security scheme. It should therefore be treated with the same level of protection as the first security factor, the actual "Password" field, e.g., obscured by default to prevent shoulder surfing.

The TOTP code itself is also a security factor for MFA authentication, albeit a temporary one, so it too should be obscured on-screen by default.

### Actual Result

The TOTP code and TOTP Key fields are displayed prominently on the web-vault "Item" record in cleartext.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Microsoft Edge

### Browser Version

122.0.2365.92 (Official build) (64-bit)

### Build Version

Web vault

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
