### ISSUE TITLE
Website refuses identification when bitwarden plugin is installed in browser

### ISSUE THREAD

**Issue by GregSNaoned** [bitwarden/clients#8493]
### Steps To Reproduce

1. Go to https:\\www.labanquepostale.fr
2. Click on connect account
3. Input ID and pswd
4. Click on coonect

### Expected Result

Access to personal spaece

### Actual Result

Identification error

### Screenshots or Videos

![unnamed](https://github.com/bitwarden/clients/assets/109293629/00034583-1887-4618-8b0a-7868dd5fa61c)

### Additional Context

Tried it on several computers with Firefox, Chrome and Edge...  And I always get the same error

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

124.0.1

### Build Version

124.0.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by GregSNaoned** [comment]
Hello,
Of course this may not be an easy to reproduce bug, since you need to have an account to reproduce it.
Nonetheless, it seems that the issue is linked to autofill, the community came up with this turnaround : 
[https://community.bitwarden.com/t/website-refuses-identification-when-bitwarden-plugin-is-installed-in-browser/64954/3](https://community.bitwarden.com/t/website-refuses-identification-when-bitwarden-plugin-is-installed-in-browser/64954/3)
But a turnaround is not a solution ;-)
