### ISSUE TITLE
Login broken on chrome

### ISSUE THREAD

**Issue by ztefanie** [bitwarden/clients#8523]
### Steps To Reproduce

1. Go to 'https://vault.bitwarden.com/#/login'
2. Enter correct login data
3. get error message
4. `{
    "error": "invalid_grant",
    "error_description": "invalid_username_or_password",
    "ErrorModel": {
        "Message": "Username or password is incorrect. Try again.",
        "Object": "error"
    }
}`

### Expected Result

Login should be successful.

### Actual Result

Error saying username/password is wrong.

### Additional Context

Tested on Firefox with the same login data, works as expected.

### Operating System

Linux

### Web Browser

Chrome

### Browser Version

Version 123.0.6312.86 (offical build) (64-Bit)

### Build Version

Version 123.0.6312.86 (Offizieller Build) (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @ztefanie ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a caching issue - could you try a hard refresh using Ctrl + F5 together.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ztefanie** [comment]
I still have this error, now on another linux machine. Cannot login with chrome, works in firefox.
