### ISSUE TITLE
Web export of organization vault is empty

### ISSUE THREAD

**Issue by CalebBurton** [bitwarden/clients#8530]
### Steps To Reproduce

1. Open the web vault and go to the export page at https://vault.bitwarden.com/#/tools/export
2. Change the "Export from" option to an organization
3. Choose a format (tested on unencrypted JSON and CSV)
4. Click to confirm format, enter master password, and export
5. Open the newly exported file

### Expected Result

The file contains entries

### Actual Result

The file is empty (for CSV) or the following object (for JSON)

```json
{
  "encrypted": false,
  "collections": [],
  "items": []
}
```

### Additional Context

The export works fine from the CLI. I see hundreds of entries when running `bw export --organizationid $BW_ORG_ID --raw --format json`.

It also works as expected when I go through the export from the Organization admin panel at `https://vault.bitwarden.com/#/organizations/<ORG_ID>/settings/tools/export`

### Operating System

Linux

### Operating System Version

nixOS 23.11

### Web Browser

Firefox

### Browser Version

124.0.1

### Build Version

Unclear. There is no version shown on the webpage, even when searching the HTML using the browser dev tools.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @CalebBurton and thank you for your report.

This is expected behaviour as exporting from an organization within the Password Manager will only contain collections that you have CanManage access to.
As you mentioned a full organizational export will be executed via the Admin Console.

Details can be found here: https://bitwarden.com/help/export-your-data/#export-an-individual-vault (Point 2)

I hope that clarifies it, if you have any follow up questions, please use our “Contact support” form located on our Help Center (https://bitwarden.com/help/) and our awesome customer success team, will be able to help.

Closing this now.

Kind regards,
Daniel

**Comment by CalebBurton** [comment]
That was the problem. Despite being the admin on the account and the creator of every collection, my access was set to "edit" in each collection rather than "manage". Changing that meant they showed up in the organization export.

I'm puzzled why my account would have the ability to run the export through the CLI and the admin console, but not through the normal web UI. This still seems like a bug to me. At the very least I would suggest providing a warning or error message in this scenario to explain why the export is empty.

**Comment by ryancwalsh** [comment]
@djsmith85 @CalebBurton Thanks for this issue and answer. I too found this very surprising and confusing. 

I'm still confused how I can be Owner but didn't have "Can Manage" permissions.

But now that I found where to set "Can Manage", the export seems to have worked. Thanks.
