### ISSUE TITLE
mondialrelay.fr - Auto-fill login password not working, and no dropdown with login

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#8544]
### Steps To Reproduce

1. Go to https://www.mondialrelay.fr/
2. Click on 'Connexion'
3. Try to auto-fill with a login(email)/password (enter anything, it does not need to be actual login/password to test that auto-fill is not working), you will see 2 issues

### Expected Result

A/ Have the password being auto-filled
B/ Having BT login dropdown-list when you have the new login dropdownlist feature of Bitwarden activated.

### Actual Result

 A/ Password is not auto-filled (only the Login is auto-filled)
 B/ There is no dropdown-list when you have the new login dropdownlist feature of Bitwarden activated.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/98819304/a82a5ed3-ccb9-4e25-8401-e4560f0bb731)

### Operating System

Windows

### Operating System Version

Windows 11 fully uptodate

### Web Browser

Chrome

### Browser Version

Chrome browser fully uptodate

### Build Version

Chrome browser fully uptodate

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
