### ISSUE TITLE
Vault Timeout setting is not saved

### ISSUE THREAD

**Issue by Scooter865** [bitwarden/clients#8615]
### Steps To Reproduce

1. Go to 'file->settings'
2. Set Vault timeout to 5 minutes (or any other value)
3. Close settings
4. Re-open settings, Vault timeout is reset to 'on restart'

### Expected Result

Vault timeout is set to 5 minutes or whatever option the user selected.

### Actual Result

The vault timeout change is not saved. Vault timeout is reset back to the 'on restart' default setting.

### Screenshots or Videos

I am allowed to change this setting but it does not get saved and reverts to on restart when I close the settings.
![image](https://github.com/bitwarden/clients/assets/42327824/55871103-f4ee-49aa-bf8c-ead073257eb5)

### Additional Context

I tried with a few timeout options including a custom 2 minute timeout. None of them get saved and the vault remains unlocked until the next restart.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Snap

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please note that by default, if you close your browser window, your browser extension will require you to login with your master password regardless of your selected vault timeout action. Are you closing your browser entirely when testing this or just the Bitwarden extension window?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Scooter865** [comment]
I'm having this issue with the desktop app for linux on Ubuntu 22.04.4 LTS.

**Comment by mcdannys** [comment]
Same here, on Linux Mint 21.3, using AppImage or .deb package
