### ISSUE TITLE
Password will not paste on ebay login screen

### ISSUE THREAD

**Issue by rbhall52** [bitwarden/clients#8634]
### Steps To Reproduce

1. Go to ebay.com
2. Click on login
3. If email is already entered, click "Next"
4. Password has to be copied from bitwarden vault and then pasted into password blank field on form

### Expected Result

I expected bitwarden to be able to paste the password into the password field on the form.

### Actual Result

When asking bitwarden to paste the password into the password field on the form, the error message appears which says that bitwarden is unable to paste the password into the password field on the form, and that the password has to be copied from the bitwarden vault and pasted manually into the password field on the form.

### Operating System

Windows

### Operating System Version

Windows 11 Home (x64) Version 22H2 (build 22621.2861)

### Web Browser

Firefox

### Browser Version

124.0.2 (64-bit)

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by B4sicallyF0x** [comment]
I think you should fill this form instead:
https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

It's the official form to report auto-fill failtures

**Comment by Greenderella** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by rbhall52** [comment]
I just tried to paste my password into ebay's password blank on their website, and bitwarden is still saying that I need to manually paste the password into the blank on the website.
