### ISSUE TITLE
Different 2FA Codes for same Account

### ISSUE THREAD

**Issue by gituser823** [bitwarden/clients#8639]
### Steps To Reproduce

Copy a 2FA Code from the Browser Plugin or the Desktop App

### Expected Result

It should show and copy the correct 2FA Code

### Actual Result

It shows and copys the wrong 2FA Code

### Additional Context

I am using the 2FA Feature with TOTP.

Now I tried logging in on a App with 2FA, but it failed.
First I thought all 2FA Codes are faulty now for some reason or the Account I tried logging in to had issues.

It shows these 2FA Codes in the Firefox Plugin as well as the Bitwarden Client App.

I then checked my Phone and noticed, that the App shows different 2FA Codes for all logins than my Browser Plugin + Desktop App.
Plugin + Desktop show the same 2FA Codes, but they are wrong.
How can this be?

Im using:
Firefox version 124.0.2 and Bitwarden Plugin version 2024.2.1

Bitwarden Desktop App:
Version 2024.3.0
Shell 28.2.9
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

Android, where the 2FA Codes work:
App Version 2024.3.0 (9799)
Android Version 14

**One more question: Bitwarden Desktop does not offer input and detect Loginwindows for any Apps, is this normal?**

### Operating System

Linux

### Operating System Version

Manjaro

### Installation method

Other

### Build Version

See above

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by stefan0xC** [comment]
>  How can this be?

If you are sure that the authenticator key is the same for both entries your device's clock (which is used to generate the [TOTP](https://en.wikipedia.org/wiki/Time-based_one-time_password)) could be off. Cf. https://bitwarden.com/help/authenticator-keys/#troubleshooting

**Comment by SergeantConfused** [comment]
Hi @gituser823,

Thank you for reporting this. I recommend checking the Time and Time Zone settings of the computer that is generating those TOTP codes, as @stefan0xC had mentioned, because inaccurate settings can result in invalid TOTP codes; I am unable to reproduce this behaviour in testing.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you all,
