### ISSUE TITLE
Vault Timeouts Open GUI and Steals Focus, and Refuses to Close

### ISSUE THREAD

**Issue by Reaper511** [bitwarden/clients#8649]
### Steps To Reproduce

1: Open your vault, then close and keep in system tray
2: Wait for it to seemingly randomly open the GUI and steal focus from other apps some time after timeout*
3: Attempt to close the window, only for it to remain open with it opening multiple invisible system tray instances
![image](https://github.com/bitwarden/clients/assets/47519003/7e8f0f0d-6519-4c6b-85ce-b88d8419e7fe)
4: Force close Bitwarden via Task Manager and relaunch

### Expected Result

To not pop up without user input, and to close when told to close.

### Actual Result

After closing the GUI while having your vault open , the GUI will reopen some time after its set timeout, and steal focus. In addition to that, it will not allow you to close it. Every attempt to close will create a new system tray instance without an icon. You will have to force close via Task Manager.

### Additional Context

To test I went to set my Vault Timeout to 1 minute, then closed the GUI. After one minute, nothing. Then at 2ish minutes, it popped up again doing the explained issues. 

I tested again, reopening and then closing the GUI, and nothing occurred as of seven minutes in.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration or combination of the system tray settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
