### ISSUE TITLE
QR Code reading not working

### ISSUE THREAD

**Issue by morgaraf** [bitwarden/clients#8676]
### Steps To Reproduce

I am reporting a bug in your Android application, as I could not find an option in your bug report system:

1. Go to the entry you want to edit.
2. Click on Edit
3. Scroll down to Authenticator key (TOTP).
4. Click on Set up TOTP.
5. Point your camera to the QR code so it fits into the zone marked by the four blue angles.

### Expected Result

I was expecting the QR code to be recognized.

### Actual Result

No recognition at all. 
Tried with Microsoft Authenticator and it took nothing for it to recognize the same QR code.

### Additional Context

Capturing from screen.

### Operating System

Android

### Operating System Version

13

### Web Browser

Chrome

### Browser Version

12345

### Build Version

678

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Could you please try uninstalling the Bitwarden app, restarting your Android device, and reinstalling the Bitwarden app?

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
