### ISSUE TITLE
Windows 11 desktop can’t select .EU domain 

### ISSUE THREAD

**Issue by srm39** [bitwarden/clients#8682]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Was prompted to update Bitwarden on  Windows 11 today, version 2024.3.2. Now unable to log in because the drop-down can't select the .EU domain (self-hosted and .com work fine).

### Actual Result

Can see option fornEU domain but cannot click on it to select it 

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by scm2409** [comment]
Hi, please don't close this as I've the same problem on linux using the appimage.

**Comment by riess82** [comment]
Same problem on Windows 10 app, bitwarden version 2024.4.3

**Comment by litbea** [comment]
Same issue here, what is shown in the screenshot is after clicking on the EU selector. Nothing changes and, of course, it tries to validate on the wrong domain.
![2024-08-06 Bitwarden EU error](https://github.com/user-attachments/assets/a449471a-fc99-492b-b254-fe480d7f4ba4)

**Comment by cherrysushi** [comment]
why is this closed as 'not planed' without any explanation or work-around?? I have the same issue on the latest Bitwarden app for Windows 
![image](https://github.com/user-attachments/assets/90021951-47c9-4ede-bdd2-abde2b45af47)

the dropdown doesn't want to select `bitwarden.eu`. i tried [tab] to switch line and it works but if I [space] or [enter] on `bitwarden.eu` it keeps `bitwarden.com`. it otherwise works on `self-hosted` and opens the modal for that one
