### ISSUE TITLE
Bitwarden Windows Desktop Trying to Install Update from 8 Bit Solutions LLC

### ISSUE THREAD

**Issue by SheldonB45** [bitwarden/clients#8698]
### Steps To Reproduce

Open Bitwarden windows desktop
Reply Restart to "Restart to update" message
Windows User Account Control will prompt for administrator password
Windows gives the  the verified publisher as 8 Bit Solutions LLC

### Expected Result

Expected the verified publisher to be Bitwarden

### Actual Result

verified publisher as 8 Bit Solutions LLC

### Screenshots or Videos

![Bitwarden 8 bit](https://github.com/bitwarden/clients/assets/166734070/766d8521-1af4-4896-8343-ac31a1e591f5)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Other

### Build Version

Version 2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Bitwarden Inc. is incorporated in the State of Delaware in the United States of America. 8bit Solutions LLC is wholly owned by Bitwarden Inc. You can verify this in our Terms of Service: https://bitwarden.com/terms/

We use GitHub issues as a place to track bugs and other development related issues. If you have any additional questions, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
