### ISSUE TITLE
Bitwarden doesn't overwrite autofilled credentials

### ISSUE THREAD

**Issue by mackaaij** [bitwarden/clients#8705]
### Steps To Reproduce

With autofill enabled and more than one account for the site:
1. Go to '[Yarden.nl](https://www.yarden.nl/mijn-yarden.htm/)'
2. Pick another credential in the Bitwarden extension to login

### Expected Result

Bitwarden overwrites the autofilled credentials with the selected credentials

### Actual Result

Bitwarden keeps the autofilled credentials

### Additional Context

Login name = Relatienummer
Password = Wachtwoord

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

123.0.6312.107

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
