### ISSUE TITLE
Exclude domains does not work on Firefox

### ISSUE THREAD

**Issue by rvw** [bitwarden/clients#8721]
### Steps To Reproduce

1. Go to a site with a login page where you have a login for. I used https://account.komoot.com as an example.
2. Click on the email address input field
3. Observe that the Bitwarden icon appears on the right in the input field and that a dropdown is shown with the saved login. Also, if you don't have a login saved for that site the plugin will show the icon and an option to add a login
4. Now go to the extension and into the settings > excluded domains
5. Enter the above-mentioned url, so it will be excluded and hit save
6. Return to the url, refresh the page or reload the browser, the Bitwarden icon and dropdown will still be visible. The domain was not successfully excluded

![Screenshot 2024-04-12 at 14 20 00](https://github.com/bitwarden/clients/assets/903647/24fb37d3-63d9-4a1b-a518-f85931c0c78f)

### Expected Result

Bitwarden is not shown in/near the input field. No icon is shown and no option is shown to login or add a new login.

### Actual Result

Bitwarden is shown:
![Group 2](https://github.com/bitwarden/clients/assets/903647/09801582-7e16-4e74-9e59-24957d124af6)

### Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Web Browser

Firefox

### Browser Version

124.0.2 (64-bit)

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software, as excluded domains do not affect autofill. More information on this can be found here: https://bitwarden.com/help/exclude-domains/

If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
