### ISSUE TITLE
Extension doesn't open in Firefox private mode

### ISSUE THREAD

**Issue by ThracianKnight1907** [bitwarden/clients#8729]
### Steps To Reproduce

1. Open Firefox in incognito mode
2. Open Bitwarden 

### Expected Result

The addon opens and asks for my PIN

### Actual Result

The Bitwarden addon doesn't open, and I can't access other webpages/open other addons' menu unless I restart Firefox

### Screenshots or Videos

![Captură de ecran de la 2024-04-13 16-01-04](https://github.com/bitwarden/clients/assets/64692701/9609aaf1-cd63-499b-8224-199b1faf30a0)

### Additional Context

Still persisting on 2024.4.1 and Firefox 125.0

### Operating System

Linux

### Operating System Version

Fedora 39

### Web Browser

Firefox

### Browser Version

124.0.2
125.0

### Build Version

2024.3.1
2024.4.1
### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @ThracianKnight1907,

Thank you for your report. I was able to reproduce this behaviour, albeit intermittently, and I have flagged it to the Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - the Engineering team will be happy to review them.

Thank you again,

**Comment by ThowZzy** [comment]
+1 to this.
I am on Windows 11, Firefox 125.0.1 and Bitwarden 2024.3.1.
Once trying to open the extension in a private window, Firefox loses any connectivity it seems, even on the non-private window.

**Comment by Thrius** [comment]
I am on Windows 10, Firefox 125.0.2 (64-bit) and Bitwarden 2024.4.1. Once trying to open the extension in a private window, Firefox loses any connectivity it seems, even on the non-private window. This issue doesn't seem to reproduce when using the same system and Firefox normal browsing mode, only reproduces with Firefox private browsing. Narrowed the issue down to the Bitwarden extension as the issue by turning off each extension one at a time, and enabling only one at a time. I only have a few extensions so it wasn't difficult to troubleshoot.
Steps to reproduce:
1. Open Firefox in private browsing mode only with Bitwarden extension allowed in private browsing
2. Navigate to a website
3. Click on the Bitwarden extension icon
4. Notice a blank window appears instead of the Bitwarden vault
5. Attempt to browse to a different website
6. Notice website won't load
7. Click on the Bitwarden extension icon once again
8. Notice this time not even a blank window appears, nothing happens (maybe a very small box appears under the extension icon?)
9. Click on some other extension if loaded and allowed in private browsing
10. Notice no window appears for this extension either.
![FF1](https://github.com/bitwarden/clients/assets/30027929/0d8b9c2a-586c-4eab-9933-30996067a1c1)

**Comment by heathlarsen** [comment]
We have done a bunch of testing in a uBlock Origin issue thread (https://github.com/uBlockOrigin/uBlock-issues/issues/3217) and it seems that after a short period (~1 minute) of browsing in Firefox Incognito mode, opening the BitWarden extension results in BitWarden failing to load (the screenshots above) and then it takes over 100% of the 'Extension' CPU process. If the user also has an ad blocker installed (testing with uBlock Origin and AdBlock Plus) then all pages will refuse to load as the ad blocker can't get any CPU time to vet pages as they are accessed.

**Comment by SamKr** [comment]
Same issue here, with and without ublock origin

**Comment by ThracianKnight1907** [comment]
The latest update (2024.4.2) seems to have fixed this for me

**Comment by Thrius** [comment]
> The latest update (2024.4.2) seems to have fixed this for me

Same here, fixed with v.2024.4.2

**Comment by trmartin4** [comment]
As noted above, we have introduced several changes in both the `2024.4.2` release and the next upcoming Firefox browser extension release that will address ongoing issues with private mode.  I will be closing this issue as that code has merged.

If you continue to experience issues after our next Firefox extension release, please feel free to re-open this or create a new issue.
