### ISSUE TITLE
Bitwarden Biometric and Passkeys do not work with Sidekick Browser

### ISSUE THREAD

**Issue by x-o-r-r-o** [bitwarden/clients#8731]
### Steps To Reproduce

Install Sidekick browser (https://www.meetsidekick.com/).
Install the Bitwarden browser extension inside it from the Chrome Web Store.
Log into your Bitwarden account.
Try to activate 'Unlock with biometrics'.
Try to login to Google account with passkey
Bitwarden cannot be set as default password manager in Sidekick Browser settings.

### Expected Result

It will simply do not work no matter what settings you have. Even Bitwarden autofill feature also do not work with Sidekick Browser.

### Actual Result

In short Bitwarden is 100% incompatible with Sidekick Browser which is chromium based browser. you will be able to install extension but you will not be able to use it properly.

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

Sidekick Browser

### Build Version

Version 120.58.1.38487

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

At the moment, Bitwarden's browser extensions are supported for the two most recent versions of Google Chrome, Mozilla Firefox, Opera, Microsoft Edge, and Safari. For Vivaldi, Brave, and Tor, only the most recent version is supported. If you would like for Bitwarden's browser extensions to be supported for Sidekick browser, the Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
