### ISSUE TITLE
MacoS Firefox vault export isn't working

### ISSUE THREAD

**Issue by Jack15911** [bitwarden/clients#8738]
### Steps To Reproduce

1. Using Firefox on MacOS log into Bitwarden Web Vault. 
2. Go to Tools/Export Vault. 
3. Choose My Vault, .json (Encrypted), Password Protected. 
4. Enter file password twice and Confirm Format. 
5. Fill popup message box with Master Password. See indication that your Master Password is "Incorrect password."

### Expected Result

Expect to see Master Password accepted and be given a location to save the export, choose the location, and save it.

### Actual Result

Popup message box into which you put your Master Password indicates it's an incorrect password.

### Additional Context

The process works properly in Safari, but it fails in Firefox.

### Operating System

macOS

### Operating System Version

Sonoma 14.1.1

### Web Browser

Firefox

### Browser Version

Firefox 124.0.2

### Build Version

24.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Jack15911** [comment]
Please re-open: 

1. I left out an important part of Steps to Reproduce: 
To step one change to "Use 'Login with device.'" (It might be the same thing for Passkeys.)

2. To Additional Context add: Vault export worked in Safari because "Login with device" is not available and I used the password.

I think what's happening is that "Login with Device" is not providing a password to be checked by the Export operation, so I get an error message of an incorrect password. It's possible that the Export page simply checks against (probably) a hash of the password when logging in. Since there was no password there the Export showed an incorrect password.

I would suggest changing the "incorrect password" warning under these circumstances to indicate there was no password present, if my reasoning is right; that would give a better hint for figuring out the error.
