### ISSUE TITLE
Password import from Firefox-csv into an existing folder creates a new folder with the same name

### ISSUE THREAD

**Issue by SGeisel** [bitwarden/clients#8766]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'Data import'
3. Fill Folder with a foldername
4. Fill Fileformat with firefox(csv)
5. Choice a csv-File exported from firefox
6. Press 'Data import'

### Expected Result

One folder with added passwords

### Actual Result

You have two folders with the same name

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
