### ISSUE TITLE
"Clone" Is acting like "edit"

### ISSUE THREAD

**Issue by TheRedKat** [bitwarden/clients#8779]
### Steps To Reproduce

1. Go to 'Secure note'
2. Click on any item or note
3. Click "Clone"

### Expected Result

Clone button must copy the text from the login, notes, cards and ids

### Actual Result

"Clone" button must copy the text from the login, notes, cards and ids.
But It is functioning like "Edit" button.
So, developers put two "edit" buttons and no "copy" button.
Might be same problem in website, but surely in windows application

### Operating System

Windows

### Operating System Version

10 home

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.4.1 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @TheRedKat ,

Your issue appears to be describing the intended behavior of the software. When you click on the clone button it creates a new item, this is why you are able to see the - Clone , next to the name because you might want to change the name of the newly cloned item - hence it "seeming" like an edit. But what you are editing is the newly cloned node.

I hope this is clear and helpful.

This issue will now be closed. 

Thanks!
