### ISSUE TITLE
Browser Extension asks for biometrical key when locking vault

### ISSUE THREAD

**Issue by Xytronix** [bitwarden/clients#8788]
### Steps To Reproduce

1. Install desktop version for mac
2. Login on both
3. Navigate to options inside the extension
4. Activate unlock by biometrics.
5. Extension pops up message to unlock vault via biometrics when timer runs out . Note the extension isn't actively opened.

### Expected Result

Application doesn't automatically ask for biometrics to unlock

### Actual Result

Extension ask for biometrics even though not needed.

### Screenshots or Videos

<img width="365" alt="image" src="https://github.com/bitwarden/clients/assets/32957125/2a14f3a9-fc27-4e75-88a7-42e2d0f27051">

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. When biometric authentication is configured for the first time, the extension displays a message prompting the user to unlock the vault via biometrics. This prompt serves to confirm that biometric authentication has been set up correctly. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by Xytronix** [comment]
Hey Alex this isn’t happening only for the first time, it makes it inconvenient as it asks for biometrics when I am working on something else. I don’t think thats really intended to happen when you don’t have the vault in the front or actively clicking a button to display biometrics message

**Comment by Xytronix** [comment]
Whenever the vault locks itself it asks automatically on the screen for biometrics

**Comment by Xytronix** [comment]
@Greenderella would you reopen this please?
