### ISSUE TITLE
Failed to Fetch. 

### ISSUE THREAD

**Issue by NvTdmf** [bitwarden/clients#8811]
### Steps To Reproduce

1. Go to a existing, saved credential. 
2. Click on edit icon. 
3. Select the Password field and update the password. 
4. Click on the save icon. 

### Expected Result

New Password is saved to record. 

### Actual Result

"An error has occurred. Failed to fetch." message appears in the upper right hand of the window. 

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/127355764/034304c3-b0b6-46ed-88f5-6526f4a93ce5)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
