### ISSUE TITLE
Firefox extension randomly unlinked from BW, not linking again

### ISSUE THREAD

**Issue by KernelBypass** [bitwarden/clients#8812]
### Steps To Reproduce

1. Firefox plugin randomly unlinked from Desktop BW
2. Trying to link it back again: `choose log in with device`

<img width="377" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/5ad4945e-921e-4c61-b70b-c4ab99c5702d">

3. It generates a fingerprint
4. Confirm it in BW desktop
5. Go back to firefox: still not logged in

### Expected Result

Should be logged in.

### Actual Result

Not logged in. Start the process again over and over: same outcome.

### Additional Context

Several browsers on Mac. Safari linked just fine, no unlinkage problems. Firefox, on the other hand, is very problematic - just the latest:
- Biometrics never working from within FF
- Login with device not working
- Extension drop down/mini window is empty in private mode

I am a paid user, Firefox extension performance is not acceptable even for a Beta version.

### Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Web Browser

Firefox

### Browser Version

125.0.1 (64-bit)

### Build Version

Version: 2024.3.1 Server version 2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by catprisbrey** [comment]
Same issue here more or less. Firefix extension disconnected randomly today and now it's not reconnecting. And i can't seem to login at Bitwarden's webpage either. But my android and other devices and browsers are still working and logged in.

**Comment by ocombe** [comment]
> UPDATE: i uninstalled the extension and reinstalled it, and then it let me login fine and is working again.

I can confirm, it works after removing the extension, but you have to restart the browser before you reinstall it.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I suggest you contact us using our “Contact support” form located on our Help Center (https://bitwarden.com/help/) so we can review your current configuration. You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

We use GitHub issues as a place to track bugs and other development related issues. The issue here will be closed.

Thanks!

**Comment by old-square-eyes** [comment]
Happening for me on Mac OS, Firefox. Uninstalling, reinstalling, master password, enable, test. That's the opposite of the convenience I want with biometrics.
