### ISSUE TITLE
Unable to Unlock Desktop Client - "Your vault is locked. Verify your identity to continue." without password field shown (Windows 11, desktop client portable version)

### ISSUE THREAD

**Issue by AyoungDukie** [bitwarden/clients#8916]
### Steps To Reproduce

1. Leave Client inactive for multiple work days
2. Return or relaunch client
3. Attempt to sign back in to vault.

### Expected Result

I would put in my master password, and maybe have an MFA access step if something was prompted. Completing these would allow access back into vault.

### Actual Result

No password field, MFA prompt, or other valid login method is presented. Instead only a logout button. I am only able to log out (which will give access back once I log back in).

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/5449443/47e5aeb7-2b9b-440f-bdd6-5259d63fa877)

### Additional Context

This is using the portable windows client (installed using the [Scoop package manager](http://scoop.sh) )

PIN was not enabled,

Vault was set to "Lock" (not log out)

Extra settings panel show what seem standard settings (though maybe I enabled Browser verification?):
![image](https://github.com/bitwarden/clients/assets/5449443/84255438-4649-43df-a41e-c8143ce2d693)

That said, I have now encountered some variation of this in the browser (being tracked #8732), and on both my personal and work Android devices (both Pixel 8 devices running Android 14, April 5 security update).

In the linked issue, the discussion has hinged around the use of ad-blockers, however these other platforms seem to contradict that. 

### Operating System

Windows

### Operating System Version

23H2 (22631.3447)

### Installation method

Other

(portable package via Scoop; sourced from this github via https://github.com/bitwarden/clients/releases )

### Build Version

2924.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I recommend removing all files from the location mentioned here (https://bitwarden.com/help/data-storage/#on-your-local-machine), restarting your device, and re-installing the application. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Eagleshot** [comment]
Hello there
I have the same issue with the Bitwarden Extension in Firefox on Windows 11, so I guess it's not isolated to the desktop client (see screenshot below).

![image](https://github.com/bitwarden/clients/assets/75380532/46ee4eb0-c77c-4b10-b75e-e3089660bd87)

@Neonwarden
