### ISSUE TITLE
Can't connect to my self-hosted vault with Desktop App and Mobile App

### ISSUE THREAD

**Issue by miditkl** [bitwarden/clients#8948]
### Steps To Reproduce

1. select your host
2. Click on self host
3. Type in the hostname of the bitwarden server
4. Click on save
5. type in your mail
6. click continue

### Expected Result

Type my password in, and use bitwarden
(on Desktop i can actually type my password, but after I want to sign in, i get an error)

### Actual Result

On mobile: Exception message: Connection failure
On PC: Failed to fetch

### Additional Context

I can open my self hosted vault on my browser and browser extension with no problems

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1 (on Android its the latest)

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @miditkl,

Thank you for reporting this. I recommend that you review your setup and make sure that those two clients are able to reach your locally-hosted Bitwarden server and that they have the necessary [certificates](https://bitwarden.com/help/certificates/) installed so that they'd be able to communicate with it; The (Connection failure) and (Failed to fetch) error messages typically indicate that the clients in question are unable to reach the Bitwarden server. I say this as I am unable to reproduce this.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by mucosol** [comment]
Hi miditkl, I have exactly the same problem with a self-hosted instance of bitwarden. Could you solve your problem in the meantime?

**Comment by miditkl** [comment]
No, unfortunately not.

**Comment by mucosol** [comment]
Thanks!
