### ISSUE TITLE
Text show error

### ISSUE THREAD

**Issue by fenghuan1994** [bitwarden/clients#8969]
### Steps To Reproduce

1. Go to 'help'
2. Click on 'about'

![截图 2024-04-29 14-47-31](https://github.com/bitwarden/clients/assets/22291785/51e693d6-4fd2-46f7-9382-0e6c16bede40)
![截图 2024-04-29 14-48-03](https://github.com/bitwarden/clients/assets/22291785/159405ff-4c7f-4181-8d1c-866c3b4a15cd)

### Expected Result

show text

### Actual Result

show "口口"

### Screenshots or Videos

![截图 2024-04-29 14-47-31](https://github.com/bitwarden/clients/assets/22291785/a75dd15f-7992-4c79-8796-bfcaab08f1f8)
![截图 2024-04-29 14-48-03](https://github.com/bitwarden/clients/assets/22291785/8a94c93d-3765-4158-8d14-b236f9baf58b)

### Operating System

Linux

### Operating System Version

ubuntu24.04

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a language setting.
You can try a fresh reinstall and see how you get on.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
