### ISSUE TITLE
Copy buttons from modal not working when used in sequence

### ISSUE THREAD

**Issue by vinismarques** [bitwarden/clients#9013]
### Steps To Reproduce

1. Navigate to a website you have password stored for.
2. Click on Bitwarden's extension icon to open the modal.
3. Click on the "Copy username" button.
4. Change focus to another window and paste the username (the modal will remain open).
5. Click on the "Copy password" button (the modal will automatically hide).
6. Change focus to another window and paste the password (it will paste the username again, the password was not sent to the clipboard).

### Expected Result

The click on the "Copy password" icon should put the password content on the clipboard, as it worked for the username.

### Actual Result

The username is copied correctly, but the password is not.

### Operating System

Linux

### Operating System Version

Arch

### Web Browser

Brave

### Browser Version

Version 1.65.123 Chromium: 124.0.6367.91 (Official Build) (64-bit)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try uninstalling the Bitwarden extension, restarting the device, and then reinstalling the Bitwarden extension.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
