### ISSUE TITLE
Unable to move passwords to organization

### ISSUE THREAD

**Issue by alfonsoar** [bitwarden/clients#9019]
### Steps To Reproduce

1. Go to "Vaults" 
2. Click on 'My Vault" 
3. Select all passwords
4. Click hamburger button 
5. Click on "Move selected to organization" 
6. Select organization
7. Click on "Save"

### Expected Result

The passwords are moved to the organization or we show the user an error message. 

### Actual Result

Passwords are not moved and I see no error message. 

### Screenshots or Videos

<img width="1440" alt="Screenshot 2024-05-02 at 11 48 07 AM" src="https://github.com/bitwarden/clients/assets/22054505/f352cb68-fd14-4d63-8605-41bea24aee5e">

### Additional Context

I noticed the call to `https://vault.bitwarden.com/api/ciphers/share` failed with a 400: 

```
{
    "message": "The model state is invalid.",
    "validationErrors": {
        "CollectionIds": [
            "You must select at least one collection."
        ]
    },
    "exceptionMessage": null,
    "exceptionStackTrace": null,
    "innerExceptionMessage": null,
    "object": "error"
}
```

### Chrome version: 

```

Google Chrome | 124.0.6367.91 (Official Build) (arm64)
-- | --
Revision | 51df0e5e17a8b0a4f281c1665dbd1b8a0c6b46af-refs/branch-heads/6367@{#984}
OS | macOS Version 13.1 (Build 22C65)
JavaScript | V8 12.4.254.14
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --restart --restart --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path | /Users/alfonso/Library/Application Support/Google/Chrome/Default
Linker | lld
Active Variations | e32097a3-ca7d8d80c75063ef-377be55a
```

### Operating System

macOS

### Operating System Version

13.1 (22C65)

### Web Browser

Chrome

### Browser Version

124.0.6367.91

### Build Version

see above

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

From the screenshot provided, it appears the account does not have permission to any collections in the organization you're attempting to move items to. You will first need to make sure the account has access to at least one collection in the organization prior to moving items there. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by alfonsoar** [comment]
Hi @Neonwarden - thanks for the quick reply, don't you think that the fact that we don't show the user an error message suggesting what you mentioned or some form of other action is a bug? Otherwise if collections is a required field I would expect to not be able to click on save.
