### ISSUE TITLE
Bitwarden extension does not work in Opera

### ISSUE THREAD

**Issue by Antonio-52** [bitwarden/clients#9097]
### Steps To Reproduce

1. Oper Opera browser
2. Click on extension Bitwarden

### Expected Result

2. A window opens with Bitwarden asking for the main password.

### Actual Result

2. A white background windows opens, gear icon rotate and no more.

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.6 LTS

### Web Browser

Opera

### Browser Version

76.0.4017.123

### Build Version

Bitwarden Password Manager extension ver.2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
