### ISSUE TITLE
Submit button below bottom of screen

### ISSUE THREAD

**Issue by jidanni** [bitwarden/clients#9120]
### Steps To Reproduce

![a](https://github.com/bitwarden/clients/assets/1230959/56bc294c-f7d4-49e6-8a8b-7dcfdc1e1337)

### Expected Result

Here after the user types in their master password, they cannot find the Submit button, because it is below the screen.

### Actual Result

Please test with all monitor sizes, and even font and zoom sizes. All I know is I use standard sizes.

### Additional Context

And the "kicker" is there is plenty of blank space within the "app window" we see here, that is wasted, but then the Submit button is off the screen.

### Operating System

Linux

### Operating System Version

Debian sid

### Web Browser

Chrome

### Browser Version

Latest beta

### Build Version

Latest

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. The submit button is in the top right corner of the extension Export window as shown in your screenshot.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jidanni** [comment]
Indeed I tested it with

$BROWSER chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html?uilocation=popout#/tabs/vault

and found that there was no submit button below... I had to use the ENTER button after entering my password.

Then coming back to GitHub to report my findings, it turns out just like you said. The submit button was indeed above everything all along, there on the top in the first place.

All I can say is that is an unfamiliar place for a submit button, as users usually work downward when filling in forms.
