### ISSUE TITLE
Allow copying version number

### ISSUE THREAD

**Issue by jidanni** [bitwarden/clients#9121]
### Steps To Reproduce

1. Submit a bug report right here on this GitHub.
2. Get to the place where we are to enter the version number.

### Expected Result

We should be able to highlight and copy with CTRL+C.

### Actual Result

All we can do is read it with our eyes, and then type what we read into the GitHub form.

### Screenshots or Videos

![v](https://github.com/bitwarden/clients/assets/1230959/3fd512c4-d4ad-43bf-96e4-3a9d5eaf5071)

### Operating System

Linux

### Operating System Version

Debian sid

### Web Browser

Chrome

### Browser Version

Latest beta

### Build Version

See above image

**Comment by sammbw** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by jidanni** [comment]
OK. Made https://community.bitwarden.com/t/allow-copying-bitwarden-version-number/66726 .

**Comment by djsmith85** [comment]
@jidanni Thank you for your report, we also noticed this and have addressed it with https://github.com/bitwarden/clients/pull/9078
