### ISSUE TITLE
Web Site Navigation Update to make more clear

### ISSUE THREAD

**Issue by dudley810** [bitwarden/clients#9132]
### Steps To Reproduce

I don't use the website very often but it seems like the navigation on the website could be more clear to find things.  This is not a bug but more like a suggestion to make finding the admin console more clear.  I think taking it out of the square box navigation would help people find it faster. 

### Expected Result

When you are on the https://vault.bitwarden.com/#/vault you will clearly see where to get to the admin-console.  No more trying to remember that it's in this square box.  

### Actual Result

When you are on the https://vault.bitwarden.com/#/vault you don't see the link for the admin console.

### Screenshots or Videos

<img width="1409" alt="Screen Shot 2024-05-10 at 11 57 54 AM" src="https://github.com/bitwarden/clients/assets/1314937/fa4a1b45-92b1-454b-9d37-678f85ed8425">
<img width="280" alt="Screen Shot 2024-05-10 at 11 58 43 AM" src="https://github.com/bitwarden/clients/assets/1314937/6063f233-bf29-457c-a75b-6f39bb08d538">

### Operating System

macOS

### Operating System Version

N/A

### Web Browser

Chrome

### Browser Version

N/A

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
