### ISSUE TITLE
New Manifest v3 Extension in Google Mail

### ISSUE THREAD

**Issue by SchneiderSam** [bitwarden/clients#9152]
### Steps To Reproduce

1. Go to 'Google Mail'
2. Click on 'Search'
See the Error

![image](https://github.com/bitwarden/clients/assets/9355398/03a85772-637a-4124-b8b1-05a96a7ef097)

### Expected Result

I certainly don't want to insert my passwords in the search field...

### Actual Result

I see the autofill Function

### Operating System

Windows

### Web Browser

Chrome

### Build Version

Version 124.0.6367.201 (Offizieller Build) (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
