### ISSUE TITLE
Unable to chance vault when verifying passkey and logged in

### ISSUE THREAD

**Issue by platnub** [bitwarden/clients#9153]
### Steps To Reproduce

1. Log in to Bitwarden in your browser extension
2. Start passkey authentication
3. You will not be able to switch to a different vault

### Expected Result

Like on the login screen, or other general use you should have the option to switch to a different vault

### Actual Result

The circle for changing vault is not programmed to show up in the passkey screen

### Screenshots or Videos

Left is when logged out, right is logged in. Both screens are called in the same way (authenticating through passkey)

![image](https://github.com/bitwarden/clients/assets/81484914/55e308f6-601e-4e46-9ea1-ea9cd81a90a6)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
