### ISSUE TITLE
Bitwarden Vault completely empty (only on Windows)

### ISSUE THREAD

**Issue by in1t5** [bitwarden/clients#9187]
### Steps To Reproduce

1. Open Windows Bitwarden client

### Expected Result

Vault showing the actual login list

### Actual Result

Vault is completely empty. Same vault worked recently and works still fine on iOS and Mac.

### Additional Context

Vault is hosted in Docker, running on Synology NAS.
Access to vault is done using local network.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by Anubarak** [comment]
I have the very same issue, my vault is empty since one week.
I tried to restart, re-logging I have uninstalled the application several times, cleared cache and all but nothing worked.
Just to let others know it might be a common problem
