### ISSUE TITLE
CLI Offline mode bw list items timeout error before giving results

### ISSUE THREAD

**Issue by Misterbabou** [bitwarden/clients#9208]
### Steps To Reproduce

1. Connect with bw CLI
2. Sync the vault
3. Disconnect from internet (or at least to the Bitwarden server)
4. 
```
bw list items
``` 
   or 
``` 
bw list items --search <text search for organization item>
```
6. Result will be output after a long wait (more than 120s) and an error message

### Expected Result

Get Json output instantly

For instance:
When I do the same as above but with : 
```
 bw list items --search <text_search for personnal item>
 ```
 I have the json output instantly

### Actual Result
```
FetchError: request to https://<my_self_host_server>/identity/connect/token failed, reason: connect ETIMEDOUT <my-IP>:443
    at ClientRequest.<anonymous> (/snapshot/clients/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:537:28)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Then the json output
```

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.6 LTS

### Shell

Bash

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Misterbabou** [comment]
Edit to my previous message. it's might be due to built-in [Event logging](https://bitwarden.com/help/event-logs/)

I checked:
https://github.com/bitwarden/clients/issues/7991#issuecomment-2112179620

Is it possible to not try event logging when Bitwarden server not reachable or not online?

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Are you able to update to a more recent version of Ubuntu to see if that makes a difference? 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by sentriz** [comment]
hey did you find a workaround/fix @Misterbabou ?

**Comment by Misterbabou** [comment]
Yes but it's not a best practice as it disable events by redirecting events to your localhost on a random trash port.
With this configuration you get the Error instantly and not a long timeout

```
bw config server https://your.remote.bitwarden.server --events http://127.0.0.1:9
```
