### ISSUE TITLE
Unable to login on Bitwarden client on Linux (Ubuntu Desktop 22.04)

### ISSUE THREAD

**Issue by Nije-PCH** [bitwarden/clients#9212]
### Steps To Reproduce

4. Click on '...'

### Expected Result

After entering master password expect the bitwarden client app to unlock the database.

### Actual Result

Bitwarden client prompts: An error has occured. Invalid Master Password

### Screenshots or Videos

![output](https://github.com/bitwarden/clients/assets/80590663/2ad76935-480e-4f4e-962c-fb6703f4c416)

### Additional Context

Master Password can be used just fine to unlock firefox extention or Bitwarden client on Windows 11 PC

### Operating System

Linux

### Operating System Version

Ubuntu Desktop 22.04

### Installation method

Snap

### Build Version
Version 2024.4.3
Shell 28.3.1
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Could you please try fully logging out and attempting to log back in?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
