### ISSUE TITLE
Desktop scaling only scales visual size, not physical size of GUI elements

### ISSUE THREAD

**Issue by rgambord** [bitwarden/clients#9238]
### Steps To Reproduce

Set desktop scaling to something other than 100% and run the bitwarden desktop client

### Expected Result

GUI elements scale visually and physically

### Actual Result

GUI elements visually scale, but element positioning and mouse events are based on unscaled sizes.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/8367936/367a3b7e-66cc-47e4-ab46-183b61fd2c34

### Additional Context

 In the example video, desktop scaling is set to 80% on KDE 6.0.4-1. 

### Operating System

Linux

### Operating System Version

6.8.9-arch1-2

### Installation method

Other

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. In order to scale the GUI elements, you must use the "Zoom in" and "Zoom out" options from the View tab (or the corresponding shortcuts):

![image](https://github.com/bitwarden/clients/assets/5418577/8870f9ee-18fe-4c26-bd2b-61e0b3b2c2d7)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by rgambord** [comment]
I think there is a misunderstanding here. The issue is with how BitWarden scales its GUI elements when the desktop scaling for a display manager is not set to 100% (for example, HiDPI screens). The elements are visually scaled to match the desktop's scaling settings, but the Bitwarden app is positioning them and registering mouse events based on their original, unscaled sizes.
