### ISSUE TITLE
Safari extension fails to populate login on Chase website

### ISSUE THREAD

**Issue by KernelBypass** [bitwarden/clients#9242]
### Steps To Reproduce

1. Go to '[https://secure.chase.com/web/auth/dashboard#/dashboard/overviewAccounts/overview/index](https://secure.chase.com/web/auth/dashboard#/dashboard/overviewAccounts/overview/index)'
2. Click on login field
3. BW scroll down list with credentials opens up below the login field
4. Click on credential from said list

### Expected Result

Credential should get populated in the field

### Actual Result

Credential does not transfer/populate to the username/password text fields. Username field becomes highlighted in red.

### Operating System

macOS

### Web Browser

Safari

### Browser Version

17.4.1

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @KernelBypass,

We appreciate you letting us know of this. Due to the nature of autofill, we track such reports internally using different forms, depending on the platform:

- Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
- Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, I have gone ahead and filed a report on your behalf. In the future, if you encounter any other page or application where Bitwarden does not perform autofill as expected, please feel free to use the forms above directly; They are also accessible via the (New issue) button on GitHub.

I will now close this report.

Thank you again,
