### ISSUE TITLE
CLI doesn't use `--session` argument with `status` command

### ISSUE THREAD

**Issue by luixo** [bitwarden/clients#9254]
### Steps To Reproduce

Run `bw status --session ${SESSION_KEY}` vs `BW_SESSION=${SESSION_KEY} bw status`

### Expected Result

Both should result in `status: unlocked`.

### Actual Result

First one will result in `status: locked`, second one in `status: unlocked`.

### Additional Context

Seems like [this bug](https://github.com/bitwarden/clients/issues/9067) was fixed, but not for all commands.
`bw list` works just fine.

### Operating System

macOS

### Shell

Zsh

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,
I attempted to reproduce your issue and was unable to do so. 

<img width="1434" alt="Screenshot 2024-05-20 at 12 46 04" src="https://github.com/bitwarden/clients/assets/152835204/bb961e5f-d508-4c57-b02e-43ab71eec5e3">

Could you run bw logout and log back in and try the same commands and let me know how you get on?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by luixo** [comment]
Sure.
Here's log:
```
 > bw --version
2024.4.1
 > bw status
{"serverUrl":null,"lastSync":"2024-05-19T23:38:05.431Z","userEmail":"<my-email>","userId":"<my-id>","status":"locked"}
 > bw logout
You have logged out.
 > bw login
? Email address: <my-email>
? Master password: [hidden]
? Two-step login code: <2fa code>
You are logged in!

To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="<session-key>"
> $env:BW_SESSION="<session-key>"

You can also pass the session key to any command with the `--session` option. ex:
$ bw list items --session <session-key>
 > bw status --session <session-key>
{"serverUrl":null,"lastSync":"2024-05-20T10:57:36.324Z","userEmail":"<my-email>","userId":"<my-id>","status":"locked"}
 > BW_SESSION=<session-key> bw status
{"serverUrl":null,"lastSync":"2024-05-20T10:57:36.324Z","userEmail":"<my-email>","userId":"<my-id>","status":"unlocked"}
```

**Comment by luixo** [comment]
Also, `status` works perfectly fine with both session methods in `2024.1.0` (I just pulled a random version a few versions before bug started to pop up in issues in github).

I installed `2024.1.0` by downloading a macos package from release page and `2024.4.1` by [homebrew](https://formulae.brew.sh/formula/bitwarden-cli).

**Comment by daniellbw** [comment]
Hi @luixo 

Please note that the `status` command returns the status of the vault - the session key is not required to work in accordance with the command. 

My apologies for overlooking this initially. This is expected behaviour.

You can have a look at the following to gain a better understanding on the status : https://bitwarden.com/help/cli/#status

**Comment by luixo** [comment]
But why does it return different results using `BW_STATUS` env variable and `--session` argument?
According to [manual](https://bitwarden.com/help/cli/#global-options), `--session` argument is a global one.

How can one get `unlocked` status via `status` command using `--session` argument?

**Comment by daniellbw** [comment]
Hi @luixo 

According to the link I sent you in the previous message this

Which mentions the following:

**status** may be one of the following:

`unlocked`, indicating you are logged in and your vault is unlocked (a BW_SESSION key environment variable is saved with an [active session key](https://bitwarden.com/help/cli/#using-a-session-key))

`locked`, indicating you are logged in but your vault is locked (no BW_SESSION key environment variable is saved with an [active session key](https://bitwarden.com/help/cli/#using-a-session-key))

`status` checks against the `BW_SESSION` key environment variable. Although you can pass your session key as a command line using --session , this does not apply for the status command.

I hope this is clear and helpful.

**Comment by luixo** [comment]
> Although you can pass your session key as a command line using --session , this does not apply for the status command.

This is not outlined in the docs as far as I read them, I guess it should be.
Is there a reason to have that limitation? For example, ansible [Bitwarden lookup](https://docs.ansible.com/ansible/latest/collections/community/general/bitwarden_lookup.html) plugin [relies](https://github.com/ansible-collections/community.general/blob/main/plugins/lookup/bitwarden.py#L132-L134) on `status` call to determine if vault is unlocked.

**Comment by luixo** [comment]
@daniellbw
Can this be addressed?

**Comment by Dual-0** [comment]
i also noticed the behavior. very confusing!

**Comment by luixo** [comment]
@daniellbw
Can this be addressed?

**Comment by TheMelbine** [comment]
Hi @daniellbw and team,

I just wanted to chime in and say that I’m also eagerly awaiting a fix for this issue. The inconsistent behavior between BW_SESSION and --session for the status command is quite confusing, especially in automation scenarios like using the Ansible Bitwarden lookup plugin.

**Comment by luixo** [comment]
@bitwarden-bot Can you add this as a bug to internal tracking system?
