### ISSUE TITLE
Copy password fails between switching accounts

### ISSUE THREAD

**Issue by rainnedancer** [bitwarden/clients#9304]
### Steps To Reproduce

1. Go to 'entry and copy the password for alternate Bitwarden account'
2. Go to the top right-hand corner to toggle between accounts and select the account for which the password was copied''
3. Paste the Master password, blank nothing in the clipboard to paste

This worked before the latest update. Changing settings to retain the clipboard to keep data (tried all settings even 5 minutes - which is a security risk) does not retain clipboard copy and paste. 

To work around I have to copy and paste into another app to activate the clipboard, toggle between accounts, go back and copy from outside app and paste

### Expected Result

Copied password is retained for the period specified in settings and allows paste when toggle is selected between accounts

### Actual Result

This worked before the latest update. Changing settings to retain the clipboard to keep data (tried all settings even 5 minutes - which is a security risk) does not retain clipboard copy and paste. 

To work around I have to copy and paste into another app to activate the clipboard, toggle between accounts, go back and copy from outside app and paste

### Additional Context

To work around I have to copy and paste into another app to activate the clipboard, toggle between accounts, go back and copy from outside app and paste

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 20244.1 Shell 282.8 Renderer 12006099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I firstly want to thank you for bringing this use case to our attention. 

Your issue appears to be describing the intended behaviour of the software after conversing with the Engineering Team. 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
