### ISSUE TITLE
Can't login to Duolingo in Firefox, It won't populate username or password fields

### ISSUE THREAD

**Issue by dystopia2017** [bitwarden/clients#9324]
### Steps To Reproduce

How to Reproduce. Run Latest Firefox 
1. Go to: https://www.duolingo.com/?isLoggingIn=true
2. Click on: Click on the bitwarden prompt in Username or Password boxes

Nothing populates in either box. You have to click on the bitwarden addon and click copy username and paste it in.
This however does not work for the password. Copying the password from the bitwarden addon adds 13 space
characters between every character in the password. For example if the password was:

`@Twe!@d#8p7TN^9hx^VA`

Then after clicking the bitwarden addon and copying password, The password in the clipboard would become:

`@             T             w             e             !             @             d             #             8             p             7             T             N             ^             9             h             x             ^             V             A`

This means to Login to Duolingo on Firefox I need to
1. Go to the login page https://www.duolingo.com/?isLoggingIn=true
2. Click the bitwarden extension and click "Copy username"
3. Paste the username currently in the clipboard into the username field
4. Click the bitwarden extension and click "Copy password"
5. Open notepad, and paste the password currently in the clipboard into notepad
`6. Use "Find and Replace" to find "             " and replace it with ""`
7. Recopy the password from notepad and return to the duolingo login page.
8. Paste the password currently in the clipboard into the password field and click login

### Expected Result

Just click on the bitwarden integration in the username or password field and it would populate like it does on every other site.

### Actual Result

Nothing populates in either field after clicking on the bitwarden prompt in the username/password boxes

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/30868809/13db4051-f141-4b3d-9cd9-d296dd9b30ee

### Additional Context

Windows 11
Firefox version 125.0.3 (Current as of time of posting)

### Operating System

Windows

### Operating System Version

Version 23H2 (OS Build 22631.3593)

### Web Browser

Firefox

### Browser Version

Firefox Version 125.0.3 (64-bit)

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
