### ISSUE TITLE
New Accounts & Changes Are Lost If Vault Timeout Is Triggered Before Confirming Changes

### ISSUE THREAD

**Issue by NathanHawke** [bitwarden/clients#9327]
### Steps To Reproduce

1. Go to 'Add Item' or 'Edit'
2. Make any change or add a new username, password, note, etc.
3. Allow the Vault timeout period to elapse.

### Expected Result

I would expect the Vault entry to still be active and unsaved, auto-saved, or maybe saved as a "draft" copy if there were unconfirmed changes made to an existing entry.

### Actual Result

After unlocking your Vault, you'll discover all of your changes, account details, etc. have vanished and are irretrievable.

### Operating System

Windows

### Operating System Version

Windows 11 Home - 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.4.1 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
