### ISSUE TITLE
Missing menu bar on mac

### ISSUE THREAD

**Issue by mwisnicki** [bitwarden/clients#9338]
### Steps To Reproduce

1. Close Bitward
2. Open bitwarden (either with launch icon of from tray)
3. Try to access main menu

### Expected Result

Global menu is accessible and says Bitwarden

### Actual Result

Global menu belongs to previously focused app, there is no way to access bitwarden menu.

This happens somewhat randomly and restarting bitwarden fixes it for a while.

### Operating System

macOS

### Operating System Version

14.4.1

### Installation method

Mac App Store

### Build Version

2024.4.1 (23240)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
