### ISSUE TITLE
include a verified badge in bitwarden flathub

### ISSUE THREAD

**Issue by userforsource** [bitwarden/clients#9368]
### Steps To Reproduce

https://flathub.org/apps/com.bitwarden.desktop
This need to be verified like other apps are without verification this is hard to trust just because this is a app which used for password. Hence the app security and trustworthy is also needed.

### Expected Result

This need a verified badge

### Actual Result

This does not have a verified badge.

### Screenshots or Videos

After steam deck everybody use flathub
Snap is stll a thing butonly for ubuntu base distros.
But if we consider chrome os or steam deck there is a almost 200M devices because most schools have chrome book and steam deck is also now sold like a hot cake.

### Operating System

Linux

### Operating System Version

flathub

### Installation method

Other

### Build Version

2024.05.23

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by quexten** [comment]
From the FlatHub page you linked:

>  This wrapper is not verified by, affiliated with, or supported by 8bit Solutions LLC. 

The FlatHub version is currently not managed by Bitwarden but a community-created wrapper: https://github.com/flathub/com.bitwarden.desktop

**Comment by userforsource** [comment]
There is no reason not to support it.

**Comment by SergeantConfused** [comment]
Hi @userforsource,

Thank you for this report. This sounds more like a feature request or an improvement suggestion, than a report about a malfunction or an unexpected behaviour of some kind. In either case, this is already being [discussed on GitHub](https://github.com/bitwarden/clients/issues/6795), and there's also a [Bitwarden community thread](https://community.bitwarden.com/t/bitwarden-should-manage-its-flathub-application/30823) about it; Please feel free to contribute to either thread, if you wish.

I will now close this GitHub report in order to consolidate this matter into the existing threads; If you have any questions or concerns, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/).

Thank you again,
