### ISSUE TITLE
Autofill and CTRL+Shift+L not working

### ISSUE THREAD

**Issue by juarez-spa3** [bitwarden/clients#9369]
### Steps To Reproduce

1. Go to https://imgur.com/signin
2. Wait for autofill. Autofill does not work.
3. Refresh the page. Autofill does not work.
4. Try CTRL+Shift+L, this keyboard shortcut doesn't work either.

### Expected Result

Autofill and CTRL+Shift+L stopped working after version 2024.5.0. Reinstalling the extension temporarily solves the problem, but after turning the computer off and on, the problem occurs again.

This issue is not specific to Imgur. I can also reproduce the problem on different websites.

### Actual Result

-

### Screenshots or Videos

I don't know if it's useful, but here's a screenshot of the console
<details><summary>Screenshot</summary>

![brr](https://github.com/bitwarden/clients/assets/153795294/e2ce402a-ef36-4b99-a01d-4fedd654a946)

</details>

### Operating System

Windows

### Operating System Version

Windows 10 22H2

### Web Browser

Brave

### Browser Version

1.66.115 Chromium: 125.0.6422.112

### Build Version

I dont know

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pamperer562580892423** [comment]
I think I have a similar problem as described here. With the new Browser Extension 2024.5.0 (BTW: Server Version 2024.5.0, Brave 1.66.115, Windows 11), when I first unlock after opening Brave, then I don't see the "number" of logins in the extension symbol, and can't use Auto-fill - and e.g. on the Google website, when I try to login (entering my email address), then in the new inline-auto-fill menu it says "no entry to view" and I can't use my in-Bitwarden-stored-passkey for Google.

When I then lock the browser extension and then unlock again, it works as usual. So you could say, I have to unlock-lock-unlock so that the extension correctly recognizes my logins for a certain website I'm on in my browser.

This is new behaviour since a few days, I would say.

**Comment by pamperer562580892423** [comment]
@juarez-spa3 Interesting. So our problems might be the same.

I can now add, that if the last "lock" lasted for a period of time (in the sense of "not short" / "not immediately") the problem occurs.

If the last "lock" was **_recently_** done, auto-fill works as expected.

But don't ask me for an exact time frame... If the problem persists, I might consider measuring time using scientific methods. ;)

**Comment by InnocentRain** [comment]
I think i have the same problem, but only in the chrome extension. 
Even if i click into the window i get the message "No items to show" but the url is correctly configured and it works just fine on mobile and in other browsers like firefox. 
If i'm on the page and i click on the extension itself i even see the login so it detects the url just fine.

**Comment by SergeantConfused** [comment]
Hello @juarez-spa3 and everyone else,

Thank you all for your input. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by Flwk** [comment]
Hi, I have the same problem : 
![Capture d'écran 2024-05-27 234650](https://github.com/bitwarden/clients/assets/3245665/763c8d90-645a-4ea9-b11b-e615f2de18b5)

As you can see, It show that there is no item, but if I click manually on the extension, there is one saved. I tried to uninstall and reinstall the extension, but the problem reappear after some time.
