### ISSUE TITLE
Windows Hello Verification no Longer accepted

### ISSUE THREAD

**Issue by AWHCC** [bitwarden/clients#9388]
### Steps To Reproduce

1. Using Version 2024.4.1
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64
2. Launch Bitwarden 
3. Click on Unlock with Windows Hello
4. Click on Ok in the Windows Hello dialog.
5. Bitwarden returns to the locked screen inviting user to click on Unlock with Windows Hello
6. Bitwarden will only open iof the master password is entered. 

### Expected Result

I expected Bitwarden to accept the Windows Hello verification and open the vault.

### Actual Result

Doom Loop with endless attempts to log on with Windows Hello.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of Windows Hello settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by AWHCC** [comment]
Could be but everything worked together until mid-last week. Will explore further.

On May 27, 2024, at 6:40 PM, sammbw ***@***.***> wrote:

﻿

Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of Windows Hello settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!
