### ISSUE TITLE
Can't use desktop app in self hosting

### ISSUE THREAD

**Issue by aleandro6804** [bitwarden/clients#9413]
### Steps To Reproduce

1) Install bitwarden in self hosting
2) Try to connect using the desktop app

### Expected Result

Desktop app to connect the account

### Actual Result

Failed to fetch

### Additional Context

Hi, i installed bitwarden in self hosting on 192.168.178.105 but i can't connect to it using the dekstop app.
The web version is working perfectly but when i try to connect using the desktop version (in the login i set "self-hosted" > "server URL: https://192.168.178.105" and then enter the email and password) it says "unable to fetch".

Am i misconfigurating something?

Thanks in advice

### Operating System

Linux

### Operating System Version

Arch Linux

### Installation method

Other

### Build Version

2024.5.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by perdingus** [comment]
Hi, exactly the same for my install.

Build Version

2024.5.0

Operating System

Linux
Operating System Version

Ubuntu Linux 22.04

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
