### ISSUE TITLE
safari plugin: autofill option keeps re-enabling itself

### ISSUE THREAD

**Issue by aaron-trout** [bitwarden/clients#9416]
### Steps To Reproduce

- Set the auto fill setting to off
- Some time later, it will re-enable itself (maybe after restarts or updates, I'm not sure)

<img width="403" alt="Screenshot 2024-05-29 at 19 16 15" src="https://github.com/bitwarden/clients/assets/2394679/0c4b93b8-b5ab-477a-a59e-4f039103d955">

### Expected Result

Once I turn the auto fill off, it stays off.

### Actual Result

It turns itself back on. I must've disabled it 20 times at this point. 

### Screenshots or Videos

See above. 

### Operating System

macOS

### Operating System Version

14.5 (23F79)

### Web Browser

Safari

### Browser Version

Version 17.5 (19618.2.12.11.6)

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
