### ISSUE TITLE
fail to search Amazon

### ISSUE THREAD

**Issue by alexfung888** [bitwarden/clients#9423]
### Steps To Reproduce

1. Go to the search box, click on it
2. Type 'Amazon'

### Expected Result

searches for amazon, or any substring of it (eg azo). I have a handful of hits.

### Actual Result

the list of logins do not change, as if all of them matches the searching criteria. For example, after typing "ama", the whole list is still being shown.

The moment I type something new (eg after "ama", add "s"), then the list is updated (since I don't have anything that matches "amas").

It seems to say that every entry of my vault includes "amazon".

What is weird is that this is the only platform with this behavior. With Chrome extension or Android version, they search for "amazon" without any problem.

### Additional Context

Version 2024.4.1
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

### Operating System

Windows

### Operating System Version

LTSC 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the URI values containing an Amazon string.

Searching your vault: https://bitwarden.com/help/searching-vault/#full-text-search

I'd also recommend updating to 2024.5.0 - if your client doesn't detect the update, you can download it from the link below. 

Bitwarden Downloads: https://bitwarden.com/download

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by alexfung888** [comment]
Haven't I said that chrome extension or the android client (of Bitwarden) search for Amazon without problem? I don't see how it "could have its origin in the URI values containing an Amazon string" when it only affects one platform.

**Comment by alexfung888** [comment]
After locking and reopening the vault, behavior returned normal. I cannot reproduce the effect any more. However, it definitely looks like a bug in the Windows client.
