### ISSUE TITLE
SyntaxError: Unexpected token '{' in Safari 15.6

### ISSUE THREAD

**Issue by samdharris** [bitwarden/clients#9427]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/login in Safari 15.6

### Expected Result

It should load the login form normally.

### Actual Result

The loading gif spins continuously and in the Safari dev tools, the error "SyntaxError: Unexpected token '{'" appears.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/8377862/1bd5f187-361b-4ccf-ae47-2541a7f11cf6

### Operating System

macOS

### Web Browser

Safari

### Browser Version

15.6.1

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by samdharris** [comment]
I appreciate this is an old version of Safari however I am not using this, I am reporting it on behalf of someone less technical and without the ability to upgrade to the latest version of Safari

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. The current version of Safari is indeed outdated can cause issues. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by djsmith85** [comment]
@samdharris: The recent changes made [here](https://github.com/bitwarden/clients/pull/9383) to support older browser versions, will be included in the next release. Hopefully this resolves this issue for you and the person you are supporting.
