### ISSUE TITLE
Vault timeout set to 24 hours but vault is locking every time I restart Firefox

### ISSUE THREAD

**Issue by jikamens** [bitwarden/clients#9469]
### Steps To Reproduce

1. Configure your vault timeout to the custom value of 24 hours with it set to lock upon timeout.
2. Quit and restart your browser.
3. Observe that your vault is locked.

### Expected Result

Vault stays unlocked for 24 hours even across browser restarts.

### Actual Result

Vault locks immediately when browser is quit and restarted.

### Operating System

Linux

### Operating System Version

Debian testing

### Web Browser

Firefox

### Browser Version

126.0.1

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
This is the [expected behavior](https://bitwarden.com/help/vault-timeout/#web-and-browser-extension-timeouts) and not something we plan on changing. When the browser closes we lose our ability to store information securely (in process memory), and we also lose any ability to run code to clean up data.
