### ISSUE TITLE
Cannot fill email and password boxes manually on websites when Chrome Extension is active (Chrome on MacOS)

### ISSUE THREAD

**Issue by Sandro87to** [bitwarden/clients#9473]
### Steps To Reproduce

1. On any website with an email or password box, try to input any text

### Expected Result

Be able to input text in the boxes

### Actual Result

No text is accepted

### Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Web Browser

Chrome

### Browser Version

Version 125.0.6422.77 (Official Build) (arm64)

### Build Version

Version: 2024.5.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a related issue which you can see here: https://github.com/bitwarden/clients/issues/8093

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a related issue which you can see here: https://github.com/bitwarden/clients/issues/8093

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!
