### ISSUE TITLE
After logon under the menu unexpected text is displayed

### ISSUE THREAD

**Issue by pgatzoyas** [bitwarden/clients#9475]
### Steps To Reproduce

please see attachement
[Bitwarden Desktop issue.pdf](https://github.com/user-attachments/files/15528548/Bitwarden.Desktop.issue.pdf)

### Expected Result

the extra lines not to appear

### Actual Result

several lines with text appear

### Screenshots or Videos

[Bitwarden Desktop issue.pdf](https://github.com/user-attachments/files/15528553/Bitwarden.Desktop.issue.pdf)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @pgatzoyas 

I am unable to reproduce this issue, Could you please uninstall or reinstall your desktop app or update to the most recent version and let us know if this issue persists by contacting support team. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.

Thanks!
