### ISSUE TITLE
Always refreshes automatically

### ISSUE THREAD

**Issue by ChishFoxcat** [bitwarden/clients#9493]
### Steps To Reproduce

1. Add a new hosting server
2. Add an account
3. Add a lot of accounts and passwords to any place, and wait for more than ten seconds to refresh

### Expected Result

Auto-refresh is not required.

### Actual Result

Refresh every 5 seconds all the time.

I've added a lot of accounts, and when flipping through the accounts below, the auto-refresh leads to a return to the top.

### Operating System

Windows

### Operating System Version

Windows 11 24H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the import process not having a chance to complete first.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
