### ISSUE TITLE
Horrible desktop UI

### ISSUE THREAD

**Issue by pkExec** [bitwarden/clients#9530]
### Steps To Reproduce

Use the desktop client for a bit, leave the computer for some time, and get back to a screen like this.
![bitwarden](https://github.com/bitwarden/clients/assets/7925305/b308a16a-d0fb-42af-a798-ad9e4433778e)

### Expected Result

An intuitive UI.

### Actual Result

1. The middle column is displaying the search results from above. It's not related to the first column.
2. The third column is displaying an item I had selected some time ago. It has no connection to either the first column, or the second column (!).
3. Search does not show the expected items. Do you know why? Because I had selected a folder that's in the first column. But I scrolled. So now I don't know that I have something selected. And I think search is broken. Until I remember to check -"hey do I have all items selected?"

### Additional Context

Quick fixes for the mess:
- Above/Below/Left of the searchbar, show a message: "Searching in Vault X, Folder Y, Collection Z"
- Make the selected item screen modal
- The options "All items", "Favorites", "Trash" do not belong in the navigation pane, either aesthetically or by function. "All items" should not act as a filter, it should be the default option. "Favorites" should be an on/off button. "Trash" should be an on/off button.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
