### ISSUE TITLE
Bitwarden won't be able to recognize nested subdomains of url

### ISSUE THREAD

**Issue by surapuramakhil** [bitwarden/clients#9534]
### Steps To Reproduce

create few accounts on workday - typically each company's workday account is considered different.
if you have more than 10 workday accounts, you need search using company name.

### Expected Result

most url match shoud be on top

### Actual Result

most count on url is on top

### Operating System

macOS

### Web Browser

Brave

### Build Version

2024.5.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
