### ISSUE TITLE
Biometrics on BW for Chrome not working requesting PERMANENT unlock of BW for Windows 

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#9539]
### Steps To Reproduce

1. Activate Windows Hello on Bitwarden Chrome extension
2. BW for Windows is not currently unlocked
3. Open Bitwarden Vault with Windows Hello

### Expected Result

Bitwarden Chrome extension should open you vault so that you can enter your credentials on the websites you want.

### Actual Result

You get the error:
"User locked or logged out
Please unlock this user in the desktop
application and try again."

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/98819304/041c61b1-4b4a-4f63-a7b0-b150b1ea2264)

### Additional Context

If BT for Windows is unlocked when using biometrics on BW for Chrome, you can unlock BW for Chrome extension. BUT this completely defeats the purpose of BW for Chrome extension.
Furthermore if you have to keep unlock BW for Windows to use BW for Chrome, it is a major security issue.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Version 125.0.6422.142 (Official Build) (64-bit)

### Build Version

Extension=v2024.5.2  Windows client=2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by alex-ioma** [comment]
I concur this is a major issues. Having the need to unlock the BW desktop client to be able to use Biometric (after the app and the browser extension have been already connected) is a major usability impairment which defeats the whole purpose of having a browser extension. 

Additionally I add that the same issue also happens with Bitwarden Chrome extensions on MacOS. I'm not sure if a new issue is needed since the issue is exactly the same as the one reported above. 

Please advise.

<img width="1479" alt="Screenshot 2024-06-07 at 2 06 04 PM" src="https://github.com/bitwarden/clients/assets/76006253/a18f2aec-60a3-4e09-bb00-a90b3bf21d25">

**Comment by steeviebops** [comment]
I seem to be having the same issue on Firefox on Windows 11. In my case, clicking the "Unlock with Biometrics" option in the browser extension causes "Awaiting confirmation from desktop" to flash briefly but the Windows Hello prompt never appears. It will only work if I unlock the desktop client first.

**Comment by oeloo** [comment]
Your issue is similar. The problem seems to be due to the BW desktop. This is a big issue: not only does it break the user's process of using BW (no Windows Hello), but it is also a major security issue (force having BW unlocked to do your daily work).

**Comment by alroberts** [comment]
I'm so damn sick of this issue. Guys.. just fricking fix this already.. it's been months and it's just such a damn annoyance.
![BitWarden-Annoying](https://github.com/bitwarden/clients/assets/21023684/2245a509-dae6-44d5-8430-6ac01dc24afd)

This situation (or similar) has been reported so many times.. Why is there no real acknowledgement of the issue? I like BitWarden but why the hell do I pay for it if this can't be fixed after a year already?

**Comment by alex-ioma** [comment]
@oeloo I would also adjust the issue Title as this thread might be used as a general issue that encompass more OSs and Browsers (the root cause might actually be the same).

**Comment by oeloo** [comment]
@alex-ioma This should be the role of the BW dev team community. Also given the severity of this issue, it is not acceptable to have any feedback ( I am not even talking about a solution here) from the BW dev team community.

**Comment by MGibson1** [comment]
Hi all, I promise we're aware and looking into flow improvements. I've outlined our current plan below, and feedback is welcome. This change is actually a short-term response to a detected security issue where biometric authentication from the browser could cause user keys to persist in desktop memory for an extended period.

The method we have of preventing long-lasting retention of sensitive data is by forcing the application to crash and restart, which we internally call process reload. It's very destructive, though, and needs to be handled by the Desktop client directly, not whenever the browser asks for a key.

The short term "solution" here was to allow the Desktop to handle user sessions as it was designed to do by needing to be unlocked prior to handling sensitive data. That way, process reload will ensure the data is disposed of automatically when the user locks or logs out of the Desktop client.

I _totally_ understand that this is a frustrating user flow change, but it was done to ensure that sensitive data is managed appropriately.

To clarify, you do not need to keep the Desktop application unlocked the entire time you use the browser, it only needs to be unlocked when you do the key exchange. I realize that that may mean unlocking twice, for now. In light of that, does anyone see a security vulnerability? I take those very seriously, but I believe this actually minimizes risk for now.

### Planned approach
The planned long-term approach for browser biometric authentication right now is to unlock the desktop client at the same time as the browser client when performing biometric authentication with the browser. That way, the user's session is managed appropriately in both the desktop and the browser. It also removes the need to separately authenticate in each client.

**Comment by alroberts** [comment]
@MGibson1  - Can you provide a timeline?

**Comment by kapitainsky** [comment]
> I _totally_ understand that this is a frustrating user flow change, but it was done to ensure that sensitive data is managed appropriately.

Thank you for detailed explanation. But how it is done in Safari browser where all works - I can unlock BW without unlocking desktop client.

**Comment by Overblown8831** [comment]
hello,
this also happens with our Edge browser. is there a schedule so that it is more enjoyable to use Bitwarden again and you don't have to unlock twice? 

**It becomes more of a risk if it becomes too complicated for users and they go back to using simple passwords or sticking them under the keyboard.**

**Comment by blxckbxrd** [comment]
@Overblown8831 > **It becomes more of a risk if it becomes too complicated for users and they go back to using simple passwords or sticking them under the keyboard.**

I run IT classes at church and in our community hall, and I constantly have to deal with groups who want to go back to older versions of software or bad practices as soon as the UX or flow changes somewhere.

But this happens with all software, not just Bitwarden.

At the moment I'm trying to turn this to our advantage and make people aware of the desktop client. But I also have to admit that I have put off explaining the desktop client too long because of the way the sync works.

Users add a new password in their browser add-on and then can't find the password in the desktop client until they manually sync.

The smartphone client was a non-issue because I teach "swipe down to refresh" in the basic class, but the desktop client when they bring their ancient laptop behemoths, well, that's another story.

The solution @MGibson1 talked about seems like a pragmatic and good way to solve the current issue. I'm looking forward to it, and if I can contribute anything other than introducing more users to Bitwarden, I'm happy to do so.

However, I would suggest some urgency, because Apple is about to do their own password thing, and that could lead too many of our beautiful sheep astray - Bitwarden has to be the best solution for the most people. Long live Bitwarden!

**Comment by oeloo** [comment]
> To clarify, you do not need to keep the Desktop application unlocked the entire time you use the browser, it only needs to be unlocked when you do the key exchange. I realize that that may mean unlocking twice, for now. In light of that, does anyone see a security vulnerability? I take those very seriously, but I believe this actually minimizes risk.

This workflow process, even temporarily, is not acceptable for users: not only is it cumbersome to explain this weird workflow to many users (it looks so weird), but even if they start doing it, it is a pain to do and a time lost. 
What about the security risk associated with the duration of two leases? In BW, you cannot even log out of both simultaneously! This urgent change clearly risks the security of BW users.
Destroying users' workflows is probably worse for security than the technical security hole you discovered: it might be exploited by a few very high-tech hackers, while leaving one of the clients unlocked is a security hole anyone can exploit!
Please provide a way for users to accept this small technical security hole to keep their normal BW workflow while you work on an urgent fix that does not break BW users' workflow.

> ### Planned approach
> The planned long-term approach for browser biometric authentication right now is to unlock the desktop client at the same time as the browser client when performing biometric authentication with the browser. That way, the user's session is managed appropriately in both the desktop and the browser. It also removes the need to separately authenticate in each client.

1Password has been using this approach since at least 2019: unlocking the 1Password desktop application also unlocks the 1Password Chrome add-on (and vice-versa).
If 1Password had discovered this security hole before 2019 and fixed it in 2019, I don't understand why BW only recognized it in 2024.
On 1Password, locking vault from one of 2 clients, locks both since 2019. This is very important for security; unfortunately, in BW in 2024, you can still not log out from the Chrome BW addon and desktop client at once.

**Comment by vision2003** [comment]
Security is of course very important, but this change renders unlocking via Windows Hello useless to me, as it's faster to type in the master password and be done with it. Not to mention that I migrated from LastPass to BitWarden (and am also paying $10/year) solely because of the Windows Hello feature.

**Comment by cpainchaud** [comment]
I hope the "long term" plan is for next week because it's damn annoying to open Bitwarden app before I can log in anywhere. 

If at least the browser plugin could make the BW app unminimize/popup that would be of great help already.

thank you

**Comment by 0ldb34r** [comment]
I can't believe how much everyone complains that the Bitwarden team has discovered a vulnerability and is trying to fix it, in their own interests as well as in those of their users, just because it inconveniences them a little for an indeterminate period of time. When proprietary companies don't do their job when it comes to keeping their users data safe, it often ends in scandal and instantly brings the company into disrepute - witness LastPass, which was the target of password thefts last summer. It seems to me that Bitwarden has every reason to take precautions, especially as flaws of this type are not necessarily exploited as everyone thinks. A vulnerability can be misused, sometimes in ways we hadn't even considered, and when it is, it's often a real mess.
Yes, it changes our habits a little, but between risking having my passwords exposed (even if the risk was slim) and having to click twice instead of once when I unlock my computer, the choice is quickly made.
I'm aware that this may affect certain uses more, but what a lack of respect when everyone comes whining with their little threat to leave the service, with no respect for the ethics of the developpers behind it.
My only personal regret is that I searched for 3 days, thinking that the problem was with my configuration and not with Bitwarden. Luckily I found this post to help me understand: a little message when opening BitWarden would have made things easier for a lot of people, I think.

**Comment by cpainchaud** [comment]
@0ldb34r  I believe you should put yourself in the shoes of business users where IT team has to manage user discontent : not only IT support was not aware of this very impacting and tickets are piling but they are now in a situation where they have to explain non IT users that they need to open BW desktop app to unlock then open browser extension to unlock and do that X amount of time a day. 
Yes it's good for security but now they are explaining that the real fix will be "long term" and that in the meantime users should just go with it. The fix should be very short plan or users will want extra long auto lock delay to avoid the situation -> less security.

**Comment by 0ldb34r** [comment]
@cpainchaud Except that there are other ways of doing this, which are just as secure: using a PIN code while waiting for the problem to be dealt with, for example. 
I fully understand that this is an embarrassment and a difficulty for your teams, but you seem to be putting aside what is required of a password manager above all else: ensuring the full and complete security of the data it stores.
If the solution were simple, Bitwarden wouldn't take much pleasure in pointing out that the solution will be found in the long term! 
Personally, I won't put my passwords with Dashlane and I won't put them with LastPass, who are completely opaque about their policy in the event of a breach. But it's up to you to make the switch. When you accept a deal with a company, you accept the ethics it upholds: in this case, putting vulnerabilities ahead of optimizing the user experience at all costs. This is consistent with an OpenSource model. 
The real question is: do you think that a bunch of you ranting and raving is going to speed up the handling of this security flaw? Or are you doing it just to let people know you're unhappy? If the latter, Bitwarden already knows about it...

**Comment by cpainchaud** [comment]
@0ldb34r you do underestimate users stupidity : if it's too inconvenient, they will go back to post it notes or whatever software they find on Google. That's real life. 

I am here to make sure that they understand that it's not something they can wait for next year.

**Comment by abinthomas744** [comment]
Can we please have a rough estimate of how long will it take for this issue to be resolved?

**Comment by masterflitzer** [comment]
> I can't believe how much everyone complains that the Bitwarden team has discovered a vulnerability and is trying to fix it...

i don't like the lack of communication about this, of course security fixes should land fast, but then notify me in the app with a little info icon that the functionality changes, i wasted time by trying to figure out what happened and finding this issue

**Comment by ejain** [comment]
Noticed this behavior on both Windows and macOS, assumed it was just another bug...

**Comment by alroberts** [comment]
I just want this damn issue resolved and a ETA. In one month my subscription expires.. it's been more than 1 month since these sorts of issues existed, especially on macOS.. So just please get on with this and fix it.. it shouldn't be rocket science.

**Comment by oeloo** [comment]
> @MGibson1
> 
> > I've outlined our current plan below, and feedback is welcome.
> 
> Would it be possible to design a light-weight "helper" app that could do the key exchange _instead_ of using the full Desktop app for this purpose? One benefit of this would be that the helper app could be set to have a much shorter timeout interval than the Desktop app. Additionally, perhaps such a helper app would not need access to the full vault contents, which might improve security (conversely, requiring the extension and the full desktop app to be simultaneously unlocked will increase the attack surface exposure). A further benefit would be decreased resource consumption on the client device.

Initially, BW desktop app vault was not unlocked when you used Windows Hello to unlock BW Chrome extension. In reverse, when unlocking your vault on BW desktop it was not unlocking your vault on Chrome extension. I think this is annoying because it also means that locking in one does not lock in the other. This is the way BW worked and in my opinion it is a security issue as many users thought that locking one locked all. So one BW tool was still unlocked !
1Password has a better good way to manage this: locking any of them, locks both. BW should do the same.

**Comment by norrisgc** [comment]
Having become increasingly frustrated by this behaviour change a month or so ago, and hoping it would be fixed soon, I've come here to discover that there's no imminent plan to actually fix it, just discussion. I'm now preventing BW locking automatically just to avoid having to keep re-opening the desktop application just to use a password in a browser. This is a very long way from ideal security and - premium subscription or not - I will very soon stop using BW (and of course, there will be no renewal - in less than a month from now.)

**Comment by cdavidowski** [comment]
I have this same issue on MacOS, so adding my vote for it to be fixed.  It is annoying for my personal use, but manageable. I can understand the frustration of administrators if you have non-technical end users.  Thanks for looking into it.

**Comment by ptoump** [comment]
Coming from #9887 , and I quote my comment there:

> That makes a lot of sense security wise, but from an ease of use perspective we shouldn't need to open the desktop app each time we need to unlock the extension.
> This will lead to keeping the desktop app unlocked for much longer periods which beats the purpose.
> I would suggest finding a way to do this "automatically" for example automatically requiring 2 biometric unlocks, one for the app and one for the extension in succession, without the user having to try to unlock the extension, fail, open the app, unlock it and then try again to unlock the extension.
> If the app is locked, then automatically prompt to unlock it..
> 
> I hope it makes sense..
> 
> Thanks,
> Panos

I agree with most of the comments here, and thank you to the team for being on top of this. 
As frustrating as it is, it's good to know that a solution is planned.

**Comment by thericle** [comment]
Until now, it was possible to unlock browser extension _using_ the desktop app, but without _unlocking_ the desktop app. Is this correct?

If I understand correctly, even after this issue is resolved, the desktop app will need to be unlocked in order to perform biometric authentication on the browser extension, it will just happen automatically instead of manually.

It doesn't seem ideal to me, since the desktop app will still be unlocked even though the user doesn't need it. I wonder if it's possible for the desktop app to be locked immediately after the authentication has finished.

**Comment by MGibson1** [comment]
For those wanting updates, we've been hard at work updating quite a lot in our browser extension <-> Desktop IPC communications. The PR relevant to this Issue is https://github.com/bitwarden/clients/pull/9945, which removes this unlocked check.

**Comment by abinthomas744** [comment]
Is it just me? or is this still a mess?

I tried installing the latest desktop version and also sideloading the latest browser extension
but it keeps asking me to enable browser integration in the desktop app when I try to enable biometric unlock on the browser, which is already enabled though

**Comment by tahayparker** [comment]
i was facing the same issue, turned out that it was because i had disabled vbscript, and so bitwarden wasnt able to run the code to enable browser integration. i would suggest reading the logs to understand what's happening

**Comment by d3smo** [comment]
Do you have any idea when it gonna been merged ?

**Comment by abinthomas744** [comment]
I've upgraded to the latest 7.1 update both desktop and browser extension, but the issue is still there.
It still asks to unlock the desktop application first to unlock the browser with biometrics

anyone else facing the same issue?

**Comment by brainiac19** [comment]
Prioritize this one please, huge impact on user experience.

**Comment by RainrZufall** [comment]
I know that the problem is being worked on, but after all these weeks/months, I have to give my opinion on it.

It's very frustrating if you actually value security. I normally lock my Bitwarden container as soon as my PC is locked (I'm not at the PC).

I now only lock Bitwarden when I shut down the PC because it's so incredibly tiring to always unlock the desktop app first in order to then unlock the browser extension as well.

With every update, I hope that this behavior will be stopped.

**Comment by oeloo** [comment]
I fully agree with this, the decision of the Bitwarden team toward this security problem is short-sighted. Technology is not the only thing in a well-secured system, breaking the security process of all Bitwarden users for a small security hole that can only be abused by very advanced technical gurus is stupid. Like many other BW users due to this bug, I have no choice but to leave my wallet permanently unlocked. Now every person, even with absolutely no technical knowledge can hack my account.

Before the decision of BW, maybe just a dozen individuals had the high technical knowledge to hack BW accounts, now they are a billion people that could potentially hack my BW account.

At least empower the end user with an option to let him decide what he considers the safest option.

**Comment by blxckbxrd** [comment]
I understand why it is the way it is at the moment, and from a technical pov I think it all makes sense. I've been using a PIN as a workaround, as @bwbug mentioned.

However, the problem with a lot of good sec practices is that they are super challenging for older users. I volunteer in my parish to help seniors with their tech and sec, and passwords and phishing are one of the main issues.

Getting them to use Bitwarden instead of Post-its, Chrome or Firefox passwords hasn't been easy, and I hate to tell you that many of them are now pressing to revert back to worse practices because of the current user experience.

Which brings me to my personal experience: I recently get a lot of heat for recommending Bitwarden. I have to accept that they think "I'm a genius and a wizkid" and to use Bitwarden you have to be under 30 and have an IQ of around 160.

This makes me feel uncomfortable and more and more frustrated. Older people are the most vulnerable group to online scams and phishing, and they just can't adapt as easily to change. They can also be a bit stubborn sometimes. It's a big obstacle for them if they have to authenticate twice, and as soon as they get the hang of it, the user experience might be different all over again.

**Although many users are pushing for a change to be shipped soon, I think this part of the user experience should be well thought out rather than rushed.**

I don't know if there's a financial incentive, but in my experience, boomers and older seniors end up signing up for family plans and have an easier time with Bitwarden overall than with supposedly "more user friendly" competing products, but please consider scenarios like mine where you have to manage and teach Bitwarden to groups of users, and the challenges that come with it.

**Comment by Jayspek** [comment]
Looks like this pull request was merged yesterday, hopefully the fix will be in the next update?
https://github.com/bitwarden/clients/pull/9945

**Comment by blxckbxrd** [comment]
The Firefox Add-on could be taking its sweet time though, but that's not because of Bitwarden-slo-mo. He's just an old fox.

Lamentations 3:25

**Comment by bilogic** [comment]
> Looks like this pull request was merged yesterday, hopefully the fix will be in the next update? #9945

it seems that the fix was implemented in the desktop app, correct?

**Comment by Jayspek** [comment]
Yes, my understanding is that the desktop app will now be able to unlock the extension without unlocking itself, which allows it to work around some sort of key storage issue.

**Comment by bilogic** [comment]
I tested. To workaround the issue, revert the desktop app to 2024.6.4 and avoid 2024.7.1, i.e. only update after a newer desktop has been released.

**Comment by bilogic** [comment]
@jlf0dev Can we please make a release of the desktop app to include #9945? 

The latest web release has broke the workaround for this problem...

**Comment by dstmar** [comment]
Updating to Desktop v2024.8.0 has resolved this issue for me.  Still running 2024.7.1 on Firefox plugin.

**Comment by MajorQuake18** [comment]
Same here! Thanks to the devs

**Comment by basrieter** [comment]
Thanks for all your efforts BW! ❤️

**Comment by sn55997** [comment]
Finally! Thanks to the developers. Quick work after all!

**Comment by tahayparker** [comment]
Thank you devs! 🖤

**Comment by aphillips69** [comment]
Thanks for the fix 👍🏻

**Comment by ySkNight** [comment]
Thank you for the fix! Add to this can we get browser extension to prompt if we enabled biometrics? Current workflow we have to click on extension or use hotkey to bring UI up and click on "Unlock with biometrics".

Hopefully we can have this QOL change sometime.

**Comment by oeloo** [comment]
@Bitwarden Team, Thank you for the fix, it is working perfectly.

**Comment by abinthomas744** [comment]
Thank You very much to the team for this fix, it had been bugging us a lot for a while now

**Comment by JafCR** [comment]
not working for me on my mac M1 running Sonoma 14.5

**Comment by gitSambhal** [comment]
Try updating the extension and app to the latest version.

**Comment by JafCR** [comment]
been working well for a few weeks now.
thanks

**Comment by alex-ioma** [comment]
It seems to work great besides a use-case: 
If you set the lock to "Immediately" as I typically do on the desktop app so that the client immediately locks as soon as it is closed or left idle, the extension lock itself in the middle of the use, say when you are creating a new entry or generating a pwd.

**Comment by alex-ioma** [comment]
Confirmed. Problem solved. Working well also with Vault Timeout "Immediately".
