### ISSUE TITLE
Credit Card Info Autofill doesn't work

### ISSUE THREAD

**Issue by Toryalai1** [bitwarden/clients#9546]
### Steps To Reproduce

1. Go to a random website that has a check out page
2. In the credit card info, right click and select autofill card
3. Nothing gets filled in

### Expected Result

I expect the card info to be filled in

### Actual Result

Card info doesn't get filled in

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/82502378/2d200e2b-0755-447c-a41d-bcf835a5e8e8)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

 2024.5.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @Toryalai1 

I attempted to reproduce what you have described here and it works as expected; 

![image](https://github.com/bitwarden/clients/assets/91448810/5255c064-5148-44f6-9e7d-befc32f7f845)


We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by apazzolini** [comment]
@Adedamola-Aina Could you confirm credit card autofill works for you on a Shopify based site? ([here's one if you need it](https://backsidesandpaper.com))

Credit card autofill works for me on all sites *except* Shopify ones.
