### ISSUE TITLE
Using 2FA code from Browser Extension fails Account login, 2FA code from iOS works

### ISSUE THREAD

**Issue by glanham-jr** [bitwarden/clients#9553]
### Steps To Reproduce

This behavior is specifically reproduced with the following scenario.

**Prerequisites**
- Have a GitHub account + Enable 2FA on GitHub (using BitWarden 2FA)
- Have 2FA available for BitWarden

**Steps to Reproduce**
1. Login to Bitwarden on iOS
2. Login to Bitwarden on Windows 10 + Firefox / Chrome Extension
3. On Windows 10, open Firefox / Chrome and navigate to GitHub
4. Login to GitHub with autofilling username/password
5. **Enter 2FA code from Browser Extension**

### Expected Result

1. The 2FA code from my extension works and I am able to login to the account
2. The 2FA code matches what I have on my iOS Bitwarden App

### Actual Result

1. The 2FA code does **not** work from the Bitwarden browser extension
2. The 2FA code from my iOS Bitwarden app doesn't match what I see in the Bitwarden extension (looking at both at the same time)
3. By manually entering the 2FA code from my iOS Bitwarden app onto the browser login, I can log into GitHub

### Additional Context

**Hardware / Software Details**
1. iPhone XS + Bitwarden App
2. Windows 10, Firefox / Chrome + Bitwarden Extension

I'm not sure if this is specifically a GitHub issue, or some strange Bitwarden client issue. Curious if anyone else can reproduce.

I've also been dealing with this for quite some time. I even updated the KDF settings on my BitWarden, logged out all clients, logged back in, and the bug still occurs. I believe I have also tried deleting and updating the 2FA code on GitHub as well, but it still occurs - happy to try this again however.

I'm also having this occur on other logins, I just chose GitHub since its the site I'm using right now.

### Operating System

Windows, iOS

### Operating System Version

Windows 10, iOS 17.5.1

### Web Browser

Chrome, Firefox

### Browser Version

Latest - has been a problem for a while

### Build Version

Version 122.0.6261.95 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @glanham-jr,

Thank you for this report. Could you please set both the Time and the Time Zone to Automatic on your computer and try to use the 6-digit TOTP codes that are being generated in the Bitwarden browser extension then? I mention that because invalid/incorrect 6-digit TOTP codes can stem from having the incorrect Time and/or Time Zone set on the device that's generating the codes or that is validating them. You can learn [more on this here](https://bitwarden.com/help/integrated-authenticator/).

I hope you find this clear and helpful; I will now proceed and close this GitHub report. Please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/) if you have any questions or concerns.

Thank you again,

**Comment by glanham-jr** [comment]
@SergeantConfused Thanks for the heads up, surprisingly my Time Zone was not set for this computer and had slipped under my radar. And thanks for the context as well :+1:
