### ISSUE TITLE
Microsoft Edge - TOTP to clipboard does not work with "Show auto-fill menu on form fields"

### ISSUE THREAD

**Issue by mbaran5** [bitwarden/clients#9574]
### Steps To Reproduce

1. Open the browser extension
2. Select "Settings"
3. Select "Auto-fill"
4. Check "Override browser auto-fill settings"
5. Set "Show auto-fill menu on form fields" to "When field is selected (on focus)" or "When auto-fill icon is selected"
6. Browse to a website for which you have a Bitwarden login entry with TOTP
7. Go to the login page
8. Click into the username/email or password field
9. Select the Bitwarden auto-fill entry next to the input field
10. Proceed with login
11. When asked to insert TOTP, try to paste the TOTP with CTRL + V

### Expected Result

TOTP being copied to the clipboard.

### Actual Result

TOTP is not copied to the clipboard

### Additional Context
Auto-filling by pressing the keyboard shortcut or manually selecting the login entry in the browser extension is not affected.

**This is working in Chrome** (fixed here - https://github.com/bitwarden/clients/issues/7354), but not Edge. 

Edge is version 126.0.2592.36 and the plugin is 2024.5.2

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Microsoft Edge

### Browser Version

126.0.2592.36

### Build Version

2024.5.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in installing the Chrome web store extension within Edge, which is not officially supported at this time, as we can not guarantee all features will work correctly in Edge.

There is a PR planned to remedy this issue in both Edge and Chrome here also: https://github.com/bitwarden/clients/pull/9266

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
