### ISSUE TITLE
Impossible connexion windows & android

### ISSUE THREAD

**Issue by rpiquerey** [bitwarden/clients#9599]
### Steps To Reproduce

Impossible de me connecter sur l'application bitwarden (windows ou android) par contre je peux utiliser l'extension chrome

### Expected Result

Impossible de me connecter sur l'application bitwarden (windows ou android) par contre je peux utiliser l'extension chrome

### Actual Result

Impossible de me connecter sur l'application bitwarden (windows ou android) par contre je peux utiliser l'extension chrome

### Operating System

Windows

### Shell

Bash

### Build Version

a

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Bonjour,

J'ai tenté de reproduire votre problème, mais je n'y suis pas parvenu. Pourriez-vous essayer de réinstaller l'application de bureau ? 

Nous utilisons les questions GitHub pour suivre les bogues et autres problèmes liés au développement. Si votre problème persiste, veuillez nous écrire en utilisant le formulaire "Contacter le support" situé dans notre Centre d'aide (https://bitwarden.com/help/).

Vous pouvez inclure un lien vers ce problème dans le contenu du message.

Vous pouvez également chercher une réponse dans notre documentation d'aide ou obtenir l'aide d'autres utilisateurs de Bitwarden sur nos forums communautaires (https://community.bitwarden.com/c/support/). 

Le problème sera clos.

Nous vous remercions de votre attention.
----------------------------------------------
Hi there,

I attempted to reproduce your issue and was unable to do so. Could you please try reinstalling the desktop app? 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
