### ISSUE TITLE
macOS downloads offline

### ISSUE THREAD

**Issue by core-code** [bitwarden/clients#9608]
### Steps To Reproduce

1.)  try to download from the previous download URL https://vault.bitwarden.com/download/?app=desktop&platform=macos&variant=dmg

### Expected Result

download succeeds

### Actual Result

download fails

### Additional Context

is this something that will be fixed or should non-MacAppStore downloads be performed only through GitHub in the future?

### Operating System

macOS

### Operating System Version

macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

any

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by lbouriez** [comment]
Hello, same with linux, links are broken (https://bitwarden.com/download/#downloads-command-line-interface)

**Comment by Neonwarden** [comment]
Hi there,

This has been reported to our team and the correct links will be updated shortly.

In the meantime, you can find the 2024.6.0 Desktop App packages here: https://github.com/bitwarden/clients/releases/tag/desktop-v2024.6.0

CLI packages can be found here: https://github.com/bitwarden/clients/releases/tag/cli-v2024.6.0

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

The issue here will be closed.

Thanks!
