### ISSUE TITLE
Can't assign whitespace as a pin key

### ISSUE THREAD

**Issue by simplerick** [bitwarden/clients#9679]
### Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Unlock with PIN'
3. Type whitespace in PIN field
4. Click on 'OK'

### Expected Result

PIN is set to whitespace

### Actual Result

Nothing happens, PIN is not set, no any warnings

### Additional Context

Actually I think I found where this happens. Is there any reason to use isNullOrWhitespace instead of isNullOrEmpty? Because I've been using whitespace as a PIN code for years.

https://github.com/bitwarden/clients/blob/18b56c0b5a14e8e143bb5adb8bcf3384c325004f/libs/angular/src/auth/components/set-pin.component.ts#L43C1-L43C41

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2024.5.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @simplerick,

Thank you for this report. That is the expected behaviour of the Unlock with PIN function at this time; If you'd like this to change and to be able to set a PIN that's completely composed of spaces, please consider submitting this as an improvement suggestion/feature request in the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/pm-feature-requests/55).

I will now proceed and close this GitHub report. If you have any questions or concerns, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/), and please include a link to this GitHub report if you do.

Thank you again,
