### ISSUE TITLE
Password generator policy doesn't apply to default type

### ISSUE THREAD

**Issue by kolja1507** [bitwarden/clients#9689]
### Steps To Reproduce

1. Go to password generator policy
1. Set **Default type** to _Passphrase_
1. Click on **Save**
1. Go to password generator

### Expected Result

In section **Password type**, _PassPHRASE_ is preselected

### Actual Result

In section **Password type**, _PassWORD_ is preselected

### Operating System

macOS, iOS

### Operating System Version

macOS 14.5, iOS 17.5.1

### Web Browser

Safari, Firefox, Brave

### Browser Version

Safari 17.5, Firefox 127.0, Brave 1.67.116

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. It's also important to note that password preferences are saved per instance. For example, this means that setting a preference in the mobile app will not affect the desktop app or browser extension.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jtodddd** [comment]
Hi there, I was able to reproduce this so I've reopened this issue. Thanks!

**Comment by kolja1507** [comment]
Since [Bitwarden Web v2024.8.0](https://github.com/bitwarden/clients/releases/tag/web-v2024.8.0) (which contains "Updates to password policy for improved clarity"), there's no **default** type to set anymore 😔.
