### ISSUE TITLE
Trashing items resets scroll position

### ISSUE THREAD

**Issue by t-hg** [bitwarden/clients#9693]
### Steps To Reproduce

1. Select folder with a lot of items
2. Scroll down
3. Select item
4. Trash item

### Expected Result

The scroll position stays where it is

### Actual Result

The scroll position resets and you are again at the top of the item list

### Operating System

Linux

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by t-hg** [comment]
Also happens when saving an item. This is inconvenient when editing/deleting multiple items

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by t-hg** [comment]
Well, not sure how you tested that, but it is a problem. Apparently I am not the only one with this issue: https://github.com/bitwarden/clients/issues/2564

You can leave this as closed because of duplicate.
