### ISSUE TITLE
BitWarden addon for Firefox fails to load anything after login

### ISSUE THREAD

**Issue by xantonin** [bitwarden/clients#9694]
### Steps To Reproduce

1. After being logged out/timed out of your session, attempt to log back in.
2. Enter password, or use another device to login
3. After approving login on device or with successful password, the add-on just shows a circle that spins
4. It never loads. You have to logout and try again.

### Expected Result

Expected to be logged in and vault load properly.

### Actual Result

The spiny circle.

### Screenshots or Videos

Pending next occurrence. 

### Additional Context

This seems to happen when it's my first login for the day, perhaps after my computer resumes from sleep mode. It's been guaranteed to happen every day for me for the past 4 weeks or so.

I'll try it from the desktop application next time see if there are network/OS problems.

### Operating System

Windows

### Operating System Version

Windows 10 Home 23H2 (22631.3737)

### Web Browser

Firefox

### Browser Version

127.0

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by fmanseau** [comment]
Disabling/Enabling the extension (or restarting the browser) "fixes" the issue until the next occurrence,

I also noticed the issue quite often since around a week or so. You mentioned Sleep mode, I always Hibernate my laptop at the end of the day, I'll try to see if that's the source of the issue. If it's the case, could be that it's preventing a token from being refreshed properly or something similar, and the extension doesn't recover.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
