### ISSUE TITLE
Can only sign into snap version of Bitwarden after a reboot

### ISSUE THREAD

**Issue by thatLeaflet** [bitwarden/clients#9703]
### Steps To Reproduce

1. Install Ubuntu 24.04
2. Run `sudo snap install bitwarden`
3. Run `sudo snap connect bitwarden:password-manager-service`
4. Open Bitwarden
5. Enter sign in details, tap Yubi-key

### Expected Result

The client would load into the vault

### Actual Result

The client is stuck loading forever.

### Additional Context

I've found that if I snap install bitwarden, connect the service, and sign in all during the same session, the client will continue to load forever.

However, if I snap install bitwarden, connect the service, reboot my system, then sign in, it works fine.

I'm not sure if this is an issue on the Bitwarden side or an issue with snap not fully propagating the service connection until a reboot. However, I do know that the connection does something even if I don't reboot; if I don't run the connect command, then I get the "JWT must have 3 parts" error message.

### Operating System

Linux

### Operating System Version

Ubuntu 24.04 LTS

### Installation method

Snap

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarikaBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in the version of Bitwarden you are using, could you please try updating your version of Bitwarden.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
