### ISSUE TITLE
LibreWolf (FireFox) Desktop integration not working (to enable biometrics)

### ISSUE THREAD

**Issue by KernelBypass** [bitwarden/clients#9726]
### Steps To Reproduce

1. Enable desktop integration in desktop BW client
2. Try to enable Biometrics (Mac) login in FireFox/LibreWolf extension by checking `unlock with Biometrics`

### Expected Result

Ebables biometrics in LibreWOlf (FireFox fork) as it does in Safari

### Actual Result

Gives error about desktop not being set up (has been going on across multiple versions for as long as I had it):

<img width="367" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/2a54e78b-d2d9-45f7-b953-5a2716dc5dcb">

...even though it _is_ set up:

<img width="514" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/1bfdb419-8b3c-4b10-bc43-caf5212a696e">

### Additional Context

LibreWolf

### Operating System

macOS

### Web Browser

Firefox

### Build Version

Version 2024.4.2 Server version 2024.6.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

At this time LibreWolf is not officially supported, though it has been reported some users were successful in enabling biometrics by enabling native messaging within LibreWolf. I'll link some resources below for you.

Native Messaging in LibreWolf: https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work
Community Forums Thread: https://community.bitwarden.com/t/librewolf-extension-biometrics-not-working/50812/3

The issue here will be closed.

Thanks!

**Comment by KernelBypass** [comment]
Thank you for the information.
