### ISSUE TITLE
Touch ID Bug on MAC

### ISSUE THREAD

**Issue by Manuel3190** [bitwarden/clients#9731]
### Steps To Reproduce

4. Click on '...'

### Expected Result

if you unlock the app after a long time, regardless of whether the device is locked in standby or whatever: you have to close the app and open it again to be able to use the TouchID function first.
If the app is not closed, you can only use the master password again to unlock the app although "to unlock" and TouchID was also specified at startup.

### Actual Result

The app cannot be unlocked with TouchID without closing it first.

### Screenshots or Videos

<img width="549" alt="Bildschirmfoto 2024-06-19 um 19 50 07" src="https://github.com/bitwarden/clients/assets/93059120/d835cb03-3f2b-4f8f-8306-3c5d4dc106ed">

### Operating System

macOS

### Operating System Version

14.5

### Installation method

Mac App Store

### Build Version

2024.6.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Grinchii** [comment]
Same problem with me on Mac.

**Comment by Greenderella** [comment]
Hi there,

The support team attempted to reproduce this report and was unable to do so. We were able to unlock the macOS desktop app and Safari extension after an idle state (even several hours before) with biometric as expected. 

I recommend you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing to see if the issue persists. Here is a guide to find any leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine.

When prompted to configure biometrics again, make sure you review the different security settings available, as they affect how the application behaves upon first login and during subsequent unlock states. Visit https://bitwarden.com/help/biometrics/#enable-unlock-with-biometrics for more information.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
