### ISSUE TITLE
Delay between entering a password and unlocking vault

### ISSUE THREAD

**Issue by curiousbarbarian** [bitwarden/clients#9737]
### Steps To Reproduce

1. Open bitwarden.
2. Type password.
3. Click enter/Unlock button.
4. Wait up to some minutes to unlock.

### Expected Result

Unlock in no time

### Actual Result

Unlock up to 2 minutes.

### Additional Context

Same issue with AppImage 2024.6.2 on Linux.

Hardware: CPU AMD Ryzen 4600U, RAM 16 GB 3600 (20% used), SSD NVME Intel (30% used, no problem with IO).

### Operating System

Linux

### Operating System Version

Debian 12.5

### Web Browser

Firefox

### Browser Version

115.12.0

### Build Version

Version: 2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your issue could have its origin in the size of your vault or configurations on your vault.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by curiousbarbarian** [comment]
Hello, @daniellbw! Thanks for quick response.
I've just tried with empty vault (1 record) and found the same issue. I also reset all settings (removed `.config/Bitwarden`) and tried with the almost-empty vault - same thing. Vault password is just 8 chars. I also gonna try with another laptop, but as far as I understand the hardware is not an issue.

The problem is definitely appeared after upgrade to 2024.6.2. In earlier versions unlocking takes no more than 1 second.

**Comment by curiousbarbarian** [comment]
I've tested empty vault on another laptop (more performant hardware) with Ubuntu 24.04 with Firefox who-know-which-version-snap. Same result. It took 10 seconds to unlock EMPTY vault with 8 characters password. Also tried AppImage with same result. For me it looks like regression somewhere in 2024.06.2.
