### ISSUE TITLE
Chrome Extension Window Flashes

### ISSUE THREAD

**Issue by geoff-beaven** [bitwarden/clients#9747]
### Steps To Reproduce

1. Open Chrome browser
2. Click Bitwarden extension to login
3. Observe flashing window

### Expected Result

A solid window without a flashing effect.

### Actual Result

A window that alternates various shades of grey that creates a "flashing" effect.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/22197442/672c5107-44ae-4b95-87c5-6d992303340b

### Operating System

macOS

### Operating System Version

14.5 (23F79)

### Web Browser

Chrome

### Browser Version

126.0.6478.62

### Build Version

2024.6.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue, but was unable to do so. I think your error could have its origin in a misconfiguration of your extension installation. Please try uninstalling and reinstalling the extension, and also try using another browser to see if the behavior persists.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
