### ISSUE TITLE
Select All is not working

### ISSUE THREAD

**Issue by Naxterra** [bitwarden/clients#9749]
### Steps To Reproduce

Go to the Vault
Click CTRL + A or Edit > Select All

### Expected Result

It should select all the items

### Actual Result

It select fields not the login items

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/41871948/1147a578-d6c9-406c-a1e4-5af2ea1d87bd)

### Operating System

Windows

### Operating System Version

11 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request. In the meantime, you may use the web vault (https://vault.bitwarden.com) to select multiple items in your vault.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
