### ISSUE TITLE
vault.bitwarden.com won't use passkey in Bitwarden

### ISSUE THREAD

**Issue by robcohen** [bitwarden/clients#9765]
### Steps To Reproduce

1. Go to vault.bitwarden.com
2. Click on log in with passkey

### Expected Result

Should pop up with bitwarden passkey

### Actual Result

Pops up Brave QR passkey device prompt

### Additional Context

Oddly, on my GrapheneOS Android it DOES allow me to log into vault.bitwarden.com with my bitwarden passkey in bitwarden, but only if I run it from within Vanadium and not within the bitwarden app itself (when clicking two factor under security link).

### Operating System

Linux

### Operating System Version

NixOS 24.04

### Web Browser

Brave

### Browser Version

1.66.118

### Build Version

Version: 2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
