### ISSUE TITLE
TrueKey CSV import is incorrect.

### ISSUE THREAD

**Issue by timcanham** [bitwarden/clients#9794]
### Steps To Reproduce

1. Export TrueKey database as CSV
2. Import via website into vault
3. The username/login/etc fields are not correct

### Expected Result

I would expect the TrueKey fields to be correctly imported into the BitWarden fields.

### Actual Result

Without doing a screendump of my usernames and passwords, the fields in the vault don't match.

### Additional Context

Here are the fields of the exported CSV:

```csv
kind,autologin,cardholder,city,company,country,dateOfBirth,deliveryPlace,content,email,expirationDate,expiryDate,favorite,firstName,gender,hexColor,issueDate,issuedDate,lastName,login,member_id,memberSince,memo,name,note,number,password,phoneNumber,protectedWithPassword,state,street,streetNumber,subdomainOnly,telephone,title,type,url,website,zipCode,tk_export_version
```

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Brave

### Browser Version

1.67.119

### Build Version

Web page, couldn't find a version, but version as of issue submission date

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment]
Hi @timcanham and thank you for your report.

I've tried to reproduce your results and can't see any issues specific to login Items (username/password). 

Could please provide more details on what kind of issue you are seeing. Does this only happen with specific entries, specific fields and what kind of false entries you are seeing? In case you open the exported file with Excel/Spreadsheet: Do the columns and value line up? Maybe a non-escaped comma is causing a shift for all fields?

In addition I do see some currently unsupported types from the TrueKey Wallet, largely around identities (Address book, Driver's License, Memberships, Passport and Social Security Number)
Also some minor mapping improvements like: protectedWithPassword -> Master password reprompt
These are likely due to the age of the importer and can for sure be added in the future.

Kind regards,
Daniel
