### ISSUE TITLE
Bitwarden lose new element creation process on locking

### ISSUE THREAD

**Issue by Tolsi** [bitwarden/clients#9796]
### Steps To Reproduce

1. Go to your Bitwarden storage
2. Try to create some new element (often I copied the password and switched to paste it into some other app )
3. Don't save it, wait for app locking
4. Unlock it again

### Expected Result

the process of creating an element will continue from the place where you left it. or will be saved in some temporary storage from which it can be continued.

### Actual Result

element was dissapeared

### Operating System

macOS

### Operating System Version

14.5 (23F79)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.5.0 (24604)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by Tolsi** [comment]
Your secret storage app's intended behavior is to lose unsaved data? ok
