### ISSUE TITLE
URL matching doesn't work with workday due to subdomains etc

### ISSUE THREAD

**Issue by surapuramakhil** [bitwarden/clients#9797]
### Steps To Reproduce

4. Click on '...'

please refer to screenshot - I always need to search of company site

![Screenshot 2024-06-23 at 4 36 40 PM](https://github.com/bitwarden/clients/assets/9161543/9e99cdcf-2965-4121-aeb8-3405f507d3ab)

### Expected Result

![Screenshot 2024-06-23 at 4 36 40 PM](https://github.com/bitwarden/clients/assets/9161543/9e99cdcf-2965-4121-aeb8-3405f507d3ab)

### Actual Result

![Screenshot 2024-06-23 at 4 36 40 PM](https://github.com/bitwarden/clients/assets/9161543/9e99cdcf-2965-4121-aeb8-3405f507d3ab)

### Screenshots or Videos

![Screenshot 2024-06-23 at 4 36 40 PM](https://github.com/bitwarden/clients/assets/9161543/9e99cdcf-2965-4121-aeb8-3405f507d3ab)

### Operating System

macOS

### Web Browser

Brave

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of your URI matching options: https://bitwarden.com/help/uri-match-detection/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
