### ISSUE TITLE
Bitwarden client exits on red (close) button

### ISSUE THREAD

**Issue by mivanishchev-vkteam** [bitwarden/clients#9817]
### Steps To Reproduce

1. Open Bitwarden client
2. Click on close (red) button
3. Bitwarden exits

### Expected Result

Bitwarden stays open (dot appears under icon on dock)

### Actual Result

Bitwarden exits

### Additional Context

Can you confirm is that an expected behaviour or not?

### Operating System

macOS

### Operating System Version

14.5

### Installation method

Mac App Store

### Build Version

2024.6.2 (25599)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

To close the icon at Dock, Go to bitwarden -> settings -> and under app settings –> check "Close to menu bar

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
