### ISSUE TITLE
Can't auto-fill the email address on https://sso.redhat.com

### ISSUE THREAD

**Issue by alexisfrjp** [bitwarden/clients#9837]
### Steps To Reproduce

Go to https://sso.redhat.com
and try to fill the information to login

redhat trying to do things differently but it's annoying since I constantly have to login again and again for no reason

### Expected Result

email address/username inserted

### Actual Result

nothing

### Operating System

Linux

### Web Browser

Firefox

### Build Version

115.12.0esr (64-bit)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by alexisfrjp** [comment]
Understood, thank you!
