### ISSUE TITLE
right click Generate password (copied)  not saving to password history on extension

### ISSUE THREAD

**Issue by Ebrehe** [bitwarden/clients#9838]
### Steps To Reproduce

right click
bitwarden 
Generate password (copied)

### Expected Result

Generate password (copied) is expected to save in password history

### Actual Result

but it's not happening

### Operating System

Windows

### Web Browser

Microsoft Edge

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
