### ISSUE TITLE
Groups API endpoint cannot be used using bw cli

### ISSUE THREAD

**Issue by Yannik** [bitwarden/clients#9844]
### Steps To Reproduce

Since bitwarden/server 2024.6.0, it is possible to manage groups via the API. I did expect this to also work via the CLI, but the necessary commands do seem to be missing:
```
$ bw list --help
Usage: bw list [options] <object>

List an array of objects from the vault.

Arguments:
  object                             Valid objects are: items, folders, collections,
                                     org-collections, org-members, organizations
```

### Expected Result

`bw list` (and get/create/edit) should allow to use the groups API endpoint to manage groups.

### Actual Result

see above

### Operating System

Linux

### Shell

Bash

### Build Version

2024.6.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there!

Your issue appears to be describing the intended behavior of the software. managing groups via the API has been supported This functionality is intended for use with the Bitwarden Public API, which allows for programmatic interaction with your vault and organizational settings.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed.
