### ISSUE TITLE
Clicking on 'Copy' icon does not copy item

### ISSUE THREAD

**Issue by technochitlin** [bitwarden/clients#9863]
### Steps To Reproduce

1. Go to any saved password in BW
2. Click on the Copy icon

### Expected Result

item copies to clipboard

### Actual Result

3. instead of an immediate copy I get 
![bitw copy](https://github.com/bitwarden/clients/assets/737753/2f024534-56e9-4dc0-bfc2-55c539509399)

which completes, but does not actually copy to clipboard. I can highlight, right-click and copy with no problem.

### Operating System

Windows

### Operating System Version

Version 22H2 (OS Build 19045.4529)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 22H2 (OS Build 19045.4529)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of your clipboard settings, or an out-of-date Bitwarden client.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
