### ISSUE TITLE
3 minute blank screen everytime with self-hosted bitwarden while connected to VPN

### ISSUE THREAD

**Issue by freQniK** [bitwarden/clients#9867]
### Steps To Reproduce

Run a self hosted bitwarden server on your lan then connect to a VPN. Every time you try to open desktop or web browser extension there is a 3 minute period where it is frozen. This just started happening about 10-15 days ago. Each time I want to fill in a login in my web browser I have no choice but to sit  and wait 3 minutes each and every time. It is so damn annoying. 

### Expected Result

That it won't freeze or that the timeout is max 5 seconds

### Actual Result

Freezes and makes me waste a lot of time during the day waiting for it. 

### Screenshots or Videos

I'll upload later. On mobile ATM. 

### Operating System

Windows, macOS, Linux, Android

### Web Browser

Chrome, Safari, Firefox, Brave

### Build Version

Newest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by freQniK** [comment]
Fixed by uninstalling extension, enabling developer mode and installing browser extension v2024.4.2

That was the most recent one that worked. 

Now to remove all Appimages from my Linux boxes and install old .deb until this annoyance is fixes

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. There are a few variables involved here, and there is some troubleshooting the support team can complete with you first.

We use GitHub issues as a place to track bugs and other development related issues. Please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by MathNodes** [comment]
https://github.com/bitwarden/clients/assets/102208536/583b987c-6219-48fb-b90d-48891daafb20

**Comment by MathNodes** [comment]
as you can clearly see, there is a 1 minute delay. Seems like 3 when this happens to you 20 times a day.

**Comment by MathNodes** [comment]
![Uploading Screenshot_2024-07-08_21-37-20.png…]()

**Comment by MathNodes** [comment]
Newest version that works as it should is version 2024.4.1

**Comment by MathNodes** [comment]
This is like this in the desktop client as well now
I have downgraded all clients on my various office computers. We are safe. We use VPNs here
