### ISSUE TITLE
Collections cannot be assigned since Desktop Version 6.0 in self-hosted Servers

### ISSUE THREAD

**Issue by DenisGajs** [bitwarden/clients#9870]
### Steps To Reproduce

1. Go to any entry
2. Click on "edit"
3. Click on "Collections"
4. Try to assign the entry to any Collection
5. An unexpected error occurs

### Expected Result

The entry should be assigned to the selected collection(s)

### Actual Result

An error pop up comes with the text "an unexpected error has occurred" and nothing happens.

### Screenshots or Videos

The following is in the logs:

[2024-06-28 10:42:07.462] [info]  Finished search indexing
[2024-06-28 10:42:20.810] [error] {
  response: {
    error: {
      code: 404,
      description: 'The requested resource could not be found.',
      reason: 'Not Found'
    }
  },
  captchaRequired: false,
  statusCode: 404
}
[2024-06-28 10:42:20.811] [error] Received API exception: [object Object]

![Bitwarden error](https://github.com/bitwarden/clients/assets/75843994/2136c20b-02cb-48ac-809a-d27e4770b2ae)

### Additional Context

The problem occurs since Version 6.0 so Version 6.1, 6.2 and 6.3 has the same error.

Version 5.0 works fine without this bug

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
