### ISSUE TITLE
Bitwarden Desktop not launching on startup

### ISSUE THREAD

**Issue by Hubbelz** [bitwarden/clients#9884]
### Steps To Reproduce

Select bitwarden desktop version to launch on startup 

### Expected Result

Bitwarden shhould be launching on startup with login using windows hello

### Actual Result

Bitwarden Desktop not launching on startup of windows 11
<img width="348" alt="bw" src="https://github.com/bitwarden/clients/assets/174254612/3c6ca8a7-0343-4d53-94bc-86111ace410a">

I have tried uninstalling and reinstalling but It does not fix the issue.

### Operating System

Windows

### Operating System Version

23H2    OS Build Version: 22631.3737

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.6.3 Shell 29.4.2 Renderer 122.0.6261.156 Node 20.9.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misunderstanding of the Unlock with Windows Hello feature - this is to enable fingerprint or face unlock in the application, not launch and login during sign in to your computer. Further down in Bitwarden's settings, you will see an option for Start automatically on login, but this still will not sign you in automatically - you'll need to complete Windows Hello authentication within Bitwarden still.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
