### ISSUE TITLE
[Privacy Issue] I can't disable email suggestion on type="email" fields even autofill is disable

### ISSUE THREAD

**Issue by herberthobregon** [bitwarden/clients#9898]
### Steps To Reproduce

1. If I go to https://snelx.com/login/email write any email and any passoword and press `ENTER` (this is very important), bitwarden `always` show an email suggestion. Even if the <input> is a search input.
2. If you are in a presentation or sharing your screen on a video call like Google Meet or Zoom, it is annoying because all participants see what accounts you have.

### Expected Result

When you touch the bitwarden icon in the <input> the list is displayed and it is not displayed automatically.

### Actual Result

 bitwarden always show an email suggestion even autofill is disable

### Screenshots or Videos

Mi config
![Bitwarden config](https://github.com/bitwarden/clients/assets/6503845/3c30872c-3d16-4700-bd34-0c59615024af)

https://github.com/bitwarden/clients/assets/6503845/b8a8f9c4-81e9-4af6-a2ad-1e70a1aa3922

### Additional Context

Also you can try this example

https://login-page-demo-page.stackblitz.io/

### Operating System

macOS

### Operating System Version

14.2.1 (23C71)

### Web Browser

Chrome

### Browser Version

122

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try restarting your device and reinstalling the extension. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
