### ISSUE TITLE
[selfhosted] How to handle reverse proxy IP whitelist

### ISSUE THREAD

**Issue by p-fruck** [bitwarden/clients#9902]
### Steps To Reproduce

Hi all,

my team and I are running a selfhosted bitwarden instance on kubernetes. Our kubernetes ingress allows some services (e.g. static websites) to be publicly available, but our bitwarden is behind an IP whitelist and only reachable from local network or VPN. All external IPs are rejected with HTTP 403

### Expected Result

The desktop client should fallback to the local cache if the server cannot be contacted

### Actual Result

The client cannot establish a connection to the server, does not display any passwords and users might even have to re-authenticate once they are back in the local network/VPN.

### Additional Context

It would be great if their was a solution to fallback to local cache if the server rejects the connection with some status code

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Desktop v2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @p-fruck, 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
