### ISSUE TITLE
About add passkey

### ISSUE THREAD

**Issue by ptntp** [bitwarden/clients#9935]
### Steps To Reproduce

4. Click on '...'

### Expected Result

If you add a passkey in to one of the entries, when you synchronize it with the Chrome extension, the content will appear blank.

### Actual Result

same

### Operating System

macOS

### Operating System Version

14.6

### Web Browser

Chrome

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by ptntp** [comment]
The following procedures are executed on the Chrome browser extension:

1. Add a new login entry and access the corresponding website.

2. Create a passkey on the webpage, invoke Bitwarden for the operation, and save the changes.

3. Perform a synchronization within the extension, only to find that the login entry has become frozen, rendering it uneditable.
