### ISSUE TITLE
[Chrome] "Make default password manager" has no effect

### ISSUE THREAD

**Issue by bllngr** [bitwarden/clients#9936]
### Steps To Reproduce

Note: This has been observed on an organisation-managed installation of Chrome with the "Offer to save passwords" option forcibly disabled. See the screenshots below.

1. Go to "Settings > Auto-fill" in the Bitwarden extension pop-up
2. Enable any option for "Show auto-fill menu on form fields"
3. In the popup, select "Make default" to make Bitwarden your default password manager
4. Observe the option "Make Bitwarden your default password manager" getting enabled
5. Restart the browser.
6. Go to "Settings > Auto-fill" again
7. Notice the option "Make Bitwarden your default password manager" being disabled again.
8. Change "Show auto-fill menu on form fields" to another (enabled) option
9. Observe the popup being shown again

### Expected Result

* The option stays enabled and works
* If that's not possible, an error message is shown to notify the user
* Optionally: the option gets greyed out, with an explanation why it can't be enabled

### Actual Result

It behaves like the option gets enabled, but it doesn't seem to work and is silently disabled again after a Browser restart.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/303458/7025c48e-2aee-47b4-9958-2419356f45e0)

![image](https://github.com/bitwarden/clients/assets/303458/32ee7cae-ec62-4edb-8679-1179e635adb8)

### Additional Context

Organisation-managed installation of Chrome with the "Offer to save passwords" option forcibly disabled. See the screenshots above.

### Operating System

Windows

### Operating System Version

Windows 11 23H2 Build 22631.3737

### Web Browser

Chrome

### Browser Version

Version 126.0.6478.127 (Official Build) (64-bit)

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a your Organisational configuration of chrome

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
