### ISSUE TITLE
Changing user agent string results in endless loading

### ISSUE THREAD

**Issue by HarbAlarm** [bitwarden/clients#9954]
### Steps To Reproduce

1. Go to 'about:config'
2. Click on 'Set "general.useragent.override" to "Roku"'
3. Restart Firefox
4. Click on Bitwarden

### Expected Result

Login page shows

### Actual Result

It keeps loading forever (tested 10+ minutes)

### Additional Context

I am setting my user agent string to "Roku" to be able to access "youtube.com/tv" without being redirected.
Unfortunately that causes Bitwarden to refuse to load.
..It took me a few hours of reinstalling, deleting caches and resetting all possible files and settings to find out the user agent was the issue.

Whenever the userg agent it's set to "Roku" Bitwarden spits out "this.memoryStorageService is null" in the debugger.
I suppose this is how you check what platform Bitwarden is on and set the respective storage service.
But since it's installed as a firefox extension already, shouldn't Bitwarden be able to tell differentely and set an override?

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in an unsupported configuration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by HarbAlarm** [comment]
Please reopen the issue; I can reproduce this behaviour on a fresh profile on Firefox 127.0.2 (64-bit) and a fresh extension installation.
When reprodcing my steps, did you make sure to restart Firefox after changing the user agent?

Here's a recording reproducing it for you:
https://github.com/bitwarden/clients/assets/29844427/89cf7d94-27a0-4ff0-a3c7-142fde99a7ad
