### ISSUE TITLE
Trying to log in with Windows Hello doesn't unlock vault

### ISSUE THREAD

**Issue by BuffCyclist0524** [bitwarden/clients#9969]
### Steps To Reproduce

1. Lock vault
2. Click on 'Unlock with biometrics'
3. Put in a pin, fingerprint, face ID etc.

### Expected Result

The vault unlocks.

### Actual Result

The app goes straight back to the "Your vault is locked" screen with no visible error messages.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/170767447/41f98219-dcec-4008-8284-6c74b796f304

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.4

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I recommend fully restarting the computer and attempting to unlock with biometrics again. Additionally, reinstalling the Desktop Application and setting up Unlock with Biometrics again may resolve the issue.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
